-- SPDX-FileCopyrightText: 2026 MesTTo
-- SPDX-License-Identifier: Apache-2.0

/-
Module: MeTTaIL.Semantics.InteractingTrieMap
Layer: Semantics
Purpose: Checked algebraic surface for the interacting-trie-map equations used by the rho and
  knotted-universe route.
  The Scala `itm` sketch writes
    ITM[K,V,X] ::= K x ITM[K,V,X] + ITM[ITM[K,V,X],V,X] + ITM[K,V,X] x ITM[K,V,X] + K + V + X
    RITM ::= ITM[RITM,1+RITM,RITM]
  Lean cannot use the first equation as a same-universe nested inductive family directly, so this file
  separates the one-step polynomial shape from its reflective fixed point. The resulting equivalence
  is the checked part needed before building a trie store, red/black reflective universe, or final
  behaviour coalgebra.
Imports: MeTTaIL.Semantics.KnottedUniverse
Trusted boundary: none
Main exports: ITMStep, RITM, RITMStep, RollUnrollEquiv, RITM.toStep, RITM.ofStep, RITM.stepEquiv,
  RITM.ofStep_toStep, RITM.toStep_ofStep, PackedBinding, PackedBinding.root_prefix_address,
  PackedBinding.root_comparable_address, Colour, Colour.swap, Colour.swap_swap
Open obligations: implement the prefix-compressed store, connect the store to path-key RSpace cuts,
  build the red/black reflective universe as a categorical object, and prove the final behaviour
  coalgebra exists there.
-/
import MeTTaIL.Semantics.KnottedUniverse

namespace MeTTaIL
namespace InteractingTrieMap

universe u

/-- One layer of the interacting-trie-map polynomial.

`Rec` is the recursive slot for `ITM[K,V,X]`. `Nested` is the nested slot standing for
`ITM[ITM[K,V,X],V,X]`. Keeping those slots explicit avoids a universe-level nested-inductive
problem while preserving the six summands of the source equation. -/
inductive ITMStep (K V X Rec Nested : Type u) : Type u where
  | triggered : K → Rec → ITMStep K V X Rec Nested
  | keyedUp : Nested → ITMStep K V X Rec Nested
  | composed : Rec → Rec → ITMStep K V X Rec Nested
  | reflective : K → ITMStep K V X Rec Nested
  | boxedIn : V → ITMStep K V X Rec Nested
  | mentioned : X → ITMStep K V X Rec Nested

/-- The reflective interacting trie map generated by `RITM ::= ITM[RITM, 1 + RITM, RITM]`.

`Option RITM` is the Lean spelling of the `1 + RITM` value slot. The `keyedUp` constructor is recursive
because, after substituting `RITM` into the ITM equation, the nested `ITM[RITM,1+RITM,RITM]` slot is
again `RITM`. -/
inductive RITM : Type u where
  | triggered : RITM → RITM → RITM
  | keyedUp : RITM → RITM
  | composed : RITM → RITM → RITM
  | reflective : RITM → RITM
  | boxedIn : Option RITM → RITM
  | mentioned : RITM → RITM

/-- The one-step polynomial for the reflective fixed point. -/
abbrev RITMStep : Type u :=
  ITMStep RITM (Option RITM) RITM RITM RITM

/-- A local equivalence record for rolling and unrolling one polynomial layer.

The file keeps this record local so the ITM surface does not need another library import. -/
structure RollUnrollEquiv (A B : Type u) where
  toStep : A → B
  ofStep : B → A
  of_to : ∀ a, ofStep (toStep a) = a
  to_of : ∀ b, toStep (ofStep b) = b

namespace RITM

/-- Unroll a reflective interacting trie map into one polynomial layer. -/
def toStep : RITM → RITMStep
  | triggered k cont => ITMStep.triggered k cont
  | keyedUp nested => ITMStep.keyedUp nested
  | composed left right => ITMStep.composed left right
  | reflective k => ITMStep.reflective k
  | boxedIn v => ITMStep.boxedIn v
  | mentioned x => ITMStep.mentioned x

/-- Roll one polynomial layer back into the reflective fixed point. -/
def ofStep : RITMStep → RITM
  | ITMStep.triggered k cont => triggered k cont
  | ITMStep.keyedUp nested => keyedUp nested
  | ITMStep.composed left right => composed left right
  | ITMStep.reflective k => reflective k
  | ITMStep.boxedIn v => boxedIn v
  | ITMStep.mentioned x => mentioned x

/-- Rolling after unrolling gives the original reflective trie map. -/
theorem ofStep_toStep (t : RITM) : ofStep t.toStep = t := by
  cases t <;> rfl

/-- Unrolling after rolling gives the original polynomial layer. -/
theorem toStep_ofStep (s : RITMStep) : (ofStep s).toStep = s := by
  cases s <;> rfl

/-- `RITM` is isomorphic to one layer of its source domain equation. -/
def stepEquiv : RollUnrollEquiv RITM RITMStep where
  toStep := toStep
  ofStep := ofStep
  of_to := ofStep_toStep
  to_of := toStep_ofStep

end RITM

/-- A packed binding address for a matched atom inside a stored expression.

This mirrors Jetta's runtime shape: a binding records the expression's store index and the path to the
matched atom inside that stored expression. -/
structure PackedBinding where
  storeIndex : Nat
  atomPath : List Nat
  deriving DecidableEq, Repr

namespace PackedBinding

/-- The root path for the stored expression that owns the binding. -/
def rootPath (binding : PackedBinding) : Denotational.PathRSpace.Path Nat :=
  [binding.storeIndex]

/-- The full path-key address of a matched atom in the store. -/
def addressPath (binding : PackedBinding) : Denotational.PathRSpace.Path Nat :=
  binding.storeIndex :: binding.atomPath

/-- The store root is a prefix of every atom address in that stored expression. -/
theorem root_prefix_address (binding : PackedBinding) :
    Denotational.PathRSpace.Prefix binding.rootPath binding.addressPath := by
  exact ⟨binding.atomPath, rfl⟩

/-- A packed atom address is path-comparable with its store root. -/
theorem root_comparable_address (binding : PackedBinding) :
    Denotational.PathRSpace.Comparable binding.rootPath binding.addressPath :=
  Or.inl (root_prefix_address binding)

end PackedBinding

abbrev Colour := KnottedUniverse.Colour

namespace Colour

/-- Swap to the opposite colour. -/
def swap : Colour → Colour :=
  KnottedUniverse.Colour.swap

/-- Colour swap is an involution. -/
theorem swap_swap (c : Colour) : swap (swap c) = c :=
  KnottedUniverse.Colour.swap_swap c

end Colour

end InteractingTrieMap
end MeTTaIL
