-- SPDX-FileCopyrightText: 2026 MesTTo
-- SPDX-License-Identifier: Apache-2.0

/-
Module: MeTTaILProofs.AC
Layer: Proofs
Purpose: Rewriting modulo associativity and commutativity, for binary-curried AC operators. Process
  calculi such as the rho calculus have a parallel composition `|` that is associative and commutative
  and is presented as a binary application `(| P Q)`, so a runtime that matches rules up to AC must
  decide AC-equivalence on such operators. The classical Maude/Kapur approach is canonical forms: flatten
  the binary tree of an AC operator into the list of its leaves, sort that list by a fixed total order,
  and rebuild as a right-nested binary tree. This module builds that canonical form `canon` on top of the
  verified `LinearOrder AST` (MeTTaILProofs.Order), and proves it sound (`canon t` is AC-equivalent to
  `t`, where AC-equivalence `ACEq` is the congruence generated by commutativity and associativity of the
  flagged operators at their binary occurrences) and complete (AC-equivalent terms have identical
  canonical forms). So `s` and `t` are `ACEq`-equivalent exactly when `canon s = canon t`, and with
  decidable equality on `AST` the test `canon s = canon t` is a verified decision procedure for this
  binary AC-equivalence. The scope is binary-curried operators: a flagged label at arity other than two
  is treated as an ordinary opaque constructor (consistent across `flat`, `canon`, and `ACEq`), since a
  binary operator like `|` never occurs at another arity. A genuinely variadic AC operator (one `n`-ary
  node) would use a different flat canonical form and is out of scope.
Imports: Mathlib.Data.List.Sort (mergeSort and its permutation/sortedness lemmas), MeTTaILProofs.Order
Trusted boundary: none (fully proved)
Main exports: ACEq, canon, canon_sound, canon_complete, acEq_iff_canon, instDecidableACEq
Open obligations: none here. Variadic (`n`-ary) AC operators are in `MeTTaILProofs.ACVariadic`
  (commutative) and `MeTTaILProofs.ACVariadicFull` (full AC). The one-step engine modulo AC is built on
  this canonical form in `MeTTaILProofs.ACEngine`, and Church-Rosser modulo AC in `MeTTaILProofs.ACNormal`.
-/
import Mathlib.Data.List.Sort
import MeTTaILProofs.Order

namespace MeTTaIL.AC

open List

/-! ## Sorting term lists by the verified total order

`canon` sorts the leaves of an AC operator using the `LinearOrder AST` from `MeTTaILProofs.Order`. The
only facts we need about the sort are that it permutes its input, that its output is sorted, and the
consequence that permutation-equal inputs sort to the *same* list (sorted permutations are unique). -/

/-- Sort a list of terms by the verified total order on `AST`. -/
def sortMS (xs : List AST) : List AST := xs.mergeSort (· ≤ ·)

/-- The sort is a permutation of its input. -/
lemma sortMS_perm (xs : List AST) : sortMS xs ~ xs := List.mergeSort_perm xs (· ≤ ·)

/-- The sort produces a `≤`-sorted list. -/
lemma sortMS_sortedLE (xs : List AST) : (sortMS xs).SortedLE := List.sortedLE_mergeSort

/-- Permutation-equal lists sort to the *same* list. This is the heart of completeness: it turns
    "same multiset of leaves" into "syntactically identical canonical form", using that two sorted
    permutations of each other are equal. -/
lemma sortMS_perm_eq {xs ys : List AST} (h : xs ~ ys) : sortMS xs = sortMS ys :=
  List.Perm.eq_of_sortedLE (sortMS_sortedLE xs) (sortMS_sortedLE ys)
    ((sortMS_perm xs).trans (h.trans (sortMS_perm ys).symm))

/-- Membership is preserved by the sort. -/
lemma sortMS_mem {x : AST} {xs : List AST} (h : x ∈ sortMS xs) : x ∈ xs :=
  (sortMS_perm xs).mem_iff.mp h

/-- Sorting a nonempty list yields a nonempty list. -/
lemma sortMS_ne_nil {xs : List AST} (h : xs ≠ []) : sortMS xs ≠ [] := by
  obtain ⟨a, ha⟩ := List.exists_mem_of_ne_nil xs h
  intro hc
  have hmem : a ∈ sortMS xs := (sortMS_perm xs).mem_iff.mpr ha
  rw [hc] at hmem
  exact List.not_mem_nil hmem

/-! ## Flatten and rebuild for a single AC label

`flat l t` collects the leaves of the binary `l`-tree at the root of `t`: it descends through nodes
`(l a b)` and stops at anything that is not such a node. `rebuild l xs` turns a leaf list back into a
right-nested `l`-tree. These are the two halves of the canonical form for one associative-commutative
label `l`. `flat` does not recurse with `canon`, so it is plain structural recursion on the term. -/

/-- The leaves of the binary `l`-tree at the root of a term. Descends through `(l a b)` nodes; every
    other shape (including the same label at a different arity) is an opaque leaf. -/
def flat (l : Label) : AST → List AST
  | .sexp m [a, b] => if l = m then flat l a ++ flat l b else [.sexp m [a, b]]
  | .var p => [.var p]
  | .subst b r v => [.subst b r v]
  | .sexp m args => [.sexp m args]

/-- Rebuild a leaf list into a right-nested `l`-tree. A single leaf rebuilds to itself; the empty list
    is a degenerate case that never arises from `flat` (which is always nonempty). -/
def rebuild (l : Label) : List AST → AST
  | [] => .sexp l []
  | [x] => x
  | x :: xs => .sexp l [x, rebuild l xs]

/-- A one-element rebuild is the element itself. -/
lemma rebuild_singleton (l : Label) (x : AST) : rebuild l [x] = x := rfl

/-- Rebuilding a cons with a nonempty tail peels off the head as a binary node. -/
lemma rebuild_cons {l : Label} {x : AST} {w : List AST} (hw : w ≠ []) :
    rebuild l (x :: w) = .sexp l [x, rebuild l w] := by
  obtain ⟨a, as, rfl⟩ := List.exists_cons_of_ne_nil hw; rfl

/-- Rebuilding a list of at least two elements. -/
lemma rebuild_cons2 (l : Label) (x y : AST) (w : List AST) :
    rebuild l (x :: y :: w) = .sexp l [x, rebuild l (y :: w)] :=
  rebuild_cons (List.cons_ne_nil y w)

/-- Rebuilding a two-element list is the binary node. -/
lemma rebuild_pair (l : Label) (x y : AST) : rebuild l [x, y] = .sexp l [x, y] := by
  rw [rebuild_cons2 l x y []]; rfl

/-- Flattening an `l`-headed binary node splits into the two subtrees' leaves. -/
lemma flat_node (l : Label) (a b : AST) : flat l (.sexp l [a, b]) = flat l a ++ flat l b := by
  simp [flat]

/-- Flattening anything that is not an `l`-headed binary node returns the node as a single leaf. -/
lemma flat_other (l m : Label) {args : List AST} (h : ∀ a b, args = [a, b] → False) :
    flat l (.sexp m args) = [.sexp m args] := by
  rcases args with _ | ⟨x, _ | ⟨y, _ | ⟨z, rest⟩⟩⟩
  · rfl
  · rfl
  · exact (h x y rfl).elim
  · rfl

/-- Flattening a binary node whose label is not `l` leaves it as a single leaf. -/
lemma flat_node_ne {l m : Label} (hlm : ¬ l = m) (a b : AST) :
    flat l (.sexp m [a, b]) = [.sexp m [a, b]] := by
  simp only [flat]; exact if_neg hlm

/-- `flat` never returns the empty list. -/
lemma flat_ne_nil (l : Label) (t : AST) : flat l t ≠ [] := by
  induction t using flat.induct (l := l) with
  | case1 a b iha ihb => rw [flat_node]; exact List.append_ne_nil_of_left_ne_nil iha _
  | case2 m a b hlm => rw [flat_node_ne hlm]; exact List.cons_ne_nil _ _
  | case3 p => exact List.cons_ne_nil _ _
  | case4 b r v => exact List.cons_ne_nil _ _
  | case5 m args hne => rw [flat_other l m hne]; exact List.cons_ne_nil _ _

/-- Every leaf produced by `flat` is itself `l`-flat: flattening it again returns just itself. This is
    what makes the canonical form stable, and it drives `flat_rebuild_inv` below. -/
lemma flat_flat (l : Label) (t : AST) : ∀ x ∈ flat l t, flat l x = [x] := by
  induction t using flat.induct (l := l) with
  | case1 a b iha ihb =>
      intro x hx
      rw [flat_node] at hx
      rcases List.mem_append.mp hx with h | h
      · exact iha x h
      · exact ihb x h
  | case2 m a b hlm =>
      intro x hx
      rw [flat_node_ne hlm, List.mem_singleton] at hx
      subst hx; exact flat_node_ne hlm a b
  | case3 p =>
      intro x hx
      simp only [flat, List.mem_singleton] at hx
      subst hx; rfl
  | case4 b r v =>
      intro x hx
      simp only [flat, List.mem_singleton] at hx
      subst hx; rfl
  | case5 m args hne =>
      intro x hx
      have hfl := flat_other l m hne
      rw [hfl, List.mem_singleton] at hx
      subst hx; exact hfl

/-- Rebuilding an `l`-flat, nonempty leaf list and flattening it again returns the same list. The leaf
    list produced inside `canon` is exactly such a list, so flattening a canonical AC subterm recovers
    its sorted leaves. -/
lemma flat_rebuild_inv {l : Label} :
    ∀ {L : List AST}, (∀ x ∈ L, flat l x = [x]) → L ≠ [] → flat l (rebuild l L) = L := by
  intro L
  induction L using rebuild.induct with
  | case1 => intro _ h; exact absurd rfl h
  | case2 x => intro hflat _; rw [rebuild_singleton]; exact hflat x (by simp)
  | case3 x xs hxs ih =>
      intro hflat _
      rw [rebuild_cons hxs, flat_node, hflat x (by simp),
        ih (fun z hz => hflat z (List.mem_cons_of_mem x hz)) hxs]
      rfl

/-- Flattening a canonicalized AC node recovers its sorted leaf list. -/
lemma flat_canon_node {l : Label} (a b : AST) :
    flat l (rebuild l (sortMS (flat l a ++ flat l b))) = sortMS (flat l a ++ flat l b) := by
  apply flat_rebuild_inv
  · intro x hx
    rcases List.mem_append.mp (sortMS_mem hx) with h | h
    · exact flat_flat l a x h
    · exact flat_flat l b x h
  · exact sortMS_ne_nil (List.append_ne_nil_of_left_ne_nil (flat_ne_nil l a) _)

/-! ## The AC congruence

`ACEq acOp` is the smallest congruence on terms generated by commutativity and associativity of the
binary applications `(l a b)` whose label `l` is flagged `acOp l = true`. The generators (`comm`,
`assoc`) fire only on binary nodes, matching a binary-curried operator like rho's `|`; a flagged label at
another arity is inert. The congruence rules (`argCong`, `substCongB`, `substCongR`) close it under all
term contexts; `refl`, `symm`, `trans` make it an equivalence. -/

/-- AC-equivalence: the congruence generated by commutativity and associativity of the binary
    applications of the `acOp`-flagged labels. -/
inductive ACEq (acOp : Label → Bool) : AST → AST → Prop where
  | refl (t : AST) : ACEq acOp t t
  | symm {s t : AST} : ACEq acOp s t → ACEq acOp t s
  | trans {s t u : AST} : ACEq acOp s t → ACEq acOp t u → ACEq acOp s u
  | comm {l : Label} {a b : AST} :
      acOp l = true → ACEq acOp (.sexp l [a, b]) (.sexp l [b, a])
  | assoc {l : Label} {a b c : AST} :
      acOp l = true →
      ACEq acOp (.sexp l [.sexp l [a, b], c]) (.sexp l [a, .sexp l [b, c]])
  | argCong {l : Label} (pre : List AST) {a a' : AST} (post : List AST) :
      ACEq acOp a a' → ACEq acOp (.sexp l (pre ++ a :: post)) (.sexp l (pre ++ a' :: post))
  | substCongB {b b' r : AST} {v : DottedPath} :
      ACEq acOp b b' → ACEq acOp (.subst b r v) (.subst b' r v)
  | substCongR {b r r' : AST} {v : DottedPath} :
      ACEq acOp r r' → ACEq acOp (.subst b r v) (.subst b r' v)

/-- Congruence of `sexp` under a pointwise AC-equivalence of arguments, built by chaining single-position
    `argCong` steps across the list. -/
lemma ACEq.sexpCongr (acOp : Label → Bool) {l : Label} {cs ds : List AST}
    (h : List.Forall₂ (ACEq acOp) cs ds) : ACEq acOp (.sexp l cs) (.sexp l ds) := by
  suffices H : ∀ (pre : List AST) {cs ds : List AST}, List.Forall₂ (ACEq acOp) cs ds →
      ACEq acOp (.sexp l (pre ++ cs)) (.sexp l (pre ++ ds)) by
    simpa using H [] h
  intro pre cs ds h
  induction h generalizing pre with
  | nil => exact ACEq.refl _
  | @cons c d cs' ds' hcd _ ih =>
      have step1 : ACEq acOp (.sexp l (pre ++ c :: cs')) (.sexp l (pre ++ d :: cs')) :=
        ACEq.argCong (l := l) pre cs' hcd
      have step2 : ACEq acOp (.sexp l (pre ++ d :: cs')) (.sexp l (pre ++ d :: ds')) := by
        have := ih (pre ++ [d]); simpa using this
      exact step1.trans step2

/-- Congruence in the first argument of a binary node. -/
lemma ACEq.sexp2_fst (acOp : Label → Bool) {l : Label} {a a' b : AST} (h : ACEq acOp a a') :
    ACEq acOp (.sexp l [a, b]) (.sexp l [a', b]) := by
  have := ACEq.argCong (acOp := acOp) (l := l) [] [b] h; simpa using this

/-- Congruence in the second argument of a binary node. -/
lemma ACEq.sexp2_snd (acOp : Label → Bool) {l : Label} {a b b' : AST} (h : ACEq acOp b b') :
    ACEq acOp (.sexp l [a, b]) (.sexp l [a, b']) := by
  have := ACEq.argCong (acOp := acOp) (l := l) [a] [] h; simpa using this

/-- Congruence of a binary node in both arguments. -/
lemma ACEq.sexp2 (acOp : Label → Bool) {l : Label} {a a' b b' : AST}
    (ha : ACEq acOp a a') (hb : ACEq acOp b b') : ACEq acOp (.sexp l [a, b]) (.sexp l [a', b']) :=
  (ACEq.sexp2_fst acOp ha).trans (ACEq.sexp2_snd acOp hb)

/-! ## Soundness lemmas: flatten, rebuild, and sort preserve AC-equivalence -/

/-- Combining two rebuilt leaf lists with the binary operator is AC-equivalent to rebuilding their
    concatenation. This is associativity in action. -/
lemma rebuild_append (acOp : Label → Bool) {l : Label} (hac : acOp l = true)
    {ys : List AST} (hys : ys ≠ []) :
    ∀ {xs : List AST}, xs ≠ [] →
      ACEq acOp (rebuild l (xs ++ ys)) (.sexp l [rebuild l xs, rebuild l ys]) := by
  intro xs
  induction xs using rebuild.induct with
  | case1 => intro h; exact absurd rfl h
  | case2 x =>
      intro _
      obtain ⟨z, zs, rfl⟩ := List.exists_cons_of_ne_nil hys
      rw [List.singleton_append, rebuild_cons2, rebuild_singleton]
      exact ACEq.refl _
  | case3 x xs hxs ih =>
      intro _
      have key := ih hxs
      have hxy : xs ++ ys ≠ [] := List.append_ne_nil_of_left_ne_nil hxs _
      rw [List.cons_append, rebuild_cons hxy, rebuild_cons hxs]
      have c1 : ACEq acOp (.sexp l [x, rebuild l (xs ++ ys)])
          (.sexp l [x, .sexp l [rebuild l xs, rebuild l ys]]) := ACEq.sexp2_snd acOp key
      have c2 : ACEq acOp (.sexp l [x, .sexp l [rebuild l xs, rebuild l ys]])
          (.sexp l [.sexp l [x, rebuild l xs], rebuild l ys]) :=
        (ACEq.assoc (acOp := acOp) (l := l) (a := x) (b := rebuild l xs) (c := rebuild l ys) hac).symm
      exact c1.trans c2

/-- Flattening then rebuilding is AC-equivalent to the original term. This is the associativity content
    of the canonical form: it does not matter how an AC tree was bracketed. -/
lemma rebuild_flat (acOp : Label → Bool) {l : Label} (hac : acOp l = true) (t : AST) :
    ACEq acOp (rebuild l (flat l t)) t := by
  induction t using flat.induct (l := l) with
  | case1 a b iha ihb =>
      rw [flat_node]
      have happ := rebuild_append acOp hac (flat_ne_nil l b) (flat_ne_nil l a)
      exact happ.trans (ACEq.sexp2 acOp iha ihb)
  | case2 m a b hlm => rw [flat_node_ne hlm, rebuild_singleton]; exact ACEq.refl _
  | case3 p => exact ACEq.refl _
  | case4 b r v => exact ACEq.refl _
  | case5 m args hne => rw [flat_other l m hne, rebuild_singleton]; exact ACEq.refl _

/-- Rebuilding permutation-equal leaf lists yields AC-equivalent terms. This is the commutativity
    content: reordering the leaves of an AC tree gives an equivalent term. -/
lemma rebuild_perm (acOp : Label → Bool) {l : Label} (hac : acOp l = true) :
    ∀ {xs ys : List AST}, xs ~ ys → ACEq acOp (rebuild l xs) (rebuild l ys) := by
  intro xs ys h
  induction h with
  | nil => exact ACEq.refl _
  | @cons x xs' ys' hxy ih =>
      cases xs' with
      | nil =>
          cases ys' with
          | nil => exact ACEq.refl _
          | cons w ws => have h0 := hxy.length_eq; simp at h0
      | cons z zs =>
          cases ys' with
          | nil => have h0 := hxy.length_eq; simp at h0
          | cons w ws =>
              rw [rebuild_cons2 l x z zs, rebuild_cons2 l x w ws]
              exact ACEq.sexp2_snd acOp ih
  | @swap x y rest =>
      cases rest with
      | nil =>
          rw [rebuild_pair l y x, rebuild_pair l x y]
          exact ACEq.comm (acOp := acOp) (l := l) (a := y) (b := x) hac
      | cons z zs =>
          rw [rebuild_cons2 l y x (z :: zs), rebuild_cons2 l x z zs,
            rebuild_cons2 l x y (z :: zs), rebuild_cons2 l y z zs]
          set W := rebuild l (z :: zs) with hW
          have a1 : ACEq acOp (.sexp l [y, .sexp l [x, W]]) (.sexp l [.sexp l [y, x], W]) :=
            (ACEq.assoc (acOp := acOp) (l := l) (a := y) (b := x) (c := W) hac).symm
          have a2 : ACEq acOp (.sexp l [.sexp l [y, x], W]) (.sexp l [.sexp l [x, y], W]) :=
            ACEq.sexp2_fst acOp (ACEq.comm (acOp := acOp) (l := l) (a := y) (b := x) hac)
          have a3 : ACEq acOp (.sexp l [.sexp l [x, y], W]) (.sexp l [x, .sexp l [y, W]]) :=
            ACEq.assoc (acOp := acOp) (l := l) (a := x) (b := y) (c := W) hac
          exact (a1.trans a2).trans a3
  | @trans xs' ys' zs' _ _ ih1 ih2 => exact ih1.trans ih2

/-! ## The canonical form -/

/-- The canonical rebuild of one node, given its already-canonical arguments. For an `acOp` label with
    exactly two arguments this flattens, sorts, and rebuilds; otherwise it is an ordinary application. -/
def canonNode (acOp : Label → Bool) (l : Label) (cargs : List AST) : AST :=
  if acOp l then
    match cargs with
    | [a, b] => rebuild l (sortMS (flat l a ++ flat l b))
    | _ => .sexp l cargs
  else .sexp l cargs

mutual
  /-- The canonical form of a term: canonicalize the arguments, then `canonNode` each application. -/
  def canon (acOp : Label → Bool) : AST → AST
    | .var p => .var p
    | .subst b r v => .subst (canon acOp b) (canon acOp r) v
    | .sexp l args => canonNode acOp l (canonList acOp args)
  /-- Pointwise `canon` of an argument list. -/
  def canonList (acOp : Label → Bool) : List AST → List AST
    | [] => []
    | a :: as => canon acOp a :: canonList acOp as
end

/-- `canonList` is the pointwise `canon` of a list. -/
lemma canonList_eq_map (acOp : Label → Bool) (ts : List AST) :
    canonList acOp ts = ts.map (canon acOp) := by
  induction ts with
  | nil => rfl
  | cons a as ih => simp only [canonList, ih, List.map_cons]

@[simp] lemma canon_var (acOp : Label → Bool) (p : DottedPath) : canon acOp (.var p) = .var p := rfl

@[simp] lemma canon_subst (acOp : Label → Bool) (b r : AST) (v : DottedPath) :
    canon acOp (.subst b r v) = .subst (canon acOp b) (canon acOp r) v := rfl

lemma canon_sexp (acOp : Label → Bool) (l : Label) (args : List AST) :
    canon acOp (.sexp l args) = canonNode acOp l (canonList acOp args) := rfl

/-- `canonNode` on an `acOp` label with two arguments. -/
lemma canonNode_pair (acOp : Label → Bool) {l : Label} (hac : acOp l = true) (a b : AST) :
    canonNode acOp l [a, b] = rebuild l (sortMS (flat l a ++ flat l b)) := by
  unfold canonNode; rw [if_pos hac]

/-- The canonical form of an AC binary node: canonicalise the arguments, flatten, sort, rebuild. -/
lemma canon_pair (acOp : Label → Bool) {l : Label} (hac : acOp l = true) (x y : AST) :
    canon acOp (.sexp l [x, y]) = rebuild l (sortMS (flat l (canon acOp x) ++ flat l (canon acOp y))) := by
  rw [canon_sexp, canonList_eq_map]
  simp only [List.map_cons, List.map_nil]
  rw [canonNode_pair acOp hac]

/-! ## Soundness: the canonical form is AC-equivalent to the original -/

/-- The canonical rebuild of one AC node is AC-equivalent to the binary application of its two
    canonical arguments: sorting permutes the flattened leaves (commutativity) and rebuild-of-flatten
    re-associates them (associativity). -/
lemma canon_acnode_core (acOp : Label → Bool) {l : Label} (hac : acOp l = true) (a b : AST) :
    ACEq acOp (rebuild l (sortMS (flat l a ++ flat l b))) (.sexp l [a, b]) := by
  have hperm : ACEq acOp (rebuild l (sortMS (flat l a ++ flat l b)))
      (rebuild l (flat l a ++ flat l b)) :=
    rebuild_perm acOp hac (sortMS_perm _)
  have happ : ACEq acOp (rebuild l (flat l a ++ flat l b))
      (.sexp l [rebuild l (flat l a), rebuild l (flat l b)]) :=
    rebuild_append acOp hac (flat_ne_nil l b) (flat_ne_nil l a)
  exact (hperm.trans happ).trans (ACEq.sexp2 acOp (rebuild_flat acOp hac a) (rebuild_flat acOp hac b))

/-- `canonNode` with already-sound arguments is AC-equivalent to the application. -/
lemma canonNode_sound (acOp : Label → Bool) {l : Label} {cargs args : List AST}
    (h : List.Forall₂ (ACEq acOp) cargs args) :
    ACEq acOp (canonNode acOp l cargs) (.sexp l args) := by
  unfold canonNode
  by_cases hac : acOp l = true
  · rw [if_pos hac]
    match cargs, h with
    | [a, b], h => exact (canon_acnode_core acOp hac a b).trans (ACEq.sexpCongr acOp h)
    | [], h => exact ACEq.sexpCongr acOp h
    | [_], h => exact ACEq.sexpCongr acOp h
    | _ :: _ :: _ :: _, h => exact ACEq.sexpCongr acOp h
  · rw [if_neg hac]
    exact ACEq.sexpCongr acOp h

mutual
  /-- Soundness of the canonical form: `canon t` is AC-equivalent to `t`. -/
  theorem canon_sound (acOp : Label → Bool) : (t : AST) → ACEq acOp (canon acOp t) t
    | .var _ => ACEq.refl _
    | .subst b r _ => (ACEq.substCongB (canon_sound acOp b)).trans (ACEq.substCongR (canon_sound acOp r))
    | .sexp _ args => canonNode_sound acOp (canonList_sound acOp args)
  /-- Pointwise soundness for argument lists. -/
  theorem canonList_sound (acOp : Label → Bool) :
      (ts : List AST) → List.Forall₂ (ACEq acOp) (canonList acOp ts) ts
    | [] => List.Forall₂.nil
    | a :: as => List.Forall₂.cons (canon_sound acOp a) (canonList_sound acOp as)
end

/-! ## Completeness: the canonical form is invariant under AC-equivalence -/

/-- Completeness of the canonical form: AC-equivalent terms have identical canonical forms. Proved by
    induction on the AC-equivalence derivation. The `comm` case reduces to permutation-invariance of the
    sort; the `assoc` case to associativity of append under the sort; the congruence cases to the
    pointwise canonicalization of arguments. -/
theorem canon_complete (acOp : Label → Bool) {s t : AST} (h : ACEq acOp s t) :
    canon acOp s = canon acOp t := by
  induction h with
  | refl _ => rfl
  | symm _ ih => exact ih.symm
  | trans _ _ ih1 ih2 => exact ih1.trans ih2
  | @comm l a b hac =>
      rw [canon_pair acOp hac, canon_pair acOp hac, sortMS_perm_eq List.perm_append_comm]
  | @assoc l a b c hac =>
      have hL : canon acOp (.sexp l [.sexp l [a, b], c])
          = rebuild l (sortMS (sortMS (flat l (canon acOp a) ++ flat l (canon acOp b))
              ++ flat l (canon acOp c))) := by
        rw [canon_pair acOp hac, canon_pair acOp hac, flat_canon_node]
      have hR : canon acOp (.sexp l [a, .sexp l [b, c]])
          = rebuild l (sortMS (flat l (canon acOp a)
              ++ sortMS (flat l (canon acOp b) ++ flat l (canon acOp c)))) := by
        rw [canon_pair acOp hac, canon_pair acOp hac, flat_canon_node]
      rw [hL, hR]
      congr 1
      have p1 : sortMS (flat l (canon acOp a) ++ flat l (canon acOp b)) ++ flat l (canon acOp c)
          ~ (flat l (canon acOp a) ++ flat l (canon acOp b)) ++ flat l (canon acOp c) :=
        (sortMS_perm _).append_right _
      have p2 : flat l (canon acOp a) ++ sortMS (flat l (canon acOp b) ++ flat l (canon acOp c))
          ~ flat l (canon acOp a) ++ (flat l (canon acOp b) ++ flat l (canon acOp c)) :=
        (sortMS_perm _).append_left _
      rw [sortMS_perm_eq p1, sortMS_perm_eq p2, List.append_assoc]
  | @argCong l pre a a' post _ ih =>
      rw [canon_sexp, canon_sexp, canonList_eq_map, canonList_eq_map,
        List.map_append, List.map_append, List.map_cons, List.map_cons, ih]
  | @substCongB b b' r _ _ ih => rw [canon_subst, canon_subst, ih]
  | @substCongR b r r' _ _ ih => rw [canon_subst, canon_subst, ih]

/-- The canonical form is idempotent: it is a genuine normal form for AC-equivalence. Immediate from
    soundness (`canon t` is AC-equivalent to `t`) and completeness (AC-equivalent terms canonicalize
    alike). -/
theorem canon_idem (acOp : Label → Bool) (t : AST) : canon acOp (canon acOp t) = canon acOp t :=
  canon_complete acOp (canon_sound acOp t)

/-! ## The decision procedure -/

/-- AC-equivalence is decided by equality of canonical forms. Soundness gives the reverse direction:
    if the canonical forms are equal then both terms are AC-equivalent to that common form. -/
theorem acEq_iff_canon (acOp : Label → Bool) {s t : AST} :
    ACEq acOp s t ↔ canon acOp s = canon acOp t := by
  constructor
  · exact canon_complete acOp
  · intro hc
    have hs : ACEq acOp (canon acOp s) s := canon_sound acOp s
    have ht : ACEq acOp (canon acOp t) t := canon_sound acOp t
    exact (hc ▸ hs.symm).trans ht

/-- AC-equivalence is decidable: compute and compare canonical forms. -/
instance instDecidableACEq (acOp : Label → Bool) (s t : AST) : Decidable (ACEq acOp s t) :=
  decidable_of_iff _ (acEq_iff_canon acOp).symm

end MeTTaIL.AC
