-- SPDX-FileCopyrightText: 2026 MesTTo
-- SPDX-License-Identifier: Apache-2.0

/-
Module: MeTTaILProofs.ACVariadic
Layer: Proofs
Purpose: Commutative variadic operators, the `n`-ary companion to the binary-curried AC of
  `MeTTaILProofs.AC`. Some operators are presented as a single `n`-ary node `(l a1 ... an)` rather than a
  curried binary tree, and are commutative (a multiset / set union, a commutative gather). The canonical
  form for such an operator sorts its argument list by the verified total order on terms: two `(l ...)`
  nodes are commutativity-equivalent exactly when their argument lists are permutations, and sorting
  decides that. `canonC` is that canonical form, `ACEqC` the commutative-variadic congruence (a permuted
  argument list under a flagged label, closed under all contexts), and `acEqC_iff_canonC` the decision
  procedure. This closes the commutative half of the variadic AC obligation; the associative half
  (flattening nested same-label nodes) is a further extension.
Imports: MeTTaILProofs.AC (sortMS and its permutation/sortedness lemmas, the LinearOrder), Mathlib for
  List.Perm.map
Trusted boundary: none (fully proved)
Main exports: ACEqC, canonC, canonC_sound, canonC_complete, acEqC_iff_canonC, instDecidableACEqC
Open obligations: the associative half (flattening `(l a (l b c))` to `(l a b c)`) for full variadic AC.
-/
import MeTTaILProofs.AC

namespace MeTTaIL.AC

open List

/-- Commutative-variadic equivalence: the congruence generated by permuting the argument list of a
    flagged `n`-ary operator. `permC` is variadic commutativity; the `argCong`/`subst` rules close it
    under contexts. -/
inductive ACEqC (acOp : Label → Bool) : AST → AST → Prop where
  | refl (t : AST) : ACEqC acOp t t
  | symm {s t : AST} : ACEqC acOp s t → ACEqC acOp t s
  | trans {s t u : AST} : ACEqC acOp s t → ACEqC acOp t u → ACEqC acOp s u
  | permC {l : Label} {args args' : List AST} :
      acOp l = true → args ~ args' → ACEqC acOp (.sexp l args) (.sexp l args')
  | argCong {l : Label} (pre : List AST) {a a' : AST} (post : List AST) :
      ACEqC acOp a a' → ACEqC acOp (.sexp l (pre ++ a :: post)) (.sexp l (pre ++ a' :: post))
  | substCongB {b b' r : AST} {v : DottedPath} :
      ACEqC acOp b b' → ACEqC acOp (.subst b r v) (.subst b' r v)
  | substCongR {b r r' : AST} {v : DottedPath} :
      ACEqC acOp r r' → ACEqC acOp (.subst b r v) (.subst b r' v)

variable (acOp : Label → Bool)

/-- Congruence of `sexp` under a pointwise `ACEqC` of arguments, by chaining single-position `argCong`. -/
lemma ACEqC.sexpCongr {l : Label} {cs ds : List AST}
    (h : List.Forall₂ (ACEqC acOp) cs ds) : ACEqC acOp (.sexp l cs) (.sexp l ds) := by
  suffices H : ∀ (pre : List AST) {cs ds : List AST}, List.Forall₂ (ACEqC acOp) cs ds →
      ACEqC acOp (.sexp l (pre ++ cs)) (.sexp l (pre ++ ds)) by
    simpa using H [] h
  intro pre cs ds h
  induction h generalizing pre with
  | nil => exact ACEqC.refl _
  | @cons c d cs' ds' hcd _ ih =>
      have step1 : ACEqC acOp (.sexp l (pre ++ c :: cs')) (.sexp l (pre ++ d :: cs')) :=
        ACEqC.argCong (l := l) pre cs' hcd
      have step2 : ACEqC acOp (.sexp l (pre ++ d :: cs')) (.sexp l (pre ++ d :: ds')) := by
        have := ih (pre ++ [d]); simpa using this
      exact step1.trans step2

mutual
  /-- The commutative-variadic canonical form: canonicalize the arguments, then sort the argument list of
      a flagged operator by the verified total order. -/
  def canonC : AST → AST
    | .var p => .var p
    | .subst b r v => .subst (canonC b) (canonC r) v
    | .sexp l args =>
        let cargs := canonCList args
        if acOp l then .sexp l (sortMS cargs) else .sexp l cargs
  def canonCList : List AST → List AST
    | [] => []
    | a :: as => canonC a :: canonCList as
end

lemma canonCList_eq_map (ts : List AST) : canonCList acOp ts = ts.map (canonC acOp) := by
  induction ts with
  | nil => rfl
  | cons a as ih => simp only [canonCList, ih, List.map_cons]

@[simp] lemma canonC_var (p : DottedPath) : canonC acOp (.var p) = .var p := rfl

@[simp] lemma canonC_subst (b r : AST) (v : DottedPath) :
    canonC acOp (.subst b r v) = .subst (canonC acOp b) (canonC acOp r) v := rfl

lemma canonC_sexp (l : Label) (args : List AST) :
    canonC acOp (.sexp l args) =
      (if acOp l then .sexp l (sortMS (canonCList acOp args)) else .sexp l (canonCList acOp args)) := rfl

/-! ## Soundness -/

mutual
  theorem canonC_sound : (t : AST) → ACEqC acOp (canonC acOp t) t
    | .var _ => ACEqC.refl _
    | .subst b r v =>
        (ACEqC.substCongB (canonC_sound b)).trans (ACEqC.substCongR (canonC_sound r))
    | .sexp l args => by
        rw [canonC_sexp]
        have hcong : ACEqC acOp (.sexp l (canonCList acOp args)) (.sexp l args) :=
          ACEqC.sexpCongr acOp (canonCList_sound args)
        by_cases hac : acOp l
        · rw [if_pos hac]
          exact (ACEqC.permC hac (sortMS_perm (canonCList acOp args))).trans hcong
        · rw [if_neg hac]; exact hcong
  theorem canonCList_sound : (ts : List AST) → List.Forall₂ (ACEqC acOp) (canonCList acOp ts) ts
    | [] => List.Forall₂.nil
    | a :: as => List.Forall₂.cons (canonC_sound a) (canonCList_sound as)
end

/-! ## Completeness -/

theorem canonC_complete {s t : AST} (h : ACEqC acOp s t) : canonC acOp s = canonC acOp t := by
  induction h with
  | refl _ => rfl
  | symm _ ih => exact ih.symm
  | trans _ _ ih1 ih2 => exact ih1.trans ih2
  | @permC l args args' hac hperm =>
      rw [canonC_sexp, canonC_sexp, if_pos hac, if_pos hac, canonCList_eq_map, canonCList_eq_map]
      rw [sortMS_perm_eq (hperm.map (canonC acOp))]
  | @argCong l pre a a' post _ ih =>
      rw [canonC_sexp, canonC_sexp, canonCList_eq_map, canonCList_eq_map,
        List.map_append, List.map_append, List.map_cons, List.map_cons, ih]
  | @substCongB b b' r v _ ih => rw [canonC_subst, canonC_subst, ih]
  | @substCongR b r r' v _ ih => rw [canonC_subst, canonC_subst, ih]

/-! ## The decision procedure -/

theorem acEqC_iff_canonC {s t : AST} : ACEqC acOp s t ↔ canonC acOp s = canonC acOp t := by
  constructor
  · exact canonC_complete acOp
  · intro hc
    exact ((hc ▸ (canonC_sound acOp s).symm).trans (canonC_sound acOp t))

instance instDecidableACEqC (s t : AST) : Decidable (ACEqC acOp s t) :=
  decidable_of_iff _ (acEqC_iff_canonC acOp).symm

end MeTTaIL.AC
