/-
Module: PLeaTTa.PeTTaSpec.OpenSubstitution
Purpose: Independent open-term substitution semantics for translation-time
  Prolog variable sharing and its explicit-equality normalization.
Trusted boundary: none
Main exports: Substitution, Unifies, ContinuationRespectsInstantiation,
  explicit_alias_prefix_equivalent_to_shared
-/
import PLeaTTa.PeTTaSpec.PrologCore

namespace PLeaTTa.PeTTaSpec.PrologCore.OpenSubstitution

/-! ### Capture-free replacement of one logical-variable identity

Pinned `build_branch/4` aliases two existing Prolog variables. There are no
binders in the generated target term/goal syntax, so replacing one identity by
an open term is capture-free. These functions are independent of PLeaTTa's
executable `Atom`, `Goal`, and substitution implementations.
-/

mutual

/-- Replace one logical-variable identity throughout an independent term. -/
def Term.instantiateOne (source : LogicVar) (replacement : Term) :
    Term → Term
  | .variable identity =>
      if identity = source then replacement else .variable identity
  | .atom name => .atom name
  | .integer value => .integer value
  | .float value => .float value
  | .string value => .string value
  | .compound functor arguments =>
      .compound functor (Terms.instantiateOne source replacement arguments)
  | .list items none =>
      .list (Terms.instantiateOne source replacement items) none
  | .list items (some tail) =>
      .list (Terms.instantiateOne source replacement items)
        (some (Term.instantiateOne source replacement tail))

/-- Ordered pointwise one-variable replacement for independent terms. -/
def Terms.instantiateOne (source : LogicVar) (replacement : Term) :
    List Term → List Term
  | [] => []
  | term :: terms =>
      Term.instantiateOne source replacement term ::
        Terms.instantiateOne source replacement terms

end

mutual

/-- Replace one logical-variable identity throughout an independent goal. -/
def Goal.instantiateOne (source : LogicVar) (replacement : Term) :
    Goal → Goal
  | .truth => .truth
  | .fail => .fail
  | .unify left right =>
      .unify (Term.instantiateOne source replacement left)
        (Term.instantiateOne source replacement right)
  | .identical left right =>
      .identical (Term.instantiateOne source replacement left)
        (Term.instantiateOne source replacement right)
  | .call predicate arguments =>
      .call predicate (Terms.instantiateOne source replacement arguments)
  | .conjunction goals =>
      .conjunction (Goals.instantiateOne source replacement goals)
  | .disjunction branches =>
      .disjunction (Goals.instantiateOne source replacement branches)
  | .cut => .cut
  | .ifThenElse condition thenBranch elseBranch =>
      .ifThenElse (Goal.instantiateOne source replacement condition)
        (Goal.instantiateOne source replacement thenBranch)
        (Goal.instantiateOne source replacement elseBranch)
  | .softCut condition thenBranch elseBranch =>
      .softCut (Goal.instantiateOne source replacement condition)
        (Goal.instantiateOne source replacement thenBranch)
        (Goal.instantiateOne source replacement elseBranch)
  | .negation goal =>
      .negation (Goal.instantiateOne source replacement goal)
  | .once goal => .once (Goal.instantiateOne source replacement goal)
  | .findall template goal output =>
      .findall (Term.instantiateOne source replacement template)
        (Goal.instantiateOne source replacement goal)
        (Term.instantiateOne source replacement output)
  | .catch goal exception handler =>
      .catch (Goal.instantiateOne source replacement goal)
        (Term.instantiateOne source replacement exception)
        (Goal.instantiateOne source replacement handler)
  | .transaction goal =>
      .transaction (Goal.instantiateOne source replacement goal)
  | .withMutex mutex goal =>
      .withMutex (Term.instantiateOne source replacement mutex)
        (Goal.instantiateOne source replacement goal)
  | .forall generator test =>
      .forall (Goal.instantiateOne source replacement generator)
        (Goal.instantiateOne source replacement test)

/-- Ordered pointwise one-variable replacement for independent goals. -/
def Goals.instantiateOne (source : LogicVar) (replacement : Term) :
    List Goal → List Goal
  | [] => []
  | goal :: goals =>
      Goal.instantiateOne source replacement goal ::
        Goals.instantiateOne source replacement goals

end

/-! ### Finite open substitutions

Bindings are applied from left to right. This file needs only the acyclic
single-alias fragment generated by `build_branch/4`; general first-order MGU
construction remains part of the full ordered Prolog semantics.
-/

/-- Finite partial substitution over independent logical-variable identities. -/
abbrev Substitution := List (LogicVar × Term)

namespace Substitution

/-- Sequentially instantiate an independent term with all finite bindings. -/
def applyTerm : Substitution → Term → Term
  | [], term => term
  | (source, replacement) :: bindings, term =>
      applyTerm bindings (Term.instantiateOne source replacement term)

/-- Sequentially instantiate an independent goal with all finite bindings. -/
def applyGoal : Substitution → Goal → Goal
  | [], goal => goal
  | (source, replacement) :: bindings, goal =>
      applyGoal bindings (Goal.instantiateOne source replacement goal)

/-- Sequentially instantiate an ordered independent goal sequence. -/
def applyGoals : Substitution → List Goal → List Goal
  | [], goals => goals
  | (source, replacement) :: bindings, goals =>
      applyGoals bindings (Goals.instantiateOne source replacement goals)

@[simp] theorem applyTerm_nil (term : Term) :
    applyTerm [] term = term := rfl

@[simp] theorem applyGoal_nil (goal : Goal) :
    applyGoal [] goal = goal := rfl

@[simp] theorem applyGoals_nil (goals : List Goal) :
    applyGoals [] goals = goals := rfl

@[simp] theorem applyTerm_singleton (source : LogicVar) (replacement term : Term) :
    applyTerm [(source, replacement)] term =
      Term.instantiateOne source replacement term := rfl

@[simp] theorem applyGoal_singleton (source : LogicVar) (replacement : Term)
    (goal : Goal) :
    applyGoal [(source, replacement)] goal =
      Goal.instantiateOne source replacement goal := rfl

@[simp] theorem applyGoals_singleton (source : LogicVar) (replacement : Term)
    (goals : List Goal) :
    applyGoals [(source, replacement)] goals =
      Goals.instantiateOne source replacement goals := rfl

end Substitution

/-- No earlier binding uses the supplied identity as its left-hand side. -/
def Fresh (bindings : Substitution) (identity : LogicVar) : Prop :=
  ∀ binding, binding ∈ bindings → binding.1 ≠ identity

/-- Independent open unification fragment needed for branch aliases.

The reflexive rule preserves a substitution. The fresh-variable rule records
the translation-time sharing induced by `Val = Out` in pinned
`build_branch/4`. Unsupported unification shapes have no rule yet rather than
being silently interpreted as failure. [SPEC translator.pl:394-397] -/
inductive Unifies : Substitution → Term → Term → Substitution → Prop where
  | reflexive (bindings : Substitution) (term : Term) :
      Unifies bindings term term bindings
  | freshAlias (bindings : Substitution) (source target : LogicVar)
      (distinct : source ≠ target) (fresh : Fresh bindings source) :
      Unifies bindings (.variable source) (.variable target)
        ((source, .variable target) :: bindings)

/-- A distinct fresh-variable alias from the empty substitution has exactly
the singleton substitution required by the explicit equality normalization. -/
theorem unifies_empty_distinct_alias_output {source target : LogicVar}
    {result : Substitution} (distinct : source ≠ target)
    (unification :
      Unifies [] (.variable source) (.variable target) result) :
    result = [(source, .variable target)] := by
  cases unification with
  | reflexive => exact False.elim (distinct rfl)
  | freshAlias => rfl

/-- The explicit equality prefix has an independent unification derivation. -/
theorem unifies_empty_distinct_alias (source target : LogicVar)
    (distinct : source ≠ target) :
    Unifies [] (.variable source) (.variable target)
      [(source, .variable target)] :=
  .freshAlias [] source target distinct (by simp [Fresh])

/-- Open Prolog identity compares instantiated syntax without grounding open
variables. This differs essentially from the older total-valuation model. -/
def Identical (bindings : Substitution) (left right : Term) : Prop :=
  bindings.applyTerm left = bindings.applyTerm right

/-- Before aliasing, two distinct open variables are not Prolog-identical. -/
theorem empty_distinct_variables_not_identical (source target : LogicVar)
    (distinct : source ≠ target) :
    ¬ Identical [] (.variable source) (.variable target) := by
  simpa [Identical] using distinct

/-- After the singleton alias, the two open variables are Prolog-identical. -/
theorem singleton_alias_makes_variables_identical (source target : LogicVar) :
    Identical [(source, .variable target)]
      (.variable source) (.variable target) := by
  simp [Identical, Term.instantiateOne]

/-- Abstract continuation observations used to state the normalization law
without assuming the unfinished call/effect semantics. -/
abbrev Continuation (Observation : Type) :=
  Substitution → List Goal → Observation → Prop

/-- A continuation respects instantiation when carrying a finite substitution
in its state is observationally equivalent to applying that substitution to
the remaining goal sequence. Proving this law for the complete ordered
Prolog semantics is the explicit remaining bridge obligation. -/
def ContinuationRespectsInstantiation {Observation : Type}
    (observe : Continuation Observation) : Prop :=
  ∀ bindings goals observation,
    observe bindings goals observation ↔
      observe [] (bindings.applyGoals goals) observation

/-- Execute only the explicit variable-alias prefix, then hand the resulting
open substitution and untouched continuation to an abstract observer. -/
def ObservesAfterAlias {Observation : Type}
    (observe : Continuation Observation) (bindings : Substitution)
    (source target : LogicVar) (goals : List Goal)
    (observation : Observation) : Prop :=
  ∃ result,
    Unifies bindings (.variable source) (.variable target) result ∧
      observe result goals observation

/-- Parametric alias-normalization theorem.

For every continuation semantics that proves the explicit substitution law,
executing a fresh alias equality is observationally equivalent to native
Prolog's translation-time sharing, represented by replacing the shared
identity throughout the remaining goals. This theorem does not assume that
the unfinished full ordered semantics satisfies the premise. -/
theorem explicit_alias_prefix_equivalent_to_shared {Observation : Type}
    (observe : Continuation Observation)
    (respects : ContinuationRespectsInstantiation observe)
    (source target : LogicVar) (distinct : source ≠ target)
    (goals : List Goal) (observation : Observation) :
    ObservesAfterAlias observe [] source target goals observation ↔
      observe []
        (Goals.instantiateOne source (.variable target) goals) observation := by
  constructor
  · rintro ⟨result, unification, observed⟩
    have resultEq :=
      unifies_empty_distinct_alias_output distinct unification
    subst result
    exact (respects [(source, .variable target)] goals observation).mp observed
  · intro observed
    refine ⟨[(source, .variable target)],
      unifies_empty_distinct_alias source target distinct, ?_⟩
    exact (respects [(source, .variable target)] goals observation).mpr observed

/-- The pinned nonempty variable-branch rule produces exactly the alias shape
consumed by the parametric normalization theorem. The final equivalence still
retains `ContinuationRespectsInstantiation` as an explicit premise; this
connects the source rule to the semantic obligation without declaring the
unfinished full ordered semantics adequate by definition. -/
theorem normalized_variable_branch_alias_semantics {Observation : Type}
    (observe : Continuation Observation)
    (respects : ContinuationRespectsInstantiation observe)
    (source target : LogicVar) (distinct : source ≠ target)
    (branchGoals aliases continuation : List Goal)
    (template : Term) (branch : Goal)
    (translation : BuildsBranchNormalized (.variable target)
      (.variable source) branchGoals aliases template branch)
    (nonempty : 0 < Goals.flatWidth branchGoals)
    (observation : Observation) :
    aliases = [.unify (.variable source) (.variable target)] ∧
      template = .variable target ∧ branch = .conjunction branchGoals ∧
      (ObservesAfterAlias observe [] source target continuation observation ↔
        observe []
          (Goals.instantiateOne source (.variable target) continuation)
          observation) := by
  obtain ⟨aliasesEq, templateEq, branchEq⟩ :=
    translation.variable_nonempty_shape nonempty
  exact ⟨aliasesEq, templateEq, branchEq,
    explicit_alias_prefix_equivalent_to_shared observe respects source target
      distinct continuation observation⟩

end PLeaTTa.PeTTaSpec.PrologCore.OpenSubstitution
