/-
Module: PLeaTTa.PeTTaSpec.PrologCore
Purpose: Independent syntax for the Prolog term and goal fragment emitted by
  pinned PeTTa's translator.  It does not reuse PLeaTTa's executable Goal IR.
Trusted boundary: none
Main exports: Term, Goal, Literal, Quotes, TranslatesExpr
-/
import MettaHyperonFull.Core.Atom

namespace PLeaTTa.PeTTaSpec.PrologCore

open Metta (Atom Ground)

/-- Logical-variable identities in the independent target.  Source variables,
anonymous reader occurrences, and variables allocated by translation occupy
disjoint namespaces, so alpha-equivalence never depends on executable names
such as `_q17`. -/
inductive LogicVar where
  | source (name : String)
  | anonymous (index : Nat)
  | generated (index : Nat)
deriving Repr, Inhabited, DecidableEq

/-- Source and translator-generated variables cannot alias. -/
theorem LogicVar.source_ne_generated (name : String) (index : Nat) :
    LogicVar.source name ≠ .generated index := by
  intro equality
  cases equality

/-- Anonymous reader occurrences cannot alias translator-generated variables. -/
theorem LogicVar.anonymous_ne_generated (anonymousIndex generatedIndex : Nat) :
    LogicVar.anonymous anonymousIndex ≠ .generated generatedIndex := by
  intro equality
  cases equality

/-- Prolog terms relevant to PeTTa's parser and translator.  Proper and dotted
lists are represented directly rather than disguised as a host-language list. -/
inductive Term where
  | variable (identity : LogicVar)
  | atom (name : String)
  | integer (value : Int)
  | float (value : Float)
  | string (value : String)
  | compound (functor : String) (arguments : List Term)
  | list (items : List Term) (tail : Option Term)
deriving Repr, Inhabited

/-- Canonical Prolog list-cell construction.  `[Head|Tail]` extends an
already-list tail and otherwise produces a dotted list.  This is independent
target syntax for pinned `translator.pl`; it does not mention PLeaTTa's
`#c` encoding. -/
def Term.prepend (head tail : Term) : Term :=
  match tail with
  | .list items finalTail => .list (head :: items) finalTail
  | other => .list [head] (some other)

/-- Translation-time state whose membership controls the pinned translator's
highest-priority hook branch.  This is intentionally a proposition-valued
interface rather than PLeaTTa's executable list representation. -/
structure TranslatorState where
  hasRule : String → Prop

/-- Independent translator state before any runtime hook registration. -/
def noTranslatorRules : TranslatorState where
  hasRule := fun _ => False

/-- The independent Prolog goal language generated by `translator.pl`.
Additional primitives can be added as their translation clauses are proved;
none of these constructors refer to PLeaTTa's executable machine. -/
inductive Goal where
  | truth
  | fail
  | unify (left right : Term)
  | identical (left right : Term)
  | call (predicate : String) (arguments : List Term)
  | conjunction (goals : List Goal)
  | disjunction (branches : List Goal)
  | cut
  | ifThenElse (condition thenBranch elseBranch : Goal)
  | softCut (condition thenBranch elseBranch : Goal)
  | negation (goal : Goal)
  | once (goal : Goal)
  | findall (template : Term) (goal : Goal) (output : Term)
  | catch (goal : Goal) (exception : Term) (handler : Goal)
  | transaction (goal : Goal)
  | withMutex (mutex : Term) (goal : Goal)
  | forall (generator test : Goal)
deriving Repr, Inhabited

mutual

/-- Number of executable top-level goals after eliminating the conjunction
wrappers introduced by `translate_expr_to_conj/3`. -/
def Goal.flatWidth : Goal → Nat
  | .conjunction goals => Goals.flatWidth goals
  | _ => 1

/-- Flattened width of an ordered independent goal sequence. -/
def Goals.flatWidth : List Goal → Nat
  | [] => 0
  | goal :: goals => goal.flatWidth + Goals.flatWidth goals

end

/-- Source atoms which PeTTa's first `translate_expr/3` clause returns without
emitting a goal.  Unsupported host grounds intentionally have no constructor. -/
inductive Literal : Atom → Term → Prop where
  | variable (name : String) :
      Literal (.var name) (.variable (.source name))
  | symbol (name : String) : Literal (.sym name) (.atom name)
  | integer (value : Int) : Literal (.gnd (.int value)) (.integer value)
  | float (value : Float) : Literal (.gnd (.float value)) (.float value)
  | string (value : String) : Literal (.gnd (.str value)) (.string value)
  | trueGround : Literal (.gnd (.bool true)) (.atom "true")
  | falseGround : Literal (.gnd (.bool false)) (.atom "false")
  | emptyList : Literal (.expr []) (.list [] none)

/-- Independently specified atomic fragment of pinned `constrain_args/3`.
Variables and atomic values are preserved without goals by
`translator.pl:2`; the supported ground/value representation is shared with
the independent literal relation, not with the executable pattern compiler. -/
inductive ConstrainsAtomicPattern : Atom → Term → Prop where
  | literal {source : Atom} {term : Term} (value : Literal source term) :
      ConstrainsAtomicPattern source term

/-- Pointwise left-to-right `maplist(constrain_args, ...)` traversal for the
atomic fragment used by `translate_clause/3` at `translator.pl:20-22`.  Every
atomic member emits an empty goal list, so flattening preserves `[]`.  Nested
compound patterns are added only when their dispatch is independently proved. -/
inductive ConstrainsAtomicPatternSeq : List Atom → List Term → Prop where
  | nil : ConstrainsAtomicPatternSeq [] []
  | cons {source : Atom} {term : Term} {sources : List Atom}
      {terms : List Term}
      (head : ConstrainsAtomicPattern source term)
      (tail : ConstrainsAtomicPatternSeq sources terms) :
      ConstrainsAtomicPatternSeq (source :: sources) (term :: terms)

/-- Independently specified recursive fragment of pinned `constrain_args/3`.
The atomic rule is `translator.pl:2`; the `cons` rule is lines 3-8.  Pattern
subterms are visited head before tail, their generated-variable counters are
threaded in that order, and their goal sequences are concatenated without
reordering. -/
inductive ConstrainsPattern : TranslatorState → Nat → Atom → Term →
    List Goal → Nat → Prop where
  | atomic {state : TranslatorState} {counter : Nat} {source : Atom}
      {term : Term} (value : ConstrainsAtomicPattern source term) :
      ConstrainsPattern state counter source term [] counter
  | cons {state : TranslatorState} {counter headCounter nextCounter : Nat}
      {headSource tailSource : Atom} {headTerm tailTerm : Term}
      {headGoals tailGoals : List Goal}
      (head : ConstrainsPattern state counter headSource headTerm headGoals
        headCounter)
      (tail : ConstrainsPattern state headCounter tailSource tailTerm tailGoals
        nextCounter) :
      ConstrainsPattern state counter
        (.expr [.sym "cons", headSource, tailSource])
        (Term.prepend headTerm tailTerm) (headGoals ++ tailGoals) nextCounter

/-- Independent left-to-right traversal used by `translate_clause/3` at
`translator.pl:20-22`.  This relation exposes both counter threading and the
ordered flattening of each member's constraint goals. -/
inductive ConstrainsPatternSeq : TranslatorState → Nat → List Atom →
    List Term → List Goal → Nat → Prop where
  | nil {state : TranslatorState} {counter : Nat} :
      ConstrainsPatternSeq state counter [] [] [] counter
  | cons {state : TranslatorState} {counter headCounter nextCounter : Nat}
      {source : Atom} {term : Term} {sources : List Atom} {terms : List Term}
      {headGoals tailGoals : List Goal}
      (head : ConstrainsPattern state counter source term headGoals
        headCounter)
      (tail : ConstrainsPatternSeq state headCounter sources terms tailGoals
        nextCounter) :
      ConstrainsPatternSeq state counter (source :: sources) (term :: terms)
        (headGoals ++ tailGoals) nextCounter

mutual

/-- Deep syntactic quotation into native Prolog terms. -/
inductive Quotes : Atom → Term → Prop where
  | variable (name : String) :
      Quotes (.var name) (.variable (.source name))
  | symbol (name : String) : Quotes (.sym name) (.atom name)
  | integer (value : Int) : Quotes (.gnd (.int value)) (.integer value)
  | float (value : Float) : Quotes (.gnd (.float value)) (.float value)
  | string (value : String) : Quotes (.gnd (.str value)) (.string value)
  | trueGround : Quotes (.gnd (.bool true)) (.atom "true")
  | falseGround : Quotes (.gnd (.bool false)) (.atom "false")
  | expression {atoms : List Atom} {terms : List Term}
      (items : QuotesList atoms terms) : Quotes (.expr atoms) (.list terms none)

/-- Pointwise quotation of expression members. -/
inductive QuotesList : List Atom → List Term → Prop where
  | nil : QuotesList [] []
  | cons {atom : Atom} {term : Term} {atoms : List Atom} {terms : List Term}
      (head : Quotes atom term) (tail : QuotesList atoms terms) :
      QuotesList (atom :: atoms) (term :: terms)

end

/-- The pinned target goal for `(and-then A B)`.  `translate_expr_to_conj/3`
retains each translated subexpression as an explicit conjunction, and the
outer conjunction preserves the source order before the identity test.
[SPEC translator.pl:177-180; translator.pl:45-47] -/
def andThenGoal (condition body output : Term)
    (conditionGoals bodyGoals : List Goal) : Goal :=
  .conjunction
    [.conjunction conditionGoals,
     .ifThenElse (.identical condition (.atom "true"))
       (.conjunction [.conjunction bodyGoals, .unify output body])
       (.unify output (.atom "false"))]

/-- The pinned target goal for `(or-else A B)`.  The body conjunction remains
inside only the false branch; the true branch binds the enclosing result
directly. [SPEC translator.pl:181-184; translator.pl:45-47] -/
def orElseGoal (condition body output : Term)
    (conditionGoals bodyGoals : List Goal) : Goal :=
  .conjunction
    [.conjunction conditionGoals,
     .ifThenElse (.identical condition (.atom "true"))
       (.unify output (.atom "true"))
       (.conjunction [.conjunction bodyGoals, .unify output body])]

/-- Independent explicit-alias normalization of pinned `build_branch/4`.

Native Prolog represents the second case below by making `value` and `output`
the same logical variable at translation time.  The normalized relation
reifies that sharing as an equality which is scheduled before the condition.
This preserves the alias outside the selected branch without defining the
reference in terms of PLeaTTa's executable compiler.

The final two fields are the branch template and the independent branch goal.
They expose the equality-before-conjunction order used by `build_branch/4`.
[SPEC translator.pl:394-397] -/
inductive BuildsBranchNormalized (output : Term) :
    Term → List Goal → List Goal → Term → Goal → Prop where
  | empty (value : Term) (goals : List Goal)
      (empty : Goals.flatWidth goals = 0) :
      BuildsBranchNormalized output value goals [] value (.unify value output)
  | aliasVariable (identity : LogicVar) (goals : List Goal)
      (nonempty : 0 < Goals.flatWidth goals) :
      BuildsBranchNormalized output (.variable identity) goals
        [.unify (.variable identity) output] output (.conjunction goals)
  | nonVariable (value : Term) (goals : List Goal)
      (nonempty : 0 < Goals.flatWidth goals)
      (notVariable : ∀ identity, value ≠ .variable identity) :
      BuildsBranchNormalized output value goals [] value
        (.conjunction (.unify value output :: goals))

/-- Pinned `translate_expr_to_conj/3` uses the atom `true` for an empty goal
sequence.  The `if` clauses omit that empty conjunction and otherwise schedule
the condition conjunction before the identity test.
[SPEC translator.pl:151-162; translator.pl:45-47] -/
def conditionThen (conditionGoals : List Goal) (decision : Goal) : List Goal :=
  if Goals.flatWidth conditionGoals = 0 then [decision]
  else [.conjunction conditionGoals, decision]

/-- Negative priority witness for `build_branch/4`: a flattened-empty branch
uses the first clause and therefore cannot manufacture a translation-time
alias, even when its result is a variable. -/
theorem BuildsBranchNormalized.zero_width_no_alias {output value : Term}
    {goals aliases : List Goal} {template : Term} {branch : Goal}
    (translation :
      BuildsBranchNormalized output value goals aliases template branch)
    (empty : Goals.flatWidth goals = 0) : aliases = [] := by
  cases translation with
  | empty => rfl
  | aliasVariable _ _ nonempty => omega
  | nonVariable _ _ nonempty _ => omega

/-- Positive priority inversion for `build_branch/4`: a variable-valued
nonempty branch has exactly the explicit alias prefix and unchanged branch
body used by the normalization. -/
theorem BuildsBranchNormalized.variable_nonempty_shape
    {output : Term} {source : LogicVar} {goals aliases : List Goal}
    {template : Term} {branch : Goal}
    (translation :
      BuildsBranchNormalized output (.variable source) goals aliases template
        branch)
    (nonempty : 0 < Goals.flatWidth goals) :
    aliases = [.unify (.variable source) output] ∧
      template = output ∧ branch = .conjunction goals := by
  cases translation with
  | empty _ _ empty => omega
  | aliasVariable => exact ⟨rfl, rfl, rfl⟩
  | nonVariable _ _ _ notVariable =>
      exact False.elim (notVariable source rfl)

mutual

/-- Independently specified fragment of pinned `translate_expr/3`.  Its rules
state native translation behavior without referring to PLeaTTa's executable
compiler. -/
inductive TranslatesExpr : TranslatorState → Nat → Atom → Term → List Goal →
    Nat → Prop where
  | literal {state : TranslatorState} {counter : Nat} {source : Atom}
      {term : Term}
      (value : Literal source term) :
      TranslatesExpr state counter source term [] counter
  | quote {state : TranslatorState} {counter : Nat} {source : Atom}
      {term : Term}
      (notShadowed : ¬ state.hasRule "quote")
      (value : Quotes source term) :
      TranslatesExpr state counter (.expr [.sym "quote", source]) term [] counter
  | cut {state : TranslatorState} {counter : Nat}
      (notShadowed : ¬ state.hasRule "cut") :
      TranslatesExpr state counter (.expr [.sym "cut"]) (.atom "true") [.cut]
        counter
  | collapse {state : TranslatorState} {counter bodyCounter : Nat}
      {source : Atom} {template : Term} {bodyGoals : List Goal}
      (notShadowed : ¬ state.hasRule "collapse")
      (body :
        TranslatesExpr state counter source template bodyGoals bodyCounter) :
      TranslatesExpr state counter (.expr [.sym "collapse", source])
        (.variable (.generated bodyCounter))
        [.findall template (.conjunction bodyGoals)
          (.variable (.generated bodyCounter))]
        (bodyCounter + 1)
  -- [SPEC translator.pl:185-188] Translation traverses pattern, value, and
  -- body in that order, but the generated goal order begins with unification.
  | letBind {state : TranslatorState}
      {counter patternCounter valueCounter nextCounter : Nat}
      {pattern value bodySource : Atom}
      {patternTerm valueTerm bodyTerm : Term}
      {patternGoals valueGoals bodyGoals : List Goal}
      (notShadowed : ¬ state.hasRule "let")
      (patternTranslation :
        TranslatesExpr state counter pattern patternTerm patternGoals
          patternCounter)
      (valueTranslation :
        TranslatesExpr state patternCounter value valueTerm valueGoals
          valueCounter)
      (bodyTranslation :
        TranslatesExpr state valueCounter bodySource bodyTerm bodyGoals
          nextCounter) :
      TranslatesExpr state counter
        (.expr [.sym "let", pattern, value, bodySource])
        bodyTerm
        ([.unify patternTerm valueTerm] ++ patternGoals ++ valueGoals ++
          bodyGoals)
        nextCounter
  -- [SPEC translator.pl:185-188] `chain` is the second head admitted by the
  -- same pinned clause as `let`.  The clause traverses the argument list as
  -- written; conventional names such as value/pattern do not justify swapping
  -- the first two translations.
  | chainBind {state : TranslatorState}
      {counter firstCounter secondCounter nextCounter : Nat}
      {first second bodySource : Atom}
      {firstTerm secondTerm bodyTerm : Term}
      {firstGoals secondGoals bodyGoals : List Goal}
      (notShadowed : ¬ state.hasRule "chain")
      (firstTranslation :
        TranslatesExpr state counter first firstTerm firstGoals firstCounter)
      (secondTranslation :
        TranslatesExpr state firstCounter second secondTerm secondGoals
          secondCounter)
      (bodyTranslation :
        TranslatesExpr state secondCounter bodySource bodyTerm bodyGoals
          nextCounter) :
      TranslatesExpr state counter
        (.expr [.sym "chain", first, second, bodySource])
        bodyTerm
        ([.unify firstTerm secondTerm] ++ firstGoals ++ secondGoals ++
          bodyGoals)
        nextCounter
  | andThen {state : TranslatorState}
      {counter conditionCounter bodyCounter : Nat}
      {conditionSource bodySource : Atom} {conditionTerm bodyTerm : Term}
      {conditionGoals bodyGoals : List Goal}
      (notShadowed : ¬ state.hasRule "and-then")
      (conditionTranslation :
        TranslatesExpr state counter conditionSource conditionTerm
          conditionGoals conditionCounter)
      (bodyTranslation :
        TranslatesExpr state conditionCounter bodySource bodyTerm bodyGoals
          bodyCounter) :
      TranslatesExpr state counter
        (.expr [.sym "and-then", conditionSource, bodySource])
        (.variable (.generated bodyCounter))
        [andThenGoal conditionTerm bodyTerm
          (.variable (.generated bodyCounter)) conditionGoals bodyGoals]
        (bodyCounter + 1)
  | orElse {state : TranslatorState}
      {counter conditionCounter bodyCounter : Nat}
      {conditionSource bodySource : Atom} {conditionTerm bodyTerm : Term}
      {conditionGoals bodyGoals : List Goal}
      (notShadowed : ¬ state.hasRule "or-else")
      (conditionTranslation :
        TranslatesExpr state counter conditionSource conditionTerm
          conditionGoals conditionCounter)
      (bodyTranslation :
        TranslatesExpr state conditionCounter bodySource bodyTerm bodyGoals
          bodyCounter) :
      TranslatesExpr state counter
        (.expr [.sym "or-else", conditionSource, bodySource])
        (.variable (.generated bodyCounter))
        [orElseGoal conditionTerm bodyTerm
          (.variable (.generated bodyCounter)) conditionGoals bodyGoals]
        (bodyCounter + 1)
  -- The equality prefix is an explicit normalization of native Prolog's
  -- translation-time variable sharing.  Its adequacy to that sharing is a
  -- separate semantic obligation; this constructor does not identify the two
  -- definitions by fiat. [SPEC translator.pl:151-155, 394-397]
  | ifThen {state : TranslatorState}
      {counter conditionCounter thenCounter : Nat}
      {conditionSource thenSource : Atom}
      {conditionTerm thenTerm branchTemplate : Term}
      {conditionGoals thenGoals aliasGoals : List Goal}
      {thenBranch : Goal}
      (notShadowed : ¬ state.hasRule "if")
      (conditionTranslation :
        TranslatesExpr state counter conditionSource conditionTerm
          conditionGoals conditionCounter)
      (thenTranslation :
        TranslatesExpr state conditionCounter thenSource thenTerm thenGoals
          thenCounter)
      (branch :
        BuildsBranchNormalized (.variable (.generated thenCounter))
          thenTerm thenGoals aliasGoals branchTemplate thenBranch) :
      TranslatesExpr state counter
        (.expr [.sym "if", conditionSource, thenSource])
        (.variable (.generated thenCounter))
        (aliasGoals ++ conditionThen conditionGoals
          (.ifThenElse (.identical conditionTerm (.atom "true"))
            thenBranch .fail))
        (thenCounter + 1)
  -- Both branch aliases are scheduled before the condition, matching the
  -- scope of the shared variables created by the two native build_branch/4
  -- calls. [SPEC translator.pl:156-162, 394-397]
  | ifThenElse {state : TranslatorState}
      {counter conditionCounter thenCounter elseCounter : Nat}
      {conditionSource thenSource elseSource : Atom}
      {conditionTerm thenTerm elseTerm : Term}
      {thenTemplate elseTemplate : Term}
      {conditionGoals thenGoals elseGoals : List Goal}
      {thenAliasGoals elseAliasGoals : List Goal}
      {thenBranch elseBranch : Goal}
      (notShadowed : ¬ state.hasRule "if")
      (conditionTranslation :
        TranslatesExpr state counter conditionSource conditionTerm
          conditionGoals conditionCounter)
      (thenTranslation :
        TranslatesExpr state conditionCounter thenSource thenTerm thenGoals
          thenCounter)
      (elseTranslation :
        TranslatesExpr state thenCounter elseSource elseTerm elseGoals
          elseCounter)
      (thenBuild :
        BuildsBranchNormalized (.variable (.generated elseCounter))
          thenTerm thenGoals thenAliasGoals thenTemplate thenBranch)
      (elseBuild :
        BuildsBranchNormalized (.variable (.generated elseCounter))
          elseTerm elseGoals elseAliasGoals elseTemplate elseBranch) :
      TranslatesExpr state counter
        (.expr [.sym "if", conditionSource, thenSource, elseSource])
        (.variable (.generated elseCounter))
        (thenAliasGoals ++ elseAliasGoals ++
          conditionThen conditionGoals
            (.ifThenElse (.identical conditionTerm (.atom "true"))
              thenBranch elseBranch))
        (elseCounter + 1)
  | progn {state : TranslatorState} {counter nextCounter : Nat}
      {sources : List Atom} {first last : Term} {goals : List Goal}
      (notShadowed : ¬ state.hasRule "progn")
      (arguments :
        TranslatesSeq state counter sources first last goals nextCounter) :
      TranslatesExpr state counter (.expr (.sym "progn" :: sources)) last goals
        nextCounter
  | prog1 {state : TranslatorState} {counter nextCounter : Nat}
      {sources : List Atom} {first last : Term} {goals : List Goal}
      (notShadowed : ¬ state.hasRule "prog1")
      (arguments :
        TranslatesSeq state counter sources first last goals nextCounter) :
      TranslatesExpr state counter (.expr (.sym "prog1" :: sources)) first goals
        nextCounter

/-- A nonempty left-to-right translation sequence.  The relation remembers
its first and last result terms, which are selected by `prog1` and `progn`
respectively, while concatenating goals in pinned execution order. -/
inductive TranslatesSeq : TranslatorState → Nat → List Atom → Term → Term →
    List Goal → Nat → Prop where
  | single {state : TranslatorState} {counter nextCounter : Nat}
      {source : Atom} {term : Term} {goals : List Goal}
      (head : TranslatesExpr state counter source term goals nextCounter) :
      TranslatesSeq state counter [source] term term goals nextCounter
  | cons {state : TranslatorState} {counter middleCounter nextCounter : Nat}
      {source : Atom} {sources : List Atom} {headTerm first last : Term}
      {headGoals tailGoals : List Goal}
      (head :
        TranslatesExpr state counter source headTerm headGoals middleCounter)
      (tail : TranslatesSeq state middleCounter sources first last tailGoals
        nextCounter) :
      TranslatesSeq state counter (source :: sources) headTerm last
        (headGoals ++ tailGoals) nextCounter

end

/-- Independent ordered `translate_args/3` traversal from pinned
`translator.pl:409-412`.  Unlike `TranslatesSeq`, this relation includes the
empty case and preserves every translated argument term, not merely the first
and last. -/
inductive TranslatesArgs : TranslatorState → Nat → List Atom → List Term →
    List Goal → Nat → Prop where
  | nil {state : TranslatorState} {counter : Nat} :
      TranslatesArgs state counter [] [] [] counter
  | cons {state : TranslatorState} {counter middleCounter nextCounter : Nat}
      {source : Atom} {sources : List Atom} {term : Term} {terms : List Term}
      {headGoals tailGoals : List Goal}
      (head :
        TranslatesExpr state counter source term headGoals middleCounter)
      (tail :
        TranslatesArgs state middleCounter sources terms tailGoals nextCounter) :
      TranslatesArgs state counter (source :: sources) (term :: terms)
        (headGoals ++ tailGoals) nextCounter

/-- Atomic refined type names supported by the first exact type-check bridge.
The three unchecked names follow pinned translator priority. Truth spellings
are excluded because their executable boolean encoding is not a type-name
encoding. Compound/dependent type terms remain a separate obligation. -/
def RefinedSymbolType (name : String) : Prop :=
  name ≠ "%Undefined%" ∧ name ≠ "Atom" ∧ name ≠ "Expression" ∧
    name ≠ "true" ∧ name ≠ "false"

/-- Independently relevant input-type modes for pinned
`translate_args_by_type/4`. `value` is the no-extra-check `%Undefined%`/`Atom`
fragment; `refined` names the exact simple type checked after evaluation. -/
inductive ArgumentMode where
  | expression
  | value
  | refined (expected : String)
deriving Repr

/-- Independent first-pass registration judgment for one source form.  It
states the exact syntactic condition under which pinned `filereader.pl`
asserts `fun/1` and `arity/2`; it does not call PLeaTTa's table collector or
compiler.  The arity here counts MeTTa inputs, so the native Prolog predicate
has one additional result slot. [SPEC filereader.pl:20-23] -/
inductive RegistersFunction : Atom → String → Nat → Prop where
  | equation (head : String) (parameters : List Atom) (right : Atom) :
      RegistersFunction
        (.expr [.sym "=", .expr (.sym head :: parameters), right])
        head parameters.length

/-- A source program registers a function/arity pair when one of its forms
satisfies the independent first-pass judgment. -/
def ProgramRegistersFunction (sources : List Atom) (head : String)
    (arity : Nat) : Prop :=
  ∃ source, source ∈ sources ∧ RegistersFunction source head arity

/-- Untyped source declarations evaluate every supplied argument.  The list
length is deliberately unconstrained: incomplete prefixes need modes even
when their length is not an accepted function arity. -/
inductive ValueArgumentModes : List ArgumentMode → Prop where
  | nil : ValueArgumentModes []
  | cons {modes : List ArgumentMode} (tail : ValueArgumentModes modes) :
      ValueArgumentModes (.value :: modes)

/-- Independent source-derived registry used by ordinary function dispatch.
`isDefined` and `acceptsArity` model the `fun/1` and predicate-arity facts
established by pinned source loading. `argumentModes` describes staging for
the arguments actually supplied to one call; accepted arity is intentionally
separate so the same registry can specify both complete calls and partial
applications. The coherence field prevents modes from inventing an
unregistered head. [SPEC filereader.pl:20-44;
translator.pl:18-34,310-370] -/
structure FunctionRegistry where
  isDefined : String → Prop
  acceptsArity : String → Nat → Prop
  argumentModes : String → List ArgumentMode → Prop
  modes_defined {head : String} {modes : List ArgumentMode} :
    argumentModes head modes → isDefined head

/-- Independent registry induced by an untyped source program.  Typed source
declarations get a separate registry/dispatch relation because they can create
multiple ordered branches; this table models the ordinary direct-or-partial
path only. [SPEC filereader.pl:20-23; translator.pl:310-346] -/
def sourceFunctionRegistry (sources : List Atom) : FunctionRegistry where
  isDefined := fun head =>
    ∃ arity, ProgramRegistersFunction sources head arity
  acceptsArity := fun head arity =>
    ProgramRegistersFunction sources head arity
  argumentModes := fun head modes =>
    (∃ arity, ProgramRegistersFunction sources head arity) ∧
      ValueArgumentModes modes
  modes_defined := by
    intro _ _ signature
    exact signature.1

/-- Small source program used to witness that first-pass registration and the
ordinary call relation are inhabited by actual function syntax. -/
def unaryIdentitySource (name : String) : List Atom :=
  [.expr [.sym "=", .expr [.sym name, .var "x"], .var "x"]]

theorem unaryIdentitySource_registers (name : String) :
    ProgramRegistersFunction (unaryIdentitySource name) name 1 := by
  exact ⟨.expr [.sym "=", .expr [.sym name, .var "x"], .var "x"],
    by simp [unaryIdentitySource], .equation name [.var "x"] (.var "x")⟩

def binaryFirstSource (name : String) : List Atom :=
  [.expr [.sym "=", .expr [.sym name, .var "x", .var "y"], .var "x"]]

theorem binaryFirstSource_registers (name : String) :
    ProgramRegistersFunction (binaryFirstSource name) name 2 := by
  exact ⟨.expr
      [.sym "=", .expr [.sym name, .var "x", .var "y"], .var "x"],
    by simp [binaryFirstSource],
    .equation name [.var "x", .var "y"] (.var "x")⟩

theorem binaryFirstSource_rejects_unary (name : String) :
    ¬ ProgramRegistersFunction (binaryFirstSource name) name 1 := by
  rintro ⟨source, sourceMember, registration⟩
  simp [binaryFirstSource] at sourceMember
  subst source
  cases registration

/-- One source declaration contributes an arrow-chain candidate for a
particular atom head.  This is the single matching shape queried by pinned
`match('&self', [':', Fun, TypeChain], ...)`.
[SPEC translator.pl:317] -/
inductive DeclaresTypeChain (head : String) :
    (Atom × Atom) → List Atom → Prop where
  | arrow (types : List Atom) :
      DeclaresTypeChain head
        (.sym head, .expr (.sym "->" :: types)) types

/-- Ordered `findall/3` candidates before duplicate removal.  Nonmatching
declarations are skipped; matching arrow declarations retain source order and
occurrence multiplicity. [SPEC translator.pl:317] -/
inductive CollectsRawTypeChains (head : String) :
    List (Atom × Atom) → List (List Atom) → Prop where
  | nil : CollectsRawTypeChains head [] []
  | keep {declaration : Atom × Atom} {chain : List Atom}
      {declarations : List (Atom × Atom)} {chains : List (List Atom)}
      (matchProof : DeclaresTypeChain head declaration chain)
      (tail : CollectsRawTypeChains head declarations chains) :
      CollectsRawTypeChains head (declaration :: declarations)
        (chain :: chains)
  | skip {declaration : Atom × Atom}
      {declarations : List (Atom × Atom)} {chains : List (List Atom)}
      (doesNotMatch : ¬ ∃ chain, DeclaresTypeChain head declaration chain)
      (tail : CollectsRawTypeChains head declarations chains) :
      CollectsRawTypeChains head (declaration :: declarations) chains

/-- A collected chain is closed when its source syntax contains no logical
variable occurrence. -/
def ClosedTypeChain (chain : List Atom) : Prop :=
  chain.flatMap Atom.vars = []

/-- Strict identity of two separately copied `findall/3` answers.  Separate
answers containing variables are renamed apart and therefore never
identical; closed answers compare by source-term structural identity.
[SPEC translator.pl:317-318] -/
inductive CopiedTypeChainsIdentical : List Atom → List Atom → Prop where
  | closed {left right : List Atom}
      (leftClosed : ClosedTypeChain left)
      (rightClosed : ClosedTypeChain right)
      (sameSyntax : (left == right) = true) :
      CopiedTypeChainsIdentical left right

/-- Remove every later answer strictly identical to one retained first
occurrence. -/
inductive RemovesCopiedTypeChainDuplicates (first : List Atom) :
    List (List Atom) → List (List Atom) → Prop where
  | nil : RemovesCopiedTypeChainDuplicates first [] []
  | drop {candidate : List Atom} {input output : List (List Atom)}
      (same : CopiedTypeChainsIdentical candidate first)
      (tail : RemovesCopiedTypeChainDuplicates first input output) :
      RemovesCopiedTypeChainDuplicates first (candidate :: input) output
  | keep {candidate : List Atom} {input output : List (List Atom)}
      (different : ¬ CopiedTypeChainsIdentical candidate first)
      (tail : RemovesCopiedTypeChainDuplicates first input output) :
      RemovesCopiedTypeChainDuplicates first (candidate :: input)
        (candidate :: output)

/-- Independent first-occurrence `list_to_set/2` judgment over the freshly
copied answer list. [SPEC translator.pl:318] -/
inductive DedupsTypeChains : List (List Atom) → List (List Atom) → Prop where
  | nil : DedupsTypeChains [] []
  | cons {first : List Atom} {input filtered unique : List (List Atom)}
      (removes : RemovesCopiedTypeChainDuplicates first input filtered)
      (tail : DedupsTypeChains filtered unique) :
      DedupsTypeChains (first :: input) (first :: unique)

/-- Independent composition of pinned type-chain collection and strict
first-occurrence duplicate removal. -/
def CollectsTypeChains (declarations : List (Atom × Atom)) (head : String)
    (chains : List (List Atom)) : Prop :=
  ∃ raw, CollectsRawTypeChains head declarations raw ∧
    DedupsTypeChains raw chains

/-- Exact pinned soft-cut type/meta-type fallback for a translated value.
Generated variables are named by the independent compiler counter.
[SPEC translator.pl:356-370] -/
def refinedTypeCheckGoals (value : Term) (expected : String) (counter : Nat) :
    List Goal :=
  let directType := Term.variable (.generated counter)
  let metaType := Term.variable (.generated (counter + 1))
  [.softCut
    (.conjunction
      [.call "get-type" [value, directType],
       .unify directType (.atom expected)])
    .truth
    (.conjunction
      [.call "get-metatype" [value, metaType],
       .unify metaType (.atom expected)])]

/-- Source-variable order used when native `findall/3` copies one declared
arrow chain into a branch-local fresh variant.  First occurrence determines
the independent generated-variable index; repeated occurrences share it.
This definition is over source syntax only and does not call PLeaTTa's
compiler or substitution implementation. [SPEC translator.pl:317-321] -/
def typeChainVariables (chain : List Atom) : List String :=
  (chain.flatMap Atom.vars).eraseDups

mutual

/-- Independent freshening of one supported type term.  Symbols are copied,
source type variables are replaced by branch-local generated variables, and
compound MeTTa type syntax becomes an independent proper Prolog list.  This
is the recursive term shape copied by `findall/3`; it does not call the
executable substitution or chain encoder. [SPEC translator.pl:317-321] -/
inductive FreshensTypeAtom (sourceChain : List Atom) (counter : Nat) :
    Atom → Term → Prop where
  | symbol (name : String) :
      FreshensTypeAtom sourceChain counter (.sym name) (.atom name)
  | variable (name : String)
      (member : name ∈ typeChainVariables sourceChain) :
      FreshensTypeAtom sourceChain counter (.var name)
        (.variable
          (.generated (counter + List.idxOf name
            (typeChainVariables sourceChain))))
  | expression {sources : List Atom} {references : List Term}
      (items : FreshensTypeAtoms sourceChain counter sources references) :
      FreshensTypeAtom sourceChain counter (.expr sources)
        (.list references none)

/-- Ordered pointwise freshening for a type chain or compound type body. -/
inductive FreshensTypeAtoms (sourceChain : List Atom) (counter : Nat) :
    List Atom → List Term → Prop where
  | nil : FreshensTypeAtoms sourceChain counter [] []
  | cons {source : Atom} {reference : Term} {sources : List Atom}
      {references : List Term}
      (head : FreshensTypeAtom sourceChain counter source reference)
      (tail : FreshensTypeAtoms sourceChain counter sources references) :
      FreshensTypeAtoms sourceChain counter (source :: sources)
        (reference :: references)

end

/-- One branch-local fresh variant of a complete declared arrow chain.  Its
counter cost is the number of distinct source type variables, irrespective of
how often each variable occurs. [SPEC translator.pl:317-321,349-351] -/
inductive FreshensTypeChain (counter : Nat) (sourceChain : List Atom) :
    List Term → Nat → Prop where
  | freshened {referenceChain : List Term}
      (atoms : FreshensTypeAtoms sourceChain counter sourceChain
        referenceChain) :
      FreshensTypeChain counter sourceChain referenceChain
        (counter + (typeChainVariables sourceChain).length)

/-- General independent type/meta-type soft-cut.  Unlike
`refinedTypeCheckGoals`, the expected type may itself be an open branch-local
variable. [SPEC translator.pl:349-370] -/
def typedTypeCheckGoals (value expected : Term) (counter : Nat) : List Goal :=
  let directType := Term.variable (.generated counter)
  let metaType := Term.variable (.generated (counter + 1))
  [.softCut
    (.conjunction
      [.call "get-type" [value, directType],
       .unify directType expected])
    .truth
    (.conjunction
      [.call "get-metatype" [value, metaType],
       .unify metaType expected])]

/-- Types which take the checked input branch of
`translate_args_by_type/4`. -/
def CheckedInputType (expected : Term) : Prop :=
  expected ≠ .atom "%Undefined%" ∧ expected ≠ .atom "Atom" ∧
    expected ≠ .atom "Expression"

/-- Types which take the checked output branch of
`typed_functioncall_branch/8`. `Expression` is intentionally checked here. -/
def CheckedResultType (expected : Term) : Prop :=
  expected ≠ .atom "%Undefined%" ∧ expected ≠ .atom "Atom"

/-- Independent ordered translation of supplied arguments against one
already-fresh arrow-chain prefix.  The empty-source rule intentionally ignores
surplus declared types, while a nonempty source with no type has no
derivation. [SPEC translator.pl:362-370] -/
inductive TranslatesFreshTypedArgs : TranslatorState → Nat → List Atom →
    List Term → List Term → List Goal → Nat → Prop where
  | nil {state : TranslatorState} {counter : Nat} {types : List Term} :
      TranslatesFreshTypedArgs state counter [] types [] [] counter
  | expression {state : TranslatorState} {counter nextCounter : Nat}
      {source : Atom} {sources : List Atom} {term : Term} {terms : List Term}
      {types : List Term} {tailGoals : List Goal}
      (quoted : Quotes source term)
      (tail : TranslatesFreshTypedArgs state counter sources types terms
        tailGoals nextCounter) :
      TranslatesFreshTypedArgs state counter (source :: sources)
        (.atom "Expression" :: types) (term :: terms) tailGoals nextCounter
  | undefined {state : TranslatorState} {counter middleCounter nextCounter : Nat}
      {source : Atom} {sources : List Atom} {term : Term} {terms : List Term}
      {types : List Term} {headGoals tailGoals : List Goal}
      (head : TranslatesExpr state counter source term headGoals middleCounter)
      (tail : TranslatesFreshTypedArgs state middleCounter sources types terms
        tailGoals nextCounter) :
      TranslatesFreshTypedArgs state counter (source :: sources)
        (.atom "%Undefined%" :: types) (term :: terms)
        (headGoals ++ tailGoals) nextCounter
  | atom {state : TranslatorState} {counter middleCounter nextCounter : Nat}
      {source : Atom} {sources : List Atom} {term : Term} {terms : List Term}
      {types : List Term} {headGoals tailGoals : List Goal}
      (head : TranslatesExpr state counter source term headGoals middleCounter)
      (tail : TranslatesFreshTypedArgs state middleCounter sources types terms
        tailGoals nextCounter) :
      TranslatesFreshTypedArgs state counter (source :: sources)
        (.atom "Atom" :: types) (term :: terms)
        (headGoals ++ tailGoals) nextCounter
  | checked {state : TranslatorState}
      {counter middleCounter nextCounter : Nat}
      {source : Atom} {sources : List Atom} {term expected : Term}
      {terms types : List Term} {headGoals tailGoals : List Goal}
      (checkedType : CheckedInputType expected)
      (head : TranslatesExpr state counter source term headGoals middleCounter)
      (tail : TranslatesFreshTypedArgs state (middleCounter + 2) sources types
        terms tailGoals nextCounter) :
      TranslatesFreshTypedArgs state counter (source :: sources)
        (expected :: types) (term :: terms)
        (headGoals ++ typedTypeCheckGoals term expected middleCounter ++
          tailGoals) nextCounter

/-- Independent result-type suffix generated after one typed call or partial
value has been constructed. -/
inductive TranslatesResultTypeCheck : Nat → Term → Term → List Goal → Nat →
    Prop where
  | undefined {counter : Nat} {value : Term} :
      TranslatesResultTypeCheck counter value (.atom "%Undefined%") [] counter
  | atom {counter : Nat} {value : Term} :
      TranslatesResultTypeCheck counter value (.atom "Atom") [] counter
  | checked {counter : Nat} {value expected : Term}
      (checkedType : CheckedResultType expected) :
      TranslatesResultTypeCheck counter value expected
        (typedTypeCheckGoals value expected counter) (counter + 2)

/-- Independent `build_call_or_partial/6` decision after typed arguments have
been translated. [SPEC translator.pl:335-346] -/
inductive BuildsCallOrPartial (registry : FunctionRegistry) : String →
    List Term → Term → Term → List Goal → Prop where
  | complete {head : String} {terms : List Term} {result : Term}
      (accepted : registry.acceptsArity head terms.length) :
      BuildsCallOrPartial registry head terms result result
        [.call head (terms ++ [result])]
  | incomplete {head : String} {terms : List Term} {result : Term}
      (rejected : ¬ registry.acceptsArity head terms.length) :
      BuildsCallOrPartial registry head terms result
        (.compound "partial" [.atom head, .list terms none]) []

/-- Independent assembly of one atom-headed, empty-prefix branch of pinned
typed function dispatch.  Freshening, argument checks, fresh incomplete-call
partial construction, and result checks are separate premises so their
adequacy lemmas can be reused independently.  Pre-bound partial heads and
their prefix goals are deliberately outside this relation.
[SPEC translator.pl:335-370] -/
inductive TranslatesTypedBranch (registry : FunctionRegistry) :
    TranslatorState → Nat → String → List Atom → List Atom → Term → Term →
      List Goal → Nat → Prop where
  | branch {state : TranslatorState} {counter freshCounter argumentCounter
      nextCounter : Nat} {head : String} {sources sourceChain : List Atom}
      {freshChain parameterTypes : List Term} {resultType sharedResult
      branchResult : Term} {terms : List Term}
      {argumentGoals callGoals resultGoals : List Goal}
      (freshened : FreshensTypeChain counter sourceChain freshChain
        freshCounter)
      (split : freshChain = parameterTypes ++ [resultType])
      (arguments : TranslatesFreshTypedArgs state freshCounter sources
        parameterTypes terms argumentGoals argumentCounter)
      (callOrPartial : BuildsCallOrPartial registry head terms sharedResult
        branchResult callGoals)
      (resultCheck : TranslatesResultTypeCheck argumentCounter branchResult
        resultType resultGoals nextCounter) :
      TranslatesTypedBranch registry state counter head sources sourceChain
        sharedResult branchResult
        (argumentGoals ++ callGoals ++ resultGoals) nextCounter

/-- Independent ordered *raw branch-construction* judgment for the
atom-headed, empty-prefix fragment.  It specifies the body of
`typed_functioncall_branch/8` pointwise, before Prolog's shared `Out` variable
has unified the branch results during `maplist/3`.  Every source type chain
contributes exactly one raw branch in source order; duplicates therefore
remain duplicates unless the separately specified `list_to_set/2`
preprocessing relation has removed them.

This relation is deliberately not the full semantics of the pinned
`maplist/3` call: shared-output unification and its substitution through every
branch still require an independent unification judgment.  Chain extraction,
nonempty guards, prefix-goal insertion, pre-bound partial heads, and final
disjunction construction are also separate outer obligations.
[SPEC translator.pl:320-321,349-358] -/
inductive TranslatesTypedBranches (registry : FunctionRegistry)
    (state : TranslatorState) (head : String) (sources : List Atom)
    (sharedResult : Term) : Nat → List (List Atom) →
      List (Term × List Goal) → Nat → Prop where
  | nil {counter : Nat} :
      TranslatesTypedBranches registry state head sources sharedResult
        counter [] [] counter
  | cons {counter middleCounter nextCounter : Nat}
      {sourceChain : List Atom} {sourceChains : List (List Atom)}
      {branchResult : Term} {branchGoals : List Goal}
      {branches : List (Term × List Goal)}
      (branch : TranslatesTypedBranch registry state counter head sources
        sourceChain sharedResult branchResult branchGoals middleCounter)
      (tail : TranslatesTypedBranches registry state head sources sharedResult
        middleCounter sourceChains branches nextCounter) :
      TranslatesTypedBranches registry state head sources sharedResult counter
        (sourceChain :: sourceChains)
        ((branchResult, branchGoals) :: branches) nextCounter

/-- Independent ordered fragment of pinned `translate_args_by_type/4`
(`translator.pl:362-370`). `Expression` inputs remain quoted source data;
value inputs use ordinary expression translation. The mode list is consumed
in lockstep with source arguments, making type-arity assumptions explicit. -/
inductive TranslatesTypedArgs : TranslatorState → Nat → List ArgumentMode →
    List Atom → List Term → List Goal → Nat → Prop where
  | nil {state : TranslatorState} {counter : Nat} :
      TranslatesTypedArgs state counter [] [] [] [] counter
  | expression {state : TranslatorState} {counter nextCounter : Nat}
      {source : Atom} {sources : List Atom} {term : Term} {terms : List Term}
      {modes : List ArgumentMode} {tailGoals : List Goal}
      (quoted : Quotes source term)
      (tail : TranslatesTypedArgs state counter modes sources terms tailGoals
        nextCounter) :
      TranslatesTypedArgs state counter (.expression :: modes)
        (source :: sources) (term :: terms) tailGoals nextCounter
  | value {state : TranslatorState} {counter middleCounter nextCounter : Nat}
      {source : Atom} {sources : List Atom} {term : Term} {terms : List Term}
      {modes : List ArgumentMode} {headGoals tailGoals : List Goal}
      (head : TranslatesExpr state counter source term headGoals middleCounter)
      (tail : TranslatesTypedArgs state middleCounter modes sources terms
        tailGoals nextCounter) :
      TranslatesTypedArgs state counter (.value :: modes) (source :: sources)
        (term :: terms) (headGoals ++ tailGoals) nextCounter
  | refined {state : TranslatorState} {counter middleCounter nextCounter : Nat}
      {source : Atom} {sources : List Atom} {term : Term} {terms : List Term}
      {modes : List ArgumentMode} {headGoals tailGoals : List Goal}
      {expected : String}
      (supportedType : RefinedSymbolType expected)
      (head : TranslatesExpr state counter source term headGoals middleCounter)
      (tail : TranslatesTypedArgs state (middleCounter + 2) modes sources terms
        tailGoals nextCounter) :
      TranslatesTypedArgs state counter (.refined expected :: modes)
        (source :: sources) (term :: terms)
        (headGoals ++ refinedTypeCheckGoals term expected middleCounter ++
          tailGoals) nextCounter

theorem TranslatesTypedArgs.modes_length_eq_terms
    {state : TranslatorState} {counter : Nat} {modes : List ArgumentMode}
    {sources : List Atom} {terms : List Term} {goals : List Goal}
    {nextCounter : Nat}
    (translation :
      TranslatesTypedArgs state counter modes sources terms goals
        nextCounter) :
    modes.length = terms.length := by
  induction translation with
  | nil => rfl
  | expression _ _ ih => simp [ih]
  | value _ _ ih => simp [ih]
  | refined _ _ _ ih => simp [ih]

/-- Within the independently supported exact typed-argument fragment, modes
are consumed in lockstep with supplied source arguments. Pinned surplus-type
tolerance is intentionally outside this exact relation and remains a separate
behavioral obligation. -/
theorem TranslatesTypedArgs.modes_length_eq_sources
    {state : TranslatorState} {counter : Nat} {modes : List ArgumentMode}
    {sources : List Atom} {terms : List Term} {goals : List Goal}
    {nextCounter : Nat}
    (translation :
      TranslatesTypedArgs state counter modes sources terms goals
        nextCounter) :
    modes.length = sources.length := by
  induction translation with
  | nil => rfl
  | expression _ _ ih => simp [ih]
  | value _ _ ih => simp [ih]
  | refined _ _ _ ih => simp [ih]

/-- Independent ordinary direct-call branch for a source-registered function.
The registry supplies a coherent direct signature, arguments follow pinned
typed staging left-to-right, and the generated output is appended as the last
Prolog argument. Typed nondeterministic branching and partial application are
separate relations. [SPEC translator.pl:310-370] -/
inductive TranslatesDefinedCall (registry : FunctionRegistry) :
    TranslatorState → Nat → String → Atom → Term → List Goal → Nat → Prop where
  | call {state : TranslatorState} {counter argumentCounter : Nat}
      {head : String} {modes : List ArgumentMode} {sources : List Atom}
      {terms : List Term} {argumentGoals : List Goal}
      (signature : registry.argumentModes head modes)
      (acceptedArity : registry.acceptsArity head modes.length)
      (notShadowed : ¬ state.hasRule head)
      (arguments :
        TranslatesTypedArgs state counter modes sources terms argumentGoals
          argumentCounter) :
      TranslatesDefinedCall registry state counter head
        (.expr (.sym head :: sources))
        (.variable (.generated argumentCounter))
        (argumentGoals ++
          [.call head (terms ++ [.variable (.generated argumentCounter)])])
        (argumentCounter + 1)

/-- Independent incomplete-arity branch for a source-registered function.
Arguments retain the same source-derived staging as a complete call, but no
call goal or fresh result is emitted: native `build_call_or_partial/6`
returns `partial(Fun, Args)` at the argument counter.
[SPEC translator.pl:335-346] -/
inductive TranslatesDefinedPartial (registry : FunctionRegistry) :
    TranslatorState → Nat → String → Atom → Term → List Goal → Nat → Prop where
  | incomplete {state : TranslatorState} {counter argumentCounter : Nat}
      {head : String} {modes : List ArgumentMode} {sources : List Atom}
      {terms : List Term} {argumentGoals : List Goal}
      (signature : registry.argumentModes head modes)
      (rejectedArity : ¬ registry.acceptsArity head modes.length)
      (notShadowed : ¬ state.hasRule head)
      (arguments :
        TranslatesTypedArgs state counter modes sources terms argumentGoals
          argumentCounter) :
      TranslatesDefinedPartial registry state counter head
        (.expr (.sym head :: sources))
        (.compound "partial" [.atom head, .list terms none])
        argumentGoals argumentCounter

theorem TranslatesDefinedCall.notShadowed {registry : FunctionRegistry}
    {state : TranslatorState} {counter : Nat} {head : String} {source : Atom}
    {term : Term} {goals : List Goal} {nextCounter : Nat}
    (translation :
      TranslatesDefinedCall registry state counter head source term goals
        nextCounter) :
    ¬ state.hasRule head := by
  cases translation
  assumption

/-- Translator-rule priority excludes every ordinary direct-call derivation.
This is the negative companion to the concrete unary witness below. -/
theorem defined_call_hook_blocks {registry : FunctionRegistry}
    {state : TranslatorState} {counter : Nat} {head : String}
    {source : Atom} {term : Term} {goals : List Goal}
    {nextCounter : Nat} (hook : state.hasRule head) :
    ¬ TranslatesDefinedCall registry state counter head source term goals
      nextCounter := by
  intro translation
  exact translation.notShadowed hook

theorem TranslatesDefinedPartial.notShadowed {registry : FunctionRegistry}
    {state : TranslatorState} {counter : Nat} {head : String} {source : Atom}
    {term : Term} {goals : List Goal} {nextCounter : Nat}
    (translation :
      TranslatesDefinedPartial registry state counter head source term goals
        nextCounter) :
    ¬ state.hasRule head := by
  cases translation
  assumption

/-- Translator-rule priority also excludes the partial-function branch. -/
theorem defined_partial_hook_blocks {registry : FunctionRegistry}
    {state : TranslatorState} {counter : Nat} {head : String}
    {source : Atom} {term : Term} {goals : List Goal}
    {nextCounter : Nat} (hook : state.hasRule head) :
    ¬ TranslatesDefinedPartial registry state counter head source term goals
      nextCounter := by
  intro translation
  exact translation.notShadowed hook

/-- A concrete non-vacuity witness: one source-defined unary value function. -/
def unaryValueFunctionRegistry (name : String) : FunctionRegistry where
  isDefined := fun head => head = name
  acceptsArity := fun head arity => head = name ∧ arity = 1
  argumentModes := fun head modes => head = name ∧ modes = [.value]
  modes_defined := by
    intro head modes signature
    exact signature.1

theorem translates_defined_unary_literal (state : TranslatorState)
    (counter : Nat) (name : String) (value : Int)
    (notShadowed : ¬ state.hasRule name) :
    TranslatesDefinedCall (unaryValueFunctionRegistry name) state counter name
      (.expr [.sym name, .gnd (.int value)])
      (.variable (.generated counter))
      [.call name [.integer value, .variable (.generated counter)]]
      (counter + 1) := by
  exact TranslatesDefinedCall.call (by simp [unaryValueFunctionRegistry])
    (by simp [unaryValueFunctionRegistry]) notShadowed
    (TranslatesTypedArgs.value (TranslatesExpr.literal (Literal.integer value))
      (TranslatesTypedArgs.nil (state := state) (counter := counter)))

/-- Concrete two-input registry whose one-argument mode is an incomplete
prefix and whose two-argument mode is complete. -/
def binaryValueFunctionRegistry (name : String) : FunctionRegistry where
  isDefined := fun head => head = name
  acceptsArity := fun head arity => head = name ∧ arity = 2
  argumentModes := fun head modes =>
    head = name ∧ (modes = [.value] ∨ modes = [.value, .value])
  modes_defined := by
    intro head modes signature
    exact signature.1

/-- Positive source-level witness for incomplete-arity partial construction. -/
theorem translates_defined_unary_partial (state : TranslatorState)
    (counter : Nat) (name : String) (value : Int)
    (notShadowed : ¬ state.hasRule name) :
    TranslatesDefinedPartial (binaryValueFunctionRegistry name) state counter
      name (.expr [.sym name, .gnd (.int value)])
      (.compound "partial" [.atom name, .list [.integer value] none]) []
      counter := by
  exact TranslatesDefinedPartial.incomplete
    (by simp [binaryValueFunctionRegistry])
    (by simp [binaryValueFunctionRegistry]) notShadowed
    (TranslatesTypedArgs.value (TranslatesExpr.literal (Literal.integer value))
      (TranslatesTypedArgs.nil (state := state) (counter := counter)))

/-- The same direct witness, now derived from an actual source definition
rather than a hand-constructed registry. -/
theorem translates_source_unary_literal (counter : Nat) (name : String)
    (value : Int) :
    TranslatesDefinedCall (sourceFunctionRegistry (unaryIdentitySource name))
      noTranslatorRules counter name
      (.expr [.sym name, .gnd (.int value)])
      (.variable (.generated counter))
      [.call name [.integer value, .variable (.generated counter)]]
      (counter + 1) := by
  have signature :
      (sourceFunctionRegistry (unaryIdentitySource name)).argumentModes
        name [.value] :=
    ⟨⟨1, unaryIdentitySource_registers name⟩,
      ValueArgumentModes.cons ValueArgumentModes.nil⟩
  exact TranslatesDefinedCall.call signature
    (unaryIdentitySource_registers name) (by simp [noTranslatorRules])
    (TranslatesTypedArgs.value (TranslatesExpr.literal (Literal.integer value))
      (TranslatesTypedArgs.nil (state := noTranslatorRules)
        (counter := counter)))

/-- Incomplete application derived from a two-input source definition. -/
theorem translates_source_unary_partial (counter : Nat) (name : String)
    (value : Int) :
    TranslatesDefinedPartial
      (sourceFunctionRegistry (binaryFirstSource name)) noTranslatorRules
      counter name (.expr [.sym name, .gnd (.int value)])
      (.compound "partial" [.atom name, .list [.integer value] none]) []
      counter := by
  have signature :
      (sourceFunctionRegistry (binaryFirstSource name)).argumentModes
        name [.value] :=
    ⟨⟨2, binaryFirstSource_registers name⟩,
      ValueArgumentModes.cons ValueArgumentModes.nil⟩
  exact TranslatesDefinedPartial.incomplete signature
    (binaryFirstSource_rejects_unary name) (by simp [noTranslatorRules])
    (TranslatesTypedArgs.value (TranslatesExpr.literal (Literal.integer value))
      (TranslatesTypedArgs.nil (state := noTranslatorRules)
        (counter := counter)))

/-- Pinned one-input functions with direct source definitions in `metta.pl`.
This source-derived classification is deliberately separate from the
executable compiler's builtin table.  It covers representation/parsing at
`metta.pl:28-31`, list operations at `metta.pl:114,139-143`, predicates at
`metta.pl:193-196`, diagnostics at `metta.pl:198-200`, and their registrations
at `metta.pl:309-323`.  Every member reaches the ordinary known-function
branch at `translator.pl:310-346`. -/
inductive PinnedUnaryBuiltin : String → Prop where
  | reprValue : PinnedUnaryBuiltin "repr"
  | repraValue : PinnedUnaryBuiltin "repra"
  | parseValue : PinnedUnaryBuiltin "parse"
  | uniqueAtom : PinnedUnaryBuiltin "unique-atom"
  | sizeAtom : PinnedUnaryBuiltin "size-atom"
  | carAtom : PinnedUnaryBuiltin "car-atom"
  | cdrAtom : PinnedUnaryBuiltin "cdr-atom"
  | isGround : PinnedUnaryBuiltin "is-ground"
  | isExpr : PinnedUnaryBuiltin "is-expr"
  | isSpace : PinnedUnaryBuiltin "is-space"
  | println : PinnedUnaryBuiltin "println!"

/-- Independent translation of a pinned unary builtin.  The argument is
evaluated before the call is appended, preserving native left-to-right goal
order.  The generated identity is a canonical representative of native's
fresh logical output variable, not an executable variable name.
[SPEC translator.pl:310-346] -/
inductive TranslatesUnaryBuiltin : TranslatorState → Nat → String → Atom →
    Term → List Goal → Nat → Prop where
  | call {state : TranslatorState} {counter argumentCounter : Nat}
      {head : String} {argumentSource : Atom} {argumentTerm : Term}
      {argumentGoals : List Goal}
      (builtin : PinnedUnaryBuiltin head)
      (notShadowed : ¬ state.hasRule head)
      (argument :
        TranslatesExpr state counter argumentSource argumentTerm argumentGoals
          argumentCounter) :
      TranslatesUnaryBuiltin state counter head
        (.expr [.sym head, argumentSource])
        (.variable (.generated argumentCounter))
        (argumentGoals ++
          [.call head
            [argumentTerm, .variable (.generated argumentCounter)]])
        (argumentCounter + 1)

/-- Every ordinary unary-builtin derivation records that the higher-priority
translator hook was absent. -/
theorem TranslatesUnaryBuiltin.notShadowed
    {state : TranslatorState} {counter : Nat} {head : String} {source : Atom}
    {term : Term} {goals : List Goal} {nextCounter : Nat}
    (translation :
      TranslatesUnaryBuiltin state counter head source term goals nextCounter) :
    ¬ state.hasRule head := by
  cases translation
  assumption

/-- Translator-rule priority excludes every member of the ordinary unary
builtin fragment, not only an individual example. -/
theorem unary_builtin_hook_blocks {state : TranslatorState} {counter : Nat}
    {head : String} {source : Atom} {term : Term} {goals : List Goal}
    {nextCounter : Nat} (hook : state.hasRule head) :
    ¬ TranslatesUnaryBuiltin state counter head source term goals
      nextCounter := by
  intro translation
  exact translation.notShadowed hook

/-- Positive source-level witness for a pure predicate in the pinned unary
builtin family. -/
theorem translates_integer_isGround (state : TranslatorState) (counter : Nat)
    (value : Int) (notShadowed : ¬ state.hasRule "is-ground") :
    TranslatesUnaryBuiltin state counter "is-ground"
      (.expr [.sym "is-ground", .gnd (.int value)])
      (.variable (.generated counter))
      [.call "is-ground"
        [.integer value, .variable (.generated counter)]]
      (counter + 1) := by
  simpa using TranslatesUnaryBuiltin.call PinnedUnaryBuiltin.isGround
    notShadowed (TranslatesExpr.literal (Literal.integer value))

/-- Positive source-level witness for the first pinned unary builtin. -/
theorem translates_literal_println (state : TranslatorState) (counter : Nat)
    (message : String) (notShadowed : ¬ state.hasRule "println!") :
    TranslatesUnaryBuiltin state counter "println!"
      (.expr [.sym "println!", .gnd (.str message)])
      (.variable (.generated counter))
      [.call "println!"
        [.string message, .variable (.generated counter)]]
      (counter + 1) := by
  simpa using TranslatesUnaryBuiltin.call PinnedUnaryBuiltin.println
    notShadowed (TranslatesExpr.literal (Literal.string message))

/-- Translator-rule priority excludes the ordinary builtin derivation. -/
theorem println_hook_blocks_unary_builtin (state : TranslatorState)
    (counter : Nat) (message : String) (hook : state.hasRule "println!") :
    ¬ TranslatesUnaryBuiltin state counter "println!"
      (.expr [.sym "println!", .gnd (.str message)])
      (.variable (.generated counter))
      [.call "println!"
        [.string message, .variable (.generated counter)]]
      (counter + 1) := by
  exact unary_builtin_hook_blocks hook

/-- Pinned two-input functions whose ordinary translation is one direct
three-argument Prolog call (two inputs plus the generated result). This
source-derived family is independent of the executable builtin table. It is
anchored to arithmetic and comparison definitions at `metta.pl:34-50`,
boolean definitions at `metta.pl:97-99`, list and multiset definitions at
`metta.pl:109,145-165`, registrations at `metta.pl:309-323`, and the ordinary
known-function branch at `translator.pl:310-346`. -/
inductive PinnedBinaryBuiltin : String → Prop where
  | notEqual : PinnedBinaryBuiltin "!="
  | add : PinnedBinaryBuiltin "+"
  | subtract : PinnedBinaryBuiltin "-"
  | multiply : PinnedBinaryBuiltin "*"
  | divide : PinnedBinaryBuiltin "/"
  | modulo : PinnedBinaryBuiltin "%"
  | less : PinnedBinaryBuiltin "<"
  | greater : PinnedBinaryBuiltin ">"
  | lessEqual : PinnedBinaryBuiltin "<="
  | greaterEqual : PinnedBinaryBuiltin ">="
  | minimum : PinnedBinaryBuiltin "min"
  | maximum : PinnedBinaryBuiltin "max"
  | booleanAnd : PinnedBinaryBuiltin "and"
  | booleanOr : PinnedBinaryBuiltin "or"
  | consAtom : PinnedBinaryBuiltin "cons-atom"
  | member : PinnedBinaryBuiltin "member"
  | isMember : PinnedBinaryBuiltin "is-member"
  | unionAtom : PinnedBinaryBuiltin "union-atom"
  | intersectionAtom : PinnedBinaryBuiltin "intersection-atom"
  | subtractionAtom : PinnedBinaryBuiltin "subtraction-atom"
  | excludeItem : PinnedBinaryBuiltin "exclude-item"
  | indexAtom : PinnedBinaryBuiltin "index-atom"
  | alphaEqual : PinnedBinaryBuiltin "=alpha"
  | isAlphaMember : PinnedBinaryBuiltin "is-alpha-member"

/-- Independent left-to-right translation of a pinned two-input builtin.
Both source arguments are evaluated before the result variable is allocated
and the direct call is appended. Higher-priority translator hooks are
excluded explicitly. [SPEC translator.pl:310-346] -/
inductive TranslatesBinaryBuiltin : TranslatorState → Nat → String → Atom →
    Term → List Goal → Nat → Prop where
  | call {state : TranslatorState} {counter argumentCounter : Nat}
      {head : String} {leftSource rightSource : Atom}
      {leftTerm rightTerm : Term} {argumentGoals : List Goal}
      (builtin : PinnedBinaryBuiltin head)
      (notShadowed : ¬ state.hasRule head)
      (arguments :
        TranslatesTypedArgs state counter [.value, .value]
          [leftSource, rightSource] [leftTerm, rightTerm] argumentGoals
          argumentCounter) :
      TranslatesBinaryBuiltin state counter head
        (.expr [.sym head, leftSource, rightSource])
        (.variable (.generated argumentCounter))
        (argumentGoals ++
          [.call head [leftTerm, rightTerm,
            .variable (.generated argumentCounter)]])
        (argumentCounter + 1)

theorem TranslatesBinaryBuiltin.notShadowed
    {state : TranslatorState} {counter : Nat} {head : String} {source : Atom}
    {term : Term} {goals : List Goal} {nextCounter : Nat}
    (translation :
      TranslatesBinaryBuiltin state counter head source term goals
        nextCounter) :
    ¬ state.hasRule head := by
  cases translation
  assumption

/-- Translator-rule priority excludes the entire direct binary family. -/
theorem binary_builtin_hook_blocks {state : TranslatorState} {counter : Nat}
    {head : String} {source : Atom} {term : Term} {goals : List Goal}
    {nextCounter : Nat} (hook : state.hasRule head) :
    ¬ TranslatesBinaryBuiltin state counter head source term goals
      nextCounter := by
  intro translation
  exact translation.notShadowed hook

/-- Positive source-level witness for ordered binary arithmetic translation. -/
theorem translates_integer_add (state : TranslatorState) (counter : Nat)
    (left right : Int) (notShadowed : ¬ state.hasRule "+") :
    TranslatesBinaryBuiltin state counter "+"
      (.expr [.sym "+", .gnd (.int left), .gnd (.int right)])
      (.variable (.generated counter))
      [.call "+" [.integer left, .integer right,
        .variable (.generated counter)]]
      (counter + 1) := by
  simpa using TranslatesBinaryBuiltin.call PinnedBinaryBuiltin.add
    notShadowed
    (TranslatesTypedArgs.value (TranslatesExpr.literal (Literal.integer left))
      (TranslatesTypedArgs.value
        (TranslatesExpr.literal (Literal.integer right))
        (TranslatesTypedArgs.nil (state := state) (counter := counter))))

/-- Independent translation after pinned `trace!` stream rewriting.  Rewriting
precedes lookup of a hook named `trace!`; the rewritten `progn` and its
`println!` child still obey their own ordinary translator-rule priorities.
[SPEC translator.pl:73-75,91-110] -/
inductive TranslatesTrace : TranslatorState → Nat → Atom → Term → List Goal →
    Nat → Prop where
  | rewrite {state : TranslatorState}
      {counter printCounter nextCounter : Nat}
      {messageSource valueSource : Atom} {printTerm valueTerm : Term}
      {printGoals valueGoals : List Goal}
      (notShadowedProgn : ¬ state.hasRule "progn")
      (printed :
        TranslatesUnaryBuiltin state counter "println!"
          (.expr [.sym "println!", messageSource]) printTerm printGoals
          printCounter)
      (value :
        TranslatesExpr state printCounter valueSource valueTerm valueGoals
          nextCounter) :
      TranslatesTrace state counter
        (.expr [.sym "trace!", messageSource, valueSource]) valueTerm
        (printGoals ++ valueGoals) nextCounter

/-- Every translated trace records that the rewritten `progn` target was not
captured by a higher-priority translator rule. -/
theorem TranslatesTrace.notShadowedProgn
    {state : TranslatorState} {counter : Nat} {source : Atom} {term : Term}
    {goals : List Goal} {nextCounter : Nat}
    (translation :
      TranslatesTrace state counter source term goals nextCounter) :
    ¬ state.hasRule "progn" := by
  cases translation
  assumption

/-- Positive trace witness.  A hook named `trace!` is intentionally
irrelevant because pinned stream rewriting happens first. -/
theorem translates_literal_trace (state : TranslatorState) (counter : Nat)
    (message : String) (value : Int)
    (notShadowedPrintln : ¬ state.hasRule "println!")
    (notShadowedProgn : ¬ state.hasRule "progn")
    (_traceHook : state.hasRule "trace!") :
    TranslatesTrace state counter
      (.expr [.sym "trace!", .gnd (.str message), .gnd (.int value)])
      (.integer value)
      [.call "println!"
        [.string message, .variable (.generated counter)]]
      (counter + 1) := by
  exact .rewrite notShadowedProgn
    (translates_literal_println state counter message notShadowedPrintln)
    (.literal (.integer value))

/-- A hook on the rewritten `progn` target prevents the ordinary trace
derivation, even though a hook named `trace!` itself cannot. -/
theorem progn_hook_blocks_trace {state : TranslatorState} {counter : Nat}
    {source : Atom} {term : Term} {goals : List Goal} {nextCounter : Nat}
    (hook : state.hasRule "progn") :
    ¬ TranslatesTrace state counter source term goals nextCounter := by
  intro translation
  exact translation.notShadowedProgn hook

/-- Independent pinned translation for the first behaviorally normalized
construct. Native emits a mutex wrapper, while PLeaTTa's sequential target
may erase that wrapper only after an ordered-observation theorem. Keeping this
relation separate prevents structural agreement from disguising the proof
obligation. -/
inductive TranslatesWithMutex : TranslatorState → Nat → Atom → Term →
    List Goal → Nat → Prop where
  -- [SPEC translator.pl:136-137]
  | wrap {state : TranslatorState} {counter nextCounter : Nat}
      {mutex bodySource : Atom} {mutexTerm bodyTerm : Term}
      {bodyGoals : List Goal}
      (notShadowed : ¬ state.hasRule "with_mutex")
      (mutexValue : Quotes mutex mutexTerm)
      (body :
        TranslatesExpr state counter bodySource bodyTerm bodyGoals nextCounter) :
      TranslatesWithMutex state counter
        (.expr [.sym "with_mutex", mutex, bodySource]) bodyTerm
        [.withMutex mutexTerm (.conjunction bodyGoals)] nextCounter

/-- Independent pinned `once` translation. Native retains the translated body
term as its result and wraps only the body conjunction. The executable's
fresh result capture is intentionally not identified with this term here. -/
inductive TranslatesOnce : TranslatorState → Nat → Atom → Term → List Goal →
    Nat → Prop where
  -- [SPEC translator.pl:127-128]
  | wrap {state : TranslatorState} {counter nextCounter : Nat}
      {bodySource : Atom} {bodyTerm : Term} {bodyGoals : List Goal}
      (notShadowed : ¬ state.hasRule "once")
      (body :
        TranslatesExpr state counter bodySource bodyTerm bodyGoals nextCounter) :
      TranslatesOnce state counter (.expr [.sym "once", bodySource]) bodyTerm
        [.once (.conjunction bodyGoals)] nextCounter

/-- Independent pinned translation of the zero-argument `empty` operation.
Native reaches `empty/1` through ordinary function dispatch and therefore
retains a logical output variable even though the predicate can never bind
it.  The executable deliberately replaces that call with an immediately
false equality.  Result-term agreement is consequently not part of this
relation; behavioral adequacy below proves that neither target has an
observable answer. [SPEC metta.pl:106; translator.pl:310-346] -/
inductive TranslatesEmpty : TranslatorState → Nat → Atom → Term →
    List Goal → Nat → Prop where
  | call {state : TranslatorState} {counter : Nat} {result : LogicVar}
      (notShadowed : ¬ state.hasRule "empty") :
      TranslatesEmpty state counter (.expr [.sym "empty"])
        (.variable result) [.call "empty" [(.variable result)]] counter

/-- Independent source-to-source expansion performed by pinned
`letstar_to_rec_let/3`.  This relation deliberately does not mention the
executable `desugarLetStar?` function. -/
inductive LetStarExpands : List Atom → Atom → Atom → Prop where
  -- [SPEC translator.pl:384-385]
  | single {pattern value body : Atom} :
      LetStarExpands [.expr [pattern, value]] body
        (.expr [.sym "let", pattern, value, body])
  -- [SPEC translator.pl:384,386]
  | cons {pattern value : Atom} {bindings : List Atom} {body nested : Atom}
      (tail : LetStarExpands bindings body nested) :
      LetStarExpands (.expr [pattern, value] :: bindings) body
        (.expr [.sym "let", pattern, value, nested])

/-- Independent pinned translation of a well-formed `let*`.  Pinned PeTTa
first expands a nonempty binding list into source-ordered nested `let` forms,
then translates that expanded source. -/
inductive TranslatesLetStar : TranslatorState → Nat → Atom → Term → List Goal →
    Nat → Prop where
  -- [SPEC translator.pl:189-190,384-386]
  | expand {state : TranslatorState} {counter nextCounter : Nat}
      {bindings : List Atom} {bodySource nestedSource : Atom}
      {term : Term} {goals : List Goal}
      (notShadowed : ¬ state.hasRule "let*")
      (expansion : LetStarExpands bindings bodySource nestedSource)
      (nested :
        TranslatesExpr state counter nestedSource term goals nextCounter) :
      TranslatesLetStar state counter
        (.expr [.sym "let*", .expr bindings, bodySource]) term goals nextCounter

/-- A translated sequence always contains at least one source expression. -/
theorem TranslatesSeq.sources_nonempty {state : TranslatorState} {counter : Nat}
    {sources : List Atom} {first last : Term} {goals : List Goal}
    {nextCounter : Nat}
    (translation :
      TranslatesSeq state counter sources first last goals nextCounter) :
    sources ≠ [] := by
  cases translation <;> simp

/-- Positive example: `progn` evaluates two literals left-to-right and returns
the second one. -/
theorem translates_two_literal_progn (state : TranslatorState) (counter : Nat)
    (first second : Int) (notShadowed : ¬ state.hasRule "progn") :
    TranslatesExpr state counter
      (.expr [.sym "progn", .gnd (.int first), .gnd (.int second)])
      (.integer second) [] counter :=
  .progn notShadowed
    (.cons (.literal (.integer first)) (.single (.literal (.integer second))))

/-- Positive example: `prog1` evaluates two literals left-to-right and returns
the first one. -/
theorem translates_two_literal_prog1 (state : TranslatorState) (counter : Nat)
    (first second : Int) (notShadowed : ¬ state.hasRule "prog1") :
    TranslatesExpr state counter
      (.expr [.sym "prog1", .gnd (.int first), .gnd (.int second)])
      (.integer first) [] counter :=
  .prog1 notShadowed
    (.cons (.literal (.integer first)) (.single (.literal (.integer second))))

/-- Positive allocation example: `collapse` collects a translated literal
into a fresh generated result variable without identifying that variable with
any source-level name. -/
theorem translates_literal_collapse (state : TranslatorState) (counter : Nat)
    (value : Int) (notShadowed : ¬ state.hasRule "collapse") :
    TranslatesExpr state counter
      (.expr [.sym "collapse", .gnd (.int value)])
      (.variable (.generated counter))
      [.findall (.integer value) (.conjunction [])
        (.variable (.generated counter))]
      (counter + 1) :=
  .collapse notShadowed (.literal (.integer value))

/-- Positive binding example: literal `let` translation emits unification
before the otherwise empty pattern, value, and body goal sequences. -/
theorem translates_literal_let (state : TranslatorState) (counter : Nat)
    (name : String) (value : Int) (notShadowed : ¬ state.hasRule "let") :
    TranslatesExpr state counter
      (.expr [.sym "let", .var name, .gnd (.int value), .var name])
      (.variable (.source name))
      [.unify (.variable (.source name)) (.integer value)]
      counter :=
  .letBind notShadowed
    (.literal (.variable name))
    (.literal (.integer value))
    (.literal (.variable name))

/-- Positive binding example: the pinned `chain` clause translates the source
value expression before the conventional binding variable and preserves that
orientation in its leading unification goal. -/
theorem translates_literal_chain (state : TranslatorState) (counter : Nat)
    (name : String) (value : Int) (notShadowed : ¬ state.hasRule "chain") :
    TranslatesExpr state counter
      (.expr [.sym "chain", .gnd (.int value), .var name, .var name])
      (.variable (.source name))
      [.unify (.integer value) (.variable (.source name))]
      counter :=
  .chainBind notShadowed
    (.literal (.integer value))
    (.literal (.variable name))
    (.literal (.variable name))

/-- Positive short-circuit example: both operands are translated before the
runtime branch is formed, while the body goals remain inside only the true
branch. -/
theorem translates_literal_andThen (state : TranslatorState) (counter : Nat)
    (value : Int) (notShadowed : ¬ state.hasRule "and-then") :
    TranslatesExpr state counter
      (.expr [.sym "and-then", .gnd (.bool true), .gnd (.int value)])
      (.variable (.generated counter))
      [andThenGoal (.atom "true") (.integer value)
        (.variable (.generated counter)) [] []]
      (counter + 1) :=
  .andThen notShadowed (.literal .trueGround) (.literal (.integer value))

/-- Positive short-circuit example for the false-path body of `or-else`. -/
theorem translates_literal_orElse (state : TranslatorState) (counter : Nat)
    (value : Int) (notShadowed : ¬ state.hasRule "or-else") :
    TranslatesExpr state counter
      (.expr [.sym "or-else", .gnd (.bool false), .gnd (.int value)])
      (.variable (.generated counter))
      [orElseGoal (.atom "false") (.integer value)
        (.variable (.generated counter)) [] []]
      (counter + 1) :=
  .orElse notShadowed (.literal .falseGround) (.literal (.integer value))

/-- Positive three-argument conditional example with two empty branch
conjunctions. Each branch retains the pinned value/output equality. -/
theorem translates_literal_ifThenElse (state : TranslatorState)
    (counter : Nat) (thenValue elseValue : Int)
    (notShadowed : ¬ state.hasRule "if") :
    TranslatesExpr state counter
      (.expr [.sym "if", .gnd (.bool true), .gnd (.int thenValue),
        .gnd (.int elseValue)])
      (.variable (.generated counter))
      [.ifThenElse (.identical (.atom "true") (.atom "true"))
        (.unify (.integer thenValue) (.variable (.generated counter)))
        (.unify (.integer elseValue) (.variable (.generated counter)))]
      (counter + 1) := by
  exact .ifThenElse notShadowed (.literal .trueGround)
    (.literal (.integer thenValue)) (.literal (.integer elseValue))
    (.empty _ [] rfl) (.empty _ [] rfl)

/-- Positive alias example: a variable-valued nonempty branch reifies native
translation-time sharing before the condition, while retaining the branch's
ordered body goal. -/
theorem translates_ifThen_variable_alias (state : TranslatorState)
    (counter : Nat) (name : String) (value : Int)
    (notShadowedIf : ¬ state.hasRule "if")
    (notShadowedLet : ¬ state.hasRule "let") :
    TranslatesExpr state counter
      (.expr [.sym "if", .gnd (.bool true),
        .expr [.sym "let", .var name, .gnd (.int value), .var name]])
      (.variable (.generated counter))
      [.unify (.variable (.source name))
          (.variable (.generated counter)),
        .ifThenElse (.identical (.atom "true") (.atom "true"))
          (.conjunction
            [.unify (.variable (.source name)) (.integer value)])
          .fail]
      (counter + 1) := by
  exact .ifThen notShadowedIf (.literal .trueGround)
    (.letBind notShadowedLet
      (.literal (.variable name))
      (.literal (.integer value))
      (.literal (.variable name)))
    (.aliasVariable (.source name)
      [.unify (.variable (.source name)) (.integer value)] (by
        change 0 < 1
        omega))

/-- Negative-priority example: registering a translator rule for `let` does
not shadow native `chain`; only a rule for the source head may do so. -/
theorem translates_chain_with_let_shadowed (counter : Nat) (name : String)
    (value : Int) :
    let state : TranslatorState := ⟨fun head => head = "let"⟩
    state.hasRule "let" ∧
      TranslatesExpr state counter
        (.expr [.sym "chain", .gnd (.int value), .var name, .var name])
        (.variable (.source name))
        [.unify (.integer value) (.variable (.source name))]
        counter := by
  dsimp
  constructor
  · rfl
  · exact .chainBind (by simp)
      (.literal (.integer value))
      (.literal (.variable name))
      (.literal (.variable name))

/-- Positive behavioral-translation example for a literal mutex body. -/
theorem translates_literal_withMutex (state : TranslatorState) (counter : Nat)
    (mutex : String) (value : Int)
    (notShadowed : ¬ state.hasRule "with_mutex") :
    TranslatesWithMutex state counter
      (.expr [.sym "with_mutex", .sym mutex, .gnd (.int value)])
      (.integer value)
      [.withMutex (.atom mutex) (.conjunction [])]
      counter :=
  .wrap notShadowed (.symbol mutex) (.literal (.integer value))

/-- Negative priority example: a registered `with_mutex` translator hook
prevents the built-in translation rule from being selected. -/
theorem withMutex_hook_blocks_builtin (counter : Nat) (mutex : String)
    (value : Int) :
    let state : TranslatorState := ⟨fun _ => True⟩
    ∀ term goals nextCounter,
      ¬ TranslatesWithMutex state counter
        (.expr [.sym "with_mutex", .sym mutex, .gnd (.int value)])
        term goals nextCounter := by
  dsimp
  intro term goals nextCounter translation
  cases translation with
  | wrap notShadowed _ _ => exact notShadowed trivial

/-- Positive native `once` translation for a literal body. -/
theorem translates_literal_once (state : TranslatorState) (counter : Nat)
    (value : Int) (notShadowed : ¬ state.hasRule "once") :
    TranslatesOnce state counter
      (.expr [.sym "once", .gnd (.int value)])
      (.integer value) [.once (.conjunction [])] counter :=
  .wrap notShadowed (.literal (.integer value))

/-- Negative priority example: a registered `once` translator hook blocks the
built-in native translation clause. -/
theorem once_hook_blocks_builtin (counter : Nat) (value : Int) :
    let state : TranslatorState := ⟨fun _ => True⟩
    ∀ term goals nextCounter,
      ¬ TranslatesOnce state counter
        (.expr [.sym "once", .gnd (.int value)]) term goals nextCounter := by
  dsimp
  intro term goals nextCounter translation
  cases translation with
  | wrap notShadowed _ => exact notShadowed trivial

/-- Positive pinned translation of the zero-argument failing operation. -/
theorem translates_empty (state : TranslatorState) (counter : Nat)
    (notShadowed : ¬ state.hasRule "empty") :
    TranslatesEmpty state counter (.expr [.sym "empty"])
      (.variable (.generated counter))
      [.call "empty" [(.variable (.generated counter))]] counter :=
  .call notShadowed

/-- Negative priority example: a registered `empty` translator hook blocks
ordinary function dispatch to the pinned failing predicate. -/
theorem empty_hook_blocks_builtin (counter : Nat) :
    let state : TranslatorState := ⟨fun _ => True⟩
    ∀ term goals nextCounter,
      ¬ TranslatesEmpty state counter (.expr [.sym "empty"])
        term goals nextCounter := by
  dsimp
  intro term goals nextCounter translation
  cases translation with
  | call notShadowed => exact notShadowed trivial

/-- Positive two-binding example: pinned `let*` expands left-to-right into two
nested `let` forms, then translates those forms in the same order. -/
theorem translates_two_literal_letStar (state : TranslatorState) (counter : Nat)
    (firstName secondName : String) (firstValue secondValue : Int)
    (letStarNotShadowed : ¬ state.hasRule "let*")
    (letNotShadowed : ¬ state.hasRule "let") :
    TranslatesLetStar state counter
      (.expr [.sym "let*",
        .expr [
          .expr [.var firstName, .gnd (.int firstValue)],
          .expr [.var secondName, .gnd (.int secondValue)]],
        .var secondName])
      (.variable (.source secondName))
      [.unify (.variable (.source firstName)) (.integer firstValue),
        .unify (.variable (.source secondName)) (.integer secondValue)]
      counter := by
  refine .expand letStarNotShadowed (.cons .single) ?_
  simpa using TranslatesExpr.letBind letNotShadowed
    (.literal (.variable firstName))
    (.literal (.integer firstValue))
    (TranslatesExpr.letBind letNotShadowed
      (.literal (.variable secondName))
      (.literal (.integer secondValue))
      (.literal (.variable secondName)))

/-- An empty binding list has no pinned `let*` expansion. -/
theorem letStar_empty_bindings_rejected (body nested : Atom) :
    ¬ LetStarExpands [] body nested := by
  intro expansion
  cases expansion

/-- A binding entry must be a two-element expression. -/
theorem letStar_malformed_binding_rejected (malformed : String)
    (body nested : Atom) :
    ¬ LetStarExpands [.sym malformed] body nested := by
  intro expansion
  cases expansion

/-- A registered `let*` translator hook has priority over the pinned builtin
expansion rule. -/
theorem letStar_hook_blocks_builtin (counter : Nat)
    (pattern value body : Atom) :
    let state : TranslatorState := ⟨fun _ => True⟩
    ∀ term goals nextCounter,
      ¬ TranslatesLetStar state counter
        (.expr [.sym "let*", .expr [.expr [pattern, value]], body])
        term goals nextCounter := by
  dsimp
  intro term goals nextCounter translation
  cases translation with
  | expand notShadowed _ _ => exact notShadowed trivial

/-- Positive pattern-traversal example: atomic pattern members retain order and
their independent Prolog representations. -/
theorem translates_atomic_pattern_pair (name : String) (value : Int) :
    ConstrainsAtomicPatternSeq [.var name, .gnd (.int value)]
      [.variable (.source name), .integer value] :=
  .cons (.literal (.variable name))
    (.cons (.literal (.integer value)) .nil)

/-- Empty native argument traversal emits no terms or goals and preserves the
fresh-variable counter. -/
theorem translates_empty_args (state : TranslatorState) (counter : Nat) :
    TranslatesArgs state counter [] [] [] counter :=
  .nil

/-- Positive ordered argument-traversal example over two source literals. -/
theorem translates_two_literal_args (state : TranslatorState) (counter : Nat)
    (first second : Int) :
    TranslatesArgs state counter
      [.gnd (.int first), .gnd (.int second)]
      [.integer first, .integer second] [] counter :=
  .cons (.literal (.integer first))
    (.cons (.literal (.integer second)) .nil)

/-- Positive mixed typed-argument example: one expression remains source data
and the following value argument is translated normally. -/
theorem translates_staged_value_args (state : TranslatorState) (counter : Nat)
    (head : String) (stagedValue evaluatedValue : Int) :
    TranslatesTypedArgs state counter [.expression, .value]
      [.expr [.sym head, .gnd (.int stagedValue)],
        .gnd (.int evaluatedValue)]
      [.list [.atom head, .integer stagedValue] none,
        .integer evaluatedValue] [] counter := by
  exact .expression
    (.expression
      (.cons (.symbol head) (.cons (.integer stagedValue) .nil)))
    (.value (.literal (.integer evaluatedValue)) .nil)

/-- Positive refined-type example: a translated integer is followed by the
exact ordered `get-type`/`get-metatype` fallback and consumes two generated
variables. -/
theorem translates_refined_integer_arg (state : TranslatorState)
    (counter : Nat) (value : Int) :
    TranslatesTypedArgs state counter [.refined "Number"]
      [.gnd (.int value)] [.integer value]
      (refinedTypeCheckGoals (.integer value) "Number" counter)
      (counter + 2) := by
  exact .refined
    ⟨by decide, by decide, by decide, by decide, by decide⟩
    (.literal (.integer value)) .nil

/-- Positive recursive-pattern example: pinned `cons` traversal preserves a
proper two-element list and leaves both the ordered goal sequence and fresh
counter unchanged. -/
theorem constrains_cons_pair (state : TranslatorState) (counter : Nat)
    (name : String) (value : Int) :
    ConstrainsPattern state counter
      (.expr [.sym "cons", .var name,
        .expr [.sym "cons", .gnd (.int value), .expr []]])
      (.list [.variable (.source name), .integer value] none) [] counter := by
  exact .cons (.atomic (.literal (.variable name)))
    (.cons (.atomic (.literal (.integer value)))
      (.atomic (.literal .emptyList)))

/-- Positive dotted-list example: a variable tail remains the explicit tail
of the independent Prolog list cell. -/
theorem constrains_dotted_cons (state : TranslatorState) (counter : Nat)
    (headName tailName : String) :
    ConstrainsPattern state counter
      (.expr [.sym "cons", .var headName, .var tailName])
      (.list [.variable (.source headName)]
        (some (.variable (.source tailName)))) [] counter := by
  exact .cons (.atomic (.literal (.variable headName)))
    (.atomic (.literal (.variable tailName)))

/-- Host payloads are not part of pinned atomic pattern syntax. -/
theorem external_not_atomic_pattern (tag payload : String) (term : Term) :
    ¬ ConstrainsAtomicPattern (.gnd (.external tag payload)) term := by
  intro translation
  cases translation with
  | literal value => cases value

/-- The current independently specified compiler fragment.  Membership is a
native translation derivation, never an executable-compiler success test. -/
def SupportedExpr (state : TranslatorState) (counter : Nat) (source : Atom) :
    Prop :=
  ∃ term goals nextCounter,
    TranslatesExpr state counter source term goals nextCounter

/-- Independently supported ordered argument lists. -/
def SupportedArgs (state : TranslatorState) (counter : Nat)
    (sources : List Atom) : Prop :=
  ∃ terms goals nextCounter,
    TranslatesArgs state counter sources terms goals nextCounter

/-- Independently supported typed-argument lists for the explicit mode list. -/
def SupportedTypedArgs (state : TranslatorState) (counter : Nat)
    (modes : List ArgumentMode) (sources : List Atom) : Prop :=
  ∃ terms goals nextCounter,
    TranslatesTypedArgs state counter modes sources terms goals nextCounter

/-- Independently supported application of one pinned unary builtin. -/
def SupportedUnaryBuiltin (state : TranslatorState) (counter : Nat)
    (head : String) (source : Atom) : Prop :=
  ∃ term goals nextCounter,
    TranslatesUnaryBuiltin state counter head source term goals nextCounter

/-- Independently supported application of one pinned two-input builtin. -/
def SupportedBinaryBuiltin (state : TranslatorState) (counter : Nat)
    (head : String) (source : Atom) : Prop :=
  ∃ term goals nextCounter,
    TranslatesBinaryBuiltin state counter head source term goals nextCounter

/-- Independently supported ordinary direct call through a source-derived
function registry. -/
def SupportedDefinedCall (registry : FunctionRegistry)
    (state : TranslatorState) (counter : Nat) (head : String)
    (source : Atom) : Prop :=
  ∃ term goals nextCounter,
    TranslatesDefinedCall registry state counter head source term goals
      nextCounter

/-- Independently supported incomplete-arity source-defined application. -/
def SupportedDefinedPartial (registry : FunctionRegistry)
    (state : TranslatorState) (counter : Nat) (head : String)
    (source : Atom) : Prop :=
  ∃ term goals nextCounter,
    TranslatesDefinedPartial registry state counter head source term goals
      nextCounter

/-- Independently supported pinned `trace!` stream-rewrite forms. -/
def SupportedTrace (state : TranslatorState) (counter : Nat)
    (source : Atom) : Prop :=
  ∃ term goals nextCounter,
    TranslatesTrace state counter source term goals nextCounter

/-- Supported source forms whose native target requires a proved sequential
behavioral normalization rather than structural goal identity. -/
def SupportedWithMutex (state : TranslatorState) (counter : Nat)
    (source : Atom) : Prop :=
  ∃ term goals nextCounter,
    TranslatesWithMutex state counter source term goals nextCounter

/-- Independently supported native `once` forms. -/
def SupportedOnce (state : TranslatorState) (counter : Nat)
    (source : Atom) : Prop :=
  ∃ term goals nextCounter,
    TranslatesOnce state counter source term goals nextCounter

/-- Independently supported zero-argument `empty` forms. -/
def SupportedEmpty (state : TranslatorState) (counter : Nat)
    (source : Atom) : Prop :=
  ∃ term goals nextCounter,
    TranslatesEmpty state counter source term goals nextCounter

/-- Independently supported, well-formed native `let*` forms. -/
def SupportedLetStar (state : TranslatorState) (counter : Nat)
    (source : Atom) : Prop :=
  ∃ term goals nextCounter,
    TranslatesLetStar state counter source term goals nextCounter

/-- Independently supported atomic pattern forms. -/
def SupportedAtomicPattern (source : Atom) : Prop :=
  ∃ term, ConstrainsAtomicPattern source term

/-- Independently supported left-to-right atomic pattern sequences. -/
def SupportedAtomicPatternSeq (sources : List Atom) : Prop :=
  ∃ terms, ConstrainsAtomicPatternSeq sources terms

/-- Independently supported recursive `constrain_args/3` patterns. -/
def SupportedPattern (state : TranslatorState) (counter : Nat)
    (source : Atom) : Prop :=
  ∃ term goals nextCounter,
    ConstrainsPattern state counter source term goals nextCounter

/-- Independently supported ordered recursive pattern traversals. -/
def SupportedPatternSeq (state : TranslatorState) (counter : Nat)
    (sources : List Atom) : Prop :=
  ∃ terms goals nextCounter,
    ConstrainsPatternSeq state counter sources terms goals nextCounter

/-- A host payload is outside the independently supported source-pattern
fragment even though the executable compiler has an internal ground-value
branch for runtime-produced atoms. -/
theorem external_not_supported_atomic_pattern (tag payload : String) :
    ¬ SupportedAtomicPattern (.gnd (.external tag payload)) := by
  intro supported
  obtain ⟨term, translation⟩ := supported
  exact external_not_atomic_pattern tag payload term translation

/-- Host payloads remain outside the larger recursive pattern fragment. -/
theorem external_not_supported_pattern (state : TranslatorState)
    (counter : Nat) (tag payload : String) :
    ¬ SupportedPattern state counter (.gnd (.external tag payload)) := by
  intro supported
  obtain ⟨term, goals, nextCounter, translation⟩ := supported
  cases translation with
  | atomic value => exact external_not_atomic_pattern tag payload term value

/-- A malformed one-argument `cons` is outside the pinned rule's supported
source shape. -/
theorem malformed_cons_not_supported_pattern (state : TranslatorState)
    (counter : Nat) (head : Atom) :
    ¬ SupportedPattern state counter (.expr [.sym "cons", head]) := by
  intro supported
  obtain ⟨term, goals, nextCounter, translation⟩ := supported
  cases translation with
  | atomic value =>
      cases value with
      | literal literal => cases literal

/-- Runtime-only host payloads cannot enter the certified source argument
fragment through a singleton list. -/
theorem external_singleton_not_supported_args (state : TranslatorState)
    (counter : Nat) (tag payload : String) :
    ¬ SupportedArgs state counter [.gnd (.external tag payload)] := by
  intro supported
  obtain ⟨terms, goals, nextCounter, translation⟩ := supported
  cases translation with
  | cons head tail =>
      cases head with
      | literal literal => cases literal

/-- A nonempty source list cannot be translated after its explicit type-mode
list is exhausted. -/
theorem typedArgs_exhausted_modes_rejected (state : TranslatorState)
    (counter : Nat) (source : Atom) :
    ¬ SupportedTypedArgs state counter [] [source] := by
  intro supported
  obtain ⟨terms, goals, nextCounter, translation⟩ := supported
  cases translation

/-- Imported host payloads are not literals in the certified compiler fragment. -/
theorem external_not_literal (tag payload : String) (term : Term) :
    ¬ Literal (.gnd (.external tag payload)) term := by
  intro h
  cases h

/-- Grounded errors are runtime values, not source literals accepted by the
pinned reader/compiler relation. -/
theorem error_not_literal (message : String) (term : Term) :
    ¬ Literal (.gnd (.error message)) term := by
  intro h
  cases h

end PLeaTTa.PeTTaSpec.PrologCore
