/-
Module: PLeaTTa.PeTTaSpec.PrologCore
Purpose: Independent syntax for the Prolog term and goal fragment emitted by
  pinned PeTTa's translator.  It does not reuse PLeaTTa's executable Goal IR.
Trusted boundary: none
Main exports: Term, Goal, Literal, Quotes, TranslatesExpr
-/
import MettaHyperonFull.Core.Atom

namespace PLeaTTa.PeTTaSpec.PrologCore

open Metta (Atom Ground)

/-- Logical-variable identities in the independent target.  Source variables,
anonymous reader occurrences, and variables allocated by translation occupy
disjoint namespaces, so alpha-equivalence never depends on executable names
such as `_q17`. -/
inductive LogicVar where
  | source (name : String)
  | anonymous (index : Nat)
  | generated (index : Nat)
deriving Repr, Inhabited

/-- Source and translator-generated variables cannot alias. -/
theorem LogicVar.source_ne_generated (name : String) (index : Nat) :
    LogicVar.source name ≠ .generated index := by
  intro equality
  cases equality

/-- Anonymous reader occurrences cannot alias translator-generated variables. -/
theorem LogicVar.anonymous_ne_generated (anonymousIndex generatedIndex : Nat) :
    LogicVar.anonymous anonymousIndex ≠ .generated generatedIndex := by
  intro equality
  cases equality

/-- Prolog terms relevant to PeTTa's parser and translator.  Proper and dotted
lists are represented directly rather than disguised as a host-language list. -/
inductive Term where
  | variable (identity : LogicVar)
  | atom (name : String)
  | integer (value : Int)
  | float (value : Float)
  | string (value : String)
  | compound (functor : String) (arguments : List Term)
  | list (items : List Term) (tail : Option Term)
deriving Repr, Inhabited

/-- Canonical Prolog list-cell construction.  `[Head|Tail]` extends an
already-list tail and otherwise produces a dotted list.  This is independent
target syntax for pinned `translator.pl`; it does not mention PLeaTTa's
`#c` encoding. -/
def Term.prepend (head tail : Term) : Term :=
  match tail with
  | .list items finalTail => .list (head :: items) finalTail
  | other => .list [head] (some other)

/-- Translation-time state whose membership controls the pinned translator's
highest-priority hook branch.  This is intentionally a proposition-valued
interface rather than PLeaTTa's executable list representation. -/
structure TranslatorState where
  hasRule : String → Prop

/-- The independent Prolog goal language generated by `translator.pl`.
Additional primitives can be added as their translation clauses are proved;
none of these constructors refer to PLeaTTa's executable machine. -/
inductive Goal where
  | truth
  | fail
  | unify (left right : Term)
  | identical (left right : Term)
  | call (predicate : String) (arguments : List Term)
  | conjunction (goals : List Goal)
  | disjunction (branches : List Goal)
  | cut
  | ifThenElse (condition thenBranch elseBranch : Goal)
  | softCut (condition thenBranch elseBranch : Goal)
  | negation (goal : Goal)
  | once (goal : Goal)
  | findall (template : Term) (goal : Goal) (output : Term)
  | catch (goal : Goal) (exception : Term) (handler : Goal)
  | transaction (goal : Goal)
  | withMutex (mutex : Term) (goal : Goal)
  | forall (generator test : Goal)
deriving Repr, Inhabited

mutual

/-- Number of executable top-level goals after eliminating the conjunction
wrappers introduced by `translate_expr_to_conj/3`. -/
def Goal.flatWidth : Goal → Nat
  | .conjunction goals => Goals.flatWidth goals
  | _ => 1

/-- Flattened width of an ordered independent goal sequence. -/
def Goals.flatWidth : List Goal → Nat
  | [] => 0
  | goal :: goals => goal.flatWidth + Goals.flatWidth goals

end

/-- Source atoms which PeTTa's first `translate_expr/3` clause returns without
emitting a goal.  Unsupported host grounds intentionally have no constructor. -/
inductive Literal : Atom → Term → Prop where
  | variable (name : String) :
      Literal (.var name) (.variable (.source name))
  | symbol (name : String) : Literal (.sym name) (.atom name)
  | integer (value : Int) : Literal (.gnd (.int value)) (.integer value)
  | float (value : Float) : Literal (.gnd (.float value)) (.float value)
  | string (value : String) : Literal (.gnd (.str value)) (.string value)
  | trueGround : Literal (.gnd (.bool true)) (.atom "true")
  | falseGround : Literal (.gnd (.bool false)) (.atom "false")
  | emptyList : Literal (.expr []) (.list [] none)

/-- Independently specified atomic fragment of pinned `constrain_args/3`.
Variables and atomic values are preserved without goals by
`translator.pl:2`; the supported ground/value representation is shared with
the independent literal relation, not with the executable pattern compiler. -/
inductive ConstrainsAtomicPattern : Atom → Term → Prop where
  | literal {source : Atom} {term : Term} (value : Literal source term) :
      ConstrainsAtomicPattern source term

/-- Pointwise left-to-right `maplist(constrain_args, ...)` traversal for the
atomic fragment used by `translate_clause/3` at `translator.pl:20-22`.  Every
atomic member emits an empty goal list, so flattening preserves `[]`.  Nested
compound patterns are added only when their dispatch is independently proved. -/
inductive ConstrainsAtomicPatternSeq : List Atom → List Term → Prop where
  | nil : ConstrainsAtomicPatternSeq [] []
  | cons {source : Atom} {term : Term} {sources : List Atom}
      {terms : List Term}
      (head : ConstrainsAtomicPattern source term)
      (tail : ConstrainsAtomicPatternSeq sources terms) :
      ConstrainsAtomicPatternSeq (source :: sources) (term :: terms)

/-- Independently specified recursive fragment of pinned `constrain_args/3`.
The atomic rule is `translator.pl:2`; the `cons` rule is lines 3-8.  Pattern
subterms are visited head before tail, their generated-variable counters are
threaded in that order, and their goal sequences are concatenated without
reordering. -/
inductive ConstrainsPattern : TranslatorState → Nat → Atom → Term →
    List Goal → Nat → Prop where
  | atomic {state : TranslatorState} {counter : Nat} {source : Atom}
      {term : Term} (value : ConstrainsAtomicPattern source term) :
      ConstrainsPattern state counter source term [] counter
  | cons {state : TranslatorState} {counter headCounter nextCounter : Nat}
      {headSource tailSource : Atom} {headTerm tailTerm : Term}
      {headGoals tailGoals : List Goal}
      (head : ConstrainsPattern state counter headSource headTerm headGoals
        headCounter)
      (tail : ConstrainsPattern state headCounter tailSource tailTerm tailGoals
        nextCounter) :
      ConstrainsPattern state counter
        (.expr [.sym "cons", headSource, tailSource])
        (Term.prepend headTerm tailTerm) (headGoals ++ tailGoals) nextCounter

/-- Independent left-to-right traversal used by `translate_clause/3` at
`translator.pl:20-22`.  This relation exposes both counter threading and the
ordered flattening of each member's constraint goals. -/
inductive ConstrainsPatternSeq : TranslatorState → Nat → List Atom →
    List Term → List Goal → Nat → Prop where
  | nil {state : TranslatorState} {counter : Nat} :
      ConstrainsPatternSeq state counter [] [] [] counter
  | cons {state : TranslatorState} {counter headCounter nextCounter : Nat}
      {source : Atom} {term : Term} {sources : List Atom} {terms : List Term}
      {headGoals tailGoals : List Goal}
      (head : ConstrainsPattern state counter source term headGoals
        headCounter)
      (tail : ConstrainsPatternSeq state headCounter sources terms tailGoals
        nextCounter) :
      ConstrainsPatternSeq state counter (source :: sources) (term :: terms)
        (headGoals ++ tailGoals) nextCounter

mutual

/-- Deep syntactic quotation into native Prolog terms. -/
inductive Quotes : Atom → Term → Prop where
  | variable (name : String) :
      Quotes (.var name) (.variable (.source name))
  | symbol (name : String) : Quotes (.sym name) (.atom name)
  | integer (value : Int) : Quotes (.gnd (.int value)) (.integer value)
  | float (value : Float) : Quotes (.gnd (.float value)) (.float value)
  | string (value : String) : Quotes (.gnd (.str value)) (.string value)
  | trueGround : Quotes (.gnd (.bool true)) (.atom "true")
  | falseGround : Quotes (.gnd (.bool false)) (.atom "false")
  | expression {atoms : List Atom} {terms : List Term}
      (items : QuotesList atoms terms) : Quotes (.expr atoms) (.list terms none)

/-- Pointwise quotation of expression members. -/
inductive QuotesList : List Atom → List Term → Prop where
  | nil : QuotesList [] []
  | cons {atom : Atom} {term : Term} {atoms : List Atom} {terms : List Term}
      (head : Quotes atom term) (tail : QuotesList atoms terms) :
      QuotesList (atom :: atoms) (term :: terms)

end

/-- The pinned target goal for `(and-then A B)`.  `translate_expr_to_conj/3`
retains each translated subexpression as an explicit conjunction, and the
outer conjunction preserves the source order before the identity test.
[SPEC translator.pl:177-180; translator.pl:45-47] -/
def andThenGoal (condition body output : Term)
    (conditionGoals bodyGoals : List Goal) : Goal :=
  .conjunction
    [.conjunction conditionGoals,
     .ifThenElse (.identical condition (.atom "true"))
       (.conjunction [.conjunction bodyGoals, .unify output body])
       (.unify output (.atom "false"))]

/-- The pinned target goal for `(or-else A B)`.  The body conjunction remains
inside only the false branch; the true branch binds the enclosing result
directly. [SPEC translator.pl:181-184; translator.pl:45-47] -/
def orElseGoal (condition body output : Term)
    (conditionGoals bodyGoals : List Goal) : Goal :=
  .conjunction
    [.conjunction conditionGoals,
     .ifThenElse (.identical condition (.atom "true"))
       (.unify output (.atom "true"))
       (.conjunction [.conjunction bodyGoals, .unify output body])]

/-- Independent explicit-alias normalization of pinned `build_branch/4`.

Native Prolog represents the second case below by making `value` and `output`
the same logical variable at translation time.  The normalized relation
reifies that sharing as an equality which is scheduled before the condition.
This preserves the alias outside the selected branch without defining the
reference in terms of PLeaTTa's executable compiler.

The final two fields are the branch template and the independent branch goal.
They expose the equality-before-conjunction order used by `build_branch/4`.
[SPEC translator.pl:394-397] -/
inductive BuildsBranchNormalized (output : Term) :
    Term → List Goal → List Goal → Term → Goal → Prop where
  | empty (value : Term) (goals : List Goal)
      (empty : Goals.flatWidth goals = 0) :
      BuildsBranchNormalized output value goals [] value (.unify value output)
  | aliasVariable (identity : LogicVar) (goals : List Goal)
      (nonempty : 0 < Goals.flatWidth goals) :
      BuildsBranchNormalized output (.variable identity) goals
        [.unify (.variable identity) output] output (.conjunction goals)
  | nonVariable (value : Term) (goals : List Goal)
      (nonempty : 0 < Goals.flatWidth goals)
      (notVariable : ∀ identity, value ≠ .variable identity) :
      BuildsBranchNormalized output value goals [] value
        (.conjunction (.unify value output :: goals))

/-- Pinned `translate_expr_to_conj/3` uses the atom `true` for an empty goal
sequence.  The `if` clauses omit that empty conjunction and otherwise schedule
the condition conjunction before the identity test.
[SPEC translator.pl:151-162; translator.pl:45-47] -/
def conditionThen (conditionGoals : List Goal) (decision : Goal) : List Goal :=
  if Goals.flatWidth conditionGoals = 0 then [decision]
  else [.conjunction conditionGoals, decision]

/-- Negative priority witness for `build_branch/4`: a flattened-empty branch
uses the first clause and therefore cannot manufacture a translation-time
alias, even when its result is a variable. -/
theorem BuildsBranchNormalized.zero_width_no_alias {output value : Term}
    {goals aliases : List Goal} {template : Term} {branch : Goal}
    (translation :
      BuildsBranchNormalized output value goals aliases template branch)
    (empty : Goals.flatWidth goals = 0) : aliases = [] := by
  cases translation with
  | empty => rfl
  | aliasVariable _ _ nonempty => omega
  | nonVariable _ _ nonempty _ => omega

mutual

/-- Independently specified fragment of pinned `translate_expr/3`.  Its rules
state native translation behavior without referring to PLeaTTa's executable
compiler. -/
inductive TranslatesExpr : TranslatorState → Nat → Atom → Term → List Goal →
    Nat → Prop where
  | literal {state : TranslatorState} {counter : Nat} {source : Atom}
      {term : Term}
      (value : Literal source term) :
      TranslatesExpr state counter source term [] counter
  | quote {state : TranslatorState} {counter : Nat} {source : Atom}
      {term : Term}
      (notShadowed : ¬ state.hasRule "quote")
      (value : Quotes source term) :
      TranslatesExpr state counter (.expr [.sym "quote", source]) term [] counter
  | cut {state : TranslatorState} {counter : Nat}
      (notShadowed : ¬ state.hasRule "cut") :
      TranslatesExpr state counter (.expr [.sym "cut"]) (.atom "true") [.cut]
        counter
  | collapse {state : TranslatorState} {counter bodyCounter : Nat}
      {source : Atom} {template : Term} {bodyGoals : List Goal}
      (notShadowed : ¬ state.hasRule "collapse")
      (body :
        TranslatesExpr state counter source template bodyGoals bodyCounter) :
      TranslatesExpr state counter (.expr [.sym "collapse", source])
        (.variable (.generated bodyCounter))
        [.findall template (.conjunction bodyGoals)
          (.variable (.generated bodyCounter))]
        (bodyCounter + 1)
  -- [SPEC translator.pl:185-188] Translation traverses pattern, value, and
  -- body in that order, but the generated goal order begins with unification.
  | letBind {state : TranslatorState}
      {counter patternCounter valueCounter nextCounter : Nat}
      {pattern value bodySource : Atom}
      {patternTerm valueTerm bodyTerm : Term}
      {patternGoals valueGoals bodyGoals : List Goal}
      (notShadowed : ¬ state.hasRule "let")
      (patternTranslation :
        TranslatesExpr state counter pattern patternTerm patternGoals
          patternCounter)
      (valueTranslation :
        TranslatesExpr state patternCounter value valueTerm valueGoals
          valueCounter)
      (bodyTranslation :
        TranslatesExpr state valueCounter bodySource bodyTerm bodyGoals
          nextCounter) :
      TranslatesExpr state counter
        (.expr [.sym "let", pattern, value, bodySource])
        bodyTerm
        ([.unify patternTerm valueTerm] ++ patternGoals ++ valueGoals ++
          bodyGoals)
        nextCounter
  -- [SPEC translator.pl:185-188] `chain` is the second head admitted by the
  -- same pinned clause as `let`.  The clause traverses the argument list as
  -- written; conventional names such as value/pattern do not justify swapping
  -- the first two translations.
  | chainBind {state : TranslatorState}
      {counter firstCounter secondCounter nextCounter : Nat}
      {first second bodySource : Atom}
      {firstTerm secondTerm bodyTerm : Term}
      {firstGoals secondGoals bodyGoals : List Goal}
      (notShadowed : ¬ state.hasRule "chain")
      (firstTranslation :
        TranslatesExpr state counter first firstTerm firstGoals firstCounter)
      (secondTranslation :
        TranslatesExpr state firstCounter second secondTerm secondGoals
          secondCounter)
      (bodyTranslation :
        TranslatesExpr state secondCounter bodySource bodyTerm bodyGoals
          nextCounter) :
      TranslatesExpr state counter
        (.expr [.sym "chain", first, second, bodySource])
        bodyTerm
        ([.unify firstTerm secondTerm] ++ firstGoals ++ secondGoals ++
          bodyGoals)
        nextCounter
  | andThen {state : TranslatorState}
      {counter conditionCounter bodyCounter : Nat}
      {conditionSource bodySource : Atom} {conditionTerm bodyTerm : Term}
      {conditionGoals bodyGoals : List Goal}
      (notShadowed : ¬ state.hasRule "and-then")
      (conditionTranslation :
        TranslatesExpr state counter conditionSource conditionTerm
          conditionGoals conditionCounter)
      (bodyTranslation :
        TranslatesExpr state conditionCounter bodySource bodyTerm bodyGoals
          bodyCounter) :
      TranslatesExpr state counter
        (.expr [.sym "and-then", conditionSource, bodySource])
        (.variable (.generated bodyCounter))
        [andThenGoal conditionTerm bodyTerm
          (.variable (.generated bodyCounter)) conditionGoals bodyGoals]
        (bodyCounter + 1)
  | orElse {state : TranslatorState}
      {counter conditionCounter bodyCounter : Nat}
      {conditionSource bodySource : Atom} {conditionTerm bodyTerm : Term}
      {conditionGoals bodyGoals : List Goal}
      (notShadowed : ¬ state.hasRule "or-else")
      (conditionTranslation :
        TranslatesExpr state counter conditionSource conditionTerm
          conditionGoals conditionCounter)
      (bodyTranslation :
        TranslatesExpr state conditionCounter bodySource bodyTerm bodyGoals
          bodyCounter) :
      TranslatesExpr state counter
        (.expr [.sym "or-else", conditionSource, bodySource])
        (.variable (.generated bodyCounter))
        [orElseGoal conditionTerm bodyTerm
          (.variable (.generated bodyCounter)) conditionGoals bodyGoals]
        (bodyCounter + 1)
  -- The equality prefix is an explicit normalization of native Prolog's
  -- translation-time variable sharing.  Its adequacy to that sharing is a
  -- separate semantic obligation; this constructor does not identify the two
  -- definitions by fiat. [SPEC translator.pl:151-155, 394-397]
  | ifThen {state : TranslatorState}
      {counter conditionCounter thenCounter : Nat}
      {conditionSource thenSource : Atom}
      {conditionTerm thenTerm branchTemplate : Term}
      {conditionGoals thenGoals aliasGoals : List Goal}
      {thenBranch : Goal}
      (notShadowed : ¬ state.hasRule "if")
      (conditionTranslation :
        TranslatesExpr state counter conditionSource conditionTerm
          conditionGoals conditionCounter)
      (thenTranslation :
        TranslatesExpr state conditionCounter thenSource thenTerm thenGoals
          thenCounter)
      (branch :
        BuildsBranchNormalized (.variable (.generated thenCounter))
          thenTerm thenGoals aliasGoals branchTemplate thenBranch) :
      TranslatesExpr state counter
        (.expr [.sym "if", conditionSource, thenSource])
        (.variable (.generated thenCounter))
        (aliasGoals ++ conditionThen conditionGoals
          (.ifThenElse (.identical conditionTerm (.atom "true"))
            thenBranch .fail))
        (thenCounter + 1)
  -- Both branch aliases are scheduled before the condition, matching the
  -- scope of the shared variables created by the two native build_branch/4
  -- calls. [SPEC translator.pl:156-162, 394-397]
  | ifThenElse {state : TranslatorState}
      {counter conditionCounter thenCounter elseCounter : Nat}
      {conditionSource thenSource elseSource : Atom}
      {conditionTerm thenTerm elseTerm : Term}
      {thenTemplate elseTemplate : Term}
      {conditionGoals thenGoals elseGoals : List Goal}
      {thenAliasGoals elseAliasGoals : List Goal}
      {thenBranch elseBranch : Goal}
      (notShadowed : ¬ state.hasRule "if")
      (conditionTranslation :
        TranslatesExpr state counter conditionSource conditionTerm
          conditionGoals conditionCounter)
      (thenTranslation :
        TranslatesExpr state conditionCounter thenSource thenTerm thenGoals
          thenCounter)
      (elseTranslation :
        TranslatesExpr state thenCounter elseSource elseTerm elseGoals
          elseCounter)
      (thenBuild :
        BuildsBranchNormalized (.variable (.generated elseCounter))
          thenTerm thenGoals thenAliasGoals thenTemplate thenBranch)
      (elseBuild :
        BuildsBranchNormalized (.variable (.generated elseCounter))
          elseTerm elseGoals elseAliasGoals elseTemplate elseBranch) :
      TranslatesExpr state counter
        (.expr [.sym "if", conditionSource, thenSource, elseSource])
        (.variable (.generated elseCounter))
        (thenAliasGoals ++ elseAliasGoals ++
          conditionThen conditionGoals
            (.ifThenElse (.identical conditionTerm (.atom "true"))
              thenBranch elseBranch))
        (elseCounter + 1)
  | progn {state : TranslatorState} {counter nextCounter : Nat}
      {sources : List Atom} {first last : Term} {goals : List Goal}
      (notShadowed : ¬ state.hasRule "progn")
      (arguments :
        TranslatesSeq state counter sources first last goals nextCounter) :
      TranslatesExpr state counter (.expr (.sym "progn" :: sources)) last goals
        nextCounter
  | prog1 {state : TranslatorState} {counter nextCounter : Nat}
      {sources : List Atom} {first last : Term} {goals : List Goal}
      (notShadowed : ¬ state.hasRule "prog1")
      (arguments :
        TranslatesSeq state counter sources first last goals nextCounter) :
      TranslatesExpr state counter (.expr (.sym "prog1" :: sources)) first goals
        nextCounter

/-- A nonempty left-to-right translation sequence.  The relation remembers
its first and last result terms, which are selected by `prog1` and `progn`
respectively, while concatenating goals in pinned execution order. -/
inductive TranslatesSeq : TranslatorState → Nat → List Atom → Term → Term →
    List Goal → Nat → Prop where
  | single {state : TranslatorState} {counter nextCounter : Nat}
      {source : Atom} {term : Term} {goals : List Goal}
      (head : TranslatesExpr state counter source term goals nextCounter) :
      TranslatesSeq state counter [source] term term goals nextCounter
  | cons {state : TranslatorState} {counter middleCounter nextCounter : Nat}
      {source : Atom} {sources : List Atom} {headTerm first last : Term}
      {headGoals tailGoals : List Goal}
      (head :
        TranslatesExpr state counter source headTerm headGoals middleCounter)
      (tail : TranslatesSeq state middleCounter sources first last tailGoals
        nextCounter) :
      TranslatesSeq state counter (source :: sources) headTerm last
        (headGoals ++ tailGoals) nextCounter

end

/-- Independent ordered `translate_args/3` traversal from pinned
`translator.pl:409-412`.  Unlike `TranslatesSeq`, this relation includes the
empty case and preserves every translated argument term, not merely the first
and last. -/
inductive TranslatesArgs : TranslatorState → Nat → List Atom → List Term →
    List Goal → Nat → Prop where
  | nil {state : TranslatorState} {counter : Nat} :
      TranslatesArgs state counter [] [] [] counter
  | cons {state : TranslatorState} {counter middleCounter nextCounter : Nat}
      {source : Atom} {sources : List Atom} {term : Term} {terms : List Term}
      {headGoals tailGoals : List Goal}
      (head :
        TranslatesExpr state counter source term headGoals middleCounter)
      (tail :
        TranslatesArgs state middleCounter sources terms tailGoals nextCounter) :
      TranslatesArgs state counter (source :: sources) (term :: terms)
        (headGoals ++ tailGoals) nextCounter

/-- Atomic refined type names supported by the first exact type-check bridge.
The three unchecked names follow pinned translator priority. Truth spellings
are excluded because their executable boolean encoding is not a type-name
encoding. Compound/dependent type terms remain a separate obligation. -/
def RefinedSymbolType (name : String) : Prop :=
  name ≠ "%Undefined%" ∧ name ≠ "Atom" ∧ name ≠ "Expression" ∧
    name ≠ "true" ∧ name ≠ "false"

/-- Independently relevant input-type modes for pinned
`translate_args_by_type/4`. `value` is the no-extra-check `%Undefined%`/`Atom`
fragment; `refined` names the exact simple type checked after evaluation. -/
inductive ArgumentMode where
  | expression
  | value
  | refined (expected : String)
deriving Repr

/-- Exact pinned soft-cut type/meta-type fallback for a translated value.
Generated variables are named by the independent compiler counter.
[SPEC translator.pl:356-370] -/
def refinedTypeCheckGoals (value : Term) (expected : String) (counter : Nat) :
    List Goal :=
  let directType := Term.variable (.generated counter)
  let metaType := Term.variable (.generated (counter + 1))
  [.softCut
    (.conjunction
      [.call "get-type" [value, directType],
       .unify directType (.atom expected)])
    .truth
    (.conjunction
      [.call "get-metatype" [value, metaType],
       .unify metaType (.atom expected)])]

/-- Independent ordered fragment of pinned `translate_args_by_type/4`
(`translator.pl:362-370`). `Expression` inputs remain quoted source data;
value inputs use ordinary expression translation. The mode list is consumed
in lockstep with source arguments, making type-arity assumptions explicit. -/
inductive TranslatesTypedArgs : TranslatorState → Nat → List ArgumentMode →
    List Atom → List Term → List Goal → Nat → Prop where
  | nil {state : TranslatorState} {counter : Nat} :
      TranslatesTypedArgs state counter [] [] [] [] counter
  | expression {state : TranslatorState} {counter nextCounter : Nat}
      {source : Atom} {sources : List Atom} {term : Term} {terms : List Term}
      {modes : List ArgumentMode} {tailGoals : List Goal}
      (quoted : Quotes source term)
      (tail : TranslatesTypedArgs state counter modes sources terms tailGoals
        nextCounter) :
      TranslatesTypedArgs state counter (.expression :: modes)
        (source :: sources) (term :: terms) tailGoals nextCounter
  | value {state : TranslatorState} {counter middleCounter nextCounter : Nat}
      {source : Atom} {sources : List Atom} {term : Term} {terms : List Term}
      {modes : List ArgumentMode} {headGoals tailGoals : List Goal}
      (head : TranslatesExpr state counter source term headGoals middleCounter)
      (tail : TranslatesTypedArgs state middleCounter modes sources terms
        tailGoals nextCounter) :
      TranslatesTypedArgs state counter (.value :: modes) (source :: sources)
        (term :: terms) (headGoals ++ tailGoals) nextCounter
  | refined {state : TranslatorState} {counter middleCounter nextCounter : Nat}
      {source : Atom} {sources : List Atom} {term : Term} {terms : List Term}
      {modes : List ArgumentMode} {headGoals tailGoals : List Goal}
      {expected : String}
      (supportedType : RefinedSymbolType expected)
      (head : TranslatesExpr state counter source term headGoals middleCounter)
      (tail : TranslatesTypedArgs state (middleCounter + 2) modes sources terms
        tailGoals nextCounter) :
      TranslatesTypedArgs state counter (.refined expected :: modes)
        (source :: sources) (term :: terms)
        (headGoals ++ refinedTypeCheckGoals term expected middleCounter ++
          tailGoals) nextCounter

/-- Independent pinned translation for the first behaviorally normalized
construct. Native emits a mutex wrapper, while PLeaTTa's sequential target
may erase that wrapper only after an ordered-observation theorem. Keeping this
relation separate prevents structural agreement from disguising the proof
obligation. -/
inductive TranslatesWithMutex : TranslatorState → Nat → Atom → Term →
    List Goal → Nat → Prop where
  -- [SPEC translator.pl:136-137]
  | wrap {state : TranslatorState} {counter nextCounter : Nat}
      {mutex bodySource : Atom} {mutexTerm bodyTerm : Term}
      {bodyGoals : List Goal}
      (notShadowed : ¬ state.hasRule "with_mutex")
      (mutexValue : Quotes mutex mutexTerm)
      (body :
        TranslatesExpr state counter bodySource bodyTerm bodyGoals nextCounter) :
      TranslatesWithMutex state counter
        (.expr [.sym "with_mutex", mutex, bodySource]) bodyTerm
        [.withMutex mutexTerm (.conjunction bodyGoals)] nextCounter

/-- Independent pinned `once` translation. Native retains the translated body
term as its result and wraps only the body conjunction. The executable's
fresh result capture is intentionally not identified with this term here. -/
inductive TranslatesOnce : TranslatorState → Nat → Atom → Term → List Goal →
    Nat → Prop where
  -- [SPEC translator.pl:127-128]
  | wrap {state : TranslatorState} {counter nextCounter : Nat}
      {bodySource : Atom} {bodyTerm : Term} {bodyGoals : List Goal}
      (notShadowed : ¬ state.hasRule "once")
      (body :
        TranslatesExpr state counter bodySource bodyTerm bodyGoals nextCounter) :
      TranslatesOnce state counter (.expr [.sym "once", bodySource]) bodyTerm
        [.once (.conjunction bodyGoals)] nextCounter

/-- Independent source-to-source expansion performed by pinned
`letstar_to_rec_let/3`.  This relation deliberately does not mention the
executable `desugarLetStar?` function. -/
inductive LetStarExpands : List Atom → Atom → Atom → Prop where
  -- [SPEC translator.pl:384-385]
  | single {pattern value body : Atom} :
      LetStarExpands [.expr [pattern, value]] body
        (.expr [.sym "let", pattern, value, body])
  -- [SPEC translator.pl:384,386]
  | cons {pattern value : Atom} {bindings : List Atom} {body nested : Atom}
      (tail : LetStarExpands bindings body nested) :
      LetStarExpands (.expr [pattern, value] :: bindings) body
        (.expr [.sym "let", pattern, value, nested])

/-- Independent pinned translation of a well-formed `let*`.  Pinned PeTTa
first expands a nonempty binding list into source-ordered nested `let` forms,
then translates that expanded source. -/
inductive TranslatesLetStar : TranslatorState → Nat → Atom → Term → List Goal →
    Nat → Prop where
  -- [SPEC translator.pl:189-190,384-386]
  | expand {state : TranslatorState} {counter nextCounter : Nat}
      {bindings : List Atom} {bodySource nestedSource : Atom}
      {term : Term} {goals : List Goal}
      (notShadowed : ¬ state.hasRule "let*")
      (expansion : LetStarExpands bindings bodySource nestedSource)
      (nested :
        TranslatesExpr state counter nestedSource term goals nextCounter) :
      TranslatesLetStar state counter
        (.expr [.sym "let*", .expr bindings, bodySource]) term goals nextCounter

/-- A translated sequence always contains at least one source expression. -/
theorem TranslatesSeq.sources_nonempty {state : TranslatorState} {counter : Nat}
    {sources : List Atom} {first last : Term} {goals : List Goal}
    {nextCounter : Nat}
    (translation :
      TranslatesSeq state counter sources first last goals nextCounter) :
    sources ≠ [] := by
  cases translation <;> simp

/-- Positive example: `progn` evaluates two literals left-to-right and returns
the second one. -/
theorem translates_two_literal_progn (state : TranslatorState) (counter : Nat)
    (first second : Int) (notShadowed : ¬ state.hasRule "progn") :
    TranslatesExpr state counter
      (.expr [.sym "progn", .gnd (.int first), .gnd (.int second)])
      (.integer second) [] counter :=
  .progn notShadowed
    (.cons (.literal (.integer first)) (.single (.literal (.integer second))))

/-- Positive example: `prog1` evaluates two literals left-to-right and returns
the first one. -/
theorem translates_two_literal_prog1 (state : TranslatorState) (counter : Nat)
    (first second : Int) (notShadowed : ¬ state.hasRule "prog1") :
    TranslatesExpr state counter
      (.expr [.sym "prog1", .gnd (.int first), .gnd (.int second)])
      (.integer first) [] counter :=
  .prog1 notShadowed
    (.cons (.literal (.integer first)) (.single (.literal (.integer second))))

/-- Positive allocation example: `collapse` collects a translated literal
into a fresh generated result variable without identifying that variable with
any source-level name. -/
theorem translates_literal_collapse (state : TranslatorState) (counter : Nat)
    (value : Int) (notShadowed : ¬ state.hasRule "collapse") :
    TranslatesExpr state counter
      (.expr [.sym "collapse", .gnd (.int value)])
      (.variable (.generated counter))
      [.findall (.integer value) (.conjunction [])
        (.variable (.generated counter))]
      (counter + 1) :=
  .collapse notShadowed (.literal (.integer value))

/-- Positive binding example: literal `let` translation emits unification
before the otherwise empty pattern, value, and body goal sequences. -/
theorem translates_literal_let (state : TranslatorState) (counter : Nat)
    (name : String) (value : Int) (notShadowed : ¬ state.hasRule "let") :
    TranslatesExpr state counter
      (.expr [.sym "let", .var name, .gnd (.int value), .var name])
      (.variable (.source name))
      [.unify (.variable (.source name)) (.integer value)]
      counter :=
  .letBind notShadowed
    (.literal (.variable name))
    (.literal (.integer value))
    (.literal (.variable name))

/-- Positive binding example: the pinned `chain` clause translates the source
value expression before the conventional binding variable and preserves that
orientation in its leading unification goal. -/
theorem translates_literal_chain (state : TranslatorState) (counter : Nat)
    (name : String) (value : Int) (notShadowed : ¬ state.hasRule "chain") :
    TranslatesExpr state counter
      (.expr [.sym "chain", .gnd (.int value), .var name, .var name])
      (.variable (.source name))
      [.unify (.integer value) (.variable (.source name))]
      counter :=
  .chainBind notShadowed
    (.literal (.integer value))
    (.literal (.variable name))
    (.literal (.variable name))

/-- Positive short-circuit example: both operands are translated before the
runtime branch is formed, while the body goals remain inside only the true
branch. -/
theorem translates_literal_andThen (state : TranslatorState) (counter : Nat)
    (value : Int) (notShadowed : ¬ state.hasRule "and-then") :
    TranslatesExpr state counter
      (.expr [.sym "and-then", .gnd (.bool true), .gnd (.int value)])
      (.variable (.generated counter))
      [andThenGoal (.atom "true") (.integer value)
        (.variable (.generated counter)) [] []]
      (counter + 1) :=
  .andThen notShadowed (.literal .trueGround) (.literal (.integer value))

/-- Positive short-circuit example for the false-path body of `or-else`. -/
theorem translates_literal_orElse (state : TranslatorState) (counter : Nat)
    (value : Int) (notShadowed : ¬ state.hasRule "or-else") :
    TranslatesExpr state counter
      (.expr [.sym "or-else", .gnd (.bool false), .gnd (.int value)])
      (.variable (.generated counter))
      [orElseGoal (.atom "false") (.integer value)
        (.variable (.generated counter)) [] []]
      (counter + 1) :=
  .orElse notShadowed (.literal .falseGround) (.literal (.integer value))

/-- Positive three-argument conditional example with two empty branch
conjunctions. Each branch retains the pinned value/output equality. -/
theorem translates_literal_ifThenElse (state : TranslatorState)
    (counter : Nat) (thenValue elseValue : Int)
    (notShadowed : ¬ state.hasRule "if") :
    TranslatesExpr state counter
      (.expr [.sym "if", .gnd (.bool true), .gnd (.int thenValue),
        .gnd (.int elseValue)])
      (.variable (.generated counter))
      [.ifThenElse (.identical (.atom "true") (.atom "true"))
        (.unify (.integer thenValue) (.variable (.generated counter)))
        (.unify (.integer elseValue) (.variable (.generated counter)))]
      (counter + 1) := by
  exact .ifThenElse notShadowed (.literal .trueGround)
    (.literal (.integer thenValue)) (.literal (.integer elseValue))
    (.empty _ [] rfl) (.empty _ [] rfl)

/-- Positive alias example: a variable-valued nonempty branch reifies native
translation-time sharing before the condition, while retaining the branch's
ordered body goal. -/
theorem translates_ifThen_variable_alias (state : TranslatorState)
    (counter : Nat) (name : String) (value : Int)
    (notShadowedIf : ¬ state.hasRule "if")
    (notShadowedLet : ¬ state.hasRule "let") :
    TranslatesExpr state counter
      (.expr [.sym "if", .gnd (.bool true),
        .expr [.sym "let", .var name, .gnd (.int value), .var name]])
      (.variable (.generated counter))
      [.unify (.variable (.source name))
          (.variable (.generated counter)),
        .ifThenElse (.identical (.atom "true") (.atom "true"))
          (.conjunction
            [.unify (.variable (.source name)) (.integer value)])
          .fail]
      (counter + 1) := by
  exact .ifThen notShadowedIf (.literal .trueGround)
    (.letBind notShadowedLet
      (.literal (.variable name))
      (.literal (.integer value))
      (.literal (.variable name)))
    (.aliasVariable (.source name)
      [.unify (.variable (.source name)) (.integer value)] (by
        change 0 < 1
        omega))

/-- Negative-priority example: registering a translator rule for `let` does
not shadow native `chain`; only a rule for the source head may do so. -/
theorem translates_chain_with_let_shadowed (counter : Nat) (name : String)
    (value : Int) :
    let state : TranslatorState := ⟨fun head => head = "let"⟩
    state.hasRule "let" ∧
      TranslatesExpr state counter
        (.expr [.sym "chain", .gnd (.int value), .var name, .var name])
        (.variable (.source name))
        [.unify (.integer value) (.variable (.source name))]
        counter := by
  dsimp
  constructor
  · rfl
  · exact .chainBind (by simp)
      (.literal (.integer value))
      (.literal (.variable name))
      (.literal (.variable name))

/-- Positive behavioral-translation example for a literal mutex body. -/
theorem translates_literal_withMutex (state : TranslatorState) (counter : Nat)
    (mutex : String) (value : Int)
    (notShadowed : ¬ state.hasRule "with_mutex") :
    TranslatesWithMutex state counter
      (.expr [.sym "with_mutex", .sym mutex, .gnd (.int value)])
      (.integer value)
      [.withMutex (.atom mutex) (.conjunction [])]
      counter :=
  .wrap notShadowed (.symbol mutex) (.literal (.integer value))

/-- Negative priority example: a registered `with_mutex` translator hook
prevents the built-in translation rule from being selected. -/
theorem withMutex_hook_blocks_builtin (counter : Nat) (mutex : String)
    (value : Int) :
    let state : TranslatorState := ⟨fun _ => True⟩
    ∀ term goals nextCounter,
      ¬ TranslatesWithMutex state counter
        (.expr [.sym "with_mutex", .sym mutex, .gnd (.int value)])
        term goals nextCounter := by
  dsimp
  intro term goals nextCounter translation
  cases translation with
  | wrap notShadowed _ _ => exact notShadowed trivial

/-- Positive native `once` translation for a literal body. -/
theorem translates_literal_once (state : TranslatorState) (counter : Nat)
    (value : Int) (notShadowed : ¬ state.hasRule "once") :
    TranslatesOnce state counter
      (.expr [.sym "once", .gnd (.int value)])
      (.integer value) [.once (.conjunction [])] counter :=
  .wrap notShadowed (.literal (.integer value))

/-- Negative priority example: a registered `once` translator hook blocks the
built-in native translation clause. -/
theorem once_hook_blocks_builtin (counter : Nat) (value : Int) :
    let state : TranslatorState := ⟨fun _ => True⟩
    ∀ term goals nextCounter,
      ¬ TranslatesOnce state counter
        (.expr [.sym "once", .gnd (.int value)]) term goals nextCounter := by
  dsimp
  intro term goals nextCounter translation
  cases translation with
  | wrap notShadowed _ => exact notShadowed trivial

/-- Positive two-binding example: pinned `let*` expands left-to-right into two
nested `let` forms, then translates those forms in the same order. -/
theorem translates_two_literal_letStar (state : TranslatorState) (counter : Nat)
    (firstName secondName : String) (firstValue secondValue : Int)
    (letStarNotShadowed : ¬ state.hasRule "let*")
    (letNotShadowed : ¬ state.hasRule "let") :
    TranslatesLetStar state counter
      (.expr [.sym "let*",
        .expr [
          .expr [.var firstName, .gnd (.int firstValue)],
          .expr [.var secondName, .gnd (.int secondValue)]],
        .var secondName])
      (.variable (.source secondName))
      [.unify (.variable (.source firstName)) (.integer firstValue),
        .unify (.variable (.source secondName)) (.integer secondValue)]
      counter := by
  refine .expand letStarNotShadowed (.cons .single) ?_
  simpa using TranslatesExpr.letBind letNotShadowed
    (.literal (.variable firstName))
    (.literal (.integer firstValue))
    (TranslatesExpr.letBind letNotShadowed
      (.literal (.variable secondName))
      (.literal (.integer secondValue))
      (.literal (.variable secondName)))

/-- An empty binding list has no pinned `let*` expansion. -/
theorem letStar_empty_bindings_rejected (body nested : Atom) :
    ¬ LetStarExpands [] body nested := by
  intro expansion
  cases expansion

/-- A binding entry must be a two-element expression. -/
theorem letStar_malformed_binding_rejected (malformed : String)
    (body nested : Atom) :
    ¬ LetStarExpands [.sym malformed] body nested := by
  intro expansion
  cases expansion

/-- A registered `let*` translator hook has priority over the pinned builtin
expansion rule. -/
theorem letStar_hook_blocks_builtin (counter : Nat)
    (pattern value body : Atom) :
    let state : TranslatorState := ⟨fun _ => True⟩
    ∀ term goals nextCounter,
      ¬ TranslatesLetStar state counter
        (.expr [.sym "let*", .expr [.expr [pattern, value]], body])
        term goals nextCounter := by
  dsimp
  intro term goals nextCounter translation
  cases translation with
  | expand notShadowed _ _ => exact notShadowed trivial

/-- Positive pattern-traversal example: atomic pattern members retain order and
their independent Prolog representations. -/
theorem translates_atomic_pattern_pair (name : String) (value : Int) :
    ConstrainsAtomicPatternSeq [.var name, .gnd (.int value)]
      [.variable (.source name), .integer value] :=
  .cons (.literal (.variable name))
    (.cons (.literal (.integer value)) .nil)

/-- Empty native argument traversal emits no terms or goals and preserves the
fresh-variable counter. -/
theorem translates_empty_args (state : TranslatorState) (counter : Nat) :
    TranslatesArgs state counter [] [] [] counter :=
  .nil

/-- Positive ordered argument-traversal example over two source literals. -/
theorem translates_two_literal_args (state : TranslatorState) (counter : Nat)
    (first second : Int) :
    TranslatesArgs state counter
      [.gnd (.int first), .gnd (.int second)]
      [.integer first, .integer second] [] counter :=
  .cons (.literal (.integer first))
    (.cons (.literal (.integer second)) .nil)

/-- Positive mixed typed-argument example: one expression remains source data
and the following value argument is translated normally. -/
theorem translates_staged_value_args (state : TranslatorState) (counter : Nat)
    (head : String) (stagedValue evaluatedValue : Int) :
    TranslatesTypedArgs state counter [.expression, .value]
      [.expr [.sym head, .gnd (.int stagedValue)],
        .gnd (.int evaluatedValue)]
      [.list [.atom head, .integer stagedValue] none,
        .integer evaluatedValue] [] counter := by
  exact .expression
    (.expression
      (.cons (.symbol head) (.cons (.integer stagedValue) .nil)))
    (.value (.literal (.integer evaluatedValue)) .nil)

/-- Positive refined-type example: a translated integer is followed by the
exact ordered `get-type`/`get-metatype` fallback and consumes two generated
variables. -/
theorem translates_refined_integer_arg (state : TranslatorState)
    (counter : Nat) (value : Int) :
    TranslatesTypedArgs state counter [.refined "Number"]
      [.gnd (.int value)] [.integer value]
      (refinedTypeCheckGoals (.integer value) "Number" counter)
      (counter + 2) := by
  exact .refined
    ⟨by decide, by decide, by decide, by decide, by decide⟩
    (.literal (.integer value)) .nil

/-- Positive recursive-pattern example: pinned `cons` traversal preserves a
proper two-element list and leaves both the ordered goal sequence and fresh
counter unchanged. -/
theorem constrains_cons_pair (state : TranslatorState) (counter : Nat)
    (name : String) (value : Int) :
    ConstrainsPattern state counter
      (.expr [.sym "cons", .var name,
        .expr [.sym "cons", .gnd (.int value), .expr []]])
      (.list [.variable (.source name), .integer value] none) [] counter := by
  exact .cons (.atomic (.literal (.variable name)))
    (.cons (.atomic (.literal (.integer value)))
      (.atomic (.literal .emptyList)))

/-- Positive dotted-list example: a variable tail remains the explicit tail
of the independent Prolog list cell. -/
theorem constrains_dotted_cons (state : TranslatorState) (counter : Nat)
    (headName tailName : String) :
    ConstrainsPattern state counter
      (.expr [.sym "cons", .var headName, .var tailName])
      (.list [.variable (.source headName)]
        (some (.variable (.source tailName)))) [] counter := by
  exact .cons (.atomic (.literal (.variable headName)))
    (.atomic (.literal (.variable tailName)))

/-- Host payloads are not part of pinned atomic pattern syntax. -/
theorem external_not_atomic_pattern (tag payload : String) (term : Term) :
    ¬ ConstrainsAtomicPattern (.gnd (.external tag payload)) term := by
  intro translation
  cases translation with
  | literal value => cases value

/-- The current independently specified compiler fragment.  Membership is a
native translation derivation, never an executable-compiler success test. -/
def SupportedExpr (state : TranslatorState) (counter : Nat) (source : Atom) :
    Prop :=
  ∃ term goals nextCounter,
    TranslatesExpr state counter source term goals nextCounter

/-- Independently supported ordered argument lists. -/
def SupportedArgs (state : TranslatorState) (counter : Nat)
    (sources : List Atom) : Prop :=
  ∃ terms goals nextCounter,
    TranslatesArgs state counter sources terms goals nextCounter

/-- Independently supported typed-argument lists for the explicit mode list. -/
def SupportedTypedArgs (state : TranslatorState) (counter : Nat)
    (modes : List ArgumentMode) (sources : List Atom) : Prop :=
  ∃ terms goals nextCounter,
    TranslatesTypedArgs state counter modes sources terms goals nextCounter

/-- Supported source forms whose native target requires a proved sequential
behavioral normalization rather than structural goal identity. -/
def SupportedWithMutex (state : TranslatorState) (counter : Nat)
    (source : Atom) : Prop :=
  ∃ term goals nextCounter,
    TranslatesWithMutex state counter source term goals nextCounter

/-- Independently supported native `once` forms. -/
def SupportedOnce (state : TranslatorState) (counter : Nat)
    (source : Atom) : Prop :=
  ∃ term goals nextCounter,
    TranslatesOnce state counter source term goals nextCounter

/-- Independently supported, well-formed native `let*` forms. -/
def SupportedLetStar (state : TranslatorState) (counter : Nat)
    (source : Atom) : Prop :=
  ∃ term goals nextCounter,
    TranslatesLetStar state counter source term goals nextCounter

/-- Independently supported atomic pattern forms. -/
def SupportedAtomicPattern (source : Atom) : Prop :=
  ∃ term, ConstrainsAtomicPattern source term

/-- Independently supported left-to-right atomic pattern sequences. -/
def SupportedAtomicPatternSeq (sources : List Atom) : Prop :=
  ∃ terms, ConstrainsAtomicPatternSeq sources terms

/-- Independently supported recursive `constrain_args/3` patterns. -/
def SupportedPattern (state : TranslatorState) (counter : Nat)
    (source : Atom) : Prop :=
  ∃ term goals nextCounter,
    ConstrainsPattern state counter source term goals nextCounter

/-- Independently supported ordered recursive pattern traversals. -/
def SupportedPatternSeq (state : TranslatorState) (counter : Nat)
    (sources : List Atom) : Prop :=
  ∃ terms goals nextCounter,
    ConstrainsPatternSeq state counter sources terms goals nextCounter

/-- A host payload is outside the independently supported source-pattern
fragment even though the executable compiler has an internal ground-value
branch for runtime-produced atoms. -/
theorem external_not_supported_atomic_pattern (tag payload : String) :
    ¬ SupportedAtomicPattern (.gnd (.external tag payload)) := by
  intro supported
  obtain ⟨term, translation⟩ := supported
  exact external_not_atomic_pattern tag payload term translation

/-- Host payloads remain outside the larger recursive pattern fragment. -/
theorem external_not_supported_pattern (state : TranslatorState)
    (counter : Nat) (tag payload : String) :
    ¬ SupportedPattern state counter (.gnd (.external tag payload)) := by
  intro supported
  obtain ⟨term, goals, nextCounter, translation⟩ := supported
  cases translation with
  | atomic value => exact external_not_atomic_pattern tag payload term value

/-- A malformed one-argument `cons` is outside the pinned rule's supported
source shape. -/
theorem malformed_cons_not_supported_pattern (state : TranslatorState)
    (counter : Nat) (head : Atom) :
    ¬ SupportedPattern state counter (.expr [.sym "cons", head]) := by
  intro supported
  obtain ⟨term, goals, nextCounter, translation⟩ := supported
  cases translation with
  | atomic value =>
      cases value with
      | literal literal => cases literal

/-- Runtime-only host payloads cannot enter the certified source argument
fragment through a singleton list. -/
theorem external_singleton_not_supported_args (state : TranslatorState)
    (counter : Nat) (tag payload : String) :
    ¬ SupportedArgs state counter [.gnd (.external tag payload)] := by
  intro supported
  obtain ⟨terms, goals, nextCounter, translation⟩ := supported
  cases translation with
  | cons head tail =>
      cases head with
      | literal literal => cases literal

/-- A nonempty source list cannot be translated after its explicit type-mode
list is exhausted. -/
theorem typedArgs_exhausted_modes_rejected (state : TranslatorState)
    (counter : Nat) (source : Atom) :
    ¬ SupportedTypedArgs state counter [] [source] := by
  intro supported
  obtain ⟨terms, goals, nextCounter, translation⟩ := supported
  cases translation

/-- Imported host payloads are not literals in the certified compiler fragment. -/
theorem external_not_literal (tag payload : String) (term : Term) :
    ¬ Literal (.gnd (.external tag payload)) term := by
  intro h
  cases h

/-- Grounded errors are runtime values, not source literals accepted by the
pinned reader/compiler relation. -/
theorem error_not_literal (message : String) (term : Term) :
    ¬ Literal (.gnd (.error message)) term := by
  intro h
  cases h

end PLeaTTa.PeTTaSpec.PrologCore
