/-
Module: PLeaTTa.PeTTaSpec.PrologResolver
Purpose: Independent logical-update-aware clause store and ordered local-call
  cursor for the Prolog fragment generated by pinned PeTTa.
Trusted boundary: none
Main exports: Database, LocalSession, CallRequest, PreparedCursor,
  semanticLocalClauseProtocol
-/
import PLeaTTa.PeTTaSpec.OpenSubstitution
import PLeaTTa.PeTTaSpec.PrologTraceSemantics
import PLeaTTa.PeTTaSpec.PrologMgu

namespace PLeaTTa.PeTTaSpec.PrologCore.Resolver

open OpenSubstitution
open Canonical

/-!
This is the database-and-clause-selection half of the certified local
resolver.  It is independent of PLeaTTa's executable `PWorld`, `Clause`,
`resolveAlts`, and `Step` definitions.

Pinned PeTTa delegates ordinary definite-clause calls to SWI-Prolog.  SWI's
logical update view tags a call with the database generation at which it
starts and exposes exactly the clauses whose creation/erasure interval
contains that generation.  The executable PLeaTTa machine currently realizes
the same shape by materializing its ordered alternatives at call entry.  This
module states the source-side rule directly: a cursor owns an immutable
ordered snapshot, not a pointer back into the live database.

Fresh standardization-apart is performed eagerly by `reserveVisible` when a
call opens.  The resulting `PreparedCursor` freezes source order, clause
copies, and their disjoint intervals before any body can open a nested call.
Head MGU construction is certified by `HeadResolution`; leftmost body
execution is the next layer.  The older one-at-a-time `pullBranch` remains only
as an internal construction/negative witness and is not exposed by the
semantic protocol.

[SPEC SWI-Prolog manual 4.14.1.1, logical update view]
[SPEC metta.pl:251-256, left-to-right `call_goals/1`]
-/

/-- Monotone logical-update generation. -/
abbrev Generation := Nat

/-- Stable identity of one asserted clause occurrence.  Duplicate clauses
remain distinct occurrences and therefore retain their multiplicity. -/
abbrev ClauseId := Nat

/-- One independent definite clause.  The output argument of a PeTTa
function is an ordinary final Prolog head argument here; it is not given a
special semantic status. -/
structure LocalClause where
  predicate : String
  arguments : List Term
  body : List Goal
deriving Repr, Inhabited

/-- A historical clause occurrence.  `erased = none` means that no erasure
generation has yet been recorded.  Erased occurrences stay in history so a
cursor opened before retraction can continue to use them. -/
structure VersionedClause where
  id : ClauseId
  clause : LocalClause
  created : Generation
  erased : Option Generation := none
deriving Repr, Inhabited

/-- The ISO/SWI visibility interval: creation is inclusive and erasure is
exclusive. -/
def VersionedClause.VisibleAt (entry : VersionedClause)
    (generation : Generation) : Prop :=
  entry.created ≤ generation ∧
    match entry.erased with
    | none => True
    | some erased => generation < erased

/-- Computable presentation of `VisibleAt`, used only to filter the finite
history. -/
def VersionedClause.visibleAt (entry : VersionedClause)
    (generation : Generation) : Bool :=
  entry.created ≤ generation &&
    match entry.erased with
    | none => true
    | some erased => generation < erased

@[simp] theorem VersionedClause.visibleAt_eq_true_iff
    (entry : VersionedClause) (generation : Generation) :
    entry.visibleAt generation = true ↔ entry.VisibleAt generation := by
  cases erased : entry.erased <;>
    simp [VersionedClause.visibleAt, VersionedClause.VisibleAt, erased]

/-- Independent dynamic clause history in source order.  `asserta` prepends
and `assertz` appends.  Retraction marks an occurrence rather than deleting
it, which is the key representation invariant behind logical-update cursors.
-/
structure Database where
  generation : Generation := 0
  nextId : ClauseId := 0
  history : List VersionedClause := []
deriving Repr, Inhabited

/-- Empty dynamic program. -/
def Database.empty : Database := {}

/-- Non-backtrackable state shared by the certified control layer and local
resolver.  `nextFresh` is a global high-water: opening or executing a nested
call may advance it, and structural backtracking never restores an older
value because the trace machine stores this session outside `Process`. -/
structure LocalSession where
  database : Database := .empty
  nextFresh : Nat := 0
deriving Repr, Inhabited

/-- Allocate the next clause occurrence at the next database generation. -/
def Database.allocate (database : Database) (clause : LocalClause) :
    VersionedClause :=
  { id := database.nextId
    clause := clause
    created := database.generation + 1 }

/-- Append one clause occurrence.  [SPEC metta.pl:277] -/
def Database.assertz (database : Database) (clause : LocalClause) : Database :=
  let entry := database.allocate clause
  { generation := database.generation + 1
    nextId := database.nextId + 1
    history := database.history ++ [entry] }

/-- Prepend one clause occurrence.  [SPEC metta.pl:278] -/
def Database.asserta (database : Database) (clause : LocalClause) : Database :=
  let entry := database.allocate clause
  { generation := database.generation + 1
    nextId := database.nextId + 1
    history := entry :: database.history }

/-- Mark the first live occurrence with the requested identity.  Failure is
represented by `none`; it is not an exception and does not fabricate a new
generation. -/
def retireFirst (generation : Generation) (id : ClauseId) :
    List VersionedClause → Option (List VersionedClause)
  | [] => none
  | entry :: rest =>
      if entry.id = id ∧ entry.erased = none then
        some ({ entry with erased := some generation } :: rest)
      else
        (retireFirst generation id rest).map (entry :: ·)

/-- Retract one identified live occurrence.  The successful update advances
the generation; failure leaves the caller with no successor database.
The source-level `retract/1` relation still has to select the first unifying
content occurrence and expose later matches on backtracking; this identity
primitive does not claim to discharge that MGU/control obligation.
[SPEC metta.pl:279-280] -/
def Database.retractId (database : Database) (id : ClauseId) :
    Option Database :=
  let nextGeneration := database.generation + 1
  match retireFirst nextGeneration id database.history with
  | none => none
  | some history =>
      some { database with generation := nextGeneration, history := history }

/-- Clause occurrences visible to one call, preserving database order and
duplicate multiplicity. -/
def Database.visibleClausesAt (database : Database)
    (generation : Generation) (predicate : String) (arity : Nat) :
    List VersionedClause :=
  database.history.filter fun entry =>
    entry.visibleAt generation &&
      entry.clause.predicate == predicate &&
      entry.clause.arguments.length == arity

/-- The deliberately wrong live-view candidate function.  It exists only for
anti-vacuity witnesses: recomputing at the current generation after every
world update allows a running call to observe newly asserted clauses. -/
def Database.liveViewClauses (database : Database)
    (predicate : String) (arity : Nat) : List VersionedClause :=
  database.visibleClausesAt database.generation predicate arity

/-- Typed request to open a locally owned predicate.  Dynamic database state
and the global fresh high-water are deliberately absent: both live in the
non-backtrackable `LocalSession`, so a branch cannot restore stale allocator
state by retaining an old request. -/
structure CallRequest where
  predicate : String
  arguments : List Term
  bindings : Substitution
deriving Repr, Inhabited

/-- Internal lazy snapshot builder.  The semantic protocol never exposes this
cursor directly because its evolving seed would be stale across body
execution; `PreparedCursor` below is the actual protocol token. -/
structure ClauseCursor where
  callGeneration : Generation
  predicate : String
  arguments : List Term
  bindings : Substitution
  remaining : List VersionedClause
  freshSeed : Nat
deriving Repr, Inhabited

/-- Build the immutable source-order snapshot used by the reservation pass.
The database and fresh seed come from explicit session state, never from the
backtrackable request. -/
def openCursor (database : Database) (freshSeed : Nat)
    (request : CallRequest) : ClauseCursor :=
  { callGeneration := database.generation
    predicate := request.predicate
    arguments := request.arguments
    bindings := request.bindings
    remaining := database.visibleClausesAt database.generation
      request.predicate request.arguments.length
    freshSeed := freshSeed }

@[simp] theorem openCursor_callGeneration (database : Database)
    (freshSeed : Nat) (request : CallRequest) :
    (openCursor database freshSeed request).callGeneration =
      database.generation := rfl

@[simp] theorem openCursor_remaining (database : Database)
    (freshSeed : Nat) (request : CallRequest) :
    (openCursor database freshSeed request).remaining =
      database.visibleClausesAt database.generation
        request.predicate request.arguments.length := rfl

/-- Candidate selection deletes entries only; hence it cannot reorder source
clauses or deduplicate equal occurrences. -/
theorem visibleClausesAt_sublist_history (database : Database)
    (generation : Generation) (predicate : String) (arity : Nat) :
    List.Sublist (database.visibleClausesAt generation predicate arity)
      database.history :=
  List.filter_sublist

/-- A clause asserted after `generation` is invisible at that older
generation. -/
@[simp] theorem Database.allocate_not_visible_at_current
    (database : Database) (clause : LocalClause) :
    (database.allocate clause).visibleAt database.generation = false := by
  simp [Database.allocate, VersionedClause.visibleAt]

/-- `assertz` cannot retroactively change the ordered view at the preceding
generation. -/
theorem Database.assertz_old_view (database : Database) (clause : LocalClause)
    (predicate : String) (arity : Nat) :
    (database.assertz clause).visibleClausesAt database.generation
        predicate arity =
      database.visibleClausesAt database.generation predicate arity := by
  simp [Database.assertz, Database.visibleClausesAt]

/-- `asserta` likewise cannot retroactively insert a clause into an already
started call. -/
theorem Database.asserta_old_view (database : Database) (clause : LocalClause)
    (predicate : String) (arity : Nat) :
    (database.asserta clause).visibleClausesAt database.generation
        predicate arity =
      database.visibleClausesAt database.generation predicate arity := by
  simp [Database.asserta, Database.visibleClausesAt]

/-! ## Standardization apart and clause-entry branches -/

mutual

/-- Variables in one independent term, in occurrence order. -/
def termVariables : Term → List LogicVar
  | .variable identity => [identity]
  | .atom _ => []
  | .integer _ => []
  | .float _ => []
  | .string _ => []
  | .compound _ arguments => termsVariables arguments
  | .list items none => termsVariables items
  | .list items (some tail) => termsVariables items ++ termVariables tail

/-- Variables in an ordered term sequence, in occurrence order. -/
def termsVariables : List Term → List LogicVar
  | [] => []
  | term :: terms => termVariables term ++ termsVariables terms

end

mutual

/-- Variables in one independent goal, in left-to-right syntax order. -/
def goalVariables : Goal → List LogicVar
  | .truth => []
  | .fail => []
  | .unify left right => termVariables left ++ termVariables right
  | .identical left right => termVariables left ++ termVariables right
  | .call _ arguments => termsVariables arguments
  | .conjunction goals => goalsVariables goals
  | .disjunction branches => goalsVariables branches
  | .cut => []
  | .ifThenElse condition thenBranch elseBranch =>
      goalVariables condition ++ goalVariables thenBranch ++
        goalVariables elseBranch
  | .softCut condition thenBranch elseBranch =>
      goalVariables condition ++ goalVariables thenBranch ++
        goalVariables elseBranch
  | .negation goal => goalVariables goal
  | .once goal => goalVariables goal
  | .findall template goal output =>
      termVariables template ++ goalVariables goal ++ termVariables output
  | .catch goal exception handler =>
      goalVariables goal ++ termVariables exception ++ goalVariables handler
  | .transaction goal => goalVariables goal
  | .withMutex mutex goal => termVariables mutex ++ goalVariables goal
  | .forall generator test => goalVariables generator ++ goalVariables test

/-- Variables in an ordered goal sequence, in occurrence order. -/
def goalsVariables : List Goal → List LogicVar
  | [] => []
  | goal :: goals => goalVariables goal ++ goalsVariables goals

end

/-- Distinct clause-local variables in stable first-occurrence order. -/
def LocalClause.variables (clause : LocalClause) : List LogicVar :=
  (termsVariables clause.arguments ++ goalsVariables clause.body).eraseDups

/-- One past a translator-generated variable index.  Source and anonymous
identities occupy disjoint namespaces and therefore impose no lower bound on
the generated namespace. -/
def logicVarGeneratedCeiling : LogicVar → Nat
  | .source _ => 0
  | .anonymous _ => 0
  | .generated index => index + 1

/-- A finite set's exclusive upper bound in the generated namespace. -/
def variablesGeneratedCeiling : List LogicVar → Nat
  | [] => 0
  | identity :: variables =>
      max (logicVarGeneratedCeiling identity)
        (variablesGeneratedCeiling variables)

def LocalClause.generatedCeiling (clause : LocalClause) : Nat :=
  variablesGeneratedCeiling clause.variables

/-- Build a stable variable renaming into consecutive fresh generated
identities.  The caller chooses a start above both the live query and the
stored clause's generated-variable ceilings. -/
def buildFreshening : Nat → List LogicVar → Substitution × Nat
  | seed, [] => ([], seed)
  | seed, identity :: variables =>
      let tail := buildFreshening (seed + 1) variables
      ((identity, .variable (.generated seed)) :: tail.1, tail.2)

/-- The freshening counter advances once per distinct clause variable. -/
theorem buildFreshening_next (seed : Nat) (variables : List LogicVar) :
    (buildFreshening seed variables).2 = seed + variables.length := by
  induction variables generalizing seed with
  | nil => rfl
  | cons identity variables induction =>
      simp only [buildFreshening, List.length_cons]
      rw [induction]
      omega

/-- Freshening retains one binding per distinct source variable. -/
theorem buildFreshening_length (seed : Nat) (variables : List LogicVar) :
    (buildFreshening seed variables).1.length = variables.length := by
  induction variables generalizing seed with
  | nil => rfl
  | cons identity variables induction =>
      simp [buildFreshening, induction]

/-- Every target allocated by `buildFreshening` lies in its advertised
half-open interval.  This turns counter arithmetic into a statement about
the actual variables consumed later by unification. -/
theorem buildFreshening_target_range (seed : Nat) (variables : List LogicVar)
    {source : LogicVar} {index : Nat}
    (member : (source, .variable (.generated index)) ∈
      (buildFreshening seed variables).1) :
    seed ≤ index ∧ index < seed + variables.length := by
  induction variables generalizing seed with
  | nil => simp [buildFreshening] at member
  | cons identity variables induction =>
      simp only [buildFreshening] at member
      rcases List.mem_cons.mp member with first | later
      · have sameIndex : index = seed := by
          have targetEquality := congrArg Prod.snd first
          simpa using targetEquality
        subst index
        simp
      · have range := induction (seed := seed + 1) later
        simp only [List.length_cons]
        constructor <;> omega

/-- Every freshening target is generated; together with
`buildFreshening_target_range` this characterizes the allocation rather than
merely counting it. -/
theorem buildFreshening_target_generated (seed : Nat)
    (variables : List LogicVar) {source : LogicVar} {target : Term}
    (member : (source, target) ∈ (buildFreshening seed variables).1) :
    ∃ index, target = .variable (.generated index) ∧
      seed ≤ index ∧ index < seed + variables.length := by
  induction variables generalizing seed with
  | nil => simp [buildFreshening] at member
  | cons identity variables induction =>
      simp only [buildFreshening] at member
      rcases List.mem_cons.mp member with first | later
      · refine ⟨seed, ?_, by simp⟩
        exact congrArg Prod.snd first
      · obtain ⟨index, targetShape, lower, upper⟩ :=
          induction (seed := seed + 1) later
        refine ⟨index, targetShape, ?_, ?_⟩
        · omega
        · simp only [List.length_cons]
          omega

/-- A generated namespace is live below `seed` when every generated identity
occurring in the finite syntax has a strictly smaller index. -/
def GeneratedBelow (seed : Nat) (variables : List LogicVar) : Prop :=
  ∀ index, .generated index ∈ variables → index < seed

/-- The computed ceiling really dominates every generated identity in the
finite syntax. -/
theorem generatedBelow_variablesGeneratedCeiling (variables : List LogicVar) :
    GeneratedBelow (variablesGeneratedCeiling variables) variables := by
  intro index member
  induction variables with
  | nil => simp at member
  | cons identity variables inductionHypothesis =>
      rcases List.mem_cons.mp member with same | later
      · subst identity
        exact Nat.lt_of_lt_of_le (Nat.lt_succ_self index)
          (Nat.le_max_left _ _)
      · exact Nat.lt_of_lt_of_le (inductionHypothesis later)
          (Nat.le_max_right _ _)

theorem GeneratedBelow.mono {smaller larger : Nat} {variables : List LogicVar}
    (below : GeneratedBelow smaller variables) (ordered : smaller ≤ larger) :
    GeneratedBelow larger variables := by
  intro index member
  exact Nat.lt_of_lt_of_le (below index member) ordered

/-- Variables carried by an open substitution, including its domain. -/
def substitutionVariables : Substitution → List LogicVar
  | [] => []
  | (source, value) :: bindings =>
      source :: termVariables value ++ substitutionVariables bindings

/-- The call allocator starts above every generated identity already live in
the query and its carried substitution. -/
def CallRequest.FreshSeedDominates (request : CallRequest) (freshSeed : Nat) :
    Prop :=
  GeneratedBelow freshSeed
    (termsVariables request.arguments ++
      substitutionVariables request.bindings)

/-- Exclusive generated-variable ceiling of a live request. -/
def CallRequest.generatedCeiling (request : CallRequest) : Nat :=
  variablesGeneratedCeiling
    (termsVariables request.arguments ++
      substitutionVariables request.bindings)

theorem CallRequest.generatedCeiling_dominates (request : CallRequest) :
    request.FreshSeedDominates request.generatedCeiling := by
  exact generatedBelow_variablesGeneratedCeiling _

/-- Cursor presentation of the same global allocator invariant. -/
def ClauseCursor.FreshSeedDominates (cursor : ClauseCursor) : Prop :=
  GeneratedBelow cursor.freshSeed
    (termsVariables cursor.arguments ++
      substitutionVariables cursor.bindings)

theorem openCursor_freshSeedDominates {database : Database} {freshSeed : Nat}
    {request : CallRequest}
    (dominates : request.FreshSeedDominates freshSeed) :
    (openCursor database freshSeed request).FreshSeedDominates := by
  exact dominates

/-- Data retained for the adequacy bridge: the exact simultaneous renaming,
the standardized clause, and its half-open fresh-index interval. -/
structure FreshClause where
  freshSubstitution : Substitution
  clause : LocalClause
  firstFresh : Nat
  nextFresh : Nat
deriving Repr, Inhabited

/-- Standardize every variable of a stored clause apart.  `max` prevents a
stored translator-generated variable from becoming one of its own targets;
the cursor's `freshSeed` is separately required to dominate the live query.
-/
def LocalClause.freshCopy (clause : LocalClause) (freshSeed : Nat) :
    FreshClause :=
  let firstFresh := max freshSeed clause.generatedCeiling
  let built := buildFreshening firstFresh clause.variables
  { freshSubstitution := built.1
    clause :=
      { predicate := clause.predicate
        arguments := built.1.applyTerms clause.arguments
        body := built.1.applyGoals clause.body }
    firstFresh := firstFresh
    nextFresh := built.2 }

@[simp] theorem LocalClause.freshCopy_predicate
    (clause : LocalClause) (freshSeed : Nat) :
    (clause.freshCopy freshSeed).clause.predicate = clause.predicate := rfl

theorem LocalClause.freshCopy_first_ge_seed
    (clause : LocalClause) (freshSeed : Nat) :
    freshSeed ≤ (clause.freshCopy freshSeed).firstFresh := by
  exact Nat.le_max_left _ _

theorem LocalClause.freshCopy_first_ge_clause
    (clause : LocalClause) (freshSeed : Nat) :
    clause.generatedCeiling ≤ (clause.freshCopy freshSeed).firstFresh := by
  exact Nat.le_max_right _ _

theorem LocalClause.freshCopy_next
    (clause : LocalClause) (freshSeed : Nat) :
    (clause.freshCopy freshSeed).nextFresh =
      (clause.freshCopy freshSeed).firstFresh + clause.variables.length := by
  simp only [LocalClause.freshCopy]
  exact buildFreshening_next _ _

/-- Every generated target used by the standardized clause lies inside the
half-open interval recorded on the copy itself. -/
theorem LocalClause.freshCopy_target_range
    (clause : LocalClause) (freshSeed : Nat)
    {source : LogicVar} {index : Nat}
    (member : (source, .variable (.generated index)) ∈
      (clause.freshCopy freshSeed).freshSubstitution) :
    (clause.freshCopy freshSeed).firstFresh ≤ index ∧
      index < (clause.freshCopy freshSeed).nextFresh := by
  change (source, .variable (.generated index)) ∈
    (buildFreshening (max freshSeed clause.generatedCeiling)
      clause.variables).1 at member
  simpa only [LocalClause.freshCopy, buildFreshening_next] using
    (buildFreshening_target_range
      (max freshSeed clause.generatedCeiling) clause.variables member)

/-- Pointwise head equations.  Equal arity is guaranteed by
`visibleClausesAt`; the fallback cases make malformed pairs explicitly clash
with the reserved `$missing` atom instead of silently truncating them. -/
def argumentEquations : List Term → List Term → List (Term × Term)
  | [], [] => []
  | left :: leftRest, right :: rightRest =>
      (left, right) :: argumentEquations leftRest rightRest
  | leftRest, [] => leftRest.map (fun left => (left, .atom "$missing"))
  | [], rightRest => rightRest.map (fun right => (.atom "$missing", right))

/-- Turn the ordered head equations into the actual leftmost equality prefix.
-/
def equationsToGoals (equations : List (Term × Term)) : List Goal :=
  equations.map fun equation => .unify equation.1 equation.2

/-- One source-ordered clause entry, ready for leftmost MGU/body execution. -/
structure ClauseBranch where
  sourceId : ClauseId
  callGeneration : Generation
  freshSubstitution : Substitution
  headEquations : List (Term × Term)
  body : List Goal
  bindings : Substitution
  firstFresh : Nat
  nextFresh : Nat
deriving Repr, Inhabited

/-- The branch's recorded fresh interval bounds every actual generated target
in its standardization substitution. -/
def ClauseBranch.FreshTargetsReserved (branch : ClauseBranch) : Prop :=
  ∀ source index,
    (source, .variable (.generated index)) ∈ branch.freshSubstitution →
      branch.firstFresh ≤ index ∧ index < branch.nextFresh

/-- Clause entry always executes head unification before the body. -/
def ClauseBranch.goals (branch : ClauseBranch) : List Goal :=
  equationsToGoals branch.headEquations ++ branch.body

/-- Eagerly reserve and standardize every clause occurrence in a call-start
snapshot.  Reservation runs once, in source order, before any clause body can
open a nested call.  The returned high-water is therefore above every clause
copy retained by the cursor. -/
def reserveVisible (callGeneration : Generation) (arguments : List Term)
    (bindings : Substitution) :
    Nat → List VersionedClause → List ClauseBranch × Nat
  | freshSeed, [] => ([], freshSeed)
  | freshSeed, entry :: rest =>
      let copied := entry.clause.freshCopy freshSeed
      let branch : ClauseBranch :=
        { sourceId := entry.id
          callGeneration := callGeneration
          freshSubstitution := copied.freshSubstitution
          headEquations := argumentEquations arguments copied.clause.arguments
          body := copied.clause.body
          bindings := bindings
          firstFresh := copied.firstFresh
          nextFresh := copied.nextFresh }
      let tail := reserveVisible callGeneration arguments bindings
        copied.nextFresh rest
      (branch :: tail.1, tail.2)

/-- Structural certificate for a completely reserved cursor.  Each branch
starts at or above the preceding high-water, and its end becomes the lower
bound for the rest of the frozen source-order list. -/
inductive FreshReservation : Nat → List ClauseBranch → Nat → Prop where
  | nil (freshSeed : Nat) : FreshReservation freshSeed [] freshSeed
  | cons (freshSeed : Nat) (branch : ClauseBranch)
      (branches : List ClauseBranch) (finalFresh : Nat)
      (startsAbove : freshSeed ≤ branch.firstFresh)
      (nonemptyInterval : branch.firstFresh ≤ branch.nextFresh)
      (tail : FreshReservation branch.nextFresh branches finalFresh) :
      FreshReservation freshSeed (branch :: branches) finalFresh

/-- The eager reservation algorithm really produces the advertised ordered,
non-overlapping interval certificate. -/
theorem reserveVisible_freshReservation (callGeneration : Generation)
    (arguments : List Term) (bindings : Substitution)
    (freshSeed : Nat) (entries : List VersionedClause) :
    FreshReservation freshSeed
      (reserveVisible callGeneration arguments bindings freshSeed entries).1
      (reserveVisible callGeneration arguments bindings freshSeed entries).2 := by
  induction entries generalizing freshSeed with
  | nil => exact .nil freshSeed
  | cons entry rest inductionHypothesis =>
      simp only [reserveVisible]
      apply FreshReservation.cons
      · exact entry.clause.freshCopy_first_ge_seed freshSeed
      · rw [entry.clause.freshCopy_next]
        exact Nat.le_add_right _ _
      · exact inductionHypothesis _

/-- Reservation never lowers the global high-water. -/
theorem FreshReservation.final_ge_start
    {freshSeed finalFresh : Nat} {branches : List ClauseBranch}
    (reserved : FreshReservation freshSeed branches finalFresh) :
    freshSeed ≤ finalFresh := by
  induction reserved with
  | nil => exact Nat.le_refl _
  | cons freshSeed branch branches finalFresh startsAbove nonemptyInterval
      tail inductionHypothesis =>
      exact Nat.le_trans startsAbove
        (Nat.le_trans nonemptyInterval inductionHypothesis)

/-- Every retained branch ends at or below the reservation's final
high-water. -/
theorem FreshReservation.member_next_le_final
    {freshSeed finalFresh : Nat} {branches : List ClauseBranch}
    (reserved : FreshReservation freshSeed branches finalFresh)
    {branch : ClauseBranch} (member : branch ∈ branches) :
    branch.nextFresh ≤ finalFresh := by
  induction reserved with
  | nil => simp at member
  | cons freshSeed head tail finalFresh startsAbove nonemptyInterval
      tailReserved inductionHypothesis =>
      rcases List.mem_cons.mp member with rfl | later
      · exact tailReserved.final_ge_start
      · exact inductionHypothesis later

/-- Every retained branch starts at or above the reservation's initial
high-water. -/
theorem FreshReservation.start_le_member_first
    {freshSeed finalFresh : Nat} {branches : List ClauseBranch}
    (reserved : FreshReservation freshSeed branches finalFresh)
    {branch : ClauseBranch} (member : branch ∈ branches) :
    freshSeed ≤ branch.firstFresh := by
  induction reserved with
  | nil => simp at member
  | cons freshSeed head tail finalFresh startsAbove nonemptyInterval
      tailReserved inductionHypothesis =>
      rcases List.mem_cons.mp member with rfl | later
      · exact startsAbove
      · exact Nat.le_trans startsAbove
          (Nat.le_trans nonemptyInterval (inductionHypothesis later))

/-- Reservation stamps every prepared branch with the call-start database
generation. -/
theorem reserveVisible_callGeneration (callGeneration : Generation)
    (arguments : List Term) (bindings : Substitution)
    (freshSeed : Nat) (entries : List VersionedClause) :
    ∀ branch ∈
      (reserveVisible callGeneration arguments bindings freshSeed entries).1,
      branch.callGeneration = callGeneration := by
  intro branch member
  induction entries generalizing freshSeed with
  | nil => simp [reserveVisible] at member
  | cons entry rest inductionHypothesis =>
      simp only [reserveVisible] at member
      rcases List.mem_cons.mp member with rfl | later
      · rfl
      · exact inductionHypothesis _ later

/-- Every eagerly reserved branch carries exactly the cumulative binding
state of the call request.  Head resolution may prepend an extension only
after that branch is pulled. -/
theorem reserveVisible_bindings (callGeneration : Generation)
    (arguments : List Term) (bindings : Substitution)
    (freshSeed : Nat) (entries : List VersionedClause) :
    ∀ branch ∈
      (reserveVisible callGeneration arguments bindings freshSeed entries).1,
      branch.bindings = bindings := by
  intro branch member
  induction entries generalizing freshSeed with
  | nil => simp [reserveVisible] at member
  | cons entry rest inductionHypothesis =>
      simp only [reserveVisible] at member
      rcases List.mem_cons.mp member with rfl | later
      · rfl
      · exact inductionHypothesis _ later

/-- Every branch built by eager reservation carries an honest interval: its
freshening substitution cannot contain a generated target outside it. -/
theorem reserveVisible_freshTargetsReserved (callGeneration : Generation)
    (arguments : List Term) (bindings : Substitution)
    (freshSeed : Nat) (entries : List VersionedClause) :
    ∀ branch ∈
      (reserveVisible callGeneration arguments bindings freshSeed entries).1,
      branch.FreshTargetsReserved := by
  intro branch member
  induction entries generalizing freshSeed with
  | nil => simp [reserveVisible] at member
  | cons entry rest inductionHypothesis =>
      simp only [reserveVisible] at member
      rcases List.mem_cons.mp member with rfl | later
      · intro source index targetMember
        exact entry.clause.freshCopy_target_range freshSeed targetMember
      · exact inductionHypothesis _ later

/-- A completely prepared local-call cursor.  Unlike `ClauseCursor`, which is
the internal reservation builder, this is the token exposed to the trace
protocol: pulling it never allocates a variable. -/
structure PreparedCursor where
  callGeneration : Generation
  predicate : String
  arguments : List Term
  bindings : Substitution
  reservationStart : Nat
  remaining : List ClauseBranch
  reservedUntil : Nat
deriving Repr, Inhabited

/-- The cursor's frozen branch list carries a valid global reservation. -/
def PreparedCursor.WellReserved (cursor : PreparedCursor) : Prop :=
  FreshReservation cursor.reservationStart cursor.remaining
    cursor.reservedUntil

/-- The reservation starts above every generated identity already live in the
request. -/
def PreparedCursor.QueryDominated (cursor : PreparedCursor) : Prop :=
  GeneratedBelow cursor.reservationStart
    (termsVariables cursor.arguments ++
      substitutionVariables cursor.bindings)

/-- Full prepared-cursor invariant: the live query lies below the reservation,
fresh intervals are globally reserved and honest about their actual targets,
and every retained occurrence belongs to the call-start generation. -/
def PreparedCursor.WellFormed (cursor : PreparedCursor) : Prop :=
  cursor.WellReserved ∧
    cursor.QueryDominated ∧
    (∀ branch ∈ cursor.remaining,
      branch.callGeneration = cursor.callGeneration) ∧
    ∀ branch ∈ cursor.remaining,
      branch.FreshTargetsReserved

/-- Every retained branch starts from the cursor's immutable call-entry
binding state.  This is kept separate from freshness/database well-formedness
because it is the substitution-lineage premise consumed by the Goal machine.
-/
def PreparedCursor.BindingsAligned (cursor : PreparedCursor) : Prop :=
  ∀ branch ∈ cursor.remaining, branch.bindings = cursor.bindings

/-- Prepare a call and advance the global high-water past every clause copy.
The database is not changed; its generation and visible clause list are
captured once in the returned token. -/
def prepareCall (session : LocalSession) (request : CallRequest) :
    PreparedCursor × LocalSession :=
  let entries := session.database.visibleClausesAt session.database.generation
    request.predicate request.arguments.length
  let reservationStart := max session.nextFresh request.generatedCeiling
  let reserved := reserveVisible session.database.generation request.arguments
    request.bindings reservationStart entries
  ({ callGeneration := session.database.generation
     predicate := request.predicate
     arguments := request.arguments
     bindings := request.bindings
     reservationStart := reservationStart
     remaining := reserved.1
     reservedUntil := reserved.2 },
   { session with nextFresh := reserved.2 })

/-- Every prepared call is well reserved. -/
theorem prepareCall_wellReserved (session : LocalSession)
    (request : CallRequest) :
    (prepareCall session request).1.WellReserved := by
  exact reserveVisible_freshReservation _ _ _ _ _

/-- Preparing a call repairs even an underspecified incoming high-water by
starting above the request's computed generated-variable ceiling.  Reachable
machine states should already satisfy that invariant; the reference open
operation does not rely on it silently. -/
theorem prepareCall_queryDominated (session : LocalSession)
    (request : CallRequest) :
    (prepareCall session request).1.QueryDominated := by
  exact request.generatedCeiling_dominates.mono (Nat.le_max_right _ _)

/-- Every cursor produced by the stateful open operation satisfies the full
reservation and logical-update ownership invariant. -/
theorem prepareCall_wellFormed (session : LocalSession)
    (request : CallRequest) :
    (prepareCall session request).1.WellFormed := by
  refine ⟨prepareCall_wellReserved session request,
    prepareCall_queryDominated session request, ?_, ?_⟩
  · exact reserveVisible_callGeneration _ _ _ _ _
  · exact reserveVisible_freshTargetsReserved _ _ _ _ _

/-- The stateful call opener produces a cursor whose complete frozen branch
list is aligned with the request substitution. -/
theorem prepareCall_bindingsAligned (session : LocalSession)
    (request : CallRequest) :
    (prepareCall session request).1.BindingsAligned := by
  exact reserveVisible_bindings _ _ _ _ _

/-- Opening a local call monotonically advances the global fresh high-water.
Since the session is stored outside backtrackable `Process`, this inequality
continues to hold after any nested execution and return to a retained branch.
-/
theorem prepareCall_nextFresh_mono (session : LocalSession)
    (request : CallRequest) :
    session.nextFresh ≤ (prepareCall session request).2.nextFresh := by
  exact Nat.le_trans (Nat.le_max_left _ _)
    (prepareCall_wellReserved session request).final_ge_start

/-- The session high-water after opening is exactly the cursor's reserved
upper bound. -/
@[simp] theorem prepareCall_nextFresh_eq_reservedUntil
    (session : LocalSession) (request : CallRequest) :
    (prepareCall session request).2.nextFresh =
      (prepareCall session request).1.reservedUntil := rfl

/-- A nested call opened after an outer call cannot collide with any clause
copy retained by the outer cursor.  This is the key property the former lazy
cursor lacked: nested body allocation starts only after *all* outer
alternatives have already been reserved. -/
theorem prepareCall_nested_fresh_disjoint
    (session : LocalSession) (outerRequest nestedRequest : CallRequest)
    {outerBranch nestedBranch : ClauseBranch}
    (outerMember : outerBranch ∈
      (prepareCall session outerRequest).1.remaining)
    (nestedMember : nestedBranch ∈
      (prepareCall (prepareCall session outerRequest).2
        nestedRequest).1.remaining) :
    outerBranch.nextFresh ≤ nestedBranch.firstFresh := by
  have outerUpper :=
    (prepareCall_wellReserved session outerRequest).member_next_le_final
      outerMember
  have nestedLower :=
    (prepareCall_wellReserved (prepareCall session outerRequest).2
      nestedRequest).start_le_member_first nestedMember
  have between :
      (prepareCall session outerRequest).1.reservedUntil ≤
        (prepareCall (prepareCall session outerRequest).2
          nestedRequest).1.reservationStart := by
    rw [← prepareCall_nextFresh_eq_reservedUntil]
    exact Nat.le_max_left _ _
  exact Nat.le_trans outerUpper (Nat.le_trans between nestedLower)

/-- The interval theorem above reaches the actual substitutions: every fresh
target retained by the outer call has a strictly smaller generated index than
every fresh target allocated by the nested call. -/
theorem prepareCall_nested_fresh_targets_ordered
    (session : LocalSession) (outerRequest nestedRequest : CallRequest)
    {outerBranch nestedBranch : ClauseBranch}
    {outerSource nestedSource : LogicVar} {outerIndex nestedIndex : Nat}
    (outerMember : outerBranch ∈
      (prepareCall session outerRequest).1.remaining)
    (nestedMember : nestedBranch ∈
      (prepareCall (prepareCall session outerRequest).2
        nestedRequest).1.remaining)
    (outerTarget : (outerSource, .variable (.generated outerIndex)) ∈
      outerBranch.freshSubstitution)
    (nestedTarget : (nestedSource, .variable (.generated nestedIndex)) ∈
      nestedBranch.freshSubstitution) :
    outerIndex < nestedIndex := by
  have outerRange :=
    (prepareCall_wellFormed session outerRequest).2.2.2
      outerBranch outerMember outerSource outerIndex outerTarget
  have nestedRange :=
    (prepareCall_wellFormed (prepareCall session outerRequest).2
      nestedRequest).2.2.2
      nestedBranch nestedMember nestedSource nestedIndex nestedTarget
  have disjoint := prepareCall_nested_fresh_disjoint session outerRequest
    nestedRequest outerMember nestedMember
  omega

/-- Opening a call preserves the dynamic database and advances only the
global fresh high-water. -/
@[simp] theorem prepareCall_database (session : LocalSession)
    (request : CallRequest) :
    (prepareCall session request).2.database = session.database := rfl

/-- The prepared token fixes the logical-update generation at call start. -/
@[simp] theorem prepareCall_generation (session : LocalSession)
    (request : CallRequest) :
    (prepareCall session request).1.callGeneration =
      session.database.generation := rfl

/-- Pull and standardize exactly one clause in the internal lazy builder.
Head equalities precede the body.  This function supports reservation lemmas
and the explicit wrong-lazy counterexample; it is not the semantic call
protocol. -/
def pullBranch (cursor : ClauseCursor) :
    Option (ClauseBranch × ClauseCursor) :=
  match cursor.remaining with
  | [] => none
  | entry :: rest =>
      let copied := entry.clause.freshCopy cursor.freshSeed
      let branch : ClauseBranch :=
        { sourceId := entry.id
          callGeneration := cursor.callGeneration
          freshSubstitution := copied.freshSubstitution
          headEquations :=
            argumentEquations cursor.arguments copied.clause.arguments
          body := copied.clause.body
          bindings := cursor.bindings
          firstFresh := copied.firstFresh
          nextFresh := copied.nextFresh }
      let next := { cursor with
        remaining := rest
        freshSeed := copied.nextFresh }
      some (branch, next)

@[simp] theorem pullBranch_none_iff (cursor : ClauseCursor) :
    pullBranch cursor = none ↔ cursor.remaining = [] := by
  cases remaining : cursor.remaining <;> simp [pullBranch, remaining]

/-- A successful standardized pull consumes precisely the snapshot head and
preserves every call-start field.  The sole evolving fields are the ordered
tail and the global fresh counter. -/
theorem pullBranch_exact {cursor next : ClauseCursor}
    {branch : ClauseBranch}
    (pulled : pullBranch cursor = some (branch, next)) :
    ∃ entry rest,
      cursor.remaining = entry :: rest ∧
      branch.sourceId = entry.id ∧
      branch.callGeneration = cursor.callGeneration ∧
      next.remaining = rest ∧
      next.callGeneration = cursor.callGeneration ∧
      next.predicate = cursor.predicate ∧
      next.arguments = cursor.arguments ∧
      next.bindings = cursor.bindings ∧
      next.freshSeed = branch.nextFresh := by
  cases remaining : cursor.remaining with
  | nil => simp [pullBranch, remaining] at pulled
  | cons entry rest =>
      simp only [pullBranch, remaining, Option.some.injEq, Prod.mk.injEq]
        at pulled
      rcases pulled with ⟨rfl, rfl⟩
      exact ⟨entry, rest, rfl, rfl, rfl, rfl, rfl, rfl, rfl, rfl, rfl⟩

/-- Clause entry is leftmost: every head equation precedes every body goal. -/
theorem pullBranch_goals_shape {cursor next : ClauseCursor}
    {branch : ClauseBranch} {entry : VersionedClause}
    {rest : List VersionedClause}
    (remaining : cursor.remaining = entry :: rest)
    (pulled : pullBranch cursor = some (branch, next)) :
    let copied := entry.clause.freshCopy cursor.freshSeed
    branch.goals =
        equationsToGoals
            (argumentEquations cursor.arguments copied.clause.arguments) ++
          copied.clause.body ∧
      branch.sourceId = entry.id ∧
      branch.callGeneration = cursor.callGeneration ∧
      next.remaining = rest ∧
      next.freshSeed = copied.nextFresh := by
  simp only [pullBranch, remaining, Option.some.injEq, Prod.mk.injEq] at pulled
  rcases pulled with ⟨rfl, rfl⟩
  simp [ClauseBranch.goals]

/-- Fresh intervals allocated to successive clause entries do not overlap. -/
theorem pullBranch_fresh_monotone {cursor next : ClauseCursor}
    {branch : ClauseBranch}
    (pulled : pullBranch cursor = some (branch, next)) :
    cursor.freshSeed ≤ branch.firstFresh ∧
      branch.firstFresh ≤ branch.nextFresh ∧
      next.freshSeed = branch.nextFresh := by
  cases remaining : cursor.remaining with
  | nil => simp [pullBranch, remaining] at pulled
  | cons entry rest =>
      simp only [pullBranch, remaining, Option.some.injEq, Prod.mk.injEq]
        at pulled
      rcases pulled with ⟨rfl, rfl⟩
      constructor
      · exact entry.clause.freshCopy_first_ge_seed cursor.freshSeed
      · constructor
        · rw [entry.clause.freshCopy_next]
          exact Nat.le_add_right _ _
        · rfl

/-- Two successive clause copies receive disjoint, monotonically ordered
fresh intervals.  This rules out the retry/cross-clause aliasing bug that a
constant per-call seed would introduce. -/
theorem pullBranch_successive_fresh_disjoint
    {start middle finish : ClauseCursor}
    {first second : ClauseBranch}
    (pulledFirst : pullBranch start = some (first, middle))
    (pulledSecond : pullBranch middle = some (second, finish)) :
    first.nextFresh ≤ second.firstFresh := by
  have firstFacts := pullBranch_fresh_monotone pulledFirst
  have secondFacts := pullBranch_fresh_monotone pulledSecond
  rw [← firstFacts.2.2]
  exact secondFacts.1

/-- The advertised interval describes every actual target in a pulled
clause's standardization-apart substitution. -/
theorem pullBranch_fresh_target_generated
    {cursor next : ClauseCursor} {branch : ClauseBranch}
    (pulled : pullBranch cursor = some (branch, next))
    {source : LogicVar} {target : Term}
    (member : (source, target) ∈ branch.freshSubstitution) :
    ∃ index, target = .variable (.generated index) ∧
      branch.firstFresh ≤ index ∧ index < branch.nextFresh := by
  cases remaining : cursor.remaining with
  | nil => simp [pullBranch, remaining] at pulled
  | cons entry rest =>
      simp only [pullBranch, remaining, Option.some.injEq, Prod.mk.injEq]
        at pulled
      rcases pulled with ⟨rfl, rfl⟩
      simpa [LocalClause.freshCopy, buildFreshening_next] using
        (buildFreshening_target_generated
          (max cursor.freshSeed entry.clause.generatedCeiling)
          entry.clause.variables member)

/-- Pulling a source-ordered clause preserves the live-query allocation
invariant because it advances, but never lowers, the global fresh counter. -/
theorem pullBranch_preserves_freshSeedDominates
    {cursor next : ClauseCursor} {branch : ClauseBranch}
    (dominates : cursor.FreshSeedDominates)
    (pulled : pullBranch cursor = some (branch, next)) :
    next.FreshSeedDominates := by
  obtain ⟨entry, rest, remaining, source, branchGeneration, tail,
      generation, predicate, arguments, bindings, fresh⟩ :=
    pullBranch_exact pulled
  unfold ClauseCursor.FreshSeedDominates at dominates ⊢
  rw [arguments, bindings]
  apply dominates.mono
  have monotone := pullBranch_fresh_monotone pulled
  omega

/-- Under the explicit live-query invariant, no target allocated for the
selected clause can alias a generated variable already present in the call
arguments or carried substitution. -/
theorem pullBranch_fresh_target_not_live
    {cursor next : ClauseCursor} {branch : ClauseBranch}
    (dominates : cursor.FreshSeedDominates)
    (pulled : pullBranch cursor = some (branch, next))
    {source : LogicVar} {target : Term}
    (member : (source, target) ∈ branch.freshSubstitution) :
    ∃ index, target = .variable (.generated index) ∧
      .generated index ∉
        (termsVariables cursor.arguments ++
          substitutionVariables cursor.bindings) := by
  obtain ⟨index, targetShape, lower, upper⟩ :=
    pullBranch_fresh_target_generated pulled member
  refine ⟨index, targetShape, ?_⟩
  intro live
  have oldIndex := dominates index live
  have monotone := pullBranch_fresh_monotone pulled
  omega

/-! ## Semantic head resolution and the internal clause protocol -/

/-- Apply the carried open substitution to both sides of every head equation
before computing the next extension. -/
def ClauseBranch.normalizedHeadEquations (branch : ClauseBranch) :
    List (Term × Term) :=
  branch.headEquations.map fun equation =>
    (branch.bindings.applyTerm equation.1,
      branch.bindings.applyTerm equation.2)

/-- Semantic clause-head resolution.  `extension` must be an MGU of the
already-normalized head equations; prepending it to the carried state is the
new open substitution.  The extension is the exact canonical reification of
the deterministic ordered MGU derivation, so raw dotted-list presentation
cannot make clause entry nondeterministic. -/
def HeadResolution (branch : ClauseBranch) (result : Substitution) : Prop :=
  ∃ extension,
    ComputesDenotationalMgu branch.normalizedHeadEquations extension ∧
      result = extension ++ branch.bindings

/-- Canonical ordered MGU selection makes source-level clause-head
resolution functional, including the exact substitution spelling. -/
theorem HeadResolution.deterministic {branch : ClauseBranch}
    {first second : Substitution}
    (one : HeadResolution branch first)
    (two : HeadResolution branch second) : first = second := by
  rcases one with ⟨firstExtension, firstComputed, rfl⟩
  rcases two with ⟨secondExtension, secondComputed, rfl⟩
  exact congrArg (fun extension => extension ++ branch.bindings)
    (firstComputed.unique secondComputed)

/-- Any semantic unifier of the normalized clause head yields the unique
ordered head-resolution result. -/
theorem HeadResolution.exists_of_unifier {branch : ClauseBranch}
    (candidate : Substitution)
    (unifies : DenotationalUnifiesEquations candidate
      branch.normalizedHeadEquations) :
    ∃ result, HeadResolution branch result := by
  rcases ComputesDenotationalMgu.exists_of_unifier candidate unifies with
    ⟨extension, computed⟩
  exact ⟨extension ++ branch.bindings, extension, computed, rfl⟩

/-- Head resolution succeeds exactly when the normalized finite-tree
equations are unifiable. -/
theorem HeadResolution.exists_iff_unifiable {branch : ClauseBranch} :
    (∃ result, HeadResolution branch result) ↔
      ∃ candidate, DenotationalUnifiesEquations candidate
        branch.normalizedHeadEquations := by
  constructor
  · rintro ⟨result, extension, computed, resultEq⟩
    exact ⟨extension, computed.isMostGeneral.1⟩
  · rintro ⟨candidate, unifies⟩
    exact HeadResolution.exists_of_unifier candidate unifies

/-- Every semantic head resolution genuinely unifies every raw head equation
after composition with the carried state. -/
theorem HeadResolution.unifies {branch : ClauseBranch}
    {result : Substitution} (resolution : HeadResolution branch result) :
    DenotationalUnifiesEquations result branch.headEquations := by
  rcases resolution with ⟨extension, computed, rfl⟩
  have mostGeneral := computed.isMostGeneral
  intro equation member
  have normalizedMember :
      (branch.bindings.applyTerm equation.1,
          branch.bindings.applyTerm equation.2) ∈
        branch.normalizedHeadEquations := by
    exact List.mem_map_of_mem member
  have unifies := mostGeneral.1 _ normalizedMember
  unfold DenotationalUnifier at unifies ⊢
  simpa [Canonical.Substitution.denote_append,
    TreeSubstitution.apply_append,
    Canonical.Substitution.denote_applyTerm] using unifies

/-- With no carried constraints, head resolution itself is an MGU of the raw
head equations. -/
theorem HeadResolution.isMostGeneral_of_empty {branch : ClauseBranch}
    {result : Substitution} (empty : branch.bindings = [])
    (resolution : HeadResolution branch result) :
    IsDenotationalMgu result branch.headEquations := by
  rcases resolution with ⟨extension, computed, resultEq⟩
  have mostGeneral := computed.isMostGeneral
  have normalized : branch.normalizedHeadEquations = branch.headEquations := by
    simp [ClauseBranch.normalizedHeadEquations, empty]
  have resultIsExtension : result = extension := by
    simpa [empty] using resultEq
  rw [resultIsExtension]
  rw [normalized] at mostGeneral
  exact mostGeneral

/-- A successfully entered clause after its head equations have been
consumed.  The body remains left-to-right, instantiated by the new MGU state.
-/
structure EnteredClause where
  sourceId : ClauseId
  callGeneration : Generation
  bindings : Substitution
  /-- The standardized-apart body before applying the head MGU.  The local
  small-step machine carries raw residual goals together with a cumulative
  substitution, so retaining this field avoids an idempotence assumption
  when a recursive body is entered. -/
  rawBody : List Goal
  body : List Goal
  nextFresh : Nat
deriving Repr, Inhabited

def ClauseBranch.enter (branch : ClauseBranch) (bindings : Substitution) :
    EnteredClause :=
  { sourceId := branch.sourceId
    callGeneration := branch.callGeneration
    bindings := bindings
    rawBody := branch.body
    body := bindings.applyGoals branch.body
    nextFresh := branch.nextFresh }

@[simp] theorem ClauseBranch.enter_body (branch : ClauseBranch)
    (bindings : Substitution) :
    (branch.enter bindings).body =
      bindings.applyGoals (branch.enter bindings).rawBody := rfl

/-- Consume the head of a fully prepared cursor.  No fresh name is allocated
here: the next cursor merely exposes the already-reserved tail. -/
def PreparedCursor.advance (cursor : PreparedCursor) (branch : ClauseBranch)
    (rest : List ClauseBranch) : PreparedCursor :=
  { cursor with
    reservationStart := branch.nextFresh
    remaining := rest }

/-- One demand on the internal prepared cursor.  A non-unifying clause is one
silent step; a unifying clause yields one entered body; exhaustion is distinct
from both.  Clause order and fresh intervals were frozen at open time, before
any selected body can allocate names in a nested call. -/
inductive LocalPull : PreparedCursor →
    Trace.PullResult PreparedCursor EnteredClause Empty Empty → Prop where
  | matched (cursor : PreparedCursor) (branch : ClauseBranch)
      (rest : List ClauseBranch) (result : Substitution)
      (remaining : cursor.remaining = branch :: rest)
      (resolved : HeadResolution branch result) :
      LocalPull cursor
        (.reply (branch.enter result) (cursor.advance branch rest))
  | rejected (cursor : PreparedCursor) (branch : ClauseBranch)
      (rest : List ClauseBranch)
      (remaining : cursor.remaining = branch :: rest)
      (clash : ¬ ∃ result, HeadResolution branch result) :
      LocalPull cursor (.silent (cursor.advance branch rest))
  | exhausted (cursor : PreparedCursor) (done : cursor.remaining = []) :
      LocalPull cursor .exhausted

/-- Every clause cursor has a next demand result.  The only classical split
is whether the finite normalized head equations have a unifier; completeness
above turns any such witness into the unique canonical MGU. -/
theorem LocalPull.total (cursor : PreparedCursor) :
    ∃ outcome, LocalPull cursor outcome := by
  cases remaining : cursor.remaining with
  | nil => exact ⟨.exhausted, .exhausted cursor remaining⟩
  | cons branch rest =>
      by_cases resolves : ∃ result, HeadResolution branch result
      · rcases resolves with ⟨result, resolved⟩
        exact ⟨.reply (branch.enter result) (cursor.advance branch rest),
          .matched cursor branch rest result remaining resolved⟩
      · exact ⟨.silent (cursor.advance branch rest),
          .rejected cursor branch rest remaining resolves⟩

/-- One cursor demand has exactly one ordered result: clause selection is a
function, canonical head resolution is functional, and match/reject/exhaust
cases are disjoint. -/
theorem LocalPull.deterministic {cursor : PreparedCursor}
    {first second : Trace.PullResult PreparedCursor EnteredClause Empty Empty}
    (one : LocalPull cursor first) (two : LocalPull cursor second) :
    first = second := by
  cases one with
  | matched branchOne restOne resultOne remainingOne resolvedOne =>
      cases two with
      | matched branchTwo restTwo resultTwo remainingTwo resolvedTwo =>
          have listEquality := remainingOne.symm.trans remainingTwo
          injection listEquality with branchEquality restEquality
          subst branchTwo
          subst restTwo
          have resultEquality := resolvedOne.deterministic resolvedTwo
          subst resultTwo
          rfl
      | rejected branchTwo restTwo remainingTwo clash =>
          have listEquality := remainingOne.symm.trans remainingTwo
          injection listEquality with branchEquality restEquality
          subst branchTwo
          exact False.elim (clash ⟨resultOne, resolvedOne⟩)
      | exhausted done =>
          rw [done] at remainingOne
          cases remainingOne
  | rejected branchOne restOne remainingOne clashOne =>
      cases two with
      | matched branchTwo restTwo resultTwo remainingTwo resolvedTwo =>
          have listEquality := remainingOne.symm.trans remainingTwo
          injection listEquality with branchEquality restEquality
          subst branchTwo
          exact False.elim (clashOne ⟨resultTwo, resolvedTwo⟩)
      | rejected branchTwo restTwo remainingTwo clashTwo =>
          have listEquality := remainingOne.symm.trans remainingTwo
          injection listEquality with branchEquality restEquality
          subst branchTwo
          subst restTwo
          rfl
      | exhausted done =>
          rw [done] at remainingOne
          cases remainingOne
  | exhausted doneOne =>
      cases two with
      | matched branchTwo restTwo resultTwo remainingTwo resolvedTwo =>
          rw [doneOne] at remainingTwo
          cases remainingTwo
      | rejected branchTwo restTwo remainingTwo clashTwo =>
          rw [doneOne] at remainingTwo
          cases remainingTwo
      | exhausted doneTwo => rfl

/-- Dropping one prepared branch preserves both its reservation tail and its
call-generation ownership. -/
theorem PreparedCursor.advance_wellFormed
    {cursor : PreparedCursor} {branch : ClauseBranch}
    {rest : List ClauseBranch}
    (wellFormed : cursor.WellFormed)
    (remaining : cursor.remaining = branch :: rest) :
    (cursor.advance branch rest).WellFormed := by
  rcases wellFormed with ⟨reserved, dominated, owned, targetsReserved⟩
  unfold PreparedCursor.WellReserved at reserved
  rw [remaining] at reserved
  change FreshReservation branch.nextFresh rest cursor.reservedUntil ∧
    GeneratedBelow branch.nextFresh
      (termsVariables cursor.arguments ++
        substitutionVariables cursor.bindings) ∧
    (∀ candidate ∈ rest,
      candidate.callGeneration = cursor.callGeneration) ∧
    ∀ candidate ∈ rest, candidate.FreshTargetsReserved
  cases reserved with
  | cons freshSeed branch branches finalFresh startsAbove nonemptyInterval
      tailReserved =>
      refine ⟨tailReserved,
        dominated.mono (Nat.le_trans startsAbove nonemptyInterval), ?_, ?_⟩
      · intro candidate member
        apply owned candidate
        rw [remaining]
        exact List.mem_cons_of_mem branch member
      · intro candidate member
        apply targetsReserved candidate
        rw [remaining]
        exact List.mem_cons_of_mem branch member

/-- Consuming one branch preserves call-entry binding alignment for every
retained alternative. -/
theorem PreparedCursor.advance_bindingsAligned
    {cursor : PreparedCursor} {branch : ClauseBranch}
    {rest : List ClauseBranch}
    (aligned : cursor.BindingsAligned)
    (remaining : cursor.remaining = branch :: rest) :
    (cursor.advance branch rest).BindingsAligned := by
  intro candidate member
  apply aligned candidate
  rw [remaining]
  exact List.mem_cons_of_mem branch member

/-- A well-formed prepared cursor standardizes every retained clause apart
from every generated identity already live in its request. -/
theorem PreparedCursor.fresh_target_not_query
    {cursor : PreparedCursor} (wellFormed : cursor.WellFormed)
    {branch : ClauseBranch} (branchMember : branch ∈ cursor.remaining)
    {source : LogicVar} {index : Nat}
    (targetMember : (source, .variable (.generated index)) ∈
      branch.freshSubstitution) :
    .generated index ∉
      (termsVariables cursor.arguments ++
        substitutionVariables cursor.bindings) := by
  intro live
  have below := wellFormed.2.1 index live
  have branchLower :=
    wellFormed.1.start_le_member_first branchMember
  have targetLower :=
    (wellFormed.2.2.2 branch branchMember source index targetMember).1
  omega

/-- Any nonterminal local demand preserves the prepared-cursor invariant. -/
theorem LocalPull.preserves_wellFormed
    {cursor : PreparedCursor}
    {outcome : Trace.PullResult PreparedCursor EnteredClause Empty Empty}
    (wellFormed : cursor.WellFormed)
    (pulled : LocalPull cursor outcome) :
    match outcome with
    | .reply _ next => next.WellFormed
    | .silent next => next.WellFormed
    | .effect _ next => next.WellFormed
    | .exhausted => True
    | .raised _ => True := by
  cases pulled with
  | matched branch rest result remaining resolved =>
      exact cursor.advance_wellFormed wellFormed remaining
  | rejected branch rest remaining clash =>
      exact cursor.advance_wellFormed wellFormed remaining
  | exhausted done => exact True.intro

/-- Any nonterminal demand preserves branch/cursor binding alignment. -/
theorem LocalPull.preserves_bindingsAligned
    {cursor : PreparedCursor}
    {outcome : Trace.PullResult PreparedCursor EnteredClause Empty Empty}
    (aligned : cursor.BindingsAligned)
    (pulled : LocalPull cursor outcome) :
    match outcome with
    | .reply _ next => next.BindingsAligned
    | .silent next => next.BindingsAligned
    | .effect _ next => next.BindingsAligned
    | .exhausted => True
    | .raised _ => True := by
  cases pulled with
  | matched branch rest result remaining resolved =>
      exact cursor.advance_bindingsAligned aligned remaining
  | rejected branch rest remaining clash =>
      exact cursor.advance_bindingsAligned aligned remaining
  | exhausted done => exact True.intro

/-- A yielded clause body can only prepend its canonical head-MGU extension
to the cursor's call-entry bindings.  This is the resolver half of the
cross-call substitution-lineage invariant. -/
theorem LocalPull.reply_bindings_extend_cursor
    {cursor next : PreparedCursor} {entered : EnteredClause}
    (aligned : cursor.BindingsAligned)
    (pulled : LocalPull cursor (.reply entered next)) :
    ∃ extension, entered.bindings = extension ++ cursor.bindings := by
  cases pulled with
  | matched branch rest result remaining resolved =>
      have branchAligned : branch.bindings = cursor.bindings := by
        apply aligned branch
        rw [remaining]
        simp
      rcases resolved with ⟨extension, computed, resultEq⟩
      refine ⟨extension, ?_⟩
      change result = extension ++ cursor.bindings
      rw [resultEq, branchAligned]

/-- Certified internal stream of source-ordered clause bodies.  This is not
the final user-answer protocol: the control layer must bind each yielded body
to the leftmost Goal interpreter.  Imported SWI calls remain a different,
trusted protocol instance. -/
def semanticLocalClauseProtocol :
    Trace.OrderedCallProtocol CallRequest PreparedCursor EnteredClause Empty Empty
    where
  Session := LocalSession
  openCall := fun before request cursor after =>
    prepareCall before request = (cursor, after)
  pull := fun before cursor outcome after =>
    LocalPull cursor outcome ∧ after = before
  prune := fun before _ after => after = before
  perform := fun _ effect _ => nomatch effect

/-- Control process used by the certified local lane.  `EnteredClause` is an
internal provider reply, while `Answer` is reserved for values produced by the
certified body interpreter. -/
abbrev LocalProcess (Answer : Type) :=
  Trace.Process CallRequest PreparedCursor EnteredClause Answer Empty Empty

/-- Open a local predicate under its own cut boundary.  The provider can
select only an entered clause occurrence; `execute` remains in the certified
layer and is solely responsible for evaluating that clause body. -/
def localCallProcess {Answer : Type} (scope : Trace.CutScopeId)
    (request : CallRequest)
    (execute : EnteredClause → LocalProcess Answer) : LocalProcess Answer :=
  Trace.Process.scopedCall scope request execute

/-- Local-call construction preserves the generic cut-scope invariant. -/
theorem localCallProcess_wellScoped {Answer : Type}
    (active scope : Trace.CutScopeId)
    (request : CallRequest) (execute : EnteredClause → LocalProcess Answer)
    (executeScoped : ∀ entered, Trace.WellScoped scope (execute entered)) :
    Trace.WellScoped active (localCallProcess scope request execute) :=
  Trace.Process.scopedCall_wellScoped active scope request execute executeScoped

/-- Opening a local call exposes only the typed request and installs the exact
call-start snapshot cursor under the predicate boundary. -/
theorem localCallProcess_open_step {Answer : Type}
    (scope : Trace.CutScopeId)
    (session : LocalSession) (request : CallRequest)
    (execute : EnteredClause → LocalProcess Answer) :
    Trace.RawStep semanticLocalClauseProtocol session
      (localCallProcess scope request execute)
      [.opened request] .none (prepareCall session request).2
      (.running
        (.cutBoundary scope
          (.await scope (prepareCall session request).1 execute))) := by
  exact .cutBoundaryProgress (protocol := semanticLocalClauseProtocol)
    scope _ _ _ session
    (prepareCall session request).2
    (.openCall (protocol := semanticLocalClauseProtocol) request
      (prepareCall session request).1 _ session
      (prepareCall session request).2 rfl)

/-- One successful local pull splices the certified body before the remaining
clause cursor, at the same predicate cut scope, without emitting an answer.
This is the concrete anti-laundering bridge from `LocalPull` into `RawStep`. -/
theorem localCallProcess_reply_splice {Answer : Type}
    (scope : Trace.CutScopeId)
    (session : LocalSession)
    {cursor next : PreparedCursor} {entered : EnteredClause}
    (execute : EnteredClause → LocalProcess Answer)
    (pulled : LocalPull cursor (.reply entered next)) :
    Trace.RawStep semanticLocalClauseProtocol session
      (.await scope cursor execute) [] .none session
      (.running
        (.choice scope (execute entered) (.await scope next execute))) :=
  .awaitReply (protocol := semanticLocalClauseProtocol) scope cursor next
    entered execute session session ⟨pulled, rfl⟩

/-- Opening the internal local protocol is functional and fixes the call-start
snapshot. -/
theorem semanticLocalClauseProtocol_open_unique
    {before firstAfter secondAfter : LocalSession}
    {request : CallRequest} {first second : PreparedCursor}
    (one : semanticLocalClauseProtocol.openCall
      before request first firstAfter)
    (two : semanticLocalClauseProtocol.openCall
      before request second secondAfter) :
    first = second ∧ firstAfter = secondAfter := by
  have pairEquality := one.symm.trans two
  exact ⟨congrArg Prod.fst pairEquality, congrArg Prod.snd pairEquality⟩

/-- The protocol-level open relation exposes only well-formed, completely
reserved cursors. -/
theorem semanticLocalClauseProtocol_open_wellFormed
    {before after : LocalSession} {request : CallRequest}
    {cursor : PreparedCursor}
    (opened : semanticLocalClauseProtocol.openCall
      before request cursor after) :
    cursor.WellFormed := by
  have cursorEquality : (prepareCall before request).1 = cursor := by
    simpa using congrArg Prod.fst opened
  rw [← cursorEquality]
  exact prepareCall_wellFormed before request

/-- Opening through the protocol cannot roll back the global fresh
high-water. -/
theorem semanticLocalClauseProtocol_open_nextFresh_mono
    {before after : LocalSession} {request : CallRequest}
    {cursor : PreparedCursor}
    (opened : semanticLocalClauseProtocol.openCall
      before request cursor after) :
    before.nextFresh ≤ after.nextFresh := by
  have afterEquality : (prepareCall before request).2 = after := by
    simpa using congrArg Prod.snd opened
  rw [← afterEquality]
  exact prepareCall_nextFresh_mono before request

/-- Pulling a prepared cursor consumes no fresh names and preserves the
non-backtrackable session exactly. -/
theorem semanticLocalClauseProtocol_pull_session
    {before after : LocalSession} {cursor : PreparedCursor}
    {outcome : Trace.PullResult PreparedCursor EnteredClause Empty Empty}
    (pulled : semanticLocalClauseProtocol.pull before cursor outcome after) :
    after = before := pulled.2

/-- Pruning a prepared cursor likewise leaves global session state intact. -/
theorem semanticLocalClauseProtocol_prune_session
    {before after : LocalSession} {cursor : PreparedCursor}
    (pruned : semanticLocalClauseProtocol.prune before cursor after) :
    after = before := pruned

/-- Every certified local-control step monotonically preserves the global
fresh high-water.  Open may reserve more names; pulls, pruning, structural
control, answers, and exceptions cannot restore an older value. -/
theorem semanticLocalClauseProtocol_rawStep_nextFresh_mono
    {Answer : Type} {before after : LocalSession}
    {process : LocalProcess Answer}
    {events : List
      (Trace.Observation CallRequest PreparedCursor Answer Empty Empty)}
    {signal : Trace.CutSignal}
    {target : Trace.RawTarget
      CallRequest PreparedCursor EnteredClause Answer Empty Empty}
    (step : Trace.RawStep semanticLocalClauseProtocol before process events
      signal after target) :
    before.nextFresh ≤ after.nextFresh := by
  apply Trace.RawStep.session_measure_mono semanticLocalClauseProtocol
    (fun session => session.nextFresh)
  · intro openBefore request cursor openAfter opened
    exact semanticLocalClauseProtocol_open_nextFresh_mono opened
  · intro pullBefore cursor outcome pullAfter pulled
    rw [semanticLocalClauseProtocol_pull_session pulled]
    exact Nat.le_refl _
  · intro pruneBefore cursor pruneAfter pruned
    rw [semanticLocalClauseProtocol_prune_session pruned]
    exact Nat.le_refl _
  · intro performBefore effect performAfter performed
    exact Empty.elim effect
  · exact step

/-- A yielded local branch inherits the exact call generation and a fresh
interval already bounded by the cursor's global reservation.  Advancing to
the retained tail preserves the full cursor invariant. -/
theorem LocalPull.reply_origin
    {cursor next : PreparedCursor} {entered : EnteredClause}
    (wellFormed : cursor.WellFormed)
    (pulled : LocalPull cursor (.reply entered next)) :
    entered.callGeneration = cursor.callGeneration ∧
      entered.nextFresh ≤ cursor.reservedUntil ∧
      next.reservationStart = entered.nextFresh ∧
      next.reservedUntil = cursor.reservedUntil ∧
      next.WellFormed := by
  have nextWellFormed := pulled.preserves_wellFormed wellFormed
  cases pulled with
  | matched branch rest result remaining resolved =>
      have member : branch ∈ cursor.remaining := by
        rw [remaining]
        simp
      exact ⟨wellFormed.2.2.1 branch member,
        wellFormed.1.member_next_le_final member,
        rfl, rfl, nextWellFormed⟩

/-- Every clause reply carries a raw standardized-apart body together with
the cumulative head-unification state that instantiates it.  This rules out a
forged mismatch between the two redundant views and lets the small-step goal
machine execute raw residual goals without assuming substitution
idempotence. -/
theorem LocalPull.reply_body_consistent
    {cursor next : PreparedCursor} {entered : EnteredClause}
    (pulled : LocalPull cursor (.reply entered next)) :
    entered.body = entered.bindings.applyGoals entered.rawBody := by
  cases pulled with
  | matched branch rest result remaining resolved =>
      exact ClauseBranch.enter_body branch result

/-! ### MGU anti-vacuity witnesses -/

def variableHeadBranch : ClauseBranch where
  sourceId := 0
  callGeneration := 0
  freshSubstitution := []
  headEquations := [(.atom "a", .variable (.generated 0))]
  body := []
  bindings := []
  firstFresh := 0
  nextFresh := 1

/-- A rigid call argument against a fresh clause variable has the expected
semantic MGU even though the variable occurs on the right. -/
theorem variableHeadBranch_resolves :
    HeadResolution variableHeadBranch
      [(.generated 0, .atom "a")] := by
  let binding : Substitution := [(.generated 0, .atom "a")]
  have computed : ComputesDenotationalMgu
      [(.atom "a", .variable (.generated 0))] binding := by
    exact computes_singleton_right_variable (.atom "a") (.generated 0)
      (by intro identity equality; cases equality) (by rfl)
  exact ⟨binding, by simpa [variableHeadBranch,
    ClauseBranch.normalizedHeadEquations] using computed, rfl⟩

def clashingHeadBranch : ClauseBranch where
  sourceId := 0
  callGeneration := 0
  freshSubstitution := []
  headEquations := [(.atom "a", .atom "b")]
  body := []
  bindings := []
  firstFresh := 0
  nextFresh := 0

/-- Distinct rigid heads cannot be accepted by the semantic resolver.  This
prevents `HeadResolution` from degenerating into an always-successful oracle.
-/
theorem clashingHeadBranch_has_no_resolution :
    ¬ ∃ result, HeadResolution clashingHeadBranch result := by
  rintro ⟨result, extension, computed, resultEq⟩
  have mostGeneral := computed.isMostGeneral
  have unifies : DenotationalUnifier extension (.atom "a") (.atom "b") :=
    mostGeneral.1 (.atom "a", .atom "b") (by simp
      [clashingHeadBranch, ClauseBranch.normalizedHeadEquations])
  exact distinct_atoms_have_no_denotational_unifier "a" "b" (by decide)
    ⟨extension, unifies⟩

/-! ## Executable anti-vacuity witnesses for logical update -/

def witnessClause (value : String) : LocalClause where
  predicate := "p"
  arguments := [.atom value]
  body := []

def witnessBefore : Database :=
  (Database.empty.assertz (witnessClause "left")).assertz
    (witnessClause "right")

def witnessRequest : CallRequest where
  predicate := "p"
  arguments := [.variable (.source "X")]
  bindings := []

def witnessCursor : ClauseCursor := openCursor witnessBefore 10 witnessRequest

def witnessSession : LocalSession :=
  { database := witnessBefore, nextFresh := 10 }

/-- The actual protocol token, with all call-start clauses eagerly reserved. -/
def witnessPreparedCursor : PreparedCursor :=
  (prepareCall witnessSession witnessRequest).1

def witnessAfterAssert : Database :=
  witnessBefore.assertz (witnessClause "late")

/-- The correct call-start snapshot contains exactly the two occurrences
visible when the call opened. -/
theorem witness_snapshot_ids : witnessCursor.remaining.map (fun entry => entry.id) =
    [0, 1] := by
  decide

/-- The token used by the actual stateful protocol preserves the same exact
source order and duplicate-sensitive occurrence identities. -/
theorem witness_prepared_snapshot_ids :
    witnessPreparedCursor.remaining.map (fun branch => branch.sourceId) =
      [0, 1] := by
  decide

/-- A new call sees the clause asserted at the later generation. -/
theorem witness_new_call_sees_assertion :
    (witnessAfterAssert.liveViewClauses "p" 1).map (fun entry => entry.id) =
      [0, 1, 2] := by
  decide

/-- The actual prepared protocol, not merely the database projection, gives a
new call all three clauses in source order after the assertion. -/
theorem witness_prepared_new_call_sees_assertion :
    (prepareCall
      { database := witnessAfterAssert, nextFresh := 10 }
      witnessRequest).1.remaining.map (fun branch => branch.sourceId) =
      [0, 1, 2] := by
  decide

/-- The already-open cursor does not drift after assertion. -/
theorem witness_open_call_does_not_see_assertion :
    2 ∉ witnessCursor.remaining.map (fun entry => entry.id) := by
  decide

/-- The actual prepared protocol token likewise cannot drift after the live
database grows. -/
theorem witness_prepared_call_does_not_see_assertion :
    2 ∉ witnessPreparedCursor.remaining.map (fun branch => branch.sourceId) := by
  decide

/-- The deliberately wrong live-view semantics does observe the new clause.
Together with `witness_open_call_does_not_see_assertion`, this is the required
anti-vacuity discriminator: snapshot and live-view semantics cannot satisfy
the same exact ordered cursor claim. -/
theorem witness_wrong_live_view_sees_assertion :
    2 ∈ (witnessAfterAssert.liveViewClauses "p" 1).map
      (fun entry => entry.id) := by
  decide

def witnessAfterRetract : Database :=
  (witnessAfterAssert.retractId 1).getD witnessAfterAssert

/-- A newly opened call no longer sees the retracted occurrence. -/
theorem witness_new_call_hides_retraction :
    (witnessAfterRetract.liveViewClauses "p" 1).map (fun entry => entry.id) =
      [0, 2] := by
  decide

/-- A newly prepared protocol token sees the post-retraction source order,
while the older prepared token below retains its frozen occurrence. -/
theorem witness_prepared_new_call_hides_retraction :
    (prepareCall
      { database := witnessAfterRetract, nextFresh := 10 }
      witnessRequest).1.remaining.map (fun branch => branch.sourceId) =
      [0, 2] := by
  decide

/-- A cursor already standing over the old snapshot retains the retracted
occurrence, as required by the logical update view. -/
theorem witness_open_call_retains_retracted_clause :
    1 ∈ witnessCursor.remaining.map (fun entry => entry.id) := by
  decide

/-- Retraction after open does not remove the occurrence already frozen in
the actual prepared token. -/
theorem witness_prepared_call_retains_retracted_clause :
    1 ∈ witnessPreparedCursor.remaining.map (fun branch => branch.sourceId) := by
  decide

/-- A nested call opened after both updates receives its own later generation,
not the enclosing call's generation. -/
theorem witness_nested_call_has_new_generation :
    (openCursor witnessAfterRetract 10 witnessRequest).callGeneration =
        witnessAfterRetract.generation ∧
      witnessCursor.callGeneration < witnessAfterRetract.generation := by
  decide

/-- The actual prepared protocol also snapshots a nested call at its own
later generation rather than inheriting the enclosing token's generation. -/
theorem witness_prepared_nested_call_has_new_generation :
    (prepareCall
      { database := witnessAfterRetract, nextFresh := 10 }
      witnessRequest).1.callGeneration = witnessAfterRetract.generation ∧
    witnessPreparedCursor.callGeneration < witnessAfterRetract.generation := by
  decide

/-! ### Eager-reservation anti-vacuity witness -/

def freshWitnessClause (name : String) : LocalClause where
  predicate := "fresh_p"
  arguments := [.variable (.source name)]
  body := []

def freshWitnessDatabase : Database :=
  (Database.empty.assertz (freshWitnessClause "left")).assertz
    (freshWitnessClause "right")

def freshWitnessRequest : CallRequest where
  predicate := "fresh_p"
  arguments := [.atom "value"]
  bindings := []

def freshWitnessSession : LocalSession :=
  { database := freshWitnessDatabase, nextFresh := 10 }

def freshOuterPrepared : PreparedCursor × LocalSession :=
  prepareCall freshWitnessSession freshWitnessRequest

def freshNestedPrepared : PreparedCursor × LocalSession :=
  prepareCall freshOuterPrepared.2 freshWitnessRequest

/-- Eager reservation assigns both retained outer clauses before the nested
call starts.  The concrete intervals make the non-collision theorem visibly
non-vacuous. -/
theorem witness_eager_reservation_precedes_nested_call :
    freshOuterPrepared.1.remaining.map
        (fun branch => (branch.firstFresh, branch.nextFresh)) =
      [(10, 11), (11, 12)] ∧
    freshOuterPrepared.2.nextFresh = 12 ∧
    freshNestedPrepared.1.remaining.map
        (fun branch => (branch.firstFresh, branch.nextFresh)) =
      [(12, 13), (13, 14)] := by
  decide

/-- Foil state after a lazy cursor has standardized only its first clause. -/
def wrongLazyAfterFirst : ClauseCursor :=
  match pullBranch (openCursor freshWitnessDatabase 10 freshWitnessRequest) with
  | none => openCursor freshWitnessDatabase 10 freshWitnessRequest
  | some (_, next) => next

/-- The retained second clause under the deliberately wrong lazy design. -/
def wrongLazySecondBranch : ClauseBranch :=
  match pullBranch wrongLazyAfterFirst with
  | none => default
  | some (branch, _) => branch

/-- A nested call opened from the lazy cursor's premature high-water. -/
def wrongLazyNestedPrepared : PreparedCursor × LocalSession :=
  prepareCall
    { database := freshWitnessDatabase
      nextFresh := wrongLazyAfterFirst.freshSeed }
    freshWitnessRequest

/-- The old lazy design really collides: the retained outer second clause and
the nested call both allocate generated variable 11.  This counterexample is
why `semanticLocalClauseProtocol` exposes only `PreparedCursor`. -/
theorem witness_wrong_lazy_freshening_collides :
    wrongLazySecondBranch.firstFresh = 11 ∧
    wrongLazyNestedPrepared.1.remaining.head!.firstFresh = 11 := by
  decide

/-! ### Cursor-step-level live-view discriminator -/

/-- Foil cursor that remembers only how many entries it has consumed and
re-queries the live database on every pull.  It is deliberately not used by
the reference resolver. -/
structure LiveViewCursor where
  predicate : String
  arity : Nat
  consumed : Nat
deriving Repr, Inhabited

/-- One step of the deliberately wrong live-view resolver. -/
def pullLiveView (database : Database) (cursor : LiveViewCursor) :
    Option (VersionedClause × LiveViewCursor) :=
  match (database.liveViewClauses cursor.predicate cursor.arity).drop
      cursor.consumed with
  | [] => none
  | entry :: _ => some (entry, { cursor with consumed := cursor.consumed + 1 })

/-- Snapshot cursor after consuming both clauses that existed at call start. -/
def witnessCursorAfterTwo : ClauseCursor :=
  match pullBranch witnessCursor with
  | none => witnessCursor
  | some (_, afterFirst) =>
      match pullBranch afterFirst with
      | none => afterFirst
      | some (_, afterSecond) => afterSecond

/-- The correct snapshot stepper is exhausted after its two original
occurrences, even though the live database has since grown. -/
theorem witness_snapshot_stepper_exhausted_after_assert :
    pullBranch witnessCursorAfterTwo = none := by
  decide

/-- On the identical post-assert database, the wrong stepper emits the late
clause instead of exhaustion.  This lifts the anti-vacuity witness from
candidate-set inequality to an actual cursor transition. -/
theorem witness_wrong_stepper_emits_late_clause :
    ∃ entry next,
      pullLiveView witnessAfterAssert
          { predicate := "p", arity := 1, consumed := 2 } =
        some (entry, next) ∧
      entry.id = 2 := by
  refine ⟨(witnessAfterAssert.liveViewClauses "p" 1)[2]!,
    { predicate := "p", arity := 1, consumed := 3 }, ?_, ?_⟩
  · rfl
  · rfl

end PLeaTTa.PeTTaSpec.PrologCore.Resolver
