/-
Module: PLeaTTa.PeTTaSpec.PrologResolver
Purpose: Independent logical-update-aware clause store and ordered local-call
  cursor for the Prolog fragment generated by pinned PeTTa.
Trusted boundary: none
Main exports: Database, CallRequest, ClauseCursor, openCursor, pullBranch
-/
import PLeaTTa.PeTTaSpec.OpenSubstitution
import PLeaTTa.PeTTaSpec.PrologTraceSemantics
import PLeaTTa.PeTTaSpec.PrologMgu

namespace PLeaTTa.PeTTaSpec.PrologCore.Resolver

open OpenSubstitution
open Canonical

/-!
This is the database-and-clause-selection half of the certified local
resolver.  It is independent of PLeaTTa's executable `PWorld`, `Clause`,
`resolveAlts`, and `Step` definitions.

Pinned PeTTa delegates ordinary definite-clause calls to SWI-Prolog.  SWI's
logical update view tags a call with the database generation at which it
starts and exposes exactly the clauses whose creation/erasure interval
contains that generation.  The executable PLeaTTa machine currently realizes
the same shape by materializing its ordered alternatives at call entry.  This
module states the source-side rule directly: a cursor owns an immutable
ordered snapshot, not a pointer back into the live database.

Fresh standardization-apart and source-order clause entry are performed by
`pullBranch`; head MGU construction and execution of the leftmost clause body
are the next layer.  No raw cursor pull bypasses freshening, so scheduling and
answer order cannot silently move into an oracle.

[SPEC SWI-Prolog manual 4.14.1.1, logical update view]
[SPEC metta.pl:251-256, left-to-right `call_goals/1`]
-/

/-- Monotone logical-update generation. -/
abbrev Generation := Nat

/-- Stable identity of one asserted clause occurrence.  Duplicate clauses
remain distinct occurrences and therefore retain their multiplicity. -/
abbrev ClauseId := Nat

/-- One independent definite clause.  The output argument of a PeTTa
function is an ordinary final Prolog head argument here; it is not given a
special semantic status. -/
structure LocalClause where
  predicate : String
  arguments : List Term
  body : List Goal
deriving Repr, Inhabited

/-- A historical clause occurrence.  `erased = none` means that no erasure
generation has yet been recorded.  Erased occurrences stay in history so a
cursor opened before retraction can continue to use them. -/
structure VersionedClause where
  id : ClauseId
  clause : LocalClause
  created : Generation
  erased : Option Generation := none
deriving Repr, Inhabited

/-- The ISO/SWI visibility interval: creation is inclusive and erasure is
exclusive. -/
def VersionedClause.VisibleAt (entry : VersionedClause)
    (generation : Generation) : Prop :=
  entry.created ≤ generation ∧
    match entry.erased with
    | none => True
    | some erased => generation < erased

/-- Computable presentation of `VisibleAt`, used only to filter the finite
history. -/
def VersionedClause.visibleAt (entry : VersionedClause)
    (generation : Generation) : Bool :=
  entry.created ≤ generation &&
    match entry.erased with
    | none => true
    | some erased => generation < erased

@[simp] theorem VersionedClause.visibleAt_eq_true_iff
    (entry : VersionedClause) (generation : Generation) :
    entry.visibleAt generation = true ↔ entry.VisibleAt generation := by
  cases erased : entry.erased <;>
    simp [VersionedClause.visibleAt, VersionedClause.VisibleAt, erased]

/-- Independent dynamic clause history in source order.  `asserta` prepends
and `assertz` appends.  Retraction marks an occurrence rather than deleting
it, which is the key representation invariant behind logical-update cursors.
-/
structure Database where
  generation : Generation := 0
  nextId : ClauseId := 0
  history : List VersionedClause := []
deriving Repr, Inhabited

/-- Empty dynamic program. -/
def Database.empty : Database := {}

/-- Allocate the next clause occurrence at the next database generation. -/
def Database.allocate (database : Database) (clause : LocalClause) :
    VersionedClause :=
  { id := database.nextId
    clause := clause
    created := database.generation + 1 }

/-- Append one clause occurrence.  [SPEC metta.pl:277] -/
def Database.assertz (database : Database) (clause : LocalClause) : Database :=
  let entry := database.allocate clause
  { generation := database.generation + 1
    nextId := database.nextId + 1
    history := database.history ++ [entry] }

/-- Prepend one clause occurrence.  [SPEC metta.pl:278] -/
def Database.asserta (database : Database) (clause : LocalClause) : Database :=
  let entry := database.allocate clause
  { generation := database.generation + 1
    nextId := database.nextId + 1
    history := entry :: database.history }

/-- Mark the first live occurrence with the requested identity.  Failure is
represented by `none`; it is not an exception and does not fabricate a new
generation. -/
def retireFirst (generation : Generation) (id : ClauseId) :
    List VersionedClause → Option (List VersionedClause)
  | [] => none
  | entry :: rest =>
      if entry.id = id ∧ entry.erased = none then
        some ({ entry with erased := some generation } :: rest)
      else
        (retireFirst generation id rest).map (entry :: ·)

/-- Retract one identified live occurrence.  The successful update advances
the generation; failure leaves the caller with no successor database.
The source-level `retract/1` relation still has to select the first unifying
content occurrence and expose later matches on backtracking; this identity
primitive does not claim to discharge that MGU/control obligation.
[SPEC metta.pl:279-280] -/
def Database.retractId (database : Database) (id : ClauseId) :
    Option Database :=
  let nextGeneration := database.generation + 1
  match retireFirst nextGeneration id database.history with
  | none => none
  | some history =>
      some { database with generation := nextGeneration, history := history }

/-- Clause occurrences visible to one call, preserving database order and
duplicate multiplicity. -/
def Database.visibleClausesAt (database : Database)
    (generation : Generation) (predicate : String) (arity : Nat) :
    List VersionedClause :=
  database.history.filter fun entry =>
    entry.visibleAt generation &&
      entry.clause.predicate == predicate &&
      entry.clause.arguments.length == arity

/-- The deliberately wrong live-view candidate function.  It exists only for
anti-vacuity witnesses: recomputing at the current generation after every
world update allows a running call to observe newly asserted clauses. -/
def Database.liveViewClauses (database : Database)
    (predicate : String) (arity : Nat) : List VersionedClause :=
  database.visibleClausesAt database.generation predicate arity

/-- Typed request to open a locally owned predicate.  The current open
substitution is carried separately from clause selection; it will be used by
the MGU layer when the fresh head is entered. -/
structure CallRequest where
  database : Database
  predicate : String
  arguments : List Term
  bindings : Substitution
  freshSeed : Nat
deriving Repr, Inhabited

/-- Ordered, immutable clause snapshot for one dynamic call. -/
structure ClauseCursor where
  callGeneration : Generation
  predicate : String
  arguments : List Term
  bindings : Substitution
  remaining : List VersionedClause
  freshSeed : Nat
deriving Repr, Inhabited

/-- Open a call exactly once at the database's current generation. -/
def openCursor (request : CallRequest) : ClauseCursor :=
  { callGeneration := request.database.generation
    predicate := request.predicate
    arguments := request.arguments
    bindings := request.bindings
    remaining := request.database.visibleClausesAt
      request.database.generation request.predicate request.arguments.length
    freshSeed := request.freshSeed }

@[simp] theorem openCursor_callGeneration (request : CallRequest) :
    (openCursor request).callGeneration = request.database.generation := rfl

@[simp] theorem openCursor_remaining (request : CallRequest) :
    (openCursor request).remaining =
      request.database.visibleClausesAt request.database.generation
        request.predicate request.arguments.length := rfl

/-- Candidate selection deletes entries only; hence it cannot reorder source
clauses or deduplicate equal occurrences. -/
theorem visibleClausesAt_sublist_history (database : Database)
    (generation : Generation) (predicate : String) (arity : Nat) :
    List.Sublist (database.visibleClausesAt generation predicate arity)
      database.history :=
  List.filter_sublist

/-- A clause asserted after `generation` is invisible at that older
generation. -/
@[simp] theorem Database.allocate_not_visible_at_current
    (database : Database) (clause : LocalClause) :
    (database.allocate clause).visibleAt database.generation = false := by
  simp [Database.allocate, VersionedClause.visibleAt]

/-- `assertz` cannot retroactively change the ordered view at the preceding
generation. -/
theorem Database.assertz_old_view (database : Database) (clause : LocalClause)
    (predicate : String) (arity : Nat) :
    (database.assertz clause).visibleClausesAt database.generation
        predicate arity =
      database.visibleClausesAt database.generation predicate arity := by
  simp [Database.assertz, Database.visibleClausesAt]

/-- `asserta` likewise cannot retroactively insert a clause into an already
started call. -/
theorem Database.asserta_old_view (database : Database) (clause : LocalClause)
    (predicate : String) (arity : Nat) :
    (database.asserta clause).visibleClausesAt database.generation
        predicate arity =
      database.visibleClausesAt database.generation predicate arity := by
  simp [Database.asserta, Database.visibleClausesAt]

/-! ## Standardization apart and clause-entry branches -/

mutual

/-- Variables in one independent term, in occurrence order. -/
def termVariables : Term → List LogicVar
  | .variable identity => [identity]
  | .atom _ => []
  | .integer _ => []
  | .float _ => []
  | .string _ => []
  | .compound _ arguments => termsVariables arguments
  | .list items none => termsVariables items
  | .list items (some tail) => termsVariables items ++ termVariables tail

/-- Variables in an ordered term sequence, in occurrence order. -/
def termsVariables : List Term → List LogicVar
  | [] => []
  | term :: terms => termVariables term ++ termsVariables terms

end

mutual

/-- Variables in one independent goal, in left-to-right syntax order. -/
def goalVariables : Goal → List LogicVar
  | .truth => []
  | .fail => []
  | .unify left right => termVariables left ++ termVariables right
  | .identical left right => termVariables left ++ termVariables right
  | .call _ arguments => termsVariables arguments
  | .conjunction goals => goalsVariables goals
  | .disjunction branches => goalsVariables branches
  | .cut => []
  | .ifThenElse condition thenBranch elseBranch =>
      goalVariables condition ++ goalVariables thenBranch ++
        goalVariables elseBranch
  | .softCut condition thenBranch elseBranch =>
      goalVariables condition ++ goalVariables thenBranch ++
        goalVariables elseBranch
  | .negation goal => goalVariables goal
  | .once goal => goalVariables goal
  | .findall template goal output =>
      termVariables template ++ goalVariables goal ++ termVariables output
  | .catch goal exception handler =>
      goalVariables goal ++ termVariables exception ++ goalVariables handler
  | .transaction goal => goalVariables goal
  | .withMutex mutex goal => termVariables mutex ++ goalVariables goal
  | .forall generator test => goalVariables generator ++ goalVariables test

/-- Variables in an ordered goal sequence, in occurrence order. -/
def goalsVariables : List Goal → List LogicVar
  | [] => []
  | goal :: goals => goalVariables goal ++ goalsVariables goals

end

/-- Distinct clause-local variables in stable first-occurrence order. -/
def LocalClause.variables (clause : LocalClause) : List LogicVar :=
  (termsVariables clause.arguments ++ goalsVariables clause.body).eraseDups

/-- One past a translator-generated variable index.  Source and anonymous
identities occupy disjoint namespaces and therefore impose no lower bound on
the generated namespace. -/
def logicVarGeneratedCeiling : LogicVar → Nat
  | .source _ => 0
  | .anonymous _ => 0
  | .generated index => index + 1

/-- A finite set's exclusive upper bound in the generated namespace. -/
def variablesGeneratedCeiling (variables : List LogicVar) : Nat :=
  variables.foldl (fun ceiling identity =>
    max ceiling (logicVarGeneratedCeiling identity)) 0

def LocalClause.generatedCeiling (clause : LocalClause) : Nat :=
  variablesGeneratedCeiling clause.variables

/-- Build a stable variable renaming into consecutive fresh generated
identities.  The caller chooses a start above both the live query and the
stored clause's generated-variable ceilings. -/
def buildFreshening : Nat → List LogicVar → Substitution × Nat
  | seed, [] => ([], seed)
  | seed, identity :: variables =>
      let tail := buildFreshening (seed + 1) variables
      ((identity, .variable (.generated seed)) :: tail.1, tail.2)

/-- The freshening counter advances once per distinct clause variable. -/
theorem buildFreshening_next (seed : Nat) (variables : List LogicVar) :
    (buildFreshening seed variables).2 = seed + variables.length := by
  induction variables generalizing seed with
  | nil => rfl
  | cons identity variables induction =>
      simp only [buildFreshening, List.length_cons]
      rw [induction]
      omega

/-- Freshening retains one binding per distinct source variable. -/
theorem buildFreshening_length (seed : Nat) (variables : List LogicVar) :
    (buildFreshening seed variables).1.length = variables.length := by
  induction variables generalizing seed with
  | nil => rfl
  | cons identity variables induction =>
      simp [buildFreshening, induction]

/-- Every target allocated by `buildFreshening` lies in its advertised
half-open interval.  This turns counter arithmetic into a statement about
the actual variables consumed later by unification. -/
theorem buildFreshening_target_range (seed : Nat) (variables : List LogicVar)
    {source : LogicVar} {index : Nat}
    (member : (source, .variable (.generated index)) ∈
      (buildFreshening seed variables).1) :
    seed ≤ index ∧ index < seed + variables.length := by
  induction variables generalizing seed with
  | nil => simp [buildFreshening] at member
  | cons identity variables induction =>
      simp only [buildFreshening] at member
      rcases List.mem_cons.mp member with first | later
      · have sameIndex : index = seed := by
          have targetEquality := congrArg Prod.snd first
          simpa using targetEquality
        subst index
        simp
      · have range := induction (seed := seed + 1) later
        simp only [List.length_cons]
        constructor <;> omega

/-- Every freshening target is generated; together with
`buildFreshening_target_range` this characterizes the allocation rather than
merely counting it. -/
theorem buildFreshening_target_generated (seed : Nat)
    (variables : List LogicVar) {source : LogicVar} {target : Term}
    (member : (source, target) ∈ (buildFreshening seed variables).1) :
    ∃ index, target = .variable (.generated index) ∧
      seed ≤ index ∧ index < seed + variables.length := by
  induction variables generalizing seed with
  | nil => simp [buildFreshening] at member
  | cons identity variables induction =>
      simp only [buildFreshening] at member
      rcases List.mem_cons.mp member with first | later
      · refine ⟨seed, ?_, by simp⟩
        exact congrArg Prod.snd first
      · obtain ⟨index, targetShape, lower, upper⟩ :=
          induction (seed := seed + 1) later
        refine ⟨index, targetShape, ?_, ?_⟩
        · omega
        · simp only [List.length_cons]
          omega

/-- A generated namespace is live below `seed` when every generated identity
occurring in the finite syntax has a strictly smaller index. -/
def GeneratedBelow (seed : Nat) (variables : List LogicVar) : Prop :=
  ∀ index, .generated index ∈ variables → index < seed

theorem GeneratedBelow.mono {smaller larger : Nat} {variables : List LogicVar}
    (below : GeneratedBelow smaller variables) (ordered : smaller ≤ larger) :
    GeneratedBelow larger variables := by
  intro index member
  exact Nat.lt_of_lt_of_le (below index member) ordered

/-- Variables carried by an open substitution, including its domain. -/
def substitutionVariables : Substitution → List LogicVar
  | [] => []
  | (source, value) :: bindings =>
      source :: termVariables value ++ substitutionVariables bindings

/-- The call allocator starts above every generated identity already live in
the query and its carried substitution. -/
def CallRequest.FreshSeedDominates (request : CallRequest) : Prop :=
  GeneratedBelow request.freshSeed
    (termsVariables request.arguments ++
      substitutionVariables request.bindings)

/-- Cursor presentation of the same global allocator invariant. -/
def ClauseCursor.FreshSeedDominates (cursor : ClauseCursor) : Prop :=
  GeneratedBelow cursor.freshSeed
    (termsVariables cursor.arguments ++
      substitutionVariables cursor.bindings)

theorem openCursor_freshSeedDominates {request : CallRequest}
    (dominates : request.FreshSeedDominates) :
    (openCursor request).FreshSeedDominates := by
  exact dominates

/-- Data retained for the adequacy bridge: the exact simultaneous renaming,
the standardized clause, and its half-open fresh-index interval. -/
structure FreshClause where
  freshSubstitution : Substitution
  clause : LocalClause
  firstFresh : Nat
  nextFresh : Nat
deriving Repr, Inhabited

/-- Standardize every variable of a stored clause apart.  `max` prevents a
stored translator-generated variable from becoming one of its own targets;
the cursor's `freshSeed` is separately required to dominate the live query.
-/
def LocalClause.freshCopy (clause : LocalClause) (freshSeed : Nat) :
    FreshClause :=
  let firstFresh := max freshSeed clause.generatedCeiling
  let built := buildFreshening firstFresh clause.variables
  { freshSubstitution := built.1
    clause :=
      { predicate := clause.predicate
        arguments := built.1.applyTerms clause.arguments
        body := built.1.applyGoals clause.body }
    firstFresh := firstFresh
    nextFresh := built.2 }

@[simp] theorem LocalClause.freshCopy_predicate
    (clause : LocalClause) (freshSeed : Nat) :
    (clause.freshCopy freshSeed).clause.predicate = clause.predicate := rfl

theorem LocalClause.freshCopy_first_ge_seed
    (clause : LocalClause) (freshSeed : Nat) :
    freshSeed ≤ (clause.freshCopy freshSeed).firstFresh := by
  exact Nat.le_max_left _ _

theorem LocalClause.freshCopy_first_ge_clause
    (clause : LocalClause) (freshSeed : Nat) :
    clause.generatedCeiling ≤ (clause.freshCopy freshSeed).firstFresh := by
  exact Nat.le_max_right _ _

theorem LocalClause.freshCopy_next
    (clause : LocalClause) (freshSeed : Nat) :
    (clause.freshCopy freshSeed).nextFresh =
      (clause.freshCopy freshSeed).firstFresh + clause.variables.length := by
  simp only [LocalClause.freshCopy]
  exact buildFreshening_next _ _

/-- Pointwise head equations.  Equal arity is guaranteed by
`visibleClausesAt`; the fallback cases make malformed pairs explicitly clash
with the reserved `$missing` atom instead of silently truncating them. -/
def argumentEquations : List Term → List Term → List (Term × Term)
  | [], [] => []
  | left :: leftRest, right :: rightRest =>
      (left, right) :: argumentEquations leftRest rightRest
  | leftRest, [] => leftRest.map (fun left => (left, .atom "$missing"))
  | [], rightRest => rightRest.map (fun right => (.atom "$missing", right))

/-- Turn the ordered head equations into the actual leftmost equality prefix.
-/
def equationsToGoals (equations : List (Term × Term)) : List Goal :=
  equations.map fun equation => .unify equation.1 equation.2

/-- One source-ordered clause entry, ready for leftmost MGU/body execution. -/
structure ClauseBranch where
  sourceId : ClauseId
  callGeneration : Generation
  freshSubstitution : Substitution
  headEquations : List (Term × Term)
  body : List Goal
  bindings : Substitution
  firstFresh : Nat
  nextFresh : Nat
deriving Repr, Inhabited

/-- Clause entry always executes head unification before the body. -/
def ClauseBranch.goals (branch : ClauseBranch) : List Goal :=
  equationsToGoals branch.headEquations ++ branch.body

/-- Pull and standardize exactly one clause.  Head equalities precede the
body, matching Prolog clause entry; the next clause remains frozen in the
cursor and receives a disjoint fresh interval. -/
def pullBranch (cursor : ClauseCursor) :
    Option (ClauseBranch × ClauseCursor) :=
  match cursor.remaining with
  | [] => none
  | entry :: rest =>
      let copied := entry.clause.freshCopy cursor.freshSeed
      let branch : ClauseBranch :=
        { sourceId := entry.id
          callGeneration := cursor.callGeneration
          freshSubstitution := copied.freshSubstitution
          headEquations :=
            argumentEquations cursor.arguments copied.clause.arguments
          body := copied.clause.body
          bindings := cursor.bindings
          firstFresh := copied.firstFresh
          nextFresh := copied.nextFresh }
      let next := { cursor with
        remaining := rest
        freshSeed := copied.nextFresh }
      some (branch, next)

@[simp] theorem pullBranch_none_iff (cursor : ClauseCursor) :
    pullBranch cursor = none ↔ cursor.remaining = [] := by
  cases remaining : cursor.remaining <;> simp [pullBranch, remaining]

/-- A successful standardized pull consumes precisely the snapshot head and
preserves every call-start field.  The sole evolving fields are the ordered
tail and the global fresh counter. -/
theorem pullBranch_exact {cursor next : ClauseCursor}
    {branch : ClauseBranch}
    (pulled : pullBranch cursor = some (branch, next)) :
    ∃ entry rest,
      cursor.remaining = entry :: rest ∧
      branch.sourceId = entry.id ∧
      branch.callGeneration = cursor.callGeneration ∧
      next.remaining = rest ∧
      next.callGeneration = cursor.callGeneration ∧
      next.predicate = cursor.predicate ∧
      next.arguments = cursor.arguments ∧
      next.bindings = cursor.bindings ∧
      next.freshSeed = branch.nextFresh := by
  cases remaining : cursor.remaining with
  | nil => simp [pullBranch, remaining] at pulled
  | cons entry rest =>
      simp only [pullBranch, remaining, Option.some.injEq, Prod.mk.injEq]
        at pulled
      rcases pulled with ⟨rfl, rfl⟩
      exact ⟨entry, rest, rfl, rfl, rfl, rfl, rfl, rfl, rfl, rfl, rfl⟩

/-- Clause entry is leftmost: every head equation precedes every body goal. -/
theorem pullBranch_goals_shape {cursor next : ClauseCursor}
    {branch : ClauseBranch} {entry : VersionedClause}
    {rest : List VersionedClause}
    (remaining : cursor.remaining = entry :: rest)
    (pulled : pullBranch cursor = some (branch, next)) :
    let copied := entry.clause.freshCopy cursor.freshSeed
    branch.goals =
        equationsToGoals
            (argumentEquations cursor.arguments copied.clause.arguments) ++
          copied.clause.body ∧
      branch.sourceId = entry.id ∧
      branch.callGeneration = cursor.callGeneration ∧
      next.remaining = rest ∧
      next.freshSeed = copied.nextFresh := by
  simp only [pullBranch, remaining, Option.some.injEq, Prod.mk.injEq] at pulled
  rcases pulled with ⟨rfl, rfl⟩
  simp [ClauseBranch.goals]

/-- Fresh intervals allocated to successive clause entries do not overlap. -/
theorem pullBranch_fresh_monotone {cursor next : ClauseCursor}
    {branch : ClauseBranch}
    (pulled : pullBranch cursor = some (branch, next)) :
    cursor.freshSeed ≤ branch.firstFresh ∧
      branch.firstFresh ≤ branch.nextFresh ∧
      next.freshSeed = branch.nextFresh := by
  cases remaining : cursor.remaining with
  | nil => simp [pullBranch, remaining] at pulled
  | cons entry rest =>
      simp only [pullBranch, remaining, Option.some.injEq, Prod.mk.injEq]
        at pulled
      rcases pulled with ⟨rfl, rfl⟩
      constructor
      · exact entry.clause.freshCopy_first_ge_seed cursor.freshSeed
      · constructor
        · rw [entry.clause.freshCopy_next]
          exact Nat.le_add_right _ _
        · rfl

/-- Two successive clause copies receive disjoint, monotonically ordered
fresh intervals.  This rules out the retry/cross-clause aliasing bug that a
constant per-call seed would introduce. -/
theorem pullBranch_successive_fresh_disjoint
    {start middle finish : ClauseCursor}
    {first second : ClauseBranch}
    (pulledFirst : pullBranch start = some (first, middle))
    (pulledSecond : pullBranch middle = some (second, finish)) :
    first.nextFresh ≤ second.firstFresh := by
  have firstFacts := pullBranch_fresh_monotone pulledFirst
  have secondFacts := pullBranch_fresh_monotone pulledSecond
  rw [← firstFacts.2.2]
  exact secondFacts.1

/-- The advertised interval describes every actual target in a pulled
clause's standardization-apart substitution. -/
theorem pullBranch_fresh_target_generated
    {cursor next : ClauseCursor} {branch : ClauseBranch}
    (pulled : pullBranch cursor = some (branch, next))
    {source : LogicVar} {target : Term}
    (member : (source, target) ∈ branch.freshSubstitution) :
    ∃ index, target = .variable (.generated index) ∧
      branch.firstFresh ≤ index ∧ index < branch.nextFresh := by
  cases remaining : cursor.remaining with
  | nil => simp [pullBranch, remaining] at pulled
  | cons entry rest =>
      simp only [pullBranch, remaining, Option.some.injEq, Prod.mk.injEq]
        at pulled
      rcases pulled with ⟨rfl, rfl⟩
      simpa [LocalClause.freshCopy, buildFreshening_next] using
        (buildFreshening_target_generated
          (max cursor.freshSeed entry.clause.generatedCeiling)
          entry.clause.variables member)

/-- Pulling a source-ordered clause preserves the live-query allocation
invariant because it advances, but never lowers, the global fresh counter. -/
theorem pullBranch_preserves_freshSeedDominates
    {cursor next : ClauseCursor} {branch : ClauseBranch}
    (dominates : cursor.FreshSeedDominates)
    (pulled : pullBranch cursor = some (branch, next)) :
    next.FreshSeedDominates := by
  obtain ⟨entry, rest, remaining, source, branchGeneration, tail,
      generation, predicate, arguments, bindings, fresh⟩ :=
    pullBranch_exact pulled
  unfold ClauseCursor.FreshSeedDominates at dominates ⊢
  rw [arguments, bindings]
  apply dominates.mono
  have monotone := pullBranch_fresh_monotone pulled
  omega

/-- Under the explicit live-query invariant, no target allocated for the
selected clause can alias a generated variable already present in the call
arguments or carried substitution. -/
theorem pullBranch_fresh_target_not_live
    {cursor next : ClauseCursor} {branch : ClauseBranch}
    (dominates : cursor.FreshSeedDominates)
    (pulled : pullBranch cursor = some (branch, next))
    {source : LogicVar} {target : Term}
    (member : (source, target) ∈ branch.freshSubstitution) :
    ∃ index, target = .variable (.generated index) ∧
      .generated index ∉
        (termsVariables cursor.arguments ++
          substitutionVariables cursor.bindings) := by
  obtain ⟨index, targetShape, lower, upper⟩ :=
    pullBranch_fresh_target_generated pulled member
  refine ⟨index, targetShape, ?_⟩
  intro live
  have oldIndex := dominates index live
  have monotone := pullBranch_fresh_monotone pulled
  omega

/-! ## Semantic head resolution and the internal clause protocol -/

/-- Apply the carried open substitution to both sides of every head equation
before computing the next extension. -/
def ClauseBranch.normalizedHeadEquations (branch : ClauseBranch) :
    List (Term × Term) :=
  branch.headEquations.map fun equation =>
    (branch.bindings.applyTerm equation.1,
      branch.bindings.applyTerm equation.2)

/-- Semantic clause-head resolution.  `extension` must be an MGU of the
already-normalized head equations; prepending it to the carried state is the
new open substitution.  The extension is the exact canonical reification of
the deterministic ordered MGU derivation, so raw dotted-list presentation
cannot make clause entry nondeterministic. -/
def HeadResolution (branch : ClauseBranch) (result : Substitution) : Prop :=
  ∃ extension,
    ComputesDenotationalMgu branch.normalizedHeadEquations extension ∧
      result = extension ++ branch.bindings

/-- Canonical ordered MGU selection makes source-level clause-head
resolution functional, including the exact substitution spelling. -/
theorem HeadResolution.deterministic {branch : ClauseBranch}
    {first second : Substitution}
    (one : HeadResolution branch first)
    (two : HeadResolution branch second) : first = second := by
  rcases one with ⟨firstExtension, firstComputed, rfl⟩
  rcases two with ⟨secondExtension, secondComputed, rfl⟩
  exact congrArg (fun extension => extension ++ branch.bindings)
    (firstComputed.unique secondComputed)

/-- Any semantic unifier of the normalized clause head yields the unique
ordered head-resolution result. -/
theorem HeadResolution.exists_of_unifier {branch : ClauseBranch}
    (candidate : Substitution)
    (unifies : DenotationalUnifiesEquations candidate
      branch.normalizedHeadEquations) :
    ∃ result, HeadResolution branch result := by
  rcases ComputesDenotationalMgu.exists_of_unifier candidate unifies with
    ⟨extension, computed⟩
  exact ⟨extension ++ branch.bindings, extension, computed, rfl⟩

/-- Head resolution succeeds exactly when the normalized finite-tree
equations are unifiable. -/
theorem HeadResolution.exists_iff_unifiable {branch : ClauseBranch} :
    (∃ result, HeadResolution branch result) ↔
      ∃ candidate, DenotationalUnifiesEquations candidate
        branch.normalizedHeadEquations := by
  constructor
  · rintro ⟨result, extension, computed, resultEq⟩
    exact ⟨extension, computed.isMostGeneral.1⟩
  · rintro ⟨candidate, unifies⟩
    exact HeadResolution.exists_of_unifier candidate unifies

/-- Every semantic head resolution genuinely unifies every raw head equation
after composition with the carried state. -/
theorem HeadResolution.unifies {branch : ClauseBranch}
    {result : Substitution} (resolution : HeadResolution branch result) :
    DenotationalUnifiesEquations result branch.headEquations := by
  rcases resolution with ⟨extension, computed, rfl⟩
  have mostGeneral := computed.isMostGeneral
  intro equation member
  have normalizedMember :
      (branch.bindings.applyTerm equation.1,
          branch.bindings.applyTerm equation.2) ∈
        branch.normalizedHeadEquations := by
    exact List.mem_map_of_mem member
  have unifies := mostGeneral.1 _ normalizedMember
  unfold DenotationalUnifier at unifies ⊢
  simpa [Canonical.Substitution.denote_append,
    TreeSubstitution.apply_append,
    Canonical.Substitution.denote_applyTerm] using unifies

/-- With no carried constraints, head resolution itself is an MGU of the raw
head equations. -/
theorem HeadResolution.isMostGeneral_of_empty {branch : ClauseBranch}
    {result : Substitution} (empty : branch.bindings = [])
    (resolution : HeadResolution branch result) :
    IsDenotationalMgu result branch.headEquations := by
  rcases resolution with ⟨extension, computed, resultEq⟩
  have mostGeneral := computed.isMostGeneral
  have normalized : branch.normalizedHeadEquations = branch.headEquations := by
    simp [ClauseBranch.normalizedHeadEquations, empty]
  have resultIsExtension : result = extension := by
    simpa [empty] using resultEq
  rw [resultIsExtension]
  rw [normalized] at mostGeneral
  exact mostGeneral

/-- A successfully entered clause after its head equations have been
consumed.  The body remains left-to-right, instantiated by the new MGU state.
-/
structure EnteredClause where
  sourceId : ClauseId
  callGeneration : Generation
  bindings : Substitution
  body : List Goal
  nextFresh : Nat
deriving Repr, Inhabited

def ClauseBranch.enter (branch : ClauseBranch) (bindings : Substitution) :
    EnteredClause :=
  { sourceId := branch.sourceId
    callGeneration := branch.callGeneration
    bindings := bindings
    body := bindings.applyGoals branch.body
    nextFresh := branch.nextFresh }

/-- One demand on the internal clause cursor.  A non-unifying clause is one
silent step; a unifying clause yields one entered body; exhaustion is distinct
from both.  Effects and exceptions arise only while executing the yielded
body, not while choosing a clause occurrence. -/
inductive LocalPull : ClauseCursor →
    Trace.PullResult ClauseCursor EnteredClause Empty Empty → Prop where
  | matched (cursor next : ClauseCursor) (branch : ClauseBranch)
      (result : Substitution)
      (pulled : pullBranch cursor = some (branch, next))
      (resolved : HeadResolution branch result) :
      LocalPull cursor (.answer (branch.enter result) next)
  | rejected (cursor next : ClauseCursor) (branch : ClauseBranch)
      (pulled : pullBranch cursor = some (branch, next))
      (clash : ¬ ∃ result, HeadResolution branch result) :
      LocalPull cursor (.silent next)
  | exhausted (cursor : ClauseCursor) (done : cursor.remaining = []) :
      LocalPull cursor .exhausted

/-- Every clause cursor has a next demand result.  The only classical split
is whether the finite normalized head equations have a unifier; completeness
above turns any such witness into the unique canonical MGU. -/
theorem LocalPull.total (cursor : ClauseCursor) :
    ∃ outcome, LocalPull cursor outcome := by
  cases pulled : pullBranch cursor with
  | none =>
      have done := (pullBranch_none_iff cursor).mp pulled
      exact ⟨.exhausted, .exhausted cursor done⟩
  | some pair =>
      rcases pair with ⟨branch, next⟩
      by_cases resolves : ∃ result, HeadResolution branch result
      · rcases resolves with ⟨result, resolved⟩
        exact ⟨.answer (branch.enter result) next,
          .matched cursor next branch result pulled resolved⟩
      · exact ⟨.silent next,
          .rejected cursor next branch pulled resolves⟩

/-- One cursor demand has exactly one ordered result: clause selection is a
function, canonical head resolution is functional, and match/reject/exhaust
cases are disjoint. -/
theorem LocalPull.deterministic {cursor : ClauseCursor}
    {first second : Trace.PullResult ClauseCursor EnteredClause Empty Empty}
    (one : LocalPull cursor first) (two : LocalPull cursor second) :
    first = second := by
  cases one with
  | matched nextOne branchOne resultOne pulledOne resolvedOne =>
      cases two with
      | matched nextTwo branchTwo resultTwo pulledTwo resolvedTwo =>
          have pairEquality : (branchOne, nextOne) =
              (branchTwo, nextTwo) :=
            Option.some.inj (pulledOne.symm.trans pulledTwo)
          have branchEquality : branchOne = branchTwo := by
            simpa using congrArg Prod.fst pairEquality
          have nextEquality : nextOne = nextTwo := by
            simpa using congrArg Prod.snd pairEquality
          subst branchTwo
          subst nextTwo
          have resultEquality := resolvedOne.deterministic resolvedTwo
          subst resultTwo
          rfl
      | rejected nextTwo branchTwo pulledTwo clash =>
          have pairEquality : (branchOne, nextOne) =
              (branchTwo, nextTwo) :=
            Option.some.inj (pulledOne.symm.trans pulledTwo)
          have branchEquality : branchOne = branchTwo := by
            simpa using congrArg Prod.fst pairEquality
          subst branchTwo
          exact False.elim (clash ⟨resultOne, resolvedOne⟩)
      | exhausted done =>
          have noPull := (pullBranch_none_iff cursor).mpr done
          rw [noPull] at pulledOne
          cases pulledOne
  | rejected nextOne branchOne pulledOne clashOne =>
      cases two with
      | matched nextTwo branchTwo resultTwo pulledTwo resolvedTwo =>
          have pairEquality : (branchOne, nextOne) =
              (branchTwo, nextTwo) :=
            Option.some.inj (pulledOne.symm.trans pulledTwo)
          have branchEquality : branchOne = branchTwo := by
            simpa using congrArg Prod.fst pairEquality
          subst branchTwo
          exact False.elim (clashOne ⟨resultTwo, resolvedTwo⟩)
      | rejected nextTwo branchTwo pulledTwo clashTwo =>
          have pairEquality : (branchOne, nextOne) =
              (branchTwo, nextTwo) :=
            Option.some.inj (pulledOne.symm.trans pulledTwo)
          have nextEquality : nextOne = nextTwo := by
            simpa using congrArg Prod.snd pairEquality
          subst nextTwo
          rfl
      | exhausted done =>
          have noPull := (pullBranch_none_iff cursor).mpr done
          rw [noPull] at pulledOne
          cases pulledOne
  | exhausted doneOne =>
      cases two with
      | matched nextTwo branchTwo resultTwo pulledTwo resolvedTwo =>
          have noPull := (pullBranch_none_iff cursor).mpr doneOne
          rw [noPull] at pulledTwo
          cases pulledTwo
      | rejected nextTwo branchTwo pulledTwo clashTwo =>
          have noPull := (pullBranch_none_iff cursor).mpr doneOne
          rw [noPull] at pulledTwo
          cases pulledTwo
      | exhausted doneTwo => rfl

/-- Certified internal stream of source-ordered clause bodies.  This is not
the final user-answer protocol: the control layer must bind each yielded body
to the leftmost Goal interpreter.  Imported SWI calls remain a different,
trusted protocol instance. -/
def semanticLocalClauseProtocol :
    Trace.OrderedCallProtocol CallRequest ClauseCursor EnteredClause Empty Empty
    where
  openCall := fun request cursor => cursor = openCursor request
  pull := LocalPull
  prune := fun _ => True

/-- Opening the internal local protocol is functional and fixes the call-start
snapshot. -/
theorem semanticLocalClauseProtocol_open_unique
    {request : CallRequest} {first second : ClauseCursor}
    (one : semanticLocalClauseProtocol.openCall request first)
    (two : semanticLocalClauseProtocol.openCall request second) :
    first = second := by
  exact one.trans two.symm

/-- A yielded local branch inherits the exact call generation and advanced
fresh counter of the certified clause pull. -/
theorem LocalPull.answer_origin
    {cursor next : ClauseCursor} {entered : EnteredClause}
    (pulled : LocalPull cursor (.answer entered next)) :
    entered.callGeneration = cursor.callGeneration ∧
      next.freshSeed = entered.nextFresh := by
  cases pulled with
  | matched next branch result branchPull resolved =>
      obtain ⟨entry, rest, remaining, source, branchGeneration, tail,
          generation, predicate, arguments, bindings, fresh⟩ :=
        pullBranch_exact branchPull
      exact ⟨branchGeneration, fresh⟩

/-! ### MGU anti-vacuity witnesses -/

def variableHeadBranch : ClauseBranch where
  sourceId := 0
  callGeneration := 0
  freshSubstitution := []
  headEquations := [(.atom "a", .variable (.generated 0))]
  body := []
  bindings := []
  firstFresh := 0
  nextFresh := 1

/-- A rigid call argument against a fresh clause variable has the expected
semantic MGU even though the variable occurs on the right. -/
theorem variableHeadBranch_resolves :
    HeadResolution variableHeadBranch
      [(.generated 0, .atom "a")] := by
  let binding : Substitution := [(.generated 0, .atom "a")]
  have computed : ComputesDenotationalMgu
      [(.atom "a", .variable (.generated 0))] binding := by
    exact computes_singleton_right_variable (.atom "a") (.generated 0)
      (by intro identity equality; cases equality) (by rfl)
  exact ⟨binding, by simpa [variableHeadBranch,
    ClauseBranch.normalizedHeadEquations] using computed, rfl⟩

def clashingHeadBranch : ClauseBranch where
  sourceId := 0
  callGeneration := 0
  freshSubstitution := []
  headEquations := [(.atom "a", .atom "b")]
  body := []
  bindings := []
  firstFresh := 0
  nextFresh := 0

/-- Distinct rigid heads cannot be accepted by the semantic resolver.  This
prevents `HeadResolution` from degenerating into an always-successful oracle.
-/
theorem clashingHeadBranch_has_no_resolution :
    ¬ ∃ result, HeadResolution clashingHeadBranch result := by
  rintro ⟨result, extension, computed, resultEq⟩
  have mostGeneral := computed.isMostGeneral
  have unifies : DenotationalUnifier extension (.atom "a") (.atom "b") :=
    mostGeneral.1 (.atom "a", .atom "b") (by simp
      [clashingHeadBranch, ClauseBranch.normalizedHeadEquations])
  exact distinct_atoms_have_no_denotational_unifier "a" "b" (by decide)
    ⟨extension, unifies⟩

/-! ## Executable anti-vacuity witnesses for logical update -/

def witnessClause (value : String) : LocalClause where
  predicate := "p"
  arguments := [.atom value]
  body := []

def witnessBefore : Database :=
  (Database.empty.assertz (witnessClause "left")).assertz
    (witnessClause "right")

def witnessRequest : CallRequest where
  database := witnessBefore
  predicate := "p"
  arguments := [.variable (.source "X")]
  bindings := []
  freshSeed := 10

def witnessCursor : ClauseCursor := openCursor witnessRequest

def witnessAfterAssert : Database :=
  witnessBefore.assertz (witnessClause "late")

/-- The correct call-start snapshot contains exactly the two occurrences
visible when the call opened. -/
theorem witness_snapshot_ids : witnessCursor.remaining.map (fun entry => entry.id) =
    [0, 1] := by
  decide

/-- A new call sees the clause asserted at the later generation. -/
theorem witness_new_call_sees_assertion :
    (witnessAfterAssert.liveViewClauses "p" 1).map (fun entry => entry.id) =
      [0, 1, 2] := by
  decide

/-- The already-open cursor does not drift after assertion. -/
theorem witness_open_call_does_not_see_assertion :
    2 ∉ witnessCursor.remaining.map (fun entry => entry.id) := by
  decide

/-- The deliberately wrong live-view semantics does observe the new clause.
Together with `witness_open_call_does_not_see_assertion`, this is the required
anti-vacuity discriminator: snapshot and live-view semantics cannot satisfy
the same exact ordered cursor claim. -/
theorem witness_wrong_live_view_sees_assertion :
    2 ∈ (witnessAfterAssert.liveViewClauses "p" 1).map
      (fun entry => entry.id) := by
  decide

def witnessAfterRetract : Database :=
  (witnessAfterAssert.retractId 1).getD witnessAfterAssert

/-- A newly opened call no longer sees the retracted occurrence. -/
theorem witness_new_call_hides_retraction :
    (witnessAfterRetract.liveViewClauses "p" 1).map (fun entry => entry.id) =
      [0, 2] := by
  decide

/-- A cursor already standing over the old snapshot retains the retracted
occurrence, as required by the logical update view. -/
theorem witness_open_call_retains_retracted_clause :
    1 ∈ witnessCursor.remaining.map (fun entry => entry.id) := by
  decide

/-- A nested call opened after both updates receives its own later generation,
not the enclosing call's generation. -/
theorem witness_nested_call_has_new_generation :
    (openCursor { witnessRequest with database := witnessAfterRetract }).callGeneration =
        witnessAfterRetract.generation ∧
      witnessCursor.callGeneration < witnessAfterRetract.generation := by
  decide

/-! ### Cursor-step-level live-view discriminator -/

/-- Foil cursor that remembers only how many entries it has consumed and
re-queries the live database on every pull.  It is deliberately not used by
the reference resolver. -/
structure LiveViewCursor where
  predicate : String
  arity : Nat
  consumed : Nat
deriving Repr, Inhabited

/-- One step of the deliberately wrong live-view resolver. -/
def pullLiveView (database : Database) (cursor : LiveViewCursor) :
    Option (VersionedClause × LiveViewCursor) :=
  match (database.liveViewClauses cursor.predicate cursor.arity).drop
      cursor.consumed with
  | [] => none
  | entry :: _ => some (entry, { cursor with consumed := cursor.consumed + 1 })

/-- Snapshot cursor after consuming both clauses that existed at call start. -/
def witnessCursorAfterTwo : ClauseCursor :=
  match pullBranch witnessCursor with
  | none => witnessCursor
  | some (_, afterFirst) =>
      match pullBranch afterFirst with
      | none => afterFirst
      | some (_, afterSecond) => afterSecond

/-- The correct snapshot stepper is exhausted after its two original
occurrences, even though the live database has since grown. -/
theorem witness_snapshot_stepper_exhausted_after_assert :
    pullBranch witnessCursorAfterTwo = none := by
  decide

/-- On the identical post-assert database, the wrong stepper emits the late
clause instead of exhaustion.  This lifts the anti-vacuity witness from
candidate-set inequality to an actual cursor transition. -/
theorem witness_wrong_stepper_emits_late_clause :
    ∃ entry next,
      pullLiveView witnessAfterAssert
          { predicate := "p", arity := 1, consumed := 2 } =
        some (entry, next) ∧
      entry.id = 2 := by
  refine ⟨(witnessAfterAssert.liveViewClauses "p" 1)[2]!,
    { predicate := "p", arity := 1, consumed := 3 }, ?_, ?_⟩
  · rfl
  · rfl

end PLeaTTa.PeTTaSpec.PrologCore.Resolver
