/-
Module: PLeaTTa.PeTTaSpec.PrologCore
Purpose: Independent syntax for the Prolog term and goal fragment emitted by
  pinned PeTTa's translator.  It does not reuse PLeaTTa's executable Goal IR.
Trusted boundary: none
Main exports: Term, Goal, Literal, Quotes, TranslatesExpr
-/
import MettaHyperonFull.Core.Atom

namespace PLeaTTa.PeTTaSpec.PrologCore

open Metta (Atom Ground)

/-- Logical-variable identities in the independent target.  Source variables,
anonymous reader occurrences, and variables allocated by translation occupy
disjoint namespaces, so alpha-equivalence never depends on executable names
such as `_q17`. -/
inductive LogicVar where
  | source (name : String)
  | anonymous (index : Nat)
  | generated (index : Nat)
deriving Repr, Inhabited

/-- Source and translator-generated variables cannot alias. -/
theorem LogicVar.source_ne_generated (name : String) (index : Nat) :
    LogicVar.source name ≠ .generated index := by
  intro equality
  cases equality

/-- Anonymous reader occurrences cannot alias translator-generated variables. -/
theorem LogicVar.anonymous_ne_generated (anonymousIndex generatedIndex : Nat) :
    LogicVar.anonymous anonymousIndex ≠ .generated generatedIndex := by
  intro equality
  cases equality

/-- Prolog terms relevant to PeTTa's parser and translator.  Proper and dotted
lists are represented directly rather than disguised as a host-language list. -/
inductive Term where
  | variable (identity : LogicVar)
  | atom (name : String)
  | integer (value : Int)
  | float (value : Float)
  | string (value : String)
  | compound (functor : String) (arguments : List Term)
  | list (items : List Term) (tail : Option Term)
deriving Repr, Inhabited

/-- Translation-time state whose membership controls the pinned translator's
highest-priority hook branch.  This is intentionally a proposition-valued
interface rather than PLeaTTa's executable list representation. -/
structure TranslatorState where
  hasRule : String → Prop

/-- The independent Prolog goal language generated by `translator.pl`.
Additional primitives can be added as their translation clauses are proved;
none of these constructors refer to PLeaTTa's executable machine. -/
inductive Goal where
  | truth
  | fail
  | unify (left right : Term)
  | identical (left right : Term)
  | call (predicate : String) (arguments : List Term)
  | conjunction (goals : List Goal)
  | disjunction (branches : List Goal)
  | cut
  | ifThenElse (condition thenBranch elseBranch : Goal)
  | softCut (condition thenBranch elseBranch : Goal)
  | negation (goal : Goal)
  | once (goal : Goal)
  | findall (template : Term) (goal : Goal) (output : Term)
  | catch (goal : Goal) (exception : Term) (handler : Goal)
  | transaction (goal : Goal)
  | withMutex (mutex : Term) (goal : Goal)
  | forall (generator test : Goal)
deriving Repr, Inhabited

/-- Source atoms which PeTTa's first `translate_expr/3` clause returns without
emitting a goal.  Unsupported host grounds intentionally have no constructor. -/
inductive Literal : Atom → Term → Prop where
  | variable (name : String) :
      Literal (.var name) (.variable (.source name))
  | symbol (name : String) : Literal (.sym name) (.atom name)
  | integer (value : Int) : Literal (.gnd (.int value)) (.integer value)
  | float (value : Float) : Literal (.gnd (.float value)) (.float value)
  | string (value : String) : Literal (.gnd (.str value)) (.string value)
  | trueGround : Literal (.gnd (.bool true)) (.atom "true")
  | falseGround : Literal (.gnd (.bool false)) (.atom "false")
  | emptyList : Literal (.expr []) (.list [] none)

mutual

/-- Deep syntactic quotation into native Prolog terms. -/
inductive Quotes : Atom → Term → Prop where
  | variable (name : String) :
      Quotes (.var name) (.variable (.source name))
  | symbol (name : String) : Quotes (.sym name) (.atom name)
  | integer (value : Int) : Quotes (.gnd (.int value)) (.integer value)
  | float (value : Float) : Quotes (.gnd (.float value)) (.float value)
  | string (value : String) : Quotes (.gnd (.str value)) (.string value)
  | trueGround : Quotes (.gnd (.bool true)) (.atom "true")
  | falseGround : Quotes (.gnd (.bool false)) (.atom "false")
  | expression {atoms : List Atom} {terms : List Term}
      (items : QuotesList atoms terms) : Quotes (.expr atoms) (.list terms none)

/-- Pointwise quotation of expression members. -/
inductive QuotesList : List Atom → List Term → Prop where
  | nil : QuotesList [] []
  | cons {atom : Atom} {term : Term} {atoms : List Atom} {terms : List Term}
      (head : Quotes atom term) (tail : QuotesList atoms terms) :
      QuotesList (atom :: atoms) (term :: terms)

end

mutual

/-- Independently specified fragment of pinned `translate_expr/3`.  Its rules
state native translation behavior without referring to PLeaTTa's executable
compiler. -/
inductive TranslatesExpr : TranslatorState → Nat → Atom → Term → List Goal →
    Nat → Prop where
  | literal {state : TranslatorState} {counter : Nat} {source : Atom}
      {term : Term}
      (value : Literal source term) :
      TranslatesExpr state counter source term [] counter
  | quote {state : TranslatorState} {counter : Nat} {source : Atom}
      {term : Term}
      (notShadowed : ¬ state.hasRule "quote")
      (value : Quotes source term) :
      TranslatesExpr state counter (.expr [.sym "quote", source]) term [] counter
  | cut {state : TranslatorState} {counter : Nat}
      (notShadowed : ¬ state.hasRule "cut") :
      TranslatesExpr state counter (.expr [.sym "cut"]) (.atom "true") [.cut]
        counter
  | collapse {state : TranslatorState} {counter bodyCounter : Nat}
      {source : Atom} {template : Term} {bodyGoals : List Goal}
      (notShadowed : ¬ state.hasRule "collapse")
      (body :
        TranslatesExpr state counter source template bodyGoals bodyCounter) :
      TranslatesExpr state counter (.expr [.sym "collapse", source])
        (.variable (.generated bodyCounter))
        [.findall template (.conjunction bodyGoals)
          (.variable (.generated bodyCounter))]
        (bodyCounter + 1)
  -- [SPEC translator.pl:185-188] Translation traverses pattern, value, and
  -- body in that order, but the generated goal order begins with unification.
  | letBind {state : TranslatorState}
      {counter patternCounter valueCounter nextCounter : Nat}
      {pattern value bodySource : Atom}
      {patternTerm valueTerm bodyTerm : Term}
      {patternGoals valueGoals bodyGoals : List Goal}
      (notShadowed : ¬ state.hasRule "let")
      (patternTranslation :
        TranslatesExpr state counter pattern patternTerm patternGoals
          patternCounter)
      (valueTranslation :
        TranslatesExpr state patternCounter value valueTerm valueGoals
          valueCounter)
      (bodyTranslation :
        TranslatesExpr state valueCounter bodySource bodyTerm bodyGoals
          nextCounter) :
      TranslatesExpr state counter
        (.expr [.sym "let", pattern, value, bodySource])
        bodyTerm
        ([.unify patternTerm valueTerm] ++ patternGoals ++ valueGoals ++
          bodyGoals)
        nextCounter
  -- [SPEC translator.pl:185-188] `chain` is the second head admitted by the
  -- same pinned clause as `let`; only the source argument order differs.
  | chainBind {state : TranslatorState}
      {counter patternCounter valueCounter nextCounter : Nat}
      {value pattern bodySource : Atom}
      {valueTerm patternTerm bodyTerm : Term}
      {valueGoals patternGoals bodyGoals : List Goal}
      (notShadowed : ¬ state.hasRule "chain")
      (patternTranslation :
        TranslatesExpr state counter pattern patternTerm patternGoals
          patternCounter)
      (valueTranslation :
        TranslatesExpr state patternCounter value valueTerm valueGoals
          valueCounter)
      (bodyTranslation :
        TranslatesExpr state valueCounter bodySource bodyTerm bodyGoals
          nextCounter) :
      TranslatesExpr state counter
        (.expr [.sym "chain", value, pattern, bodySource])
        bodyTerm
        ([.unify patternTerm valueTerm] ++ patternGoals ++ valueGoals ++
          bodyGoals)
        nextCounter
  | progn {state : TranslatorState} {counter nextCounter : Nat}
      {sources : List Atom} {first last : Term} {goals : List Goal}
      (notShadowed : ¬ state.hasRule "progn")
      (arguments :
        TranslatesSeq state counter sources first last goals nextCounter) :
      TranslatesExpr state counter (.expr (.sym "progn" :: sources)) last goals
        nextCounter
  | prog1 {state : TranslatorState} {counter nextCounter : Nat}
      {sources : List Atom} {first last : Term} {goals : List Goal}
      (notShadowed : ¬ state.hasRule "prog1")
      (arguments :
        TranslatesSeq state counter sources first last goals nextCounter) :
      TranslatesExpr state counter (.expr (.sym "prog1" :: sources)) first goals
        nextCounter

/-- A nonempty left-to-right translation sequence.  The relation remembers
its first and last result terms, which are selected by `prog1` and `progn`
respectively, while concatenating goals in pinned execution order. -/
inductive TranslatesSeq : TranslatorState → Nat → List Atom → Term → Term →
    List Goal → Nat → Prop where
  | single {state : TranslatorState} {counter nextCounter : Nat}
      {source : Atom} {term : Term} {goals : List Goal}
      (head : TranslatesExpr state counter source term goals nextCounter) :
      TranslatesSeq state counter [source] term term goals nextCounter
  | cons {state : TranslatorState} {counter middleCounter nextCounter : Nat}
      {source : Atom} {sources : List Atom} {headTerm first last : Term}
      {headGoals tailGoals : List Goal}
      (head :
        TranslatesExpr state counter source headTerm headGoals middleCounter)
      (tail : TranslatesSeq state middleCounter sources first last tailGoals
        nextCounter) :
      TranslatesSeq state counter (source :: sources) headTerm last
        (headGoals ++ tailGoals) nextCounter

end

/-- Independent pinned translation for the first behaviorally normalized
construct. Native emits a mutex wrapper, while PLeaTTa's sequential target
may erase that wrapper only after an ordered-observation theorem. Keeping this
relation separate prevents structural agreement from disguising the proof
obligation. -/
inductive TranslatesWithMutex : TranslatorState → Nat → Atom → Term →
    List Goal → Nat → Prop where
  -- [SPEC translator.pl:136-137]
  | wrap {state : TranslatorState} {counter nextCounter : Nat}
      {mutex bodySource : Atom} {mutexTerm bodyTerm : Term}
      {bodyGoals : List Goal}
      (notShadowed : ¬ state.hasRule "with_mutex")
      (mutexValue : Quotes mutex mutexTerm)
      (body :
        TranslatesExpr state counter bodySource bodyTerm bodyGoals nextCounter) :
      TranslatesWithMutex state counter
        (.expr [.sym "with_mutex", mutex, bodySource]) bodyTerm
        [.withMutex mutexTerm (.conjunction bodyGoals)] nextCounter

/-- Independent pinned `once` translation. Native retains the translated body
term as its result and wraps only the body conjunction. The executable's
fresh result capture is intentionally not identified with this term here. -/
inductive TranslatesOnce : TranslatorState → Nat → Atom → Term → List Goal →
    Nat → Prop where
  -- [SPEC translator.pl:127-128]
  | wrap {state : TranslatorState} {counter nextCounter : Nat}
      {bodySource : Atom} {bodyTerm : Term} {bodyGoals : List Goal}
      (notShadowed : ¬ state.hasRule "once")
      (body :
        TranslatesExpr state counter bodySource bodyTerm bodyGoals nextCounter) :
      TranslatesOnce state counter (.expr [.sym "once", bodySource]) bodyTerm
        [.once (.conjunction bodyGoals)] nextCounter

/-- A translated sequence always contains at least one source expression. -/
theorem TranslatesSeq.sources_nonempty {state : TranslatorState} {counter : Nat}
    {sources : List Atom} {first last : Term} {goals : List Goal}
    {nextCounter : Nat}
    (translation :
      TranslatesSeq state counter sources first last goals nextCounter) :
    sources ≠ [] := by
  cases translation <;> simp

/-- Positive example: `progn` evaluates two literals left-to-right and returns
the second one. -/
theorem translates_two_literal_progn (state : TranslatorState) (counter : Nat)
    (first second : Int) (notShadowed : ¬ state.hasRule "progn") :
    TranslatesExpr state counter
      (.expr [.sym "progn", .gnd (.int first), .gnd (.int second)])
      (.integer second) [] counter :=
  .progn notShadowed
    (.cons (.literal (.integer first)) (.single (.literal (.integer second))))

/-- Positive example: `prog1` evaluates two literals left-to-right and returns
the first one. -/
theorem translates_two_literal_prog1 (state : TranslatorState) (counter : Nat)
    (first second : Int) (notShadowed : ¬ state.hasRule "prog1") :
    TranslatesExpr state counter
      (.expr [.sym "prog1", .gnd (.int first), .gnd (.int second)])
      (.integer first) [] counter :=
  .prog1 notShadowed
    (.cons (.literal (.integer first)) (.single (.literal (.integer second))))

/-- Positive allocation example: `collapse` collects a translated literal
into a fresh generated result variable without identifying that variable with
any source-level name. -/
theorem translates_literal_collapse (state : TranslatorState) (counter : Nat)
    (value : Int) (notShadowed : ¬ state.hasRule "collapse") :
    TranslatesExpr state counter
      (.expr [.sym "collapse", .gnd (.int value)])
      (.variable (.generated counter))
      [.findall (.integer value) (.conjunction [])
        (.variable (.generated counter))]
      (counter + 1) :=
  .collapse notShadowed (.literal (.integer value))

/-- Positive binding example: literal `let` translation emits unification
before the otherwise empty pattern, value, and body goal sequences. -/
theorem translates_literal_let (state : TranslatorState) (counter : Nat)
    (name : String) (value : Int) (notShadowed : ¬ state.hasRule "let") :
    TranslatesExpr state counter
      (.expr [.sym "let", .var name, .gnd (.int value), .var name])
      (.variable (.source name))
      [.unify (.variable (.source name)) (.integer value)]
      counter :=
  .letBind notShadowed
    (.literal (.variable name))
    (.literal (.integer value))
    (.literal (.variable name))

/-- Positive binding example: `chain` has source order value, pattern, body,
but the pinned translator traverses pattern, value, body and emits the same
ordered binding goals as `let`. -/
theorem translates_literal_chain (state : TranslatorState) (counter : Nat)
    (name : String) (value : Int) (notShadowed : ¬ state.hasRule "chain") :
    TranslatesExpr state counter
      (.expr [.sym "chain", .gnd (.int value), .var name, .var name])
      (.variable (.source name))
      [.unify (.variable (.source name)) (.integer value)]
      counter :=
  .chainBind notShadowed
    (.literal (.variable name))
    (.literal (.integer value))
    (.literal (.variable name))

/-- Negative-priority example: registering a translator rule for `let` does
not shadow native `chain`; only a rule for the source head may do so. -/
theorem translates_chain_with_let_shadowed (counter : Nat) (name : String)
    (value : Int) :
    let state : TranslatorState := ⟨fun head => head = "let"⟩
    state.hasRule "let" ∧
      TranslatesExpr state counter
        (.expr [.sym "chain", .gnd (.int value), .var name, .var name])
        (.variable (.source name))
        [.unify (.variable (.source name)) (.integer value)]
        counter := by
  dsimp
  constructor
  · rfl
  · exact .chainBind (by simp)
      (.literal (.variable name))
      (.literal (.integer value))
      (.literal (.variable name))

/-- Positive behavioral-translation example for a literal mutex body. -/
theorem translates_literal_withMutex (state : TranslatorState) (counter : Nat)
    (mutex : String) (value : Int)
    (notShadowed : ¬ state.hasRule "with_mutex") :
    TranslatesWithMutex state counter
      (.expr [.sym "with_mutex", .sym mutex, .gnd (.int value)])
      (.integer value)
      [.withMutex (.atom mutex) (.conjunction [])]
      counter :=
  .wrap notShadowed (.symbol mutex) (.literal (.integer value))

/-- Negative priority example: a registered `with_mutex` translator hook
prevents the built-in translation rule from being selected. -/
theorem withMutex_hook_blocks_builtin (counter : Nat) (mutex : String)
    (value : Int) :
    let state : TranslatorState := ⟨fun _ => True⟩
    ∀ term goals nextCounter,
      ¬ TranslatesWithMutex state counter
        (.expr [.sym "with_mutex", .sym mutex, .gnd (.int value)])
        term goals nextCounter := by
  dsimp
  intro term goals nextCounter translation
  cases translation with
  | wrap notShadowed _ _ => exact notShadowed trivial

/-- Positive native `once` translation for a literal body. -/
theorem translates_literal_once (state : TranslatorState) (counter : Nat)
    (value : Int) (notShadowed : ¬ state.hasRule "once") :
    TranslatesOnce state counter
      (.expr [.sym "once", .gnd (.int value)])
      (.integer value) [.once (.conjunction [])] counter :=
  .wrap notShadowed (.literal (.integer value))

/-- Negative priority example: a registered `once` translator hook blocks the
built-in native translation clause. -/
theorem once_hook_blocks_builtin (counter : Nat) (value : Int) :
    let state : TranslatorState := ⟨fun _ => True⟩
    ∀ term goals nextCounter,
      ¬ TranslatesOnce state counter
        (.expr [.sym "once", .gnd (.int value)]) term goals nextCounter := by
  dsimp
  intro term goals nextCounter translation
  cases translation with
  | wrap notShadowed _ => exact notShadowed trivial

/-- The current independently specified compiler fragment.  Membership is a
native translation derivation, never an executable-compiler success test. -/
def SupportedExpr (state : TranslatorState) (counter : Nat) (source : Atom) :
    Prop :=
  ∃ term goals nextCounter,
    TranslatesExpr state counter source term goals nextCounter

/-- Supported source forms whose native target requires a proved sequential
behavioral normalization rather than structural goal identity. -/
def SupportedWithMutex (state : TranslatorState) (counter : Nat)
    (source : Atom) : Prop :=
  ∃ term goals nextCounter,
    TranslatesWithMutex state counter source term goals nextCounter

/-- Independently supported native `once` forms. -/
def SupportedOnce (state : TranslatorState) (counter : Nat)
    (source : Atom) : Prop :=
  ∃ term goals nextCounter,
    TranslatesOnce state counter source term goals nextCounter

/-- Imported host payloads are not literals in the certified compiler fragment. -/
theorem external_not_literal (tag payload : String) (term : Term) :
    ¬ Literal (.gnd (.external tag payload)) term := by
  intro h
  cases h

/-- Grounded errors are runtime values, not source literals accepted by the
pinned reader/compiler relation. -/
theorem error_not_literal (message : String) (term : Term) :
    ¬ Literal (.gnd (.error message)) term := by
  intro h
  cases h

end PLeaTTa.PeTTaSpec.PrologCore
