/-
Module: PLeaTTa.PeTTaSpec.PrologTraceSemantics
Purpose: Independent demand-driven control and observation layer for the
  ordered Prolog fragment generated by pinned PeTTa.
Trusted boundary: an abstract ordered-call protocol; imported implementations
  must be justified separately by replayable traces.
Main exports: OrderedCallProtocol, Process, RawStep, Transition, Steps
-/
import PLeaTTa.PeTTaSpec.PrologSemantics

namespace PLeaTTa.PeTTaSpec.PrologCore.Trace

/-!
This module is the control/interaction foundation for the independent Prolog
semantics.  It deliberately does not identify a call with a completed answer
list.  A call is opened once and then pulled one observation at a time, so a
finite prefix may contain an answer even when the continuation later diverges.

Cut is not an oracle operation.  Choice nodes carry an explicit call scope;
`commit` propagates through the search tree, prunes only choices in that scope,
and is caught only by the matching cut boundary.  This is the linear small-step
shape used by established operational accounts of Prolog control, presented
here independently of PLeaTTa's executable `Goal`, `Conf`, and `Step` types.

The existing complete-list `Ordered.Runs` relation remains useful as a
terminating projection.  It is not the foundation for cut, effects, exceptions,
or divergence.

This tranche proves the generic leftmost search and *cut* control layer with
explicit non-backtrackable provider/session state.  `raised` is observable and
unwinds structural choices with cursor cleanup, but catch handlers, findall
collectors, and transactions remain separate open obligations.  An imported
protocol instance is still only an exact-trace assumption, never a theorem
that its opaque cursors implement those invariants.
-/

/-- Identity of one dynamically entered *cut* scope.  Exception handlers and
answer-collection regions require their own delimiter types when they are
added; reusing this identifier for them would incorrectly conflate control
transparency policies. -/
abbrev CutScopeId := Nat

variable {Request Token Reply Answer Effect Exception : Type}

/-- One demand on an already-open ordered call cursor.  Returning an answer
does not imply that the call is exhausted: the next cursor remains available
for another pull. -/
inductive PullResult (Token Reply Effect Exception : Type) where
  | silent (next : Token)
  | reply (value : Reply) (next : Token)
  | effect (value : Effect) (next : Token)
  | exhausted
  | raised (exception : Exception)

/-- Abstract demand-driven meaning of calls not reduced by this control layer.

The protocol exposes explicit session transitions for four distinct actions:
opening a typed request, pulling exactly one ordered result, pruning a live
cursor, and performing a typed effect.  An imported SWI worker may instantiate
these relations as an explicit trusted boundary.  A locally owned predicate
must instantiate them with the certified clause resolver and MGU development;
parameterization does not discharge that obligation. -/
structure OrderedCallProtocol
    (Request Token Reply Effect Exception : Type) where
  /-- Explicit non-backtrackable provider/control state.  Local execution uses
  this for the global fresh high-water and dynamic world; imported providers
  use it for their transcript/session state. -/
  Session : Type
  openCall : Session → Request → Token → Session → Prop
  pull : Session → Token → PullResult Token Reply Effect Exception →
    Session → Prop
  prune : Session → Token → Session → Prop
  perform : Session → Effect → Session → Prop

namespace OrderedCallProtocol

/-- Lift an old stateless protocol into the explicit-session interface.  The
unit session is definitionally preserved by every action. -/
def pure
    (openCall : Request → Token → Prop)
    (pull : Token → PullResult Token Reply Effect Exception → Prop)
    (prune : Token → Prop) :
    OrderedCallProtocol Request Token Reply Effect Exception where
  Session := Unit
  openCall := fun before request token after =>
    openCall request token ∧ after = before
  pull := fun before token result after =>
    pull token result ∧ after = before
  prune := fun before token after => prune token ∧ after = before
  perform := fun before _ after => after = before

end OrderedCallProtocol

/-- Observable events.  Lists of these events are ordered traces, not sets:
answer duplicates and the order of effects remain visible. -/
inductive Observation (Request Token Answer Effect Exception : Type) where
  | opened (request : Request)
  | answer (value : Answer)
  | effect (value : Effect)
  | pruned (cursor : Token)
  | raised (exception : Exception)
  | completed

namespace Observation

/-- Forget every observable except answers.  This lossy map is suitable only
for relating a completed trace to the older complete-answer-list semantics; it
must never be used as the primary equivalence notion. -/
def answers :
    List (Observation Request Token Answer Effect Exception) → List Answer
  | [] => []
  | .answer value :: events => value :: answers events
  | _ :: events => answers events

theorem answers_append
    (left right : List (Observation Request Token Answer Effect Exception)) :
    answers (left ++ right) = answers left ++ answers right := by
  induction left with
  | nil => rfl
  | cons event events inductionHypothesis =>
      cases event <;> simp [answers, inductionHypothesis]

end Observation

/-- A defunctionalized ordered search process.

`choice scope left right` records a live left-to-right choice point.
`cutBoundary scope body` is the only node that catches a matching commit.
`bind scope head tail` sequences every answer of `head` through `tail`, while
retaining the remaining answers as a choice in the same scope.
`await scope cursor next` is the only interaction point with an external/local
call provider.  A provider reply is internal: the certified layer splices
`next reply` before the retained cursor and only that process can yield an
observable answer. -/
inductive Process (Request Token Reply Answer Effect Exception : Type) where
  | done
  | yield (value : Answer)
      (next : Process Request Token Reply Answer Effect Exception)
  | delay (next : Process Request Token Reply Answer Effect Exception)
  | emit (value : Effect)
      (next : Process Request Token Reply Answer Effect Exception)
  | raise (exception : Exception)
  | commit (scope : CutScopeId)
      (next : Process Request Token Reply Answer Effect Exception)
  | openCall (request : Request)
      (next : Token → Process Request Token Reply Answer Effect Exception)
  | await (scope : CutScopeId) (cursor : Token)
      (next : Reply → Process Request Token Reply Answer Effect Exception)
  | choice (scope : CutScopeId)
      (left right : Process Request Token Reply Answer Effect Exception)
  | cutBoundary (scope : CutScopeId)
      (body : Process Request Token Reply Answer Effect Exception)
  | bind (scope : CutScopeId)
      (head : Process Request Token Reply Answer Effect Exception)
      (tail : Answer → Process Request Token Reply Answer Effect Exception)

namespace Process

/-- Live cursors owned by the current process state, in left-to-right order.
Function continuations are latent and therefore own no cursor until entered.
This projection does not itself establish that tokens are issued, distinct, or
linearly owned; the future well-formedness judgment must establish those facts
for processes produced by Goal specialization. -/
def liveTokens : Process Request Token Reply Answer Effect Exception → List Token
  | .done => []
  | .yield _ next => liveTokens next
  | .delay next => liveTokens next
  | .emit _ next => liveTokens next
  | .raise _ => []
  | .commit _ next => liveTokens next
  | .openCall _ _ => []
  | .await _ cursor _ => [cursor]
  | .choice _ left right => liveTokens left ++ liveTokens right
  | .cutBoundary _ body => liveTokens body
  | .bind _ head _ => liveTokens head

end Process

/-- Structural cut-scope discipline for control processes.

Every transparent control node uses the currently active cut scope.  Entering
`cutBoundary scope body` changes the active scope only for `body`; on return,
the surrounding judgment resumes with its previous scope.  This rules out the
malformed shape in which a commit for an outer scope is placed underneath an
opaque inner boundary and leaves an unpruned alternative behind.

The judgment intentionally says nothing yet about cursor issuance/linearity or
freshness of newly entered scope identifiers.  Those are separate obligations
for Goal specialization and the local resolver. -/
inductive WellScoped :
    CutScopeId → Process Request Token Reply Answer Effect Exception → Prop where
  | done (active : CutScopeId) : WellScoped active .done
  | yield (active : CutScopeId) (value : Answer)
      (next : Process Request Token Reply Answer Effect Exception)
      (nextScoped : WellScoped active next) :
      WellScoped active (.yield value next)
  | delay (active : CutScopeId)
      (next : Process Request Token Reply Answer Effect Exception)
      (nextScoped : WellScoped active next) :
      WellScoped active (.delay next)
  | emit (active : CutScopeId) (value : Effect)
      (next : Process Request Token Reply Answer Effect Exception)
      (nextScoped : WellScoped active next) :
      WellScoped active (.emit value next)
  | raise (active : CutScopeId) (exception : Exception) :
      WellScoped active (.raise exception)
  | commit (active : CutScopeId)
      (next : Process Request Token Reply Answer Effect Exception)
      (nextScoped : WellScoped active next) :
      WellScoped active (.commit active next)
  | openCall (active : CutScopeId) (request : Request)
      (next : Token → Process Request Token Reply Answer Effect Exception)
      (nextScoped : ∀ cursor, WellScoped active (next cursor)) :
      WellScoped active (.openCall request next)
  | await (active : CutScopeId) (cursor : Token)
      (next : Reply → Process Request Token Reply Answer Effect Exception)
      (nextScoped : ∀ reply, WellScoped active (next reply)) :
      WellScoped active (.await active cursor next)
  | choice (active : CutScopeId)
      (left right : Process Request Token Reply Answer Effect Exception)
      (leftScoped : WellScoped active left)
      (rightScoped : WellScoped active right) :
      WellScoped active (.choice active left right)
  | cutBoundary (active scope : CutScopeId)
      (body : Process Request Token Reply Answer Effect Exception)
      (bodyScoped : WellScoped scope body) :
      WellScoped active (.cutBoundary scope body)
  | bind (active : CutScopeId)
      (head : Process Request Token Reply Answer Effect Exception)
      (tail : Answer → Process Request Token Reply Answer Effect Exception)
      (headScoped : WellScoped active head)
      (tailScoped : ∀ answer, WellScoped active (tail answer)) :
      WellScoped active (.bind active head tail)

namespace WellScoped

/-- Inversion through an opaque cut boundary. -/
theorem cutBoundary_body
    {active scope : CutScopeId}
    {body : Process Request Token Reply Answer Effect Exception}
    (wellFormed : WellScoped active (.cutBoundary scope body)) :
    WellScoped scope body := by
  cases wellFormed
  assumption

/-- Inversion through a same-scope ordered choice. -/
theorem choice_left
    {scope : CutScopeId}
    {left right : Process Request Token Reply Answer Effect Exception}
    (wellFormed : WellScoped scope (.choice scope left right)) :
    WellScoped scope left := by
  cases wellFormed
  assumption

/-- Any well-scoped commit carries exactly the active cut scope. -/
theorem commit_scope_eq
    {active scope : CutScopeId}
    {next : Process Request Token Reply Answer Effect Exception}
    (wellFormed : WellScoped active (.commit scope next)) : scope = active := by
  cases wellFormed
  rfl

end WellScoped

/-- A cut signal is internal control state.  It is deliberately absent from
the ordered-call protocol and from user-visible observations. -/
inductive CutSignal where
  | none
  | commit (scope : CutScopeId)
deriving DecidableEq

/-- A cut signal, if present, names the currently active cut scope. -/
def SignalMatches (active : CutScopeId) : CutSignal → Prop
  | .none => True
  | .commit scope => scope = active

/-- Terminal tags remain explicit in machine states.  Completion/failure and
exceptional termination therefore cannot collapse merely because both stop
the current process. -/
inductive Terminal (Exception : Type) where
  | completed
  | raised (exception : Exception)

/-- Target of one raw process step. -/
inductive RawTarget (Request Token Reply Answer Effect Exception : Type) where
  | terminal (tag : Terminal Exception)
  | running (process : Process Request Token Reply Answer Effect Exception)

/-- Sequentially prune every live cursor in a discarded branch.  Threading the
session makes cleanup observable to stateful foreign providers and prevents
pointwise prune assumptions from laundering incompatible state transitions. -/
inductive Prunes
    (protocol : OrderedCallProtocol Request Token Reply Effect Exception) :
    protocol.Session → List Token → protocol.Session → Prop where
  | nil (session : protocol.Session) : Prunes protocol session [] session
  | cons (before middle after : protocol.Session) (token : Token)
      (tokens : List Token)
      (head : protocol.prune before token middle)
      (tail : Prunes protocol middle tokens after) :
      Prunes protocol before (token :: tokens) after

/-- No answer is present in an internal-progress event batch. -/
def AnswerFree
    (events : List (Observation Request Token Answer Effect Exception)) : Prop :=
  ∀ answer, Observation.answer answer ∉ events

/-- One raw transition of the ordered control machine.

The relation is recursive through `choice`, `cutBoundary`, and `bind`, making the
leftmost demand and every cut-pruning decision structurally visible.  A step
may emit several prune events because one commit can discard several live
cursors while it propagates to its cut boundary. -/
inductive RawStep
    (protocol : OrderedCallProtocol Request Token Reply Effect Exception) :
    protocol.Session →
    Process Request Token Reply Answer Effect Exception →
    List (Observation Request Token Answer Effect Exception) →
    CutSignal → protocol.Session →
    RawTarget Request Token Reply Answer Effect Exception → Prop where
  | done (session : protocol.Session) :
      RawStep protocol session .done [.completed] .none session
        (.terminal .completed)
  | yield (value : Answer)
      (next : Process Request Token Reply Answer Effect Exception)
      (session : protocol.Session) :
      RawStep protocol session (.yield value next) [.answer value] .none
        session (.running next)
  | delay (next : Process Request Token Reply Answer Effect Exception)
      (session : protocol.Session) :
      RawStep protocol session (.delay next) [] .none session (.running next)
  | emit (value : Effect)
      (next : Process Request Token Reply Answer Effect Exception)
      (before after : protocol.Session) :
      protocol.perform before value after →
      RawStep protocol before (.emit value next) [.effect value] .none after
        (.running next)
  | raise (exception : Exception) (session : protocol.Session) :
      RawStep protocol session (.raise exception) [.raised exception] .none
        session (.terminal (.raised exception))
  | commit (scope : CutScopeId)
      (next : Process Request Token Reply Answer Effect Exception)
      (session : protocol.Session) :
      RawStep protocol session (.commit scope next) [] (.commit scope) session
        (.running next)
  | openCall (request : Request) (cursor : Token)
      (next : Token → Process Request Token Reply Answer Effect Exception)
      (before after : protocol.Session)
      (opened : protocol.openCall before request cursor after) :
      RawStep protocol before (.openCall request next) [.opened request] .none
        after (.running (next cursor))
  | awaitSilent (scope : CutScopeId) (cursor next : Token)
      (resume : Reply → Process Request Token Reply Answer Effect Exception)
      (before after : protocol.Session)
      (pulled : protocol.pull before cursor (.silent next) after) :
      RawStep protocol before (.await scope cursor resume) [] .none after
        (.running (.await scope next resume))
  | awaitReply (scope : CutScopeId) (cursor next : Token) (reply : Reply)
      (resume : Reply → Process Request Token Reply Answer Effect Exception)
      (before after : protocol.Session)
      (pulled : protocol.pull before cursor (.reply reply next) after) :
      RawStep protocol before (.await scope cursor resume) [] .none after
        (.running (.choice scope (resume reply)
          (.await scope next resume)))
  | awaitEffect (scope : CutScopeId) (cursor next : Token) (effect : Effect)
      (resume : Reply → Process Request Token Reply Answer Effect Exception)
      (before after : protocol.Session)
      (pulled : protocol.pull before cursor (.effect effect next) after) :
      RawStep protocol before (.await scope cursor resume) [.effect effect] .none
        after
        (.running (.await scope next resume))
  | awaitExhausted (scope : CutScopeId) (cursor : Token)
      (resume : Reply → Process Request Token Reply Answer Effect Exception)
      (before after : protocol.Session)
      (pulled : protocol.pull before cursor .exhausted after) :
      RawStep protocol before (.await scope cursor resume) [.completed] .none
        after (.terminal .completed)
  | awaitRaised (scope : CutScopeId) (cursor : Token)
      (resume : Reply → Process Request Token Reply Answer Effect Exception)
      (exception : Exception)
      (before after : protocol.Session)
      (pulled : protocol.pull before cursor (.raised exception) after) :
      RawStep protocol before (.await scope cursor resume)
        [.raised exception] .none after (.terminal (.raised exception))
  | choiceProgress (scope : CutScopeId)
      (left right next : Process Request Token Reply Answer Effect Exception)
      (events : List (Observation Request Token Answer Effect Exception))
      (before after : protocol.Session)
      (step : RawStep protocol before left events .none after (.running next)) :
      RawStep protocol before (.choice scope left right) events .none after
        (.running (.choice scope next right))
  | choiceComplete (scope : CutScopeId)
      (left right : Process Request Token Reply Answer Effect Exception)
      (before after : protocol.Session)
      (step : RawStep protocol before left [.completed] .none after
        (.terminal .completed)) :
      RawStep protocol before (.choice scope left right) [] .none after
        (.running right)
  | choiceRaised (scope : CutScopeId)
      (left right : Process Request Token Reply Answer Effect Exception)
      (exception : Exception)
      (events : List (Observation Request Token Answer Effect Exception))
      (before middle after : protocol.Session)
      (step : RawStep protocol before left events .none middle
        (.terminal (.raised exception)))
      (pruned : Prunes protocol middle right.liveTokens after) :
      RawStep protocol before (.choice scope left right)
        (events ++ right.liveTokens.map Observation.pruned) .none after
        (.terminal (.raised exception))
  | choiceCommitHere (scope : CutScopeId)
      (left right next : Process Request Token Reply Answer Effect Exception)
      (events : List (Observation Request Token Answer Effect Exception))
      (before middle after : protocol.Session)
      (step : RawStep protocol before left events (.commit scope) middle
        (.running next))
      (pruned : Prunes protocol middle right.liveTokens after) :
      RawStep protocol before (.choice scope left right)
        (events ++ right.liveTokens.map Observation.pruned)
        (.commit scope) after (.running next)
  | choiceCommitOutside (scope other : CutScopeId)
      (different : other ≠ scope)
      (left right next : Process Request Token Reply Answer Effect Exception)
      (events : List (Observation Request Token Answer Effect Exception))
      (before after : protocol.Session)
      (step : RawStep protocol before left events (.commit other) after
        (.running next)) :
      RawStep protocol before (.choice scope left right) events (.commit other)
        after
        (.running (.choice scope next right))
  | cutBoundaryProgress (scope : CutScopeId)
      (body next : Process Request Token Reply Answer Effect Exception)
      (events : List (Observation Request Token Answer Effect Exception))
      (before after : protocol.Session)
      (step : RawStep protocol before body events .none after (.running next)) :
      RawStep protocol before (.cutBoundary scope body) events .none after
        (.running (.cutBoundary scope next))
  | cutBoundaryComplete (scope : CutScopeId)
      (body : Process Request Token Reply Answer Effect Exception)
      (before after : protocol.Session)
      (step : RawStep protocol before body [.completed] .none after
        (.terminal .completed)) :
      RawStep protocol before (.cutBoundary scope body) [.completed] .none after
        (.terminal .completed)
  | cutBoundaryRaised (scope : CutScopeId)
      (body : Process Request Token Reply Answer Effect Exception)
      (exception : Exception)
      (events : List (Observation Request Token Answer Effect Exception))
      (before after : protocol.Session)
      (step : RawStep protocol before body events .none after
        (.terminal (.raised exception))) :
      RawStep protocol before (.cutBoundary scope body) events .none after
        (.terminal (.raised exception))
  | cutBoundaryCatch (scope : CutScopeId)
      (body next : Process Request Token Reply Answer Effect Exception)
      (events : List (Observation Request Token Answer Effect Exception))
      (before after : protocol.Session)
      (step : RawStep protocol before body events (.commit scope) after
        (.running next)) :
      RawStep protocol before (.cutBoundary scope body) events .none after
        (.running (.cutBoundary scope next))
  | cutBoundaryPass (scope other : CutScopeId)
      (different : other ≠ scope)
      (body next : Process Request Token Reply Answer Effect Exception)
      (events : List (Observation Request Token Answer Effect Exception))
      (before after : protocol.Session)
      (step : RawStep protocol before body events (.commit other) after
        (.running next)) :
      RawStep protocol before (.cutBoundary scope body) events (.commit other)
        after
        (.running (.cutBoundary scope next))
  | bindAnswer (scope : CutScopeId)
      (head next : Process Request Token Reply Answer Effect Exception)
      (tail : Answer → Process Request Token Reply Answer Effect Exception)
      (answer : Answer)
      (before after : protocol.Session)
      (step : RawStep protocol before head [.answer answer] .none after
        (.running next)) :
      RawStep protocol before (.bind scope head tail) [] .none after
        (.running (.choice scope (tail answer) (.bind scope next tail)))
  | bindProgress (scope : CutScopeId)
      (head next : Process Request Token Reply Answer Effect Exception)
      (tail : Answer → Process Request Token Reply Answer Effect Exception)
      (events : List (Observation Request Token Answer Effect Exception))
      (signal : CutSignal)
      (before after : protocol.Session)
      (step : RawStep protocol before head events signal after (.running next))
      (answerFree : AnswerFree events) :
      RawStep protocol before (.bind scope head tail) events signal after
        (.running (.bind scope next tail))
  | bindComplete (scope : CutScopeId)
      (head : Process Request Token Reply Answer Effect Exception)
      (tail : Answer → Process Request Token Reply Answer Effect Exception)
      (events : List (Observation Request Token Answer Effect Exception))
      (before after : protocol.Session)
      (step : RawStep protocol before head events .none after
        (.terminal .completed))
      (answerFree : AnswerFree events) :
      RawStep protocol before (.bind scope head tail) events .none after
        (.terminal .completed)
  | bindRaised (scope : CutScopeId)
      (head : Process Request Token Reply Answer Effect Exception)
      (tail : Answer → Process Request Token Reply Answer Effect Exception)
      (exception : Exception)
      (events : List (Observation Request Token Answer Effect Exception))
      (before after : protocol.Session)
      (step : RawStep protocol before head events .none after
        (.terminal (.raised exception)))
      (answerFree : AnswerFree events) :
      RawStep protocol before (.bind scope head tail) events .none after
        (.terminal (.raised exception))

namespace RawStep

/-- Target-indexed subject reduction for the structural cut-scope discipline. -/
theorem preserves_wellScoped_target
    (protocol : OrderedCallProtocol Request Token Reply Effect Exception)
    {active : CutScopeId}
    {process : Process Request Token Reply Answer Effect Exception}
    {events : List (Observation Request Token Answer Effect Exception)}
    {signal : CutSignal}
    {before after : protocol.Session}
    {target : RawTarget Request Token Reply Answer Effect Exception}
    (step : RawStep protocol before process events signal after target)
    (wellFormed : WellScoped active process) :
    match target with
    | .terminal _ => True
    | .running next => WellScoped active next := by
  induction step generalizing active with
  | done session => exact True.intro
  | yield value next session =>
      cases wellFormed with
      | yield _ _ _ nextScoped => exact nextScoped
  | delay next session =>
      cases wellFormed with
      | delay _ _ nextScoped => exact nextScoped
  | emit value next before after performed =>
      cases wellFormed with
      | emit _ _ _ nextScoped => exact nextScoped
  | raise exception session => exact True.intro
  | commit scope next session =>
      cases wellFormed with
      | commit _ _ nextScoped => exact nextScoped
  | openCall request cursor next before after opened =>
      cases wellFormed with
      | openCall _ _ _ nextScoped => exact nextScoped cursor
  | awaitSilent scope cursor next resume before after pulled =>
      cases wellFormed with
      | await _ _ _ nextScoped => exact .await scope next resume nextScoped
  | awaitReply scope cursor next reply resume before after pulled =>
      cases wellFormed with
      | await _ _ _ nextScoped =>
          exact .choice scope (resume reply) (.await scope next resume)
            (nextScoped reply) (.await scope next resume nextScoped)
  | awaitEffect scope cursor next effect resume before after pulled =>
      cases wellFormed with
      | await _ _ _ nextScoped => exact .await scope next resume nextScoped
  | awaitExhausted scope cursor resume before after pulled => exact True.intro
  | awaitRaised scope cursor resume exception before after pulled =>
      exact True.intro
  | choiceProgress scope left right next events before after step
      inductionHypothesis =>
      cases wellFormed with
      | choice _ _ _ leftScoped rightScoped =>
          exact .choice scope next right
            (inductionHypothesis leftScoped) rightScoped
  | choiceComplete scope left right before after step inductionHypothesis =>
      cases wellFormed with
      | choice _ _ _ leftScoped rightScoped => exact rightScoped
  | choiceRaised scope left right exception events before middle after step
      pruned inductionHypothesis =>
      exact True.intro
  | choiceCommitHere scope left right next events before middle after step pruned
      inductionHypothesis =>
      cases wellFormed with
      | choice _ _ _ leftScoped rightScoped =>
          exact inductionHypothesis leftScoped
  | choiceCommitOutside scope other different left right next events before after
      step inductionHypothesis =>
      cases wellFormed with
      | choice _ _ _ leftScoped rightScoped =>
          exact .choice scope next right
            (inductionHypothesis leftScoped) rightScoped
  | cutBoundaryProgress scope body next events before after step
      inductionHypothesis =>
      cases wellFormed with
      | cutBoundary active _ _ bodyScoped =>
          exact .cutBoundary active scope next
            (inductionHypothesis bodyScoped)
  | cutBoundaryComplete scope body before after step inductionHypothesis =>
      exact True.intro
  | cutBoundaryRaised scope body exception events before after step
      inductionHypothesis =>
      exact True.intro
  | cutBoundaryCatch scope body next events before after step
      inductionHypothesis =>
      cases wellFormed with
      | cutBoundary active _ _ bodyScoped =>
          exact .cutBoundary active scope next
            (inductionHypothesis bodyScoped)
  | cutBoundaryPass scope other different body next events before after step
      inductionHypothesis =>
      cases wellFormed with
      | cutBoundary active _ _ bodyScoped =>
          exact .cutBoundary active scope next
            (inductionHypothesis bodyScoped)
  | bindAnswer scope head next tail answer before after step
      inductionHypothesis =>
      cases wellFormed with
      | bind _ _ _ headScoped tailScoped =>
          exact .choice scope (tail answer) (.bind scope next tail)
            (tailScoped answer)
            (.bind scope next tail
              (inductionHypothesis headScoped) tailScoped)
  | bindProgress scope head next tail events signal before after step answerFree
      inductionHypothesis =>
      cases wellFormed with
      | bind _ _ _ headScoped tailScoped =>
          exact .bind scope next tail
            (inductionHypothesis headScoped) tailScoped
  | bindComplete scope head tail events before after step answerFree
      inductionHypothesis =>
      exact True.intro
  | bindRaised scope head tail exception events before after step answerFree
      inductionHypothesis =>
      exact True.intro

/-- Any running successor of a well-scoped process is well-scoped at the same
enclosing scope.  The raw relation therefore cannot manufacture the malformed
outer-commit-under-inner-boundary shape after entry. -/
theorem preserves_wellScoped
    (protocol : OrderedCallProtocol Request Token Reply Effect Exception)
    {active : CutScopeId}
    {process next : Process Request Token Reply Answer Effect Exception}
    {events : List (Observation Request Token Answer Effect Exception)}
    {signal : CutSignal}
    {before after : protocol.Session}
    (step : RawStep protocol before process events signal after (.running next))
    (wellFormed : WellScoped active process) :
    WellScoped active next :=
  preserves_wellScoped_target protocol step wellFormed

/-- A well-scoped process can emit only a commit for its currently active cut
scope.  In particular, the `choiceCommitOutside` and `cutBoundaryPass` rules
remain available for raw diagnostic inputs but are unreachable from a
well-scoped process. -/
theorem signal_matches_active
    (protocol : OrderedCallProtocol Request Token Reply Effect Exception)
    {active : CutScopeId}
    {process : Process Request Token Reply Answer Effect Exception}
    {events : List (Observation Request Token Answer Effect Exception)}
    {signal : CutSignal}
    {before after : protocol.Session}
    {target : RawTarget Request Token Reply Answer Effect Exception}
    (step : RawStep protocol before process events signal after target)
    (wellFormed : WellScoped active process) :
    SignalMatches active signal := by
  induction step generalizing active <;> cases wellFormed <;>
    simp_all (config := { failIfUnchanged := false }) [SignalMatches]
  case choiceCommitOutside.choice => solve_by_elim
  case cutBoundaryPass.cutBoundary =>
    exfalso
    solve_by_elim

/-- Convenient negative form of `signal_matches_active`. -/
theorem no_foreign_commit
    (protocol : OrderedCallProtocol Request Token Reply Effect Exception)
    {active other : CutScopeId}
    {process : Process Request Token Reply Answer Effect Exception}
    {events : List (Observation Request Token Answer Effect Exception)}
    {before after : protocol.Session}
    {target : RawTarget Request Token Reply Answer Effect Exception}
    (step : RawStep protocol before process events (.commit other) after target)
    (wellFormed : WellScoped active process)
    (different : other ≠ active) : False :=
  different (signal_matches_active protocol step wellFormed)

/-- Sequential pruning preserves every monotone measure admitted by one prune
operation. -/
theorem prunes_measure_mono
    (protocol : OrderedCallProtocol Request Token Reply Effect Exception)
    (measure : protocol.Session → Nat)
    (pruneMono : ∀ before token after,
      protocol.prune before token after → measure before ≤ measure after)
    {before after : protocol.Session} {tokens : List Token}
    (pruned : Prunes protocol before tokens after) :
    measure before ≤ measure after := by
  induction pruned with
  | nil => exact Nat.le_refl _
  | cons before middle after token tokens head tail inductionHypothesis =>
      exact Nat.le_trans (pruneMono before token middle head)
        inductionHypothesis

/-- Generic rely/guarantee lifting: if each protocol action is monotone in a
session measure, every structural control step is monotone too.  Choice,
backtracking, cut, and exception unwinding cannot roll state back because the
session is threaded outside `Process`; cleanup composes through `Prunes`. -/
theorem session_measure_mono
    (protocol : OrderedCallProtocol Request Token Reply Effect Exception)
    (measure : protocol.Session → Nat)
    (openMono : ∀ before request token after,
      protocol.openCall before request token after →
        measure before ≤ measure after)
    (pullMono : ∀ before token outcome after,
      protocol.pull before token outcome after →
        measure before ≤ measure after)
    (pruneMono : ∀ before token after,
      protocol.prune before token after → measure before ≤ measure after)
    (performMono : ∀ before effect after,
      protocol.perform before effect after → measure before ≤ measure after)
    {before after : protocol.Session}
    {process : Process Request Token Reply Answer Effect Exception}
    {events : List (Observation Request Token Answer Effect Exception)}
    {signal : CutSignal}
    {target : RawTarget Request Token Reply Answer Effect Exception}
    (step : RawStep protocol before process events signal after target) :
    measure before ≤ measure after := by
  induction step with
  | done session => exact Nat.le_refl _
  | yield value next session => exact Nat.le_refl _
  | delay next session => exact Nat.le_refl _
  | emit value next before after performed =>
      exact performMono before value after performed
  | raise exception session => exact Nat.le_refl _
  | commit scope next session => exact Nat.le_refl _
  | openCall request cursor next before after opened =>
      exact openMono before request cursor after opened
  | awaitSilent scope cursor next resume before after pulled =>
      exact pullMono before cursor (.silent next) after pulled
  | awaitReply scope cursor next reply resume before after pulled =>
      exact pullMono before cursor (.reply reply next) after pulled
  | awaitEffect scope cursor next effect resume before after pulled =>
      exact pullMono before cursor (.effect effect next) after pulled
  | awaitExhausted scope cursor resume before after pulled =>
      exact pullMono before cursor .exhausted after pulled
  | awaitRaised scope cursor resume exception before after pulled =>
      exact pullMono before cursor (.raised exception) after pulled
  | choiceProgress scope left right next events before after step
      inductionHypothesis => exact inductionHypothesis
  | choiceComplete scope left right before after step inductionHypothesis =>
      exact inductionHypothesis
  | choiceRaised scope left right exception events before middle after step
      pruned inductionHypothesis =>
      exact Nat.le_trans inductionHypothesis
        (prunes_measure_mono protocol measure pruneMono pruned)
  | choiceCommitHere scope left right next events before middle after step
      pruned inductionHypothesis =>
      exact Nat.le_trans inductionHypothesis
        (prunes_measure_mono protocol measure pruneMono pruned)
  | choiceCommitOutside scope other different left right next events before after
      step inductionHypothesis => exact inductionHypothesis
  | cutBoundaryProgress scope body next events before after step
      inductionHypothesis => exact inductionHypothesis
  | cutBoundaryComplete scope body before after step inductionHypothesis =>
      exact inductionHypothesis
  | cutBoundaryRaised scope body exception events before after step
      inductionHypothesis => exact inductionHypothesis
  | cutBoundaryCatch scope body next events before after step
      inductionHypothesis => exact inductionHypothesis
  | cutBoundaryPass scope other different body next events before after step
      inductionHypothesis => exact inductionHypothesis
  | bindAnswer scope head next tail answer before after step
      inductionHypothesis => exact inductionHypothesis
  | bindProgress scope head next tail events signal before after step answerFree
      inductionHypothesis => exact inductionHypothesis
  | bindComplete scope head tail events before after step answerFree
      inductionHypothesis => exact inductionHypothesis
  | bindRaised scope head tail exception events before after step answerFree
      inductionHypothesis => exact inductionHypothesis

end RawStep

/-- Public machine state.  The provider/control session is part of every
endpoint rather than an invisible parameter of the transition relation.  It
is therefore non-backtrackable across structural choices.  An escaped cut is
recorded rather than silently treated as failure; well-scoped compiled calls
must surround execution with the corresponding cut boundary. -/
inductive State
    (protocol : OrderedCallProtocol Request Token Reply Effect Exception) where
  | terminal (session : protocol.Session) (tag : Terminal Exception)
  | running (session : protocol.Session)
      (process : Process Request Token Reply Answer Effect Exception)
  | uncaughtCut (session : protocol.Session) (scope : CutScopeId)
      (continuation : Process Request Token Reply Answer Effect Exception)

private def RawTarget.toState
    (protocol : OrderedCallProtocol Request Token Reply Effect Exception)
    (session : protocol.Session) :
    RawTarget Request Token Reply Answer Effect Exception →
      State (Answer := Answer) protocol
  | .terminal tag => .terminal session tag
  | .running process => .running session process

/-- One top-level transition. -/
inductive Transition
    (protocol : OrderedCallProtocol Request Token Reply Effect Exception) :
    State protocol →
    List (Observation Request Token Answer Effect Exception) →
    State protocol → Prop where
  | ordinary (process : Process Request Token Reply Answer Effect Exception)
      (events : List (Observation Request Token Answer Effect Exception))
      (before after : protocol.Session)
      (target : RawTarget Request Token Reply Answer Effect Exception)
      (step : RawStep protocol before process events .none after target) :
      Transition protocol (.running before process) events
        (target.toState protocol after)
  | uncaught (process next : Process Request Token Reply Answer Effect Exception)
      (events : List (Observation Request Token Answer Effect Exception))
      (before after : protocol.Session)
      (scope : CutScopeId)
      (step : RawStep protocol before process events (.commit scope) after
        (.running next)) :
      Transition protocol (.running before process) events
        (.uncaughtCut after scope next)

/-- A finite transition prefix.  Event lists compose by append, preserving the
exact order and multiplicity produced by every step. -/
inductive Steps
    (protocol : OrderedCallProtocol Request Token Reply Effect Exception) :
    State protocol →
    List (Observation Request Token Answer Effect Exception) →
    State protocol → Prop where
  | refl (state : State protocol) :
      Steps protocol state [] state
  | cons (start middle finish : State protocol)
      (first rest : List (Observation Request Token Answer Effect Exception))
      (head : Transition protocol start first middle)
      (tail : Steps protocol middle rest finish) :
      Steps protocol start (first ++ rest) finish

/-- Exactly `count` top-level transitions.  Keeping the transition count in
the judgment prevents an "arbitrarily long prefix" theorem from being
vacuously witnessed by reflexivity. -/
inductive StepsN
    (protocol : OrderedCallProtocol Request Token Reply Effect Exception) :
    Nat → State protocol →
    List (Observation Request Token Answer Effect Exception) →
    State protocol → Prop where
  | zero (state : State protocol) :
      StepsN protocol 0 state [] state
  | succ (count : Nat)
      (start middle finish : State protocol)
      (first rest : List (Observation Request Token Answer Effect Exception))
      (head : Transition protocol start first middle)
      (tail : StepsN protocol count middle rest finish) :
      StepsN protocol (count + 1) start (first ++ rest) finish

namespace StepsN

/-- Forget only the exact transition count, retaining the same ordered events
and endpoints in the ordinary finite-prefix relation. -/
theorem toSteps
    (protocol : OrderedCallProtocol Request Token Reply Effect Exception)
    {count : Nat}
    {start finish : State protocol}
    {events : List (Observation Request Token Answer Effect Exception)}
    (execution : StepsN protocol count start events finish) :
    Steps protocol start events finish := by
  induction execution with
  | zero state => exact .refl state
  | succ _ start middle finish first rest head _ inductionHypothesis =>
      exact .cons start middle finish first rest head inductionHypothesis

end StepsN

/-- Open one predicate call under its own cut boundary.  Provider replies are
not answers: each reply is interpreted by `resume`, and the `awaitReply` rule
places that certified interpretation before the still-live cursor at exactly
this predicate scope. -/
def Process.scopedCall (scope : CutScopeId) (request : Request)
    (resume : Reply → Process Request Token Reply Answer Effect Exception) :
    Process Request Token Reply Answer Effect Exception :=
  .cutBoundary scope
    (.openCall request (fun cursor => .await scope cursor resume))

/-- A scoped call is well formed whenever every certified reply continuation
is well formed at the fresh predicate scope. -/
theorem Process.scopedCall_wellScoped (active scope : CutScopeId)
    (request : Request)
    (resume : Reply → Process Request Token Reply Answer Effect Exception)
    (resumeScoped : ∀ reply, WellScoped scope (resume reply)) :
    WellScoped active (Process.scopedCall scope request resume) := by
  apply WellScoped.cutBoundary
  apply WellScoped.openCall
  intro cursor
  exact .await scope cursor resume resumeScoped

/-- Provider interaction itself is answer-free.  Even a malicious abstract
provider cannot smuggle a user answer through the reply channel: an answer can
become observable only after the certified continuation is spliced and takes
its own later `yield` step. -/
theorem RawStep.await_answerFree
    (protocol : OrderedCallProtocol Request Token Reply Effect Exception)
    (scope : CutScopeId) (cursor : Token)
    (resume : Reply → Process Request Token Reply Answer Effect Exception)
    {events : List (Observation Request Token Answer Effect Exception)}
    {signal : CutSignal}
    {before after : protocol.Session}
    {target : RawTarget Request Token Reply Answer Effect Exception}
    (step : RawStep protocol before (.await scope cursor resume) events signal
      after target) :
    AnswerFree events := by
  cases step <;> simp [AnswerFree]

/-- Generic inversion for a cursor whose protocol admits only a silent
self-loop.  Keeping the protocol abstract avoids baking a provider's schedule
into the control semantics; the conclusion is forced solely by the supplied
pull contract. -/
theorem RawStep.await_only_silent
    (protocol : OrderedCallProtocol Request Token Reply Effect Exception)
    (scope : CutScopeId) (cursor : Token)
    (resume : Reply → Process Request Token Reply Answer Effect Exception)
    (pullOnly : ∀ before result after,
      protocol.pull before cursor result after →
        result = .silent cursor ∧ after = before)
    {before after : protocol.Session}
    {process : Process Request Token Reply Answer Effect Exception}
    {events : List (Observation Request Token Answer Effect Exception)}
    {signal : CutSignal}
    {target : RawTarget Request Token Reply Answer Effect Exception}
    (step : RawStep protocol before process events signal after target)
    (processEq : process = .await scope cursor resume) :
    events = [] ∧ signal = .none ∧ after = before ∧
      target = .running (.await scope cursor resume) := by
  induction step <;> simp_all
  all_goals
    have contract := pullOnly _ _ _ ‹protocol.pull _ cursor _ _›
    simp_all

/-- Specialization for a provider whose replies already are trusted observable
answers.  This is appropriate for the explicitly trusted imported-SWI lane;
locally owned predicates instead use `Reply = EnteredClause` and provide a
certified body-execution continuation. -/
def Process.directAwait (scope : CutScopeId) (cursor : Token) :
    Process Request Token Answer Answer Effect Exception :=
  .await scope cursor (fun answer => .yield answer .done)

/-- Direct-answer awaiting is well scoped at its declared predicate scope. -/
theorem Process.directAwait_wellScoped (scope : CutScopeId) (cursor : Token) :
    WellScoped scope
      (Process.directAwait (Request := Request) (Token := Token)
        (Answer := Answer) (Effect := Effect)
        (Exception := Exception) scope cursor) := by
  apply WellScoped.await
  intro answer
  apply WellScoped.yield
  exact .done _

/-- A two-answer process used to demonstrate that trace equality observes
answer order rather than only the final answer set. -/
def orderedPair (first second : Answer) :
    Process Request Token Reply Answer Effect Exception :=
  .yield first (.yield second .done)

/-- The ordered-pair witness produces both answers and then ordinary
completion, in exactly that order. -/
theorem orderedPair_steps
    (protocol : OrderedCallProtocol Request Token Reply Effect Exception)
    (session : protocol.Session) (first second : Answer) :
    Steps protocol (.running session (orderedPair first second))
      [.answer first, .answer second, .completed]
      (.terminal session .completed) := by
  refine .cons _ _ _ _ _
    (.ordinary _ _ session session _ (.yield first _ session)) ?_
  refine .cons _ _ _ _ _
    (.ordinary _ _ session session _ (.yield second _ session)) ?_
  refine .cons _ _ _ _ _
    (.ordinary _ _ session session _ (.done session)) ?_
  exact .refl (.terminal session .completed)

/-- Reversing two distinct answers changes the trace. -/
theorem answer_order_observable
    {first second : Answer} (different : first ≠ second) :
    ([Observation.answer first, Observation.answer second,
        Observation.completed] :
      List (Observation Request Token Answer Effect Exception)) ≠
    [.answer second, .answer first, .completed] := by
  intro equality
  injection equality with headEquality
  exact different (Observation.answer.inj headEquality)

/-- Removing one duplicate changes the trace. -/
theorem answer_multiplicity_observable (answer : Answer) :
    ([Observation.answer answer, Observation.answer answer,
        Observation.completed] :
      List (Observation Request Token Answer Effect Exception)) ≠
    [.answer answer, .completed] := by
  simp

/-- Ordinary exhaustion/failure and an exception are distinct observations. -/
theorem exception_is_not_completion (exception : Exception) :
    ([Observation.raised exception] :
      List (Observation Request Token Answer Effect Exception)) ≠
    [.completed] := by
  simp

/-- The step relation itself cannot reinterpret a raised exception as ordinary
completion; the list inequality above is therefore reflected operationally. -/
theorem raised_cannot_complete
    (protocol : OrderedCallProtocol Request Token Reply Effect Exception)
    (session : protocol.Session) (exception : Exception) :
    ¬ RawStep protocol session
      (Process.raise exception :
        Process Request Token Reply Answer Effect Exception)
      ([Observation.completed] :
        List (Observation Request Token Answer Effect Exception))
      .none session (.terminal .completed) := by
  intro step
  cases step

/-- The lossy terminating projection keeps the ordered pair, including any
duplicate, in its original order. -/
theorem orderedPair_answer_projection (first second : Answer) :
    Observation.answers
      ([Observation.answer first, Observation.answer second,
          Observation.completed] :
        List (Observation Request Token Answer Effect Exception)) =
      [first, second] := by
  rfl

/-- Process whose first branch commits before producing its answer. -/
def commitFirst (first second : Answer) :
    Process Request Token Reply Answer Effect Exception :=
  .cutBoundary 0
    (.choice 0
      (.commit 0 (.yield first .done))
      (.yield second .done))

/-- A same-scope commit removes the later answer.  This is an anti-vacuity
witness: a semantics that merely concatenated both branches could not derive
this exact trace. -/
theorem commitFirst_steps
    (protocol : OrderedCallProtocol Request Token Reply Effect Exception)
    (session : protocol.Session) (first second : Answer) :
    Steps protocol (.running session (commitFirst first second))
      [.answer first, .completed] (.terminal session .completed) := by
  have prunable : Prunes protocol session
      (Process.liveTokens
        (Process.yield second Process.done :
          Process Request Token Reply Answer Effect Exception)) session := by
    simpa [Process.liveTokens] using (Prunes.nil session)
  have commitStep : RawStep protocol session
      (Process.cutBoundary 0
        (Process.choice 0
          (Process.commit 0 (Process.yield first Process.done))
          (Process.yield second Process.done)))
      [] .none session
      (.running
        (Process.cutBoundary 0 (Process.yield first Process.done))) :=
    .cutBoundaryCatch 0 _ _ [] session session
      (.choiceCommitHere 0 _ _ _ [] session session session
        (.commit 0 _ session) prunable)
  refine .cons _ _ _ _ _
    (.ordinary _ _ session session _ commitStep) ?_
  refine .cons _ _ _ _ _
    (.ordinary _ _ session session _
      (.cutBoundaryProgress 0 _ _ _ session session
        (.yield first _ session))) ?_
  refine .cons _ _ _ _ _
    (.ordinary _ _ session session _
      (.cutBoundaryComplete 0 _ session session (.done session))) ?_
  exact .refl (.terminal session .completed)

/-- A post-cut effect is not merely hidden from the final answer bag: it is
never emitted.  An eager implementation that ran the right branch before
observing the commit therefore has a different trace. -/
theorem commit_skips_later_effect
    (protocol : OrderedCallProtocol Request Token Reply Effect Exception)
    (session : protocol.Session) (answer : Answer) (effect : Effect) :
    Steps protocol
      (.running session
        (.cutBoundary 0
          (.choice 0
            (.commit 0 (.yield answer .done))
            (.emit effect .done))))
      [.answer answer, .completed] (.terminal session .completed) := by
  have prunable : Prunes protocol session
      (Process.liveTokens
        (Process.emit effect Process.done :
          Process Request Token Reply Answer Effect Exception)) session := by
    simpa [Process.liveTokens] using (Prunes.nil session)
  have commitStep : RawStep protocol session
      (Process.cutBoundary 0
        (Process.choice 0
          (Process.commit 0 (Process.yield answer Process.done))
          (Process.emit effect Process.done)))
      [] .none session
      (.running
        (Process.cutBoundary 0 (Process.yield answer Process.done))) :=
    .cutBoundaryCatch 0 _ _ [] session session
      (.choiceCommitHere 0 _ _ _ [] session session session
        (.commit 0 _ session) prunable)
  refine .cons _ _ _ _ _
    (.ordinary _ _ session session _ commitStep) ?_
  refine .cons _ _ _ _ _
    (.ordinary _ _ session session _
      (.cutBoundaryProgress 0 _ _ _ session session
        (.yield answer _ session))) ?_
  refine .cons _ _ _ _ _
    (.ordinary _ _ session session _
      (.cutBoundaryComplete 0 _ session session (.done session))) ?_
  exact .refl (.terminal session .completed)

/-- A well-scoped nested cut: the inner commit discards only the later inner
branch, while the sibling alternative in the enclosing scope remains live. -/
def innerCommitWithOuterSibling (selected skipped outer : Answer) :
    Process Request Token Reply Answer Effect Exception :=
  .cutBoundary 0
    (.choice 0
      (.cutBoundary 1
        (.choice 1
          (.commit 1 (.yield selected .done))
          (.yield skipped .done)))
      (.yield outer .done))

/-- The nested-cut witness satisfies the structural cut-scope discipline. -/
theorem innerCommitWithOuterSibling_wellScoped
    (selected skipped outer : Answer) :
    WellScoped 0
      (innerCommitWithOuterSibling
        (Request := Request) (Token := Token)
        (Reply := Reply)
        (Effect := Effect) (Exception := Exception)
        selected skipped outer) := by
  apply WellScoped.cutBoundary
  apply WellScoped.choice
  · apply WellScoped.cutBoundary
    apply WellScoped.choice
    · apply WellScoped.commit
      apply WellScoped.yield
      exact .done _
    · apply WellScoped.yield
      exact .done _
  · apply WellScoped.yield
    exact .done _

/-- An inner cut cannot prune a sibling choice point owned by the enclosing
scope.  The selected inner answer and the outer answer both remain observable,
whereas the later answer in the inner scope is absent. -/
theorem inner_cut_preserves_outer_sibling_steps
    (protocol : OrderedCallProtocol Request Token Reply Effect Exception)
    (session : protocol.Session) (selected skipped outer : Answer) :
    Steps protocol
      (.running session
        (innerCommitWithOuterSibling selected skipped outer))
      [.answer selected, .answer outer, .completed]
      (.terminal session .completed) := by
  have innerPrunable : Prunes protocol session
      (Process.liveTokens
        (Process.yield skipped Process.done :
          Process Request Token Reply Answer Effect Exception)) session := by
    simpa [Process.liveTokens] using (Prunes.nil session)
  have innerCommit : RawStep protocol session
      (Process.cutBoundary 1
        (Process.choice 1
          (Process.commit 1 (Process.yield selected Process.done))
          (Process.yield skipped Process.done)))
      [] .none session
      (.running
        (Process.cutBoundary 1 (Process.yield selected Process.done))) :=
    .cutBoundaryCatch 1 _ _ [] session session
      (.choiceCommitHere 1 _ _ _ [] session session session
        (.commit 1 _ session) innerPrunable)
  have firstStep : RawStep protocol session
      (innerCommitWithOuterSibling selected skipped outer)
      [] .none session
      (.running
        (.cutBoundary 0
          (.choice 0
            (.cutBoundary 1 (.yield selected .done))
            (.yield outer .done)))) :=
    .cutBoundaryProgress 0 _ _ [] session session
      (.choiceProgress 0 _ _ _ [] session session innerCommit)
  have secondStep : RawStep protocol session
      (.cutBoundary 0
        (.choice 0
          (.cutBoundary 1 (.yield selected .done))
          (.yield outer .done)))
      [.answer selected] .none session
      (.running
        (.cutBoundary 0
          (.choice 0
            (.cutBoundary 1 .done)
            (.yield outer .done)))) :=
    .cutBoundaryProgress 0 _ _ _ session session
      (.choiceProgress 0 _ _ _ _ session session
        (.cutBoundaryProgress 1 _ _ _ session session
          (.yield selected _ session)))
  have thirdStep : RawStep protocol session
      (.cutBoundary 0
        (.choice 0
          (.cutBoundary 1 .done)
          (.yield outer .done)))
      [] .none session
      (.running (.cutBoundary 0 (.yield outer .done))) :=
    .cutBoundaryProgress 0 _ _ [] session session
      (.choiceComplete 0 _ _ session session
        (.cutBoundaryComplete 1 _ session session (.done session)))
  refine .cons _ _ _ _ _
    (.ordinary _ _ session session _ firstStep) ?_
  refine .cons _ _ _ _ _
    (.ordinary _ _ session session _ secondStep) ?_
  refine .cons _ _ _ _ _
    (.ordinary _ _ session session _ thirdStep) ?_
  refine .cons _ _ _ _ _
    (.ordinary _ _ session session _
      (.cutBoundaryProgress 0 _ _ _ session session
        (.yield outer _ session))) ?_
  refine .cons _ _ _ _ _
    (.ordinary _ _ session session _
      (.cutBoundaryComplete 0 _ session session (.done session))) ?_
  exact .refl (.terminal session .completed)

/-- A same-scope commit explicitly prunes a live call cursor in a discarded
branch.  This is the abstract counterpart of a nondeterministic foreign
predicate receiving its prune notification. -/
theorem commit_prunes_live_cursor
    (protocol : OrderedCallProtocol Request Token Reply Effect Exception)
    (answer : Answer) (cursor : Token)
    (before after : protocol.Session)
    (canPrune : protocol.prune before cursor after) :
    RawStep protocol before
      (.cutBoundary 0
        (.choice 0
          (.commit 0 (.yield answer .done))
          (.await 0 cursor (fun _ => .done))))
      [.pruned cursor] .none after
      (.running (.cutBoundary 0 (.yield answer .done))) := by
  have prunable : Prunes protocol before
      (Process.liveTokens
        (Process.await 0 cursor (fun _ => Process.done) :
          Process Request Token Reply Answer Effect Exception)) after := by
    simpa [Process.liveTokens] using
      (Prunes.cons before after after cursor [] canPrune
        (Prunes.nil after))
  simpa [Process.liveTokens] using
    (RawStep.cutBoundaryCatch (protocol := protocol) 0 _ _
      [Observation.pruned cursor] before after
      (RawStep.choiceCommitHere (protocol := protocol) 0 _ _ _ []
        before before after (RawStep.commit 0 _ before) prunable))

/-- Exceptional unwinding prunes every live cursor in the discarded sibling
before preserving the raised terminal tag.  This is the exception-symmetric
counterpart of cut cleanup; a live foreign cursor cannot be silently leaked
merely because the left branch raised instead of committed. -/
theorem exception_prunes_live_cursor
    {Answer : Type}
    (protocol : OrderedCallProtocol Request Token Reply Effect Exception)
    (exception : Exception) (cursor : Token)
    (before after : protocol.Session)
    (canPrune : protocol.prune before cursor after) :
    RawStep protocol before
      ((.cutBoundary 0
        (.choice 0
          (.raise exception)
          (.await 0 cursor (fun _ => .done)))) :
        Process Request Token Reply Answer Effect Exception)
      [.raised exception, .pruned cursor] .none after
      (.terminal (.raised exception)) := by
  have pruned : Prunes protocol before
      (Process.liveTokens
        (Process.await 0 cursor (fun _ => Process.done) :
          Process Request Token Reply Answer Effect Exception)) after := by
    simpa [Process.liveTokens] using
      (Prunes.cons (protocol := protocol) before after after cursor []
        canPrune (Prunes.nil (protocol := protocol) after))
  simpa [Process.liveTokens] using
    (RawStep.cutBoundaryRaised (protocol := protocol) 0 _ exception
      [Observation.raised exception, Observation.pruned cursor]
      before after
      (RawStep.choiceRaised (protocol := protocol) 0 _ _ exception
        [Observation.raised exception] before before after
        (RawStep.raise (protocol := protocol) exception before) pruned))

/-! ## Reply-splice anti-vacuity witnesses -/

/-- Cursor positions for a two-clause local-call witness. -/
inductive TwoClauseToken where
  | first
  | second
  | done
deriving DecidableEq

/-- Internal provider replies name clause occurrences only.  They carry no
answer, effect, exception, or schedule. -/
inductive TwoClauseReply where
  | firstClause
  | secondClause
deriving DecidableEq

/-- The provider exposes source clause order one occurrence at a time. -/
inductive TwoClausePull : TwoClauseToken →
    PullResult TwoClauseToken TwoClauseReply Empty Empty → Prop where
  | first : TwoClausePull .first (.reply .firstClause .second)
  | second : TwoClausePull .second (.reply .secondClause .done)
  | done : TwoClausePull .done .exhausted

def twoClauseProtocol :
    OrderedCallProtocol Unit TwoClauseToken TwoClauseReply Empty Empty :=
  OrderedCallProtocol.pure
    (fun _ cursor => cursor = .first)
    TwoClausePull
    (fun _ => True)

private theorem twoClause_open :
    twoClauseProtocol.openCall () () .first () := by
  exact ⟨rfl, rfl⟩

private theorem twoClause_pull_first :
    twoClauseProtocol.pull () .first (.reply .firstClause .second) () := by
  exact ⟨TwoClausePull.first, rfl⟩

private theorem twoClause_pull_second :
    twoClauseProtocol.pull () .second (.reply .secondClause .done) () := by
  exact ⟨TwoClausePull.second, rfl⟩

private theorem twoClause_pull_done :
    twoClauseProtocol.pull () .done .exhausted () := by
  exact ⟨TwoClausePull.done, rfl⟩

private theorem twoClause_prune (token : TwoClauseToken) :
    twoClauseProtocol.prune () token () := by
  exact ⟨True.intro, rfl⟩

/-- Certified interpretation of the internal clause tags.  The first clause
commits in the predicate scope before yielding; the provider itself has no
constructor capable of expressing either operation. -/
def twoClauseCutBodies (selected skipped : Answer) : TwoClauseReply →
    Process Unit TwoClauseToken TwoClauseReply Answer Empty Empty
  | .firstClause => .commit 0 (.yield selected .done)
  | .secondClause => .yield skipped .done

def twoClauseCutCall (selected skipped : Answer) :
    Process Unit TwoClauseToken TwoClauseReply Answer Empty Empty :=
  Process.scopedCall 0 () (twoClauseCutBodies selected skipped)

/-- The reply splice puts the entered body before the still-live clause
cursor.  Consequently a cut in clause one prunes clause two before the latter
can be pulled or yield its answer.  A provider-owned scheduler or eager answer
bag cannot realize this exact trace. -/
theorem first_clause_cut_prunes_later_clause
    (selected skipped : Answer) :
    Steps twoClauseProtocol
      (.running () (twoClauseCutCall selected skipped))
      [.opened (), .pruned .second, .answer selected, .completed]
      (.terminal () .completed) := by
  have opened : RawStep twoClauseProtocol ()
      (twoClauseCutCall selected skipped)
      [.opened ()] .none ()
      (.running
        (.cutBoundary 0
          (.await 0 TwoClauseToken.first
            (twoClauseCutBodies selected skipped)))) := by
    exact .cutBoundaryProgress (protocol := twoClauseProtocol) 0 _ _ _ () ()
      (.openCall (protocol := twoClauseProtocol) () TwoClauseToken.first _ () ()
        twoClause_open)
  have spliced : RawStep twoClauseProtocol ()
      (.cutBoundary 0
        (.await 0 TwoClauseToken.first
          (twoClauseCutBodies selected skipped)))
      [] .none ()
      (.running
        (.cutBoundary 0
          (.choice 0
            (.commit 0 (.yield selected .done))
            (.await 0 TwoClauseToken.second
              (twoClauseCutBodies selected skipped))))) := by
    exact .cutBoundaryProgress (protocol := twoClauseProtocol) 0 _ _ _ () ()
      (.awaitReply (protocol := twoClauseProtocol) 0 TwoClauseToken.first
        TwoClauseToken.second TwoClauseReply.firstClause _ () ()
        twoClause_pull_first)
  have prunable : Prunes twoClauseProtocol ()
      (Process.liveTokens
        (Process.await 0 TwoClauseToken.second
          (twoClauseCutBodies selected skipped))) () := by
    simpa [Process.liveTokens] using
      (Prunes.cons (protocol := twoClauseProtocol) () () ()
        TwoClauseToken.second []
        (twoClause_prune .second)
        (Prunes.nil (protocol := twoClauseProtocol) ()))
  have committed : RawStep twoClauseProtocol ()
      (.cutBoundary 0
        (.choice 0
          (.commit 0 (.yield selected .done))
          (.await 0 TwoClauseToken.second
            (twoClauseCutBodies selected skipped))))
      [.pruned .second] .none ()
      (.running (.cutBoundary 0 (.yield selected .done))) := by
    exact .cutBoundaryCatch (protocol := twoClauseProtocol) 0 _ _ _ () ()
      (.choiceCommitHere (protocol := twoClauseProtocol) 0 _ _ _ [] () () ()
        (.commit (protocol := twoClauseProtocol) 0 _ ()) prunable)
  refine .cons _ _ _ _ _
    (.ordinary (protocol := twoClauseProtocol) _ _ () () _ opened) ?_
  refine .cons _ _ _ _ _
    (.ordinary (protocol := twoClauseProtocol) _ _ () () _ spliced) ?_
  refine .cons _ _ _ _ _
    (.ordinary (protocol := twoClauseProtocol) _ _ () () _ committed) ?_
  refine .cons _ _ _ _ _
    (.ordinary (protocol := twoClauseProtocol) _ _ () () _
      (.cutBoundaryProgress (protocol := twoClauseProtocol) 0 _ _ _ () ()
        (.yield (protocol := twoClauseProtocol) selected _ ()))) ?_
  refine .cons _ _ _ _ _
    (.ordinary (protocol := twoClauseProtocol) _ _ () () _
      (.cutBoundaryComplete (protocol := twoClauseProtocol) 0 _ () ()
        (.done (protocol := twoClauseProtocol) ()))) ?_
  exact .refl
    (.terminal (protocol := twoClauseProtocol) (Answer := Answer) () .completed)

/-- Certified interpretation without a cut.  The reply tags still carry no
answer data; only the left-to-right body interpreter can yield the two
observable values. -/
def twoClauseOrderedBodies (first second : Answer) : TwoClauseReply →
    Process Unit TwoClauseToken TwoClauseReply Answer Empty Empty
  | .firstClause => .yield first .done
  | .secondClause => .yield second .done

def twoClauseOrderedCall (first second : Answer) :
    Process Unit TwoClauseToken TwoClauseReply Answer Empty Empty :=
  Process.scopedCall 0 () (twoClauseOrderedBodies first second)

/-- Pulling both source-ordered clause occurrences preserves answer order and
duplicate multiplicity.  In particular, setting `first = second` still emits
two answer observations before completion. -/
theorem two_clause_answers_preserve_order_and_multiplicity
    (first second : Answer) :
    Steps twoClauseProtocol
      (.running () (twoClauseOrderedCall first second))
      [.opened (), .answer first, .answer second, .completed]
      (.terminal () .completed) := by
  have opened : RawStep twoClauseProtocol ()
      (twoClauseOrderedCall first second)
      [.opened ()] .none ()
      (.running
        (.cutBoundary 0
          (.await 0 TwoClauseToken.first
            (twoClauseOrderedBodies first second)))) := by
    exact .cutBoundaryProgress (protocol := twoClauseProtocol) 0 _ _ _ () ()
      (.openCall (protocol := twoClauseProtocol) () TwoClauseToken.first _ () ()
        twoClause_open)
  have firstSpliced : RawStep twoClauseProtocol ()
      (.cutBoundary 0
        (.await 0 TwoClauseToken.first
          (twoClauseOrderedBodies first second)))
      [] .none ()
      (.running
        (.cutBoundary 0
          (.choice 0 (.yield first .done)
            (.await 0 TwoClauseToken.second
              (twoClauseOrderedBodies first second))))) := by
    exact .cutBoundaryProgress (protocol := twoClauseProtocol) 0 _ _ _ () ()
      (.awaitReply (protocol := twoClauseProtocol) 0 TwoClauseToken.first
        TwoClauseToken.second TwoClauseReply.firstClause _ () ()
        twoClause_pull_first)
  have firstAnswer : RawStep twoClauseProtocol ()
      (.cutBoundary 0
        (.choice 0 (.yield first .done)
          (.await 0 TwoClauseToken.second
            (twoClauseOrderedBodies first second))))
      [.answer first] .none ()
      (.running
        (.cutBoundary 0
          (.choice 0 .done
            (.await 0 TwoClauseToken.second
              (twoClauseOrderedBodies first second))))) := by
    exact .cutBoundaryProgress (protocol := twoClauseProtocol) 0 _ _ _ () ()
      (.choiceProgress (protocol := twoClauseProtocol) 0 _ _ _ _ () ()
        (.yield (protocol := twoClauseProtocol) first .done ()))
  have advanceSecond : RawStep twoClauseProtocol ()
      (.cutBoundary 0
        (.choice 0 .done
          (.await 0 TwoClauseToken.second
            (twoClauseOrderedBodies first second))))
      [] .none ()
      (.running
        (.cutBoundary 0
          (.await 0 TwoClauseToken.second
            (twoClauseOrderedBodies first second)))) := by
    exact .cutBoundaryProgress (protocol := twoClauseProtocol) 0 _ _ _ () ()
      (.choiceComplete (protocol := twoClauseProtocol) 0 _ _ () ()
        (.done (protocol := twoClauseProtocol) ()))
  have secondSpliced : RawStep twoClauseProtocol ()
      (.cutBoundary 0
        (.await 0 TwoClauseToken.second
          (twoClauseOrderedBodies first second)))
      [] .none ()
      (.running
        (.cutBoundary 0
          (.choice 0 (.yield second .done)
            (.await 0 TwoClauseToken.done
              (twoClauseOrderedBodies first second))))) := by
    exact .cutBoundaryProgress (protocol := twoClauseProtocol) 0 _ _ _ () ()
      (.awaitReply (protocol := twoClauseProtocol) 0 TwoClauseToken.second
        TwoClauseToken.done TwoClauseReply.secondClause _ () ()
        twoClause_pull_second)
  have secondAnswer : RawStep twoClauseProtocol ()
      (.cutBoundary 0
        (.choice 0 (.yield second .done)
          (.await 0 TwoClauseToken.done
            (twoClauseOrderedBodies first second))))
      [.answer second] .none ()
      (.running
        (.cutBoundary 0
          (.choice 0 .done
            (.await 0 TwoClauseToken.done
              (twoClauseOrderedBodies first second))))) := by
    exact .cutBoundaryProgress (protocol := twoClauseProtocol) 0 _ _ _ () ()
      (.choiceProgress (protocol := twoClauseProtocol) 0 _ _ _ _ () ()
        (.yield (protocol := twoClauseProtocol) second .done ()))
  have advanceDone : RawStep twoClauseProtocol ()
      (.cutBoundary 0
        (.choice 0 .done
          (.await 0 TwoClauseToken.done
            (twoClauseOrderedBodies first second))))
      [] .none ()
      (.running
        (.cutBoundary 0
          (.await 0 TwoClauseToken.done
            (twoClauseOrderedBodies first second)))) := by
    exact .cutBoundaryProgress (protocol := twoClauseProtocol) 0 _ _ _ () ()
      (.choiceComplete (protocol := twoClauseProtocol) 0 _ _ () ()
        (.done (protocol := twoClauseProtocol) ()))
  have exhausted : RawStep twoClauseProtocol ()
      (.cutBoundary 0
        (.await 0 TwoClauseToken.done
          (twoClauseOrderedBodies first second)))
      [.completed] .none () (.terminal .completed) := by
    exact .cutBoundaryComplete (protocol := twoClauseProtocol) 0 _ () ()
      (.awaitExhausted (protocol := twoClauseProtocol) 0 TwoClauseToken.done _
        () () twoClause_pull_done)
  refine .cons _ _ _ _ _
    (.ordinary (protocol := twoClauseProtocol) _ _ () () _ opened) ?_
  refine .cons _ _ _ _ _
    (.ordinary (protocol := twoClauseProtocol) _ _ () () _ firstSpliced) ?_
  refine .cons _ _ _ _ _
    (.ordinary (protocol := twoClauseProtocol) _ _ () () _ firstAnswer) ?_
  refine .cons _ _ _ _ _
    (.ordinary (protocol := twoClauseProtocol) _ _ () () _ advanceSecond) ?_
  refine .cons _ _ _ _ _
    (.ordinary (protocol := twoClauseProtocol) _ _ () () _ secondSpliced) ?_
  refine .cons _ _ _ _ _
    (.ordinary (protocol := twoClauseProtocol) _ _ () () _ secondAnswer) ?_
  refine .cons _ _ _ _ _
    (.ordinary (protocol := twoClauseProtocol) _ _ () () _ advanceDone) ?_
  refine .cons _ _ _ _ _
    (.ordinary (protocol := twoClauseProtocol) _ _ () () _ exhausted) ?_
  exact .refl
    (.terminal (protocol := twoClauseProtocol) (Answer := Answer) () .completed)

/-- The scope discipline rejects the malformed configuration used by the raw
scope-discrimination witness below: an outer-scope commit may not occur inside
an opaque inner cut boundary. -/
theorem outer_commit_under_inner_not_wellScoped
    (next right : Process Request Token Reply Answer Effect Exception) :
    ¬ (WellScoped 0
      (.cutBoundary 0 (.cutBoundary 1 (.choice 1 (.commit 0 next) right)))) := by
  intro wellFormed
  have innerScoped := WellScoped.cutBoundary_body wellFormed
  have choiceScoped := WellScoped.cutBoundary_body innerScoped
  have leftScoped := WellScoped.choice_left choiceScoped
  have impossible : (0 : Nat) = 1 := WellScoped.commit_scope_eq leftScoped
  exact Nat.zero_ne_one impossible

/-- Raw scope-discrimination witness on intentionally ill-scoped input: a
commit passes through a differently scoped choice and cut boundary, so the
right branch is retained.  `WellScoped` rejects this outer-commit-under-inner-
boundary shape; the theorem tests the raw relation's scope tags and does not
claim that a compiler may emit the source process. -/
theorem different_scope_is_not_pruned
    (protocol : OrderedCallProtocol Request Token Reply Effect Exception)
    (session : protocol.Session)
    (next right : Process Request Token Reply Answer Effect Exception) :
    RawStep protocol session
      (.cutBoundary 0 (.cutBoundary 1 (.choice 1 (.commit 0 next) right)))
      [] .none session
      (.running (.cutBoundary 0 (.cutBoundary 1 (.choice 1 next right)))) := by
  exact .cutBoundaryCatch 0 _ _ [] session session
    (.cutBoundaryPass 1 0 (by decide) _ _ [] session session
      (.choiceCommitOutside 1 0 (by decide) _ _ _ [] session session
        (.commit 0 next session)))

/-- The same intentionally ill-scoped raw witness cannot take a step that
globally discards the differently scoped alternative.  The well-scoped
cut-locality property used by compiled programs is
`inner_cut_preserves_outer_sibling_steps` above. -/
theorem different_scope_global_prune_impossible
    (protocol : OrderedCallProtocol Request Token Reply Effect Exception)
    (session : protocol.Session) (answer : Answer) :
    ¬ ∃ events, RawStep protocol session
        (.cutBoundary 0
          (.cutBoundary 1
            (.choice 1 (.commit 0 .done) (.yield answer .done))))
        events .none session
        (.running (.cutBoundary 0 (.cutBoundary 1 .done))) := by
  rintro ⟨events, step⟩
  cases step with
  | cutBoundaryProgress _ _ _ _ _ _ inner =>
      cases inner with
      | cutBoundaryProgress _ _ _ _ _ _ choiceStep => cases choiceStep
      | cutBoundaryCatch _ _ _ _ _ _ choiceStep =>
          cases choiceStep with
          | choiceCommitHere _ _ _ _ _ _ _ _ leafStep _ => cases leafStep
  | cutBoundaryCatch _ _ _ _ _ _ inner =>
      cases inner with
      | cutBoundaryPass _ _ _ _ _ _ _ _ choiceStep => cases choiceStep

/-- Tokens for the canonical one-answer-then-diverge counterexample. -/
inductive OneThenLoopToken where
  | first
  | loop
deriving DecidableEq

/-- Pull relation for a call that yields one answer and then takes arbitrarily
many silent steps without reporting exhaustion. -/
inductive OneThenLoopPull (answer : Answer) :
    OneThenLoopToken →
    PullResult OneThenLoopToken Answer Effect Exception → Prop where
  | first : OneThenLoopPull answer .first (.reply answer .loop)
  | loop : OneThenLoopPull answer .loop (.silent .loop)

def oneThenLoopProtocol (answer : Answer) :
    OrderedCallProtocol Unit OneThenLoopToken Answer Effect Exception :=
  OrderedCallProtocol.pure
    (fun _ cursor => cursor = .first)
    (OneThenLoopPull answer)
    (fun _ => True)

private theorem oneThenLoop_pull_first (answer : Answer) :
    (oneThenLoopProtocol (Effect := Effect) (Exception := Exception) answer).pull
      () .first (.reply answer .loop) () := by
  exact ⟨OneThenLoopPull.first, rfl⟩

private theorem oneThenLoop_pull_loop (answer : Answer) :
    (oneThenLoopProtocol (Effect := Effect) (Exception := Exception) answer).pull
      () .loop (.silent .loop) () := by
  exact ⟨OneThenLoopPull.loop, rfl⟩

private theorem oneThenLoop_loop_not_exhausted (answer : Answer) :
    ¬ (oneThenLoopProtocol (Effect := Effect) (Exception := Exception) answer).pull
      () .loop .exhausted () := by
  rintro ⟨pulled, _⟩
  cases pulled

private theorem oneThenLoop_pull_only (answer : Answer) :
    ∀ before result after,
      (oneThenLoopProtocol
        (Effect := Effect) (Exception := Exception) answer).pull
          before .loop result after →
        result = .silent .loop ∧ after = before := by
  intro before result after pulled
  rcases pulled with ⟨pulled, afterEq⟩
  cases pulled
  exact ⟨rfl, afterEq⟩

/-- Complete one-step inversion for the divergent suffix.  The deliberately
open cursor can take exactly one kind of step: silent, session-preserving, and
back to the same open process.  In particular it cannot fabricate completion,
an exception, an answer, or an effect. -/
private theorem oneThenLoop_raw_step_shape (answer : Answer)
    {before after : Unit}
    {process : Process Unit OneThenLoopToken Answer Answer Effect Exception}
    {events : List
      (Observation Unit OneThenLoopToken Answer Effect Exception)}
    {signal : CutSignal}
    {target : RawTarget Unit OneThenLoopToken Answer Answer Effect Exception}
    (step : RawStep
      (oneThenLoopProtocol (Effect := Effect) (Exception := Exception) answer)
      before process events signal after target)
    (processEq : process = Process.directAwait 0 OneThenLoopToken.loop) :
    events = [] ∧ signal = .none ∧ after = before ∧
      target = .running (Process.directAwait 0 OneThenLoopToken.loop) := by
  exact RawStep.await_only_silent
    (oneThenLoopProtocol answer) 0 OneThenLoopToken.loop
    (fun value => .yield value .done) (oneThenLoop_pull_only answer)
    step (by simpa [Process.directAwait] using processEq)

/-- The first answer is observable before the divergent suffix. -/
theorem oneThenLoop_answer_prefix (answer : Answer) :
    Steps (oneThenLoopProtocol (Effect := Effect) (Exception := Exception) answer)
      (.running () (Process.directAwait 0 OneThenLoopToken.first))
      [.answer answer]
      (.running () (Process.directAwait 0 OneThenLoopToken.loop)) := by
  let resume : Answer → Process Unit OneThenLoopToken Answer Answer
      Effect Exception := fun value => .yield value .done
  refine .cons _ _ _ _ _
    (.ordinary (protocol := oneThenLoopProtocol answer) _ _ () () _
      (.awaitReply (protocol := oneThenLoopProtocol answer) 0 _ _ answer resume
        () () (oneThenLoop_pull_first answer))) ?_
  refine .cons _ _ _ _ _
    (.ordinary (protocol := oneThenLoopProtocol answer) _ _ () () _
      (.choiceProgress (protocol := oneThenLoopProtocol answer) 0 _ _ _ _ () ()
        (.yield (protocol := oneThenLoopProtocol answer) answer .done ()))) ?_
  refine .cons _ _ _ _ _
    (.ordinary (protocol := oneThenLoopProtocol answer) _ _ () () _
      (.choiceComplete (protocol := oneThenLoopProtocol answer) 0 _ _ () ()
        (.done (protocol := oneThenLoopProtocol answer) ()))) ?_
  exact .refl _

/-- For every finite demand budget, the suffix can remain open without
fabricating either exhaustion or failure. -/
theorem oneThenLoop_arbitrarily_long_open_prefix (answer : Answer) :
    ∀ steps : Nat,
      StepsN (oneThenLoopProtocol (Effect := Effect) (Exception := Exception) answer)
        steps
        (.running () (Process.directAwait 0 OneThenLoopToken.loop)) []
        (.running () (Process.directAwait 0 OneThenLoopToken.loop)) := by
  intro steps
  induction steps with
  | zero => exact .zero _
  | succ steps inductionHypothesis =>
      refine .succ steps _ _ _ _ _
        (.ordinary (protocol := oneThenLoopProtocol answer) _ _ () () _
          (.awaitSilent (protocol := oneThenLoopProtocol answer) 0 _ _ _ () ()
            (oneThenLoop_pull_loop answer))) ?_
      change StepsN (oneThenLoopProtocol answer) steps
        (.running () (Process.directAwait 0 OneThenLoopToken.loop)) []
        (.running () (Process.directAwait 0 OneThenLoopToken.loop))
      exact inductionHypothesis

/-- The divergent suffix cannot be reclassified as ordinary exhaustion.  This
is the negative half of the finite-prefix witness: the semantics supports
arbitrarily many silent demands, but no demand can fabricate completion. -/
theorem oneThenLoop_cannot_complete (answer : Answer) :
    ¬ RawStep
      (oneThenLoopProtocol (Effect := Effect) (Exception := Exception) answer)
      ()
      (Process.directAwait 0 OneThenLoopToken.loop)
      [.completed] .none () (.terminal .completed) := by
  intro step
  have shape := oneThenLoop_raw_step_shape answer step rfl
  cases shape.1

/-- Every exact finite execution from the divergent suffix stays in the same
open state and emits no event.  This strengthens the one-step inversion above:
no finite number of silent demands can manufacture a terminal state. -/
theorem oneThenLoop_finite_prefix_stays_open (answer : Answer) :
    ∀ (count : Nat)
      (events : List
        (Observation Unit OneThenLoopToken Answer Effect Exception))
      (finish : State
        (oneThenLoopProtocol (Effect := Effect) (Exception := Exception) answer)),
      StepsN
        (oneThenLoopProtocol (Effect := Effect) (Exception := Exception) answer)
        count
        (.running () (Process.directAwait 0 OneThenLoopToken.loop)) events finish →
      events = [] ∧
        finish = .running () (Process.directAwait 0 OneThenLoopToken.loop) := by
  intro count
  induction count with
  | zero =>
      intro events finish execution
      cases execution
      exact ⟨rfl, rfl⟩
  | succ count inductionHypothesis =>
      intro events finish execution
      cases execution with
      | succ _ start middle finish first rest head tail =>
          cases head with
          | ordinary process observed before after target step =>
              have shape := oneThenLoop_raw_step_shape answer step rfl
              rcases shape with
                ⟨observedEmpty, _, afterEq, targetEq⟩
              subst first
              subst after
              subst target
              rcases inductionHypothesis rest finish tail with
                ⟨restEmpty, finishOpen⟩
              subst rest
              exact ⟨rfl, finishOpen⟩
          | uncaught process next observed before after scope step =>
              have shape := oneThenLoop_raw_step_shape answer step rfl
              cases shape.2.1

/-- In particular, the one-answer-then-diverge suffix has no finite completed
run, regardless of how many silent pulls are allowed. -/
theorem oneThenLoop_no_finite_completion (answer : Answer) :
    ∀ (count : Nat)
      (events : List
        (Observation Unit OneThenLoopToken Answer Effect Exception)),
      ¬ StepsN
        (oneThenLoopProtocol (Effect := Effect) (Exception := Exception) answer)
        count
        (.running () (Process.directAwait 0 OneThenLoopToken.loop)) events
        (.terminal () .completed) := by
  intro count events execution
  have staysOpen :=
    oneThenLoop_finite_prefix_stays_open
      (Effect := Effect) (Exception := Exception) answer
      count events (.terminal () .completed) execution
  cases staysOpen.2

end PLeaTTa.PeTTaSpec.PrologCore.Trace
