-- SPDX-FileCopyrightText: 2026 MesTTo
-- SPDX-License-Identifier: Apache-2.0

/-
LeaTTa: a machine-checked operational semantics and metatheory of MeTTa in Lean 4.
Book root (Verso manual genre). Built with `lake exe docs`.
-/
import VersoManual
import Illuminate
import Docs.Cd

import Docs.Papers
import Docs.ObjectLanguage
import Docs.Interpreter
import Docs.TypeSystem
import Docs.Metatheory
import Docs.Operational
import Docs.Correspondence
import Docs.Blockchain
import Docs.MeTTaIL
import Docs.CordialMiners
import Docs.FutureWork
import Docs.Discussion
import Docs.Appendices

open Verso.Genre Manual
open Verso.Genre.Manual.InlineLean
open Illuminate

open Docs

set_option pp.rawOnError true
set_option verso.code.warnLineLength 100

#doc (Manual) "LeaTTa: A Machine-Checked Operational Semantics and Metatheory of MeTTa in Lean 4" =>
%%%
authors := ["The LeaTTa Project"]
shortTitle := "LeaTTa"
%%%

:::paragraph
*Alpha.* This is an early, alpha-stage release and a starting foundation. It currently formalises
Hyperon Experimental's minimal interpreter and standard library, the published MeTTa operational
semantics, a distributed atomspace slice, the MeTTaIL formalization, and the Cordial Miners safety
core. The limitations chapter states the remaining gaps directly.
:::

{index}[LeaTTa]
*LeaTTa* is a formalization of *MeTTa*, the language at the heart of OpenCog Hyperon
{citep goertzelMetagraph}[], carried out in the {citet lean4}[] interactive theorem prover. If you
are a MeTTa developer, you can think of it as a machine-checked specification: every rule that fires,
every type that is checked, every result that comes back is defined by Lean code that Lean's own
kernel verifies. The formalization covers:

 * the minimal interpreter;
 * the standard library;
 * the gradual type system;
 * the published four-register operational semantics;
 * the distributed atomspace proof target;
 * the MeTTaIL formalization;
 * a body of machine-checked *metatheory*: determinism, confluence of the deterministic fragment,
   type soundness, gradual-typing consistency, binding and atomspace laws, observation facts,
   soundness *and* completeness of first-argument indexing, distributed delivery and convergence
   boundaries, and a bisimulation connecting the kernel's rule-firing core to the published
   operational semantics of MeTTa at the level of which rules fire {citep mops}[].

Every theorem in this book is checked by Lean's kernel. The development contains *no* `sorry`,
`admit`, `native_decide`, `partial`, or `unsafe`; the public axiom audit files report only the three
standard classical axioms of Mathlib {citep mathlib}[] where those library paths require them, and the
gradual-typing non-transitivity result depends on no axioms at all. The executable interpreter is
validated against Hyperon's own test corpus (270/270 assertions). CI fails on root Lean/Lake warnings
and on any unreviewed book warning; the only allowed book warning is the known upstream Verso v4.31.0
`@[expose]` warning.

:::paragraph
LeaTTa is written for two audiences:

 * *MeTTa/Hyperon developers*, who get an independent, executable *specification* of the language.
   The MeTTa operational-semantics paper {citep mops}[] envisions exactly this role: a
   "JVM-specification" of MeTTa against which implementations can be judged compliant.
 * *Programming-language researchers*, who get a worked formalization in the gradual-typing line of
   work begun by {citet siekTaha}[], in the tradition of mechanized language metatheory.
:::

# Why Formalize MeTTa? Blockchain, AGI, and Verifiable Semantics
%%%
tag := "sec-why"
%%%

MeTTa is headed for use as an *on-chain / smart-contract* language. On a blockchain, a contract's
behaviour must be predictable, replayable, and auditable. An optimised on-chain evaluator must be
provably faithful to the published semantics, or a miner and a verifier could disagree on the result.
A machine-checked metatheory is what lets you close that gap. That is what drives LeaTTa's emphasis:

 * *Determinism / replayability*: the abstract machine is a single-valued function; all
   non-determinism is reified in an explicit result list, never in the transition relation.
 * *Type soundness*: a well-typed program is never rejected with a spurious error, and a reported
   type error is faithful (never fabricated).
 * *Auditability*: the knowledge base (contract state) is mutated *only* by explicit, attributable
   `add-atom`/`remove-atom`; pure reduction never changes it.
 * *Gas*: a resource-bounded variant in which energy is provably never created.
 * *Optimisation-faithfulness*: first-argument indexing computes exactly the published
   semantics' result set.

# A Note on This Document

A complete API reference, every definition and theorem with its docstring, is generated by doc-gen4
and hosted alongside this book at [the API reference](api/index.html).

This book is generated by Verso, the documentation system of the Lean language. Every Lean code
block is elaborated by the same compiler that checks the whole development, so nothing in this book
can drift silently out of date. For example, the following is checked as you read it:

```lean
example : 1 + 1 = 2 := rfl
```

Diagrams are generated by Lean as well. The central result of {ref "sec-why"}[the preceding section],
that the optimised interpreter and the published specification reduce a term to the *same* answers,
is the commuting square below, drawn here as a preview and proved in the correspondence chapter:

```diagram (cssWidth := "24em")
cd do
  let a ← CDM.node "t" cdBlue
  let b ← CDM.node "t" cdGreen
  let a' ← CDM.node "results" cdBlue
  let b' ← CDM.node "results" cdGreen
  CDM.grid #[#[some a, some a'], #[some b, some b']]
  CDM.arrow a a' (some "kernel") cdBlue .above
  CDM.arrow b b' (some "MOPS") cdGreen .below
  CDM.arrow a b (some "=") cdInk .left
  CDM.arrow a' b' (some "=") cdInk .right
```

The remaining chapters cover the object language, the minimal interpreter and its standard
library, the gradual type system, the metatheory, the operational semantics and its correspondence to
the interpreter, the blockchain-oriented guarantees, the `future-work` branch, and a discussion
of the development's current limitations and open problems.

{include 1 Docs.ObjectLanguage}

{include 1 Docs.Interpreter}

{include 1 Docs.TypeSystem}

{include 1 Docs.Metatheory}

{include 1 Docs.Operational}

{include 1 Docs.Correspondence}

{include 1 Docs.Blockchain}

{include 1 Docs.MeTTaIL}

{include 1 Docs.CordialMiners}

{include 1 Docs.FutureWork}

{include 1 Docs.Discussion}

{include 1 Docs.Appendices}
